PhASAR: psr::FlowFunctions< AnalysisDomainTy, Container > Class Template Reference
psr::FlowFunctions< AnalysisDomainTy, Container > Class Template Reference abstract
#include "phasar/DataFlow/IfdsIde/FlowFunctions.h"
Public Types
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using n_t = typename AnalysisDomainTy::n_t
using FlowFunctionType = FlowFunction< d_t, Container >
using FlowFunctionPtrType = typename FlowFunctionType::FlowFunctionPtrType
using container_type = typename FlowFunctionType::container_type
Public Member Functions
virtual ~FlowFunctions ()=default
virtual FlowFunctionPtrType getNormalFlowFunction (n_t Curr, n_t Succ)=0
virtual FlowFunctionPtrType getCallFlowFunction (n_t CallInst, f_t CalleeFun)=0
virtual FlowFunctionPtrType getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, n_t RetSite)=0
virtual void applyUnbalancedRetFlowFunctionSideEffects (f_t CalleeFun, n_t ExitInst, d_t Source)
virtual FlowFunctionPtrType getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees)=0
virtual FlowFunctionPtrType getSummaryFlowFunction (n_t, f_t)
Additional Inherited Members
Protected Types inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
using d_t = AnalysisDomainTy::d_t
using container_type = Container
Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
auto unionFlows (FlowFunctionPtrTypeOf< F1 > OneFF, FlowFunctionPtrTypeOf< F2 > OtherFF)
Static Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
static auto identityFlow ()
static auto lambdaFlow (Fn &&F)
static auto generateFlow (d_t FactToGenerate, d_t From)
static auto generateFlowIf (d_t FactToGenerate, Fn Predicate)
static auto generateManyFlows (Range &&FactsToGenerate, d_t From)
static auto killFlow (d_t FactToKill)
static auto killFlowIf (Fn Predicate)
static auto killManyFlows (Range &&FactsToKill)
static auto killAllFlows ()
static auto generateFlowAndKillAllOthers (d_t FactToGenerate, d_t From)
static auto generateManyFlowsAndKillAllOthers (Range &&FactsToGenerate, d_t From)
static auto transferFlow (d_t FactToGenerate, d_t From)
Detailed Description
template<typename AnalysisDomainTy, typename Container>
class psr::FlowFunctions< AnalysisDomainTy, Container >
Definition at line 629 of file FlowFunctions.h.
Member Typedef Documentation
container_type
template<typename AnalysisDomainTy , typename Container > using psr::FlowFunctions< AnalysisDomainTy, Container >::container_type = typename FlowFunctionType::container_type
Definition at line 645 of file FlowFunctions.h.
d_t
template<typename AnalysisDomainTy , typename Container > using psr::FlowFunctions< AnalysisDomainTy, Container >::d_t = typename AnalysisDomainTy::d_t
Definition at line 638 of file FlowFunctions.h.
f_t
template<typename AnalysisDomainTy , typename Container > using psr::FlowFunctions< AnalysisDomainTy, Container >::f_t = typename AnalysisDomainTy::f_t
Definition at line 639 of file FlowFunctions.h.
FlowFunctionPtrType
template<typename AnalysisDomainTy , typename Container > using psr::FlowFunctions< AnalysisDomainTy, Container >::FlowFunctionPtrType = typename FlowFunctionType::FlowFunctionPtrType
Definition at line 643 of file FlowFunctions.h.
FlowFunctionType
template<typename AnalysisDomainTy , typename Container > using psr::FlowFunctions< AnalysisDomainTy, Container >::FlowFunctionType = FlowFunction<d_t, Container>
Definition at line 642 of file FlowFunctions.h.
n_t
template<typename AnalysisDomainTy , typename Container > using psr::FlowFunctions< AnalysisDomainTy, Container >::n_t = typename AnalysisDomainTy::n_t
Definition at line 640 of file FlowFunctions.h.
Constructor & Destructor Documentation
~FlowFunctions()
template<typename AnalysisDomainTy , typename Container > virtual psr::FlowFunctions< AnalysisDomainTy, Container >::~FlowFunctions () virtual default
Member Function Documentation
applyUnbalancedRetFlowFunctionSideEffects()
template<typename AnalysisDomainTy , typename Container > virtual void psr::FlowFunctions< AnalysisDomainTy, Container >::applyUnbalancedRetFlowFunctionSideEffects (f_t CalleeFun, n_t ExitInst, d_t Source) inline virtual
Performs any side-effects of a return-flow-function
In case of unbalanced returns (if the option followReturnsPastSeeds is activated in the IfdsIdeSolverConfig), we will eventually reach a function that is not called from other functions. Still, we may want to apply a return-flow-function – just for its side-effects, such as registering a taint
Definition at line 811 of file FlowFunctions.h.
getCallFlowFunction()
template<typename AnalysisDomainTy , typename Container > virtual FlowFunctionPtrType psr::FlowFunctions< AnalysisDomainTy, Container >::getCallFlowFunction (n_t CallInst, f_t CalleeFun) pure virtual
Handles call flows: describes the effects of a function call at callInst to the callee target destFun. If a call instruction has multiple callee targets, for instance, because it is an indirect function call that cannot be analyzed precisely in a static manner, the call flow function will be queried for each callee target.
This flow function usually handles parameter passing and maps actual to formal parameters. If an analysis writer does not wish to analyze a given callee target they can return a flow function implementation that kills all data-flow facts (e.g. KillAll) such that call is not followed. A commonly used trick to model the effects of functions that are not present (e.g. library functions such as malloc(), free(), etc.) is to kill all facts at the call to the respective target and plugin the semantics in the call-to-return flow function. In the call-to-return flow function, an analysis writer can check if the function of interest is one of the possible targets and then, return a flow function implementation that describes the special semantics of that function call.
Let start_point be the starting point of the callee target CalleeFun.
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds right before the CallInst. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each target fact that is generated will hold before start_point.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before CallInst. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass as identity into the callee target
f(o) -> {q}       // map actual o into formal q
f(p) -> {r}       // map actual p into formal r
f(.) -> {}        // kill all other facts that are not visible to the
                  // callee target
The above implementation corresponds to the following edges in the exploded supergraph.
                           0  o  p   ...
                            \  \  \  ...
x = CalleeFun(o, p, ...)     \  \  +----------------+
                              \  +----------------  |
                                +-------------+  +  |
                                     ...      |  |  |
                                     ...      |  |  |
                           0  o  p   ...      |  |  |
                                              |  |  |
                                              |  |  |
                                              |  |  |
                    Ty CalleeFun(q, r, ...)   |  |  |
                                              v  v  v
                                              0  q  r   ...
                                start point
Implemented in psr::DefaultAliasAwareIDEProblem< AnalysisDomainTy >, psr::DefaultAliasAwareIFDSProblem, psr::DefaultNoAliasIDEProblem< AnalysisDomainTy >, psr::DefaultNoAliasIFDSProblem, psr::DefaultReachableAllocationSitesIDEProblem< AnalysisDomainTy >, psr::DefaultReachableAllocationSitesIFDSProblem, psr::IDEFeatureTaintAnalysis, psr::IDELinearConstantAnalysis, psr::IDEProtoAnalysis, psr::IDESolverTest, psr::IDETypeStateAnalysis< TypeStateDescriptionTy >, psr::IFDSConstAnalysis, psr::IFDSProtoAnalysis, psr::IFDSSignAnalysis, psr::IFDSSolverTest, psr::IFDSTaintAnalysis, psr::IFDSTypeAnalysis, psr::IFDSUninitializedVariables, psr::IDESecureHeapPropagation, and psr::XTaint::IDEExtendedTaintAnalysis.
Referenced by psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallFlowFunction().
getCallToRetFlowFunction()
template<typename AnalysisDomainTy , typename Container > virtual FlowFunctionPtrType psr::FlowFunctions< AnalysisDomainTy, Container >::getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees) pure virtual
Describes the data-flows alongsite a CallSite.
This flow function usually passes all data-flow facts that are not involved in the function call alongsite the CallSite. Data-flow facts that are not actual parameters or passed by value, modifications to those within a callee are not visible in the caller context, are mostly passed as identity. The call-to-return flow function may also be used to describe special semantics (cf. getCallFlowFunction()).
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds right before the CallSite. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each target fact that is generated will hold after CallSite.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before CallSite. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass lambda as identity alongsite the CallSite
f(o) -> {o}       // assuming that o is passed by value, it is passed
                  // alongsite the CallSite
f(p) -> {}        // assuming that p is a pointer-typed value, we need
                  // to kill p, as it will be handled by the call- and
                  // return-flow functions
f(.) -> {.}       // pass everything that is not involved in the call
                  // as identity
The above implementation corresponds to the following edges in the exploded supergraph.
                           0  o   ...
                           |  |
                           |  +-------+
                           +--------+ |
                                    | |
x = CalleeFun(o, p, ...)            | |
                                    | |
                           +--------+ |
                           |  +-------+
                           v  v
                           0  o  x   ...
Implemented in psr::DefaultAliasAwareIDEProblem< AnalysisDomainTy >, psr::DefaultAliasAwareIFDSProblem, psr::DefaultNoAliasIDEProblem< AnalysisDomainTy >, psr::DefaultNoAliasIFDSProblem, psr::DefaultReachableAllocationSitesIDEProblem< AnalysisDomainTy >, psr::DefaultReachableAllocationSitesIFDSProblem, psr::XTaint::IDEExtendedTaintAnalysis, psr::IDEFeatureTaintAnalysis, psr::IDELinearConstantAnalysis, psr::IDEProtoAnalysis, psr::IDESecureHeapPropagation, psr::IDESolverTest, psr::IDETypeStateAnalysis< TypeStateDescriptionTy >, psr::IFDSConstAnalysis, psr::IFDSProtoAnalysis, psr::IFDSSignAnalysis, psr::IFDSSolverTest, psr::IFDSTaintAnalysis, psr::IFDSTypeAnalysis, and psr::IFDSUninitializedVariables.
Referenced by psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetFlowFunction().
getNormalFlowFunction()
template<typename AnalysisDomainTy , typename Container > virtual FlowFunctionPtrType psr::FlowFunctions< AnalysisDomainTy, Container >::getNormalFlowFunction (n_t Curr, n_t Succ) pure virtual
Describes the effects of the current instruction, i.e. data-flows, along normal (non-call, non-return) instructions. Analysis writers are free to inspect the successor instructions, too, as a lookahead.
Let instruction_1 := Curr, instruction_2 := Succ, and 0 the tautological lambda fact.
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds before the current statement under analysis. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each combination of input fact d_i (given as an input to f) and respective output facts (f(d_i)) represents an edge that must be "drawn" to construct the exploded supergraph for the analysis problem to be solved.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before instruction_1. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass the lambda (or zero fact) as identity
f(o) -> {o, x}    // generate a new fact x from o
f(.) -> {.}       // pass all other facts that hold before
                  // instruction_1 as identity
The above implementation corresponds to the following edges in the exploded supergraph.
                        0  o      ...
                        |  |\     ...
x = instruction_1 o p   |  | \    ...
                        |  |  |   ...
                        v  v  v   ...
                        0  o  x   ...
y = instruction_2 q r
Implemented in psr::DefaultAliasAwareIDEProblem< AnalysisDomainTy >, psr::DefaultAliasAwareIFDSProblem, psr::DefaultNoAliasIDEProblem< AnalysisDomainTy >, psr::DefaultNoAliasIFDSProblem, psr::DefaultReachableAllocationSitesIDEProblem< AnalysisDomainTy >, psr::DefaultReachableAllocationSitesIFDSProblem, psr::XTaint::IDEExtendedTaintAnalysis, psr::IDEFeatureTaintAnalysis, psr::IDELinearConstantAnalysis, psr::IDEProtoAnalysis, psr::IDESecureHeapPropagation, psr::IDESolverTest, psr::IDETypeStateAnalysis< TypeStateDescriptionTy >, psr::IFDSConstAnalysis, psr::IFDSProtoAnalysis, psr::IFDSSignAnalysis, psr::IFDSSolverTest, psr::IFDSTaintAnalysis, psr::IFDSTypeAnalysis, and psr::IFDSUninitializedVariables.
Referenced by psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalFlowFunction().
getRetFlowFunction()
template<typename AnalysisDomainTy , typename Container > virtual FlowFunctionPtrType psr::FlowFunctions< AnalysisDomainTy, Container >::getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, n_t RetSite) pure virtual
Handles return flows: describes the data-flows from an ExitInst to the corresponding RetSite.
This flow function usually handles the returned value of the callee target as well as the parameter mapping back to the caller of CalleeFun for pointer parameters as modifications made by CalleeFun are visible to the caller. Data-flow facts that are not returned or escape via function pointer parameters (or global variables) are usually killed.
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds right before the ExitInst. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each target fact that is generated will hold after CallSite.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before ExitInst. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass as identity into the callee target
f(r) -> {x}       // map return value to lhs variable at CallSite
f(q) -> {o}       // map pointer-typed formal q to actual o
f(.) -> {}        // kill all other facts that are not visible to the
                  // caller
The above implementation corresponds to the following edges in the exploded supergraph.
                        0  o   ...
x = CalleeFun(o, ...)
                              +------------------+
                           +--|---------------+  |
                        +--|--|------------+  |  |
                        v  v  v   ...      |  |  |
                        0  o  x   ...      |  |  |
                                           |  |  |
                                           |  |  |
                                           |  |  |
                    Ty CalleeFun(q, ...)   |  |  |
                                           |  |  |
                                           0  q  r   ...
                                return r
Implemented in psr::DefaultAliasAwareIDEProblem< AnalysisDomainTy >, psr::DefaultAliasAwareIFDSProblem, psr::DefaultNoAliasIDEProblem< AnalysisDomainTy >, psr::DefaultNoAliasIFDSProblem, psr::DefaultReachableAllocationSitesIDEProblem< AnalysisDomainTy >, psr::DefaultReachableAllocationSitesIFDSProblem, psr::IDEFeatureTaintAnalysis, psr::IDELinearConstantAnalysis, psr::IDEProtoAnalysis, psr::IFDSProtoAnalysis, psr::XTaint::IDEExtendedTaintAnalysis, psr::IDESolverTest, psr::IDETypeStateAnalysis< TypeStateDescriptionTy >, psr::IFDSConstAnalysis, psr::IFDSSignAnalysis, psr::IFDSSolverTest, psr::IFDSTaintAnalysis, psr::IFDSTypeAnalysis, psr::IFDSUninitializedVariables, and psr::IDESecureHeapPropagation.
Referenced by psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getRetFlowFunction().
getSummaryFlowFunction()
template<typename AnalysisDomainTy , typename Container > virtual FlowFunctionPtrType psr::FlowFunctions< AnalysisDomainTy, Container >::getSummaryFlowFunction (n_t , f_t) inline virtual
May be used to encode special sementics of a given callee target (whose call should not be directly followed by the data-flow solver) similar to the getCallFlowFunction() --> getCallToRetFlowFunction() trick (cf. getCallFlowFunction()).
The default implementation returns a nullptr to indicate that the mechanism should not be used.
Reimplemented in psr::IDEFeatureTaintAnalysis, psr::IDEProtoAnalysis, psr::IDESolverTest, psr::IDETypeStateAnalysis< TypeStateDescriptionTy >, psr::IFDSConstAnalysis, psr::IFDSProtoAnalysis, psr::IFDSSignAnalysis, psr::IFDSSolverTest, psr::IFDSTaintAnalysis, psr::IFDSUninitializedVariables, psr::IDESecureHeapPropagation, psr::XTaint::IDEExtendedTaintAnalysis, psr::IDELinearConstantAnalysis, and psr::IFDSTypeAnalysis.
Definition at line 876 of file FlowFunctions.h.
Referenced by psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryFlowFunction().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/FlowFunctions.h