PhASAR: psr::IDETabulationProblem< AnalysisDomainTy, Container > Class Template Reference
psr::IDETabulationProblem< AnalysisDomainTy, Container > Class Template Reference abstract
The analysis problem interface for IDE problems (solvable by the IDESolver). Create a subclass from this and override all pure-virtual functions to create your own IDE analysis.
#include "phasar/DataFlow/IfdsIde/IDETabulationProblem.h"
Public Types
using ProblemAnalysisDomain = AnalysisDomainTy
using d_t = typename AnalysisDomainTy::d_t
using n_t = typename AnalysisDomainTy::n_t
using f_t = typename AnalysisDomainTy::f_t
using t_t = typename AnalysisDomainTy::t_t
using v_t = typename AnalysisDomainTy::v_t
using l_t = typename AnalysisDomainTy::l_t
using i_t = typename AnalysisDomainTy::i_t
using db_t = typename AnalysisDomainTy::db_t
using ConfigurationTy = HasNoConfigurationType
Public Types inherited from psr::FlowFunctions< AnalysisDomainTy, Container >
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using n_t = typename AnalysisDomainTy::n_t
using FlowFunctionType = FlowFunction< d_t, Container >
using FlowFunctionPtrType = typename FlowFunctionType::FlowFunctionPtrType
using container_type = typename FlowFunctionType::container_type
Public Types inherited from psr::EdgeFunctions< AnalysisDomainTy >
using n_t = typename AnalysisDomainTy::n_t
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using l_t = typename AnalysisDomainTy::l_t
Public Types inherited from psr::JoinLattice< AnalysisDomainTy >
using l_t = typename AnalysisDomainTy::l_t
Public Types inherited from psr::SemiRing< AnalysisDomainTy >
using l_t = typename AnalysisDomainTy::l_t
Public Member Functions
IDETabulationProblem (const db_t *IRDB, std::vector< std::string > EntryPoints, std::optional< d_t > ZeroValue) noexcept(std::is_nothrow_move_constructible_v< d_t >)
IDETabulationProblem (IDETabulationProblem &&) noexcept=default
IDETabulationProblem & operator= (IDETabulationProblem &&) noexcept=default
IDETabulationProblem (const IDETabulationProblem &)=delete
IDETabulationProblem & operator= (const IDETabulationProblem &)=delete
~IDETabulationProblem () override=default
void setAnalysisPrinter (MaybeUniquePtr< AnalysisPrinterBase< AnalysisDomainTy > > P)
constexpr AnalysisPrinterBase< AnalysisDomainTy > & printer () noexcept
constexpr MaybeUniquePtr< AnalysisPrinterBase< AnalysisDomainTy > > consumePrinter () noexcept
virtual bool isZeroValue (d_t FlowFact) const noexcept
virtual InitialSeeds< n_t, d_t, l_t > initialSeeds ()=0
ByConstRef< d_t > getZeroValue () const
Returns the special tautological lambda (or zero) fact.
void initializeZeroValue (d_t Zero) noexcept(std::is_nothrow_assignable_v< std::optional< d_t > &, d_t && >)
void setIFDSIDESolverConfig (IFDSIDESolverConfig Config) noexcept
Sets the configuration to be used by the IFDS/IDE solver.
IFDSIDESolverConfig & getIFDSIDESolverConfig () noexcept
Returns the configuration of the IFDS/IDE solver.
virtual void emitTextReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream &OS=llvm::outs())
virtual void emitGraphicalReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream &OS=llvm::outs())
virtual bool setSoundness (Soundness)
const db_t * getProjectIRDB () const noexcept
llvm::ArrayRef< std::string > getEntryPoints () const noexcept
Public Member Functions inherited from psr::FlowFunctions< AnalysisDomainTy, Container >
virtual ~FlowFunctions ()=default
virtual FlowFunctionPtrType getNormalFlowFunction (n_t Curr, n_t Succ)=0
virtual FlowFunctionPtrType getCallFlowFunction (n_t CallInst, f_t CalleeFun)=0
virtual FlowFunctionPtrType getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, n_t RetSite)=0
virtual void applyUnbalancedRetFlowFunctionSideEffects (f_t CalleeFun, n_t ExitInst, d_t Source)
virtual FlowFunctionPtrType getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees)=0
virtual FlowFunctionPtrType getSummaryFlowFunction (n_t, f_t)
Public Member Functions inherited from psr::EdgeFunctions< AnalysisDomainTy >
virtual ~EdgeFunctions ()=default
virtual EdgeFunction< l_t > getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t Succ, d_t SuccNode)=0
virtual EdgeFunction< l_t > getCallEdgeFunction (n_t CallInst, d_t SrcNode, f_t CalleeFun, d_t DestNode)=0
virtual EdgeFunction< l_t > getReturnEdgeFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, d_t ExitNode, n_t RetSite, d_t RetNode)=0
virtual EdgeFunction< l_t > getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t RetSite, d_t RetSiteNode, llvm::ArrayRef< f_t > Callees)=0
virtual EdgeFunction< l_t > getSummaryEdgeFunction (n_t, d_t, n_t, d_t)
Public Member Functions inherited from psr::JoinLattice< AnalysisDomainTy >
virtual ~JoinLattice ()=default
virtual l_t topElement ()
virtual l_t bottomElement ()
virtual l_t join (l_t Lhs, l_t Rhs)
Public Member Functions inherited from psr::SemiRing< AnalysisDomainTy >
virtual ~SemiRing ()=default
virtual EdgeFunction< l_t > extend (const EdgeFunction< l_t > &L, const EdgeFunction< l_t > &R)
virtual EdgeFunction< l_t > combine (const EdgeFunction< l_t > &L, const EdgeFunction< l_t > &R)
Public Member Functions inherited from psr::AllTopFnProvider< AnalysisDomainTy >
virtual ~AllTopFnProvider ()=default
virtual EdgeFunction< typename AnalysisDomainTy::l_t > allTopFunction ()
Returns an edge function that represents the top element of the analysis.
Protected Member Functions
FlowFunctions< AnalysisDomainTy, Container >::FlowFunctionPtrType generateFromZero (d_t FactToGenerate)
template<typename D = d_t, typename L = l_t>
void onResult (n_t Instr, D &&DfFact, L &&LatticeElement, DataFlowAnalysisType AnalysisType)
template<typename D = d_t>
requires std::is_same_v<l_t, BinaryDomain>
void onResult (n_t Instr, D &&DfFact, DataFlowAnalysisType AnalysisType)
InitialSeeds< n_t, d_t, l_t > createDefaultSeeds ()
Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
auto unionFlows (FlowFunctionPtrTypeOf< F1 > OneFF, FlowFunctionPtrTypeOf< F2 > OtherFF)
Protected Attributes
const db_t * IRDB {}
std::vector< std::string > EntryPoints
std::optional< d_t > ZeroValue
IFDSIDESolverConfig SolverConfig {}
Soundness SF = Soundness::Soundy
MaybeUniquePtr< AnalysisPrinterBase< AnalysisDomainTy > > Printer
Additional Inherited Members
Protected Types inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
using d_t = AnalysisDomainTy::d_t
using container_type = Container
Static Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
static auto identityFlow ()
static auto lambdaFlow (Fn &&F)
static auto generateFlow (d_t FactToGenerate, d_t From)
static auto generateFlowIf (d_t FactToGenerate, Fn Predicate)
static auto generateManyFlows (Range &&FactsToGenerate, d_t From)
static auto killFlow (d_t FactToKill)
static auto killFlowIf (Fn Predicate)
static auto killManyFlows (Range &&FactsToKill)
static auto killAllFlows ()
static auto generateFlowAndKillAllOthers (d_t FactToGenerate, d_t From)
static auto generateManyFlowsAndKillAllOthers (Range &&FactsToGenerate, d_t From)
static auto transferFlow (d_t FactToGenerate, d_t From)
Detailed Description
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>>
class psr::IDETabulationProblem< AnalysisDomainTy, Container >
The analysis problem interface for IDE problems (solvable by the IDESolver). Create a subclass from this and override all pure-virtual functions to create your own IDE analysis.
For more information on how to write an IDE analysis, see Writing an IDE Analysis
Definition at line 69 of file IDETabulationProblem.h.
Member Typedef Documentation
ConfigurationTy
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::ConfigurationTy = HasNoConfigurationType
Definition at line 85 of file IDETabulationProblem.h.
d_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::d_t = typename AnalysisDomainTy::d_t
Definition at line 76 of file IDETabulationProblem.h.
db_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::db_t = typename AnalysisDomainTy::db_t
Definition at line 83 of file IDETabulationProblem.h.
f_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::f_t = typename AnalysisDomainTy::f_t
Definition at line 78 of file IDETabulationProblem.h.
i_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::i_t = typename AnalysisDomainTy::i_t
Definition at line 82 of file IDETabulationProblem.h.
l_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::l_t = typename AnalysisDomainTy::l_t
Definition at line 81 of file IDETabulationProblem.h.
n_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::n_t = typename AnalysisDomainTy::n_t
Definition at line 77 of file IDETabulationProblem.h.
ProblemAnalysisDomain
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::ProblemAnalysisDomain = AnalysisDomainTy
Definition at line 75 of file IDETabulationProblem.h.
t_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::t_t = typename AnalysisDomainTy::t_t
Definition at line 79 of file IDETabulationProblem.h.
v_t
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDETabulationProblem< AnalysisDomainTy, Container >::v_t = typename AnalysisDomainTy::v_t
Definition at line 80 of file IDETabulationProblem.h.
Constructor & Destructor Documentation
IDETabulationProblem() [1/3]
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::IDETabulationProblem< AnalysisDomainTy, Container >::IDETabulationProblem (const db_t * IRDB, std::vector< std::string > EntryPoints, std::optional< d_t > ZeroValue) inline explicit noexcept
Takes an IR database (IRDB) and collects information from it to create a tabulation problem.
Parameters
[in] IRDB The project IR database, that holds the code under analysis
[in] EntryPoints The (mangled) names of all entry functions of the target being analyzed, given as a vector of strings. An example would simply be {"main"}. To set every function as entry point, pass "__ALL__"
[in] ZeroValue Provides the special tautological zero value (aka. Λ). If not provided here, you must set it via initializeZeroValue().
Definition at line 98 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::IRDB.
IDETabulationProblem() [2/3]
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::IDETabulationProblem< AnalysisDomainTy, Container >::IDETabulationProblem (IDETabulationProblem< AnalysisDomainTy, Container > &&) default noexcept
IDETabulationProblem() [3/3]
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::IDETabulationProblem< AnalysisDomainTy, Container >::IDETabulationProblem (const IDETabulationProblem< AnalysisDomainTy, Container > &) delete
~IDETabulationProblem()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::IDETabulationProblem< AnalysisDomainTy, Container >::~IDETabulationProblem () override default
Member Function Documentation
consumePrinter()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> constexpr MaybeUniquePtr< AnalysisPrinterBase< AnalysisDomainTy > > psr::IDETabulationProblem< AnalysisDomainTy, Container >::consumePrinter () inline constexpr noexcept
Definition at line 133 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::Printer.
createDefaultSeeds()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> InitialSeeds< n_t, d_t, l_t > psr::IDETabulationProblem< AnalysisDomainTy, Container >::createDefaultSeeds () inline protected
Seeds that just start with ZeroValue and bottomElement() at the starting points of each EntryPoint function. Takes the ALL EntryPoint into account.
Definition at line 221 of file IDETabulationProblem.h.
References psr::addSeedsForStartingPoints(), psr::JoinLattice< AnalysisDomainTy >::bottomElement(), psr::IDETabulationProblem< AnalysisDomainTy, Container >::EntryPoints, psr::IDETabulationProblem< AnalysisDomainTy, Container >::getZeroValue(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::IRDB.
emitGraphicalReport()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDETabulationProblem< AnalysisDomainTy, Container >::emitGraphicalReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream & OS = llvm::outs()) inline virtual
Generates a graphical report, e.g. in html or other markup languages, of the results that is written to the specified output stream.
Definition at line 182 of file IDETabulationProblem.h.
emitTextReport()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDETabulationProblem< AnalysisDomainTy, Container >::emitTextReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream & OS = llvm::outs()) inline virtual
Generates a text report of the results that is written to the specified output stream.
Reimplemented in psr::IFDSUninitializedVariables, psr::IDESecureHeapPropagation, psr::XTaint::IDEExtendedTaintAnalysis, psr::IDEFeatureTaintAnalysis, psr::IDELinearConstantAnalysis, and psr::IDETypeStateAnalysis< TypeStateDescriptionTy >.
Definition at line 175 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::Printer.
generateFromZero()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowFunctions< AnalysisDomainTy, Container >::FlowFunctionPtrType psr::IDETabulationProblem< AnalysisDomainTy, Container >::generateFromZero (d_t FactToGenerate) inline protected
Definition at line 200 of file IDETabulationProblem.h.
References psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >::generateFlow(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::getZeroValue().
Referenced by psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getNormalFlowFunction().
getEntryPoints()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> llvm::ArrayRef< std::string > psr::IDETabulationProblem< AnalysisDomainTy, Container >::getEntryPoints () const inline noexcept
Definition at line 194 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::EntryPoints.
getIFDSIDESolverConfig()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> IFDSIDESolverConfig & psr::IDETabulationProblem< AnalysisDomainTy, Container >::getIFDSIDESolverConfig () inline noexcept
Returns the configuration of the IFDS/IDE solver.
Definition at line 168 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::SolverConfig.
Referenced by psr::PathAwareIDESolver< AnalysisDomainTy, Container >::PathAwareIDESolver().
getProjectIRDB()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> const db_t * psr::IDETabulationProblem< AnalysisDomainTy, Container >::getProjectIRDB () const inline noexcept
Definition at line 192 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::IRDB.
getZeroValue()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> ByConstRef< d_t > psr::IDETabulationProblem< AnalysisDomainTy, Container >::getZeroValue () const inline
Returns the special tautological lambda (or zero) fact.
Definition at line 151 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::ZeroValue.
Referenced by psr::IDETabulationProblem< AnalysisDomainTy, Container >::createDefaultSeeds(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::generateFromZero().
initializeZeroValue()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDETabulationProblem< AnalysisDomainTy, Container >::initializeZeroValue (d_t Zero) inline noexcept
Definition at line 156 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::ZeroValue.
initialSeeds()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual InitialSeeds< n_t, d_t, l_t > psr::IDETabulationProblem< AnalysisDomainTy, Container >::initialSeeds () pure virtual
Returns initial seeds to be used for the analysis. This is a mapping of statements to initial analysis facts.
Implemented in psr::CFLFieldSensIFDSProblem, psr::XTaint::IDEExtendedTaintAnalysis, psr::IDEFeatureTaintAnalysis, psr::IDEGeneralizedLCA, psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >, psr::IDELinearConstantAnalysis, psr::IDEProtoAnalysis, psr::IDESecureHeapPropagation, psr::IDESolverTest, psr::IDETypeStateAnalysis< TypeStateDescriptionTy >, psr::IFDSConstAnalysis, psr::IFDSProtoAnalysis, psr::IFDSSignAnalysis, psr::IFDSSolverTest, psr::IFDSTaintAnalysis, psr::IFDSTypeAnalysis, and psr::IFDSUninitializedVariables.
Referenced by psr::CFLFieldSensIFDSProblem::initialSeeds().
isZeroValue()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual bool psr::IDETabulationProblem< AnalysisDomainTy, Container >::isZeroValue (d_t FlowFact) const inline virtual noexcept
Checks if the given data-flow fact is the special tautological lambda (or zero) fact.
Reimplemented in psr::XTaint::IDEExtendedTaintAnalysis, psr::IDELinearConstantAnalysis, psr::IDEProtoAnalysis, psr::IDESecureHeapPropagation, psr::IDESolverTest, psr::IDETypeStateAnalysis< TypeStateDescriptionTy >, psr::IFDSConstAnalysis, psr::IFDSProtoAnalysis, psr::IFDSSignAnalysis, psr::IFDSSolverTest, psr::IFDSTypeAnalysis, psr::IFDSUninitializedVariables, psr::IDEFeatureTaintAnalysis, and psr::IFDSTaintAnalysis.
Definition at line 141 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::ZeroValue.
onResult() [1/2]
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> template<typename D = d_t> requires std::is_same_v<l_t, BinaryDomain> void psr::IDETabulationProblem< AnalysisDomainTy, Container >::onResult (n_t Instr, D && DfFact, DataFlowAnalysisType AnalysisType) inline protected
Definition at line 214 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::Printer, and PSR_FWD.
onResult() [2/2]
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> template<typename D = d_t, typename L = l_t> void psr::IDETabulationProblem< AnalysisDomainTy, Container >::onResult (n_t Instr, D && DfFact, L && LatticeElement, DataFlowAnalysisType AnalysisType) inline protected
Definition at line 206 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::Printer, and PSR_FWD.
operator=() [1/2]
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> IDETabulationProblem & psr::IDETabulationProblem< AnalysisDomainTy, Container >::operator= (const IDETabulationProblem< AnalysisDomainTy, Container > &) delete
operator=() [2/2]
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> IDETabulationProblem & psr::IDETabulationProblem< AnalysisDomainTy, Container >::operator= (IDETabulationProblem< AnalysisDomainTy, Container > &&) default noexcept
printer()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> constexpr AnalysisPrinterBase< AnalysisDomainTy > & psr::IDETabulationProblem< AnalysisDomainTy, Container >::printer () inline constexpr noexcept
Definition at line 127 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::Printer.
setAnalysisPrinter()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDETabulationProblem< AnalysisDomainTy, Container >::setAnalysisPrinter (MaybeUniquePtr< AnalysisPrinterBase< AnalysisDomainTy > > P) inline
Definition at line 118 of file IDETabulationProblem.h.
References psr::NullAnalysisPrinter< AnalysisDomainTy >::getInstance(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::Printer.
setIFDSIDESolverConfig()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDETabulationProblem< AnalysisDomainTy, Container >::setIFDSIDESolverConfig (IFDSIDESolverConfig Config) inline noexcept
Sets the configuration to be used by the IFDS/IDE solver.
Definition at line 163 of file IDETabulationProblem.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::SolverConfig.
setSoundness()
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual bool psr::IDETabulationProblem< AnalysisDomainTy, Container >::setSoundness (Soundness) inline virtual
Sets the level of soundness to be used by the analysis. Returns false if the level of soundness is ignored. Otherwise, true.
Definition at line 190 of file IDETabulationProblem.h.
Member Data Documentation
EntryPoints
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> std::vector<std::string> psr::IDETabulationProblem< AnalysisDomainTy, Container >::EntryPoints protected
Definition at line 235 of file IDETabulationProblem.h.
Referenced by psr::IDETabulationProblem< AnalysisDomainTy, Container >::createDefaultSeeds(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::getEntryPoints().
IRDB
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> const db_t* psr::IDETabulationProblem< AnalysisDomainTy, Container >::IRDB {} protected
Definition at line 234 of file IDETabulationProblem.h.
Referenced by psr::IDETabulationProblem< AnalysisDomainTy, Container >::createDefaultSeeds(), psr::IDETabulationProblem< AnalysisDomainTy, Container >::getProjectIRDB(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::IDETabulationProblem().
Printer
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> MaybeUniquePtr<AnalysisPrinterBase<AnalysisDomainTy> > psr::IDETabulationProblem< AnalysisDomainTy, Container >::Printer protected
Definition at line 242 of file IDETabulationProblem.h.
Referenced by psr::IDETabulationProblem< AnalysisDomainTy, Container >::consumePrinter(), psr::IDETabulationProblem< AnalysisDomainTy, Container >::emitTextReport(), psr::IDETabulationProblem< AnalysisDomainTy, Container >::onResult(), psr::IDETabulationProblem< AnalysisDomainTy, Container >::onResult(), psr::IDETabulationProblem< AnalysisDomainTy, Container >::printer(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::setAnalysisPrinter().
SF
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> Soundness psr::IDETabulationProblem< AnalysisDomainTy, Container >::SF = Soundness::Soundy protected
Definition at line 240 of file IDETabulationProblem.h.
SolverConfig
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> IFDSIDESolverConfig psr::IDETabulationProblem< AnalysisDomainTy, Container >::SolverConfig {} protected
Definition at line 238 of file IDETabulationProblem.h.
Referenced by psr::IDETabulationProblem< AnalysisDomainTy, Container >::getIFDSIDESolverConfig(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::setIFDSIDESolverConfig().
ZeroValue
template<IdeAnalysisDomain AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>> std::optional<d_t> psr::IDETabulationProblem< AnalysisDomainTy, Container >::ZeroValue protected
Definition at line 236 of file IDETabulationProblem.h.
Referenced by psr::IDETabulationProblem< AnalysisDomainTy, Container >::getZeroValue(), psr::IDETabulationProblem< AnalysisDomainTy, Container >::initializeZeroValue(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::isZeroValue().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/IDETabulationProblem.h