PhASAR: psr::DIBasedTypeHierarchy Class Reference
psr::DIBasedTypeHierarchy Class Reference
Represents the type hierarchy of the target program.
#include "phasar/PhasarLLVM/TypeHierarchy/DIBasedTypeHierarchy.h"
Public Types
using ClassType = const llvm::DIType *
using f_t = const llvm::Function *
Public Member Functions
DIBasedTypeHierarchy (const LLVMProjectIRDB &IRDB)
Creates a type hierarchy based on an intermediate representation database.
DIBasedTypeHierarchy (const LLVMProjectIRDB *IRDB, const DIBasedTypeHierarchyData &SerializedData)
Loads an already computed type hierarchy.
~DIBasedTypeHierarchy () override=default
bool hasType (ClassType Type) const override
bool isSubType (ClassType Type, ClassType SubType) const override
std::set< ClassType > getSubTypes (ClassType Type) const override
llvm::iterator_range< const ClassType * > subTypesOf (ClassType Ty) const noexcept
A more efficient version of getSubTypes()
ClassType getType (llvm::StringRef TypeName) const noexcept override
std::vector< ClassType > getAllTypes () const override
const auto & getAllVTables () const noexcept
llvm::StringRef getTypeName (ClassType Type) const override
size_t size () const noexcept override
bool empty () const noexcept override
void print (llvm::raw_ostream &OS=llvm::outs()) const override
void printAsDot (llvm::raw_ostream &OS=llvm::outs()) const
Prints the class hierarchy to an ostream in dot format.
void printAsJson (llvm::raw_ostream &OS=llvm::outs()) const override
Prints the class hierarchy to an ostream in JSON format.
Public Member Functions inherited from psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >
virtual ~TypeHierarchy ()=default
Static Public Member Functions
static llvm::StringRef typeName (ClassType Type)
Static Public Attributes
static constexpr llvm::StringLiteral StructPrefix = "struct."
static constexpr llvm::StringLiteral ClassPrefix = "class."
static constexpr llvm::StringLiteral VTablePrefix = "_ZTV"
static constexpr llvm::StringLiteral VTablePrefixDemang
static constexpr llvm::StringLiteral PureVirtualCallName
Detailed Description
Represents the type hierarchy of the target program.
Note
This class only works, if the target program's IR was generated with debug information. Pass -g to the compiler to achieve this.
Definition at line 32 of file DIBasedTypeHierarchy.h.
Member Typedef Documentation
ClassType
using psr::DIBasedTypeHierarchy::ClassType = const llvm::DIType *
Definition at line 35 of file DIBasedTypeHierarchy.h.
f_t
using psr::DIBasedTypeHierarchy::f_t = const llvm::Function *
Definition at line 36 of file DIBasedTypeHierarchy.h.
Constructor & Destructor Documentation
DIBasedTypeHierarchy() [1/2]
psr::DIBasedTypeHierarchy::DIBasedTypeHierarchy (const LLVMProjectIRDB & IRDB) explicit
Creates a type hierarchy based on an intermediate representation database.
Parameters
[in] IRDB The IR database of which the type hierarchy will be based upon. This MUST contain debug information for the algorithm to work!
DIBasedTypeHierarchy() [2/2]
psr::DIBasedTypeHierarchy::DIBasedTypeHierarchy (const LLVMProjectIRDB * IRDB, const DIBasedTypeHierarchyData & SerializedData) explicit
Loads an already computed type hierarchy.
Parameters
[in] IRDB The IR database of the type hierarchy.
[in] SerializedData The already existing type hierarchy, given by the appropiate class DIBasedTypeHierarchyData, which contains all neccesary information.
~DIBasedTypeHierarchy()
psr::DIBasedTypeHierarchy::~DIBasedTypeHierarchy () override default
Member Function Documentation
empty()
bool psr::DIBasedTypeHierarchy::empty () const inline override virtual noexcept
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 105 of file DIBasedTypeHierarchy.h.
getAllTypes()
std::vector< ClassType > psr::DIBasedTypeHierarchy::getAllTypes () const inline override virtual
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 84 of file DIBasedTypeHierarchy.h.
getAllVTables()
const auto & psr::DIBasedTypeHierarchy::getAllVTables () const inline noexcept
Definition at line 88 of file DIBasedTypeHierarchy.h.
getSubTypes()
std::set< ClassType > psr::DIBasedTypeHierarchy::getSubTypes (ClassType Type) const inline override virtual
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 70 of file DIBasedTypeHierarchy.h.
References subTypesOf().
getType()
ClassType psr::DIBasedTypeHierarchy::getType (llvm::StringRef TypeName) const inline override virtual noexcept
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 80 of file DIBasedTypeHierarchy.h.
getTypeName()
llvm::StringRef psr::DIBasedTypeHierarchy::getTypeName (ClassType Type) const inline override virtual
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 98 of file DIBasedTypeHierarchy.h.
References typeName().
hasType()
bool psr::DIBasedTypeHierarchy::hasType (ClassType Type) const inline override virtual
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 61 of file DIBasedTypeHierarchy.h.
isSubType()
bool psr::DIBasedTypeHierarchy::isSubType (ClassType Type, ClassType SubType) const inline override virtual
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 65 of file DIBasedTypeHierarchy.h.
References subTypesOf().
print()
void psr::DIBasedTypeHierarchy::print (llvm::raw_ostream & OS = llvm::outs()) const override virtual
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
printAsDot()
void psr::DIBasedTypeHierarchy::printAsDot (llvm::raw_ostream & OS = llvm::outs()) const
Prints the class hierarchy to an ostream in dot format.
Parameters
OS outputstream
printAsJson()
void psr::DIBasedTypeHierarchy::printAsJson (llvm::raw_ostream & OS = llvm::outs()) const override virtual
Prints the class hierarchy to an ostream in JSON format.
Parameters
OS outputstream
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
size()
size_t psr::DIBasedTypeHierarchy::size () const inline override virtual noexcept
Implements psr::TypeHierarchy< const llvm::DIType *, const llvm::Function * >.
Definition at line 102 of file DIBasedTypeHierarchy.h.
subTypesOf()
llvm::iterator_range< const ClassType * > psr::DIBasedTypeHierarchy::subTypesOf (ClassType Ty) const noexcept
A more efficient version of getSubTypes()
Referenced by getSubTypes(), and isSubType().
typeName()
static llvm::StringRef psr::DIBasedTypeHierarchy::typeName (ClassType Type) inline static
Definition at line 90 of file DIBasedTypeHierarchy.h.
Referenced by getTypeName().
Member Data Documentation
ClassPrefix
constexpr llvm::StringLiteral psr::DIBasedTypeHierarchy::ClassPrefix = "class." inline static constexpr
Definition at line 39 of file DIBasedTypeHierarchy.h.
PureVirtualCallName
constexpr llvm::StringLiteral psr::DIBasedTypeHierarchy::PureVirtualCallName inline static constexpr
Initial value:
=
      "__cxa_pure_virtual"
Definition at line 43 of file DIBasedTypeHierarchy.h.
StructPrefix
constexpr llvm::StringLiteral psr::DIBasedTypeHierarchy::StructPrefix = "struct." inline static constexpr
Definition at line 38 of file DIBasedTypeHierarchy.h.
VTablePrefix
constexpr llvm::StringLiteral psr::DIBasedTypeHierarchy::VTablePrefix = "_ZTV" inline static constexpr
Definition at line 40 of file DIBasedTypeHierarchy.h.
VTablePrefixDemang
constexpr llvm::StringLiteral psr::DIBasedTypeHierarchy::VTablePrefixDemang inline static constexpr
Initial value:
=
      "vtable for "
Definition at line 41 of file DIBasedTypeHierarchy.h.
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/TypeHierarchy/DIBasedTypeHierarchy.h