PhASAR: psr::LLVMBasedICFG Class Reference
psr::LLVMBasedICFG Class Reference
A class that implements a inter-procedural control flow graph. Conforms to the ICFGBase CRTP interface.
#include "phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h"
Public Types
using f_t = typename CFGTraits< Derived >::f_t
using n_t = typename CFGTraits< Derived >::n_t
Public Types inherited from psr::ICFGBase< LLVMBasedICFG >
using n_t = typename CFGTraits< LLVMBasedICFG >::n_t
using f_t = typename CFGTraits< LLVMBasedICFG >::f_t
Public Member Functions
LLVMBasedICFG (LLVMProjectIRDB *IRDB, CallGraphAnalysisType CGType, llvm::ArrayRef< std::string > EntryPoints={}, DIBasedTypeHierarchy *TH=nullptr, LLVMAliasInfoRef PT=nullptr, Soundness S=Soundness::Soundy, bool IncludeGlobals=true)
LLVMBasedICFG (LLVMProjectIRDB *IRDB, Resolver &CGResolver, llvm::ArrayRef< std::string > EntryPoints={}, Soundness S=Soundness::Soundy, bool IncludeGlobals=true)
LLVMBasedICFG (LLVMProjectIRDB *IRDB, Resolver &CGResolver, LLVMVFTableProvider VTP, llvm::ArrayRef< std::string > EntryPoints={}, Soundness S=Soundness::Soundy, bool IncludeGlobals=true)
LLVMBasedICFG (CallGraph< n_t, f_t > CG, const LLVMProjectIRDB *IRDB)
Creates an ICFG with an already given call-graph.
LLVMBasedICFG (const LLVMProjectIRDB *IRDB, const CallGraphData &SerializedCG)
~LLVMBasedICFG ()
LLVMBasedICFG (const LLVMBasedICFG &)=delete
LLVMBasedICFG & operator= (const LLVMBasedICFG &)=delete
LLVMBasedICFG (LLVMBasedICFG &&) noexcept=default
LLVMBasedICFG & operator= (LLVMBasedICFG &&) noexcept=default
std::string exportICFGAsDot (bool WithSourceCodeInfo=true) const
nlohmann::json exportICFGAsJson (bool WithSourceCodeInfo=true) const
Similar to exportICFGAsDot, but exports the ICFG as JSON instead.
size_t getNumVertexFunctions () const noexcept
auto getAllVertexFunctions () const noexcept
const LLVMProjectIRDB * getIRDB () const noexcept
Gets the underlying IRDB.
void print (ByConstRef< f_t > Fun, llvm::raw_ostream &OS) const
void print (llvm::raw_ostream &OS=llvm::outs()) const
Prints the underlying call-graph as DOT to the given output-stream.
void printAsJson (llvm::raw_ostream &OS=llvm::outs()) const
Prints the underlying call-graph as Json to the given output-stream.
Public Member Functions inherited from psr::LLVMBasedCFG
LLVMBasedCFG () noexcept=default
LLVMBasedCFG (bool IgnoreDbgInstructions) noexcept
nlohmann::json exportCFGAsJson (const llvm::Function *F) const
nlohmann::json exportCFGAsSourceCodeJson (const llvm::Function *F) const
Public Member Functions inherited from psr::ICFGBase< LLVMBasedICFG >
decltype(auto) getAllFunctions () const
f_t getFunction (llvm::StringRef Fun) const
bool isIndirectFunctionCall (ByConstRef< n_t > Inst) const
bool isVirtualFunctionCall (ByConstRef< n_t > Inst) const
decltype(auto) allNonCallStartNodes () const
decltype(auto) getCallGraph () const noexcept
Returns a view to the underlying call-graph.
decltype(auto) getCalleesOfCallAt (ByConstRef< n_t > Inst) const
decltype(auto) getCallersOf (ByConstRef< f_t > Fun) const
decltype(auto) getCallsFromWithin (ByConstRef< f_t > Fun) const
Returns an iterable range of all call-instruction in the given function.
decltype(auto) getReturnSitesOfCallAt (ByConstRef< n_t > Inst) const
void print (llvm::raw_ostream &OS=llvm::outs()) const
Prints the underlying call-graph as DOT to the given output-stream.
void printAsJson (llvm::raw_ostream &OS=llvm::outs()) const
Prints the underlying call-graph as Json to the given output-stream.
size_t getNumCallSites () const noexcept
Static Public Member Functions
static bool isPhasarGenerated (const llvm::Function &F) noexcept
Returns true, if a function was generated by phasar.
Static Public Attributes
static constexpr llvm::StringLiteral GlobalCRuntimeModelName
Additional Inherited Members
Protected Member Functions inherited from psr::CRTPBase< Derived >
constexpr CRTPBase () noexcept=default
constexpr Derived & self () &noexcept
constexpr Derived && self () &&noexcept
constexpr const Derived & self () const &noexcept
Detailed Description
A class that implements a inter-procedural control flow graph. Conforms to the ICFGBase CRTP interface.
Definition at line 47 of file LLVMBasedICFG.h.
Member Typedef Documentation
f_t
using psr::ICFGBase< Derived >::f_t = typename CFGTraits<Derived>::f_t
Definition at line 31 of file ICFGBase.h.
n_t
using psr::ICFGBase< Derived >::n_t = typename CFGTraits<Derived>::n_t
Definition at line 30 of file ICFGBase.h.
Constructor & Destructor Documentation
LLVMBasedICFG() [1/7]
psr::LLVMBasedICFG::LLVMBasedICFG (LLVMProjectIRDB * IRDB, CallGraphAnalysisType CGType, llvm::ArrayRef< std::string > EntryPoints = {}, DIBasedTypeHierarchy * TH = nullptr, LLVMAliasInfoRef PT = nullptr, Soundness S = Soundness::Soundy, bool IncludeGlobals = true) explicit
Constructs the ICFG based on the given IRDB and the entry-points using a fixpoint iteration. This may take a long time.
Parameters
IRDB The IR code where the ICFG should be based on. Must not be nullptr.
CGType The analysis kind to use for call-graph resolution
EntryPoints The names of the functions to start with when incrementally building up the ICFG. For whole-program analysis of an executable use {"main"}.
TH The type-hierarchy implementation to use. Must be non-null, if the selected call-graph analysis requires type-hierarchy information; currently, this holds for the CHA and RTA algorithms.
PT The points-to implementation to use. Will be constructed on-the-fly if nullptr, but required; currently, this holds for the OTF and VTA algorithms.
S The soundness level to expect from the analysis. Currently unused
IncludeGlobals Properly include global constructors/destructors into the ICFG, if true. Requires to generate artificial functions into the IRDB. True by default
LLVMBasedICFG() [2/7]
psr::LLVMBasedICFG::LLVMBasedICFG (LLVMProjectIRDB * IRDB, Resolver & CGResolver, llvm::ArrayRef< std::string > EntryPoints = {}, Soundness S = Soundness::Soundy, bool IncludeGlobals = true) explicit
LLVMBasedICFG() [3/7]
psr::LLVMBasedICFG::LLVMBasedICFG (LLVMProjectIRDB * IRDB, Resolver & CGResolver, LLVMVFTableProvider VTP, llvm::ArrayRef< std::string > EntryPoints = {}, Soundness S = Soundness::Soundy, bool IncludeGlobals = true) explicit
LLVMBasedICFG() [4/7]
psr::LLVMBasedICFG::LLVMBasedICFG (CallGraph< n_t, f_t > CG, const LLVMProjectIRDB * IRDB) explicit
Creates an ICFG with an already given call-graph.
LLVMBasedICFG() [5/7]
psr::LLVMBasedICFG::LLVMBasedICFG (const LLVMProjectIRDB * IRDB, const CallGraphData & SerializedCG) explicit
~LLVMBasedICFG()
psr::LLVMBasedICFG::~LLVMBasedICFG ()
LLVMBasedICFG() [6/7]
psr::LLVMBasedICFG::LLVMBasedICFG (const LLVMBasedICFG &) delete
LLVMBasedICFG() [7/7]
psr::LLVMBasedICFG::LLVMBasedICFG (LLVMBasedICFG &&) default noexcept
Member Function Documentation
exportICFGAsDot()
std::string psr::LLVMBasedICFG::exportICFGAsDot (bool WithSourceCodeInfo = true) const
Exports the whole ICFG (not only the call-graph) as DOT.
Parameters
WithSourceCodeInfo If true, not only contains the LLVM instructions as labels, but source-code information as well (e.g. function name, line no, col no, src-line).
exportICFGAsJson()
nlohmann::json psr::LLVMBasedICFG::exportICFGAsJson (bool WithSourceCodeInfo = true) const
Similar to exportICFGAsDot, but exports the ICFG as JSON instead.
getAllVertexFunctions()
auto psr::LLVMBasedICFG::getAllVertexFunctions () const inline noexcept
Returns all functions from the underlying IRDB that are part of the ICFG, i.e. that are reachable from the entry-points
Definition at line 125 of file LLVMBasedICFG.h.
References psr::CallGraphBase< Derived >::getAllVertexFunctions().
getIRDB()
const LLVMProjectIRDB * psr::LLVMBasedICFG::getIRDB () const inline noexcept
Gets the underlying IRDB.
Definition at line 130 of file LLVMBasedICFG.h.
getNumVertexFunctions()
size_t psr::LLVMBasedICFG::getNumVertexFunctions () const inline noexcept
Definition at line 119 of file LLVMBasedICFG.h.
References psr::CallGraphBase< Derived >::getNumVertexFunctions().
isPhasarGenerated()
static bool psr::LLVMBasedICFG::isPhasarGenerated (const llvm::Function & F) inline static noexcept
Returns true, if a function was generated by phasar.
Definition at line 134 of file LLVMBasedICFG.h.
References psr::GlobalCtorsDtorsModel::isPhasarGenerated().
operator=() [1/2]
LLVMBasedICFG & psr::LLVMBasedICFG::operator= (const LLVMBasedICFG &) delete
operator=() [2/2]
LLVMBasedICFG & psr::LLVMBasedICFG::operator= (LLVMBasedICFG &&) default noexcept
print() [1/2]
void psr::CFGBase< Derived >::print (ByConstRef< f_t > Fun, llvm::raw_ostream & OS) const inline
Definition at line 136 of file CFGBase.h.
print() [2/2]
void psr::ICFGBase< Derived >::print (llvm::raw_ostream & OS = llvm::outs()) const inline
Prints the underlying call-graph as DOT to the given output-stream.
Definition at line 104 of file ICFGBase.h.
printAsJson()
void psr::ICFGBase< Derived >::printAsJson (llvm::raw_ostream & OS = llvm::outs()) const inline
Prints the underlying call-graph as Json to the given output-stream.
Definition at line 109 of file ICFGBase.h.
Member Data Documentation
GlobalCRuntimeModelName
constexpr llvm::StringLiteral psr::LLVMBasedICFG::GlobalCRuntimeModelName static constexpr
Initial value:
=
      GlobalCtorsDtorsModel::ModelName
Definition at line 55 of file LLVMBasedICFG.h.
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h