PhASAR: psr::UnorderedSet< T > Class Template Reference
psr::UnorderedSet< T > Class Template Reference
#include "phasar/Utils/TableWrappers.h"
Public Types
using value_type = T
Public Member Functions
UnorderedSet () noexcept=default
void reserve (size_t Capacity)
auto insert (T Val)
bool contains (ByConstRef< T > Val) const noexcept
bool erase (ByConstRef< T > Val)
auto begin () const noexcept
auto end () const noexcept
void clear () noexcept(std::is_nothrow_default_constructible_v< decltype(Set)>)
auto cells () const noexcept
detail::CellVecSmallVectorTy< T > cellVec () const
template<typename FilterFn >
detail::CellVecSmallVectorTy< T > cellVec (FilterFn Filter) const
template<typename Projection , typename ResultProjection = IdentityFn>
detail::CellVecSmallVectorTy< std::invoke_result_t< ResultProjection, T > > allOf (Projection Proj, ByConstRef< std::invoke_result_t< Projection, T > > Of, ResultProjection ResProj={}) const
size_t size () const noexcept
bool empty () const noexcept
size_t getApproxSizeInBytes () const noexcept
Detailed Description
template<typename T>
class psr::UnorderedSet< T >
Definition at line 381 of file TableWrappers.h.
Member Typedef Documentation
value_type
template<typename T > using psr::UnorderedSet< T >::value_type = T
Definition at line 383 of file TableWrappers.h.
Constructor & Destructor Documentation
UnorderedSet()
template<typename T > psr::UnorderedSet< T >::UnorderedSet () default noexcept
Member Function Documentation
allOf()
template<typename T > template<typename Projection , typename ResultProjection = IdentityFn> detail::CellVecSmallVectorTy< std::invoke_result_t< ResultProjection, T > > psr::UnorderedSet< T >::allOf (Projection Proj, ByConstRef< std::invoke_result_t< Projection, T > > Of, ResultProjection ResProj = {}) const inline
Definition at line 425 of file TableWrappers.h.
begin()
template<typename T > auto psr::UnorderedSet< T >::begin () const inline noexcept
Definition at line 394 of file TableWrappers.h.
Referenced by psr::UnorderedSet< T >::cells().
cells()
template<typename T > auto psr::UnorderedSet< T >::cells () const inline noexcept
Definition at line 403 of file TableWrappers.h.
References psr::UnorderedSet< T >::begin(), and psr::UnorderedSet< T >::end().
cellVec() [1/2]
template<typename T > detail::CellVecSmallVectorTy< T > psr::UnorderedSet< T >::cellVec () const inline
Definition at line 405 of file TableWrappers.h.
References psr::Ret.
cellVec() [2/2]
template<typename T > template<typename FilterFn > detail::CellVecSmallVectorTy< T > psr::UnorderedSet< T >::cellVec (FilterFn Filter) const inline
Definition at line 413 of file TableWrappers.h.
References psr::Ret.
clear()
template<typename T > void psr::UnorderedSet< T >::clear () inline noexcept
Definition at line 398 of file TableWrappers.h.
contains()
template<typename T > bool psr::UnorderedSet< T >::contains (ByConstRef< T > Val) const inline noexcept
Definition at line 390 of file TableWrappers.h.
empty()
template<typename T > bool psr::UnorderedSet< T >::empty () const inline noexcept
Definition at line 437 of file TableWrappers.h.
end()
template<typename T > auto psr::UnorderedSet< T >::end () const inline noexcept
Definition at line 395 of file TableWrappers.h.
Referenced by psr::UnorderedSet< T >::cells().
erase()
template<typename T > bool psr::UnorderedSet< T >::erase (ByConstRef< T > Val) inline
Definition at line 392 of file TableWrappers.h.
getApproxSizeInBytes()
template<typename T > size_t psr::UnorderedSet< T >::getApproxSizeInBytes () const inline noexcept
Definition at line 439 of file TableWrappers.h.
insert()
template<typename T > auto psr::UnorderedSet< T >::insert (T Val) inline
Definition at line 388 of file TableWrappers.h.
reserve()
template<typename T > void psr::UnorderedSet< T >::reserve (size_t Capacity) inline
Definition at line 386 of file TableWrappers.h.
size()
template<typename T > size_t psr::UnorderedSet< T >::size () const inline noexcept
Definition at line 436 of file TableWrappers.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/TableWrappers.h