PhASAR: psr::CFGBase< Derived > Class Template Reference
psr::CFGBase< Derived > Class Template Reference
#include "phasar/ControlFlow/CFGBase.h"
Public Types
using n_t = typename CFGTraits< Derived >::n_t
using f_t = typename CFGTraits< Derived >::f_t
Public Member Functions
f_t getFunctionOf (ByConstRef< n_t > Inst) const noexcept
Returns the function where the given instruction is defined.
decltype(auto) getPredsOf (ByConstRef< n_t > Inst) const
decltype(auto) getSuccsOf (ByConstRef< n_t > Inst) const
decltype(auto) getAllControlFlowEdges (ByConstRef< f_t > Fun) const
Returns an iterable range of all edges in the CFG of the given function.
decltype(auto) getAllInstructionsOf (ByConstRef< f_t > Fun) const
decltype(auto) getStartPointsOf (ByConstRef< f_t > Fun) const
decltype(auto) getExitPointsOf (ByConstRef< f_t > Fun) const
bool isCallSite (ByConstRef< n_t > Inst) const noexcept
bool isExitInst (ByConstRef< n_t > Inst) const noexcept
bool isStartPoint (ByConstRef< n_t > Inst) const noexcept
bool isFieldLoad (ByConstRef< n_t > Inst) const noexcept
bool isFieldStore (ByConstRef< n_t > Inst) const noexcept
bool isFallThroughSuccessor (ByConstRef< n_t > Inst, ByConstRef< n_t > Succ) const noexcept
bool isBranchTarget (ByConstRef< n_t > Inst, ByConstRef< n_t > Succ) const noexcept
bool isHeapAllocatingFunction (ByConstRef< f_t > Fun) const
bool isSpecialMemberFunction (ByConstRef< f_t > Fun) const
SpecialMemberFunctionType getSpecialMemberFunctionType (ByConstRef< f_t > Fun) const
decltype(auto) getStatementId (ByConstRef< n_t > Inst) const
decltype(auto) getFunctionName (ByConstRef< f_t > Fun) const
decltype(auto) getDemangledFunctionName (ByConstRef< f_t > Fun) const
void print (ByConstRef< f_t > Fun, llvm::raw_ostream &OS) const
Additional Inherited Members
Protected Member Functions inherited from psr::CRTPBase< Derived >
constexpr CRTPBase () noexcept=default
constexpr Derived & self () &noexcept
constexpr Derived && self () &&noexcept
constexpr const Derived & self () const &noexcept
Detailed Description
template<typename Derived>
class psr::CFGBase< Derived >
Definition at line 26 of file CFGBase.h.
Member Typedef Documentation
f_t
template<typename Derived > using psr::CFGBase< Derived >::f_t = typename CFGTraits<Derived>::f_t
Definition at line 34 of file CFGBase.h.
n_t
template<typename Derived > using psr::CFGBase< Derived >::n_t = typename CFGTraits<Derived>::n_t
Definition at line 33 of file CFGBase.h.
Member Function Documentation
getAllControlFlowEdges()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getAllControlFlowEdges (ByConstRef< f_t > Fun) const inline
Returns an iterable range of all edges in the CFG of the given function.
Definition at line 57 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getAllInstructionsOf()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getAllInstructionsOf (ByConstRef< f_t > Fun) const inline
Returns an iterable range of all instructions of the given function. NOTE: even if the CFG is initialized to ignore debugging instructions, they may be contained here.
Definition at line 66 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getDemangledFunctionName()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getDemangledFunctionName (ByConstRef< f_t > Fun) const inline
Definition at line 130 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getExitPointsOf()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getExitPointsOf (ByConstRef< f_t > Fun) const inline
Returns an iterable range of all exit instructions (often return instructions) of the given function. For a backward-CFG, this is typically a singleton range
Definition at line 82 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getFunctionName()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getFunctionName (ByConstRef< f_t > Fun) const inline
Definition at line 125 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getFunctionOf()
template<typename Derived > f_t psr::CFGBase< Derived >::getFunctionOf (ByConstRef< n_t > Inst) const inline noexcept
Returns the function where the given instruction is defined.
Definition at line 37 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getPredsOf()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getPredsOf (ByConstRef< n_t > Inst) const inline
Returns an iterable range of all predecessor instructions of Inst in the CFG
Definition at line 42 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getSpecialMemberFunctionType()
template<typename Derived > SpecialMemberFunctionType psr::CFGBase< Derived >::getSpecialMemberFunctionType (ByConstRef< f_t > Fun) const inline
Definition at line 118 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getStartPointsOf()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getStartPointsOf (ByConstRef< f_t > Fun) const inline
Returns an iterable range of all starting instructions of the given function. For a forward-CFG, this is typically a singleton range
Definition at line 74 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getStatementId()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getStatementId (ByConstRef< n_t > Inst) const inline
Definition at line 121 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
getSuccsOf()
template<typename Derived > decltype(auto) psr::CFGBase< Derived >::getSuccsOf (ByConstRef< n_t > Inst) const inline
Returns an iterable range of all successor instructions of Inst in the CFG. NOTE: This function is typically being called in a hot part of the analysis and should therefore be highly optimized for performance
Definition at line 50 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isBranchTarget()
template<typename Derived > bool psr::CFGBase< Derived >::isBranchTarget (ByConstRef< n_t > Inst, ByConstRef< n_t > Succ) const inline noexcept
Definition at line 107 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isCallSite()
template<typename Derived > bool psr::CFGBase< Derived >::isCallSite (ByConstRef< n_t > Inst) const inline noexcept
Definition at line 87 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isExitInst()
template<typename Derived > bool psr::CFGBase< Derived >::isExitInst (ByConstRef< n_t > Inst) const inline noexcept
Definition at line 90 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isFallThroughSuccessor()
template<typename Derived > bool psr::CFGBase< Derived >::isFallThroughSuccessor (ByConstRef< n_t > Inst, ByConstRef< n_t > Succ) const inline noexcept
Definition at line 103 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isFieldLoad()
template<typename Derived > bool psr::CFGBase< Derived >::isFieldLoad (ByConstRef< n_t > Inst) const inline noexcept
Definition at line 96 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isFieldStore()
template<typename Derived > bool psr::CFGBase< Derived >::isFieldStore (ByConstRef< n_t > Inst) const inline noexcept
Definition at line 99 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isHeapAllocatingFunction()
template<typename Derived > bool psr::CFGBase< Derived >::isHeapAllocatingFunction (ByConstRef< f_t > Fun) const inline
Definition at line 111 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isSpecialMemberFunction()
template<typename Derived > bool psr::CFGBase< Derived >::isSpecialMemberFunction (ByConstRef< f_t > Fun) const inline
Definition at line 114 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
isStartPoint()
template<typename Derived > bool psr::CFGBase< Derived >::isStartPoint (ByConstRef< n_t > Inst) const inline noexcept
Definition at line 93 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
print()
template<typename Derived > void psr::CFGBase< Derived >::print (ByConstRef< f_t > Fun, llvm::raw_ostream & OS) const inline
Definition at line 135 of file CFGBase.h.
References psr::CRTPBase< Derived >::self().
The documentation for this class was generated from the following file:
include/phasar/ControlFlow/CFGBase.h