PhASAR: psr::CallGraphBuilder< N, F > Class Template Reference
psr::CallGraphBuilder< N, F > Class Template Reference
#include "phasar/ControlFlow/CallGraph.h"
Public Types
using n_t = typename CallGraph< N, F >::n_t
using f_t = typename CallGraph< N, F >::f_t
using FunctionVertexTy = typename CallGraph< n_t, f_t >::FunctionVertexTy
using InstructionVertexTy = typename CallGraph< n_t, f_t >::InstructionVertexTy
Public Member Functions
void reserve (size_t MaxNumFunctions)
FunctionVertexTy * addFunctionVertex (f_t Fun)
InstructionVertexTy * addInstructionVertex (n_t Inst)
InstructionVertexTy * getInstVertexOrNull (ByConstRef< n_t > Inst) const noexcept
void addCallEdge (n_t CS, f_t Callee)
void addCallEdge (n_t CS, InstructionVertexTy *Callees, f_t Callee)
void addCallEdge (n_t CS, f_t Callee, FunctionVertexTy *Callers)
CallGraph< n_t, f_t > consumeCallGraph () noexcept
const CallGraph< n_t, f_t > & viewCallGraph () const noexcept
Detailed Description
template<typename N, typename F>
class psr::CallGraphBuilder< N, F >
A mutable wrapper over a CallGraph. Use this to build a call-graph from within your call-graph ananlysis.
Definition at line 156 of file CallGraph.h.
Member Typedef Documentation
f_t
template<typename N , typename F > using psr::CallGraphBuilder< N, F >::f_t = typename CallGraph<N, F>::f_t
Definition at line 159 of file CallGraph.h.
FunctionVertexTy
template<typename N , typename F > using psr::CallGraphBuilder< N, F >::FunctionVertexTy = typename CallGraph<n_t, f_t>::FunctionVertexTy
Definition at line 160 of file CallGraph.h.
InstructionVertexTy
template<typename N , typename F > using psr::CallGraphBuilder< N, F >::InstructionVertexTy = typename CallGraph<n_t, f_t>::InstructionVertexTy
Definition at line 161 of file CallGraph.h.
n_t
template<typename N , typename F > using psr::CallGraphBuilder< N, F >::n_t = typename CallGraph<N, F>::n_t
Definition at line 158 of file CallGraph.h.
Member Function Documentation
addCallEdge() [1/3]
template<typename N , typename F > void psr::CallGraphBuilder< N, F >::addCallEdge (n_t CS, f_t Callee) inline
Adds a new directional edge to the call-graph indicating that CS may call Callee
Definition at line 203 of file CallGraph.h.
References psr::CallGraphBuilder< N, F >::addCallEdge(), psr::CallGraphBuilder< N, F >::addFunctionVertex(), and psr::CallGraphBuilder< N, F >::addInstructionVertex().
Referenced by psr::CallGraphBuilder< N, F >::addCallEdge(), psr::CallGraphBuilder< N, F >::addCallEdge(), and psr::CallGraphBuilder< N, F >::addCallEdge().
addCallEdge() [2/3]
template<typename N , typename F > void psr::CallGraphBuilder< N, F >::addCallEdge (n_t CS, f_t Callee, FunctionVertexTy * Callers) inline
Same as addCallEdge(n_t, f_t), but uses an already known FunctionVertexTy to save a lookup
Definition at line 218 of file CallGraph.h.
References psr::CallGraphBuilder< N, F >::addCallEdge(), and psr::CallGraphBuilder< N, F >::addInstructionVertex().
addCallEdge() [3/3]
template<typename N , typename F > void psr::CallGraphBuilder< N, F >::addCallEdge (n_t CS, InstructionVertexTy * Callees, f_t Callee) inline
Same as addCallEdge(n_t, f_t), but uses an already known InstructionVertexTy to save a lookup
Definition at line 211 of file CallGraph.h.
References psr::CallGraphBuilder< N, F >::addCallEdge(), and psr::CallGraphBuilder< N, F >::addFunctionVertex().
addFunctionVertex()
template<typename N , typename F > FunctionVertexTy * psr::CallGraphBuilder< N, F >::addFunctionVertex (f_t Fun) inline
Registeres a new function in the call-graph. Returns a list of all call-sites that are known so far to potentially call this function. Do not manually add elements to this vector – use addCallEdge instead.
Definition at line 172 of file CallGraph.h.
Referenced by psr::CallGraphBuilder< N, F >::addCallEdge(), and psr::CallGraphBuilder< N, F >::addCallEdge().
addInstructionVertex()
template<typename N , typename F > InstructionVertexTy * psr::CallGraphBuilder< N, F >::addInstructionVertex (n_t Inst) inline
Registeres a new call-site in the call-graph. Returns a list of all callee functions that are known so far to potentially be called by this function. Do not manually add elements to this vector – use addCallEdge instead.
Definition at line 186 of file CallGraph.h.
References psr::StableVector< T, Allocator >::emplace_back().
Referenced by psr::CallGraphBuilder< N, F >::addCallEdge(), and psr::CallGraphBuilder< N, F >::addCallEdge().
consumeCallGraph()
template<typename N , typename F > CallGraph< n_t, f_t > psr::CallGraphBuilder< N, F >::consumeCallGraph () inline noexcept
Moves the completely built call-graph out of this builder for further use. Do not use the builder after it anymore.
Definition at line 225 of file CallGraph.h.
getInstVertexOrNull()
template<typename N , typename F > InstructionVertexTy * psr::CallGraphBuilder< N, F >::getInstVertexOrNull (ByConstRef< n_t > Inst) const inline noexcept
Tries to lookup the InstructionVertex for the given call-site. Returns nullptr on failure.
Definition at line 197 of file CallGraph.h.
reserve()
template<typename N , typename F > void psr::CallGraphBuilder< N, F >::reserve (size_t MaxNumFunctions) inline
Definition at line 163 of file CallGraph.h.
viewCallGraph()
template<typename N , typename F > const CallGraph< n_t, f_t > & psr::CallGraphBuilder< N, F >::viewCallGraph () const inline noexcept
Returns a view on the current (partial) call-graph that has already been constructed
Definition at line 231 of file CallGraph.h.
The documentation for this class was generated from the following file:
include/phasar/ControlFlow/CallGraph.h