PhASAR: psr::Table< R, C, V > Class Template Reference
psr::Table< R, C, V > Class Template Reference
#include "phasar/Utils/Table.h"
Classes
struct Cell
Public Member Functions
Table () noexcept=default
Table (const Table &T)=default
Table & operator= (const Table &T)=delete
Table (Table &&T) noexcept=default
Table & operator= (Table &&T) noexcept=default
~Table ()=default
void insert (R Row, C Column, V Val)
void clear () noexcept
bool empty () const noexcept
size_t size () const noexcept
size_t getApproxSizeInBytes () const noexcept
std::set< Cell > cellSet () const
template<typename Fn >
void foreachCell (Fn Handler) const
template<typename Fn >
void foreachCell (Fn Handler)
std::vector< Cell > cellVec () const
std::unordered_map< R, V > column (ByConstRef< C > ColumnKey) const
bool contains (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) const noexcept
bool containsColumn (ByConstRef< C > ColumnKey) const noexcept
bool containsRow (ByConstRef< R > RowKey) const noexcept
V & get (R RowKey, C ColumnKey)
V getOrDefault (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) const
std::optional< V > tryGet (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey)
ByConstRef< V > get (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) const noexcept
V remove (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey)
void remove (ByConstRef< R > RowKey)
std::unordered_map< C, V > & row (R RowKey)
ByConstRef< std::unordered_map< C, V > > row (ByConstRef< R > RowKey) const noexcept
const std::unordered_map< R, std::unordered_map< C, V > > & rowMap () const &noexcept
std::unordered_map< R, std::unordered_map< C, V > > && rowMap () &&noexcept
const std::unordered_map< R, std::unordered_map< C, V > > & rowMapView () const noexcept
void reserve (size_t Capacity)
bool operator== (const Table< R, C, V > &Other) noexcept
bool operator< (const Table< R, C, V > &Other) noexcept
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Table< R, C, V > &Tab)
Detailed Description
template<typename R, typename C, typename V>
class psr::Table< R, C, V >
Definition at line 36 of file Table.h.
Constructor & Destructor Documentation
Table() [1/3]
template<typename R , typename C , typename V > psr::Table< R, C, V >::Table () default noexcept
Table() [2/3]
template<typename R , typename C , typename V > psr::Table< R, C, V >::Table (const Table< R, C, V > & T) explicit default
Table() [3/3]
template<typename R , typename C , typename V > psr::Table< R, C, V >::Table (Table< R, C, V > && T) default noexcept
~Table()
template<typename R , typename C , typename V > psr::Table< R, C, V >::~Table () default
Member Function Documentation
cellSet()
template<typename R , typename C , typename V > std::set< Cell > psr::Table< R, C, V >::cellSet () const inline
Definition at line 104 of file Table.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::getAsJson().
cellVec()
template<typename R , typename C , typename V > std::vector< Cell > psr::Table< R, C, V >::cellVec () const inline
Definition at line 130 of file Table.h.
Referenced by psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyLookupByTargetNode().
clear()
template<typename R , typename C , typename V > void psr::Table< R, C, V >::clear () inline noexcept
Definition at line 80 of file Table.h.
column()
template<typename R , typename C , typename V > std::unordered_map< R, V > psr::Table< R, C, V >::column (ByConstRef< C > ColumnKey) const inline
Definition at line 142 of file Table.h.
contains()
template<typename R , typename C , typename V > bool psr::Table< R, C, V >::contains (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) const inline noexcept
Definition at line 153 of file Table.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::val().
containsColumn()
template<typename R , typename C , typename V > bool psr::Table< R, C, V >::containsColumn (ByConstRef< C > ColumnKey) const inline noexcept
Definition at line 163 of file Table.h.
containsRow()
template<typename R , typename C , typename V > bool psr::Table< R, C, V >::containsRow (ByConstRef< R > RowKey) const inline noexcept
Definition at line 173 of file Table.h.
empty()
template<typename R , typename C , typename V > bool psr::Table< R, C, V >::empty () const inline noexcept
Definition at line 82 of file Table.h.
foreachCell() [1/2]
template<typename R , typename C , typename V > template<typename Fn > void psr::Table< R, C, V >::foreachCell (Fn Handler) inline
Definition at line 122 of file Table.h.
foreachCell() [2/2]
template<typename R , typename C , typename V > template<typename Fn > void psr::Table< R, C, V >::foreachCell (Fn Handler) const inline
Definition at line 115 of file Table.h.
get() [1/2]
template<typename R , typename C , typename V > ByConstRef< V > psr::Table< R, C, V >::get (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) const inline noexcept
Definition at line 212 of file Table.h.
get() [2/2]
template<typename R , typename C , typename V > V & psr::Table< R, C, V >::get (R RowKey, C ColumnKey) inline
Definition at line 178 of file Table.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::val().
getApproxSizeInBytes()
template<typename R , typename C , typename V > size_t psr::Table< R, C, V >::getApproxSizeInBytes () const inline noexcept
Definition at line 86 of file Table.h.
getOrDefault()
template<typename R , typename C , typename V > V psr::Table< R, C, V >::getOrDefault (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) const inline
Definition at line 184 of file Table.h.
insert()
template<typename R , typename C , typename V > void psr::Table< R, C, V >::insert (R Row, C Column, V Val) inline
Definition at line 75 of file Table.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::setVal().
operator<()
template<typename R , typename C , typename V > bool psr::Table< R, C, V >::operator< (const Table< R, C, V > & Other) inline noexcept
Definition at line 294 of file Table.h.
operator=() [1/2]
template<typename R , typename C , typename V > Table & psr::Table< R, C, V >::operator= (const Table< R, C, V > & T) delete
operator=() [2/2]
template<typename R , typename C , typename V > Table & psr::Table< R, C, V >::operator= (Table< R, C, V > && T) default noexcept
operator==()
template<typename R , typename C , typename V > bool psr::Table< R, C, V >::operator== (const Table< R, C, V > & Other) inline noexcept
Definition at line 290 of file Table.h.
remove() [1/2]
template<typename R , typename C , typename V > void psr::Table< R, C, V >::remove (ByConstRef< R > RowKey) inline
Definition at line 252 of file Table.h.
remove() [2/2]
template<typename R , typename C , typename V > V psr::Table< R, C, V >::remove (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) inline
Definition at line 229 of file Table.h.
References psr::Ret.
reserve()
template<typename R , typename C , typename V > void psr::Table< R, C, V >::reserve (size_t Capacity) inline
Definition at line 288 of file Table.h.
row() [1/2]
template<typename R , typename C , typename V > ByConstRef< std::unordered_map< C, V > > psr::Table< R, C, V >::row (ByConstRef< R > RowKey) const inline noexcept
Definition at line 260 of file Table.h.
row() [2/2]
template<typename R , typename C , typename V > std::unordered_map< C, V > & psr::Table< R, C, V >::row (R RowKey) inline
Definition at line 254 of file Table.h.
rowMap() [1/2]
template<typename R , typename C , typename V > std::unordered_map< R, std::unordered_map< C, V > > && psr::Table< R, C, V >::rowMap () && inline noexcept
Definition at line 276 of file Table.h.
rowMap() [2/2]
template<typename R , typename C , typename V > const std::unordered_map< R, std::unordered_map< C, V > > & psr::Table< R, C, V >::rowMap () const & inline noexcept
Definition at line 270 of file Table.h.
rowMapView()
template<typename R , typename C , typename V > const std::unordered_map< R, std::unordered_map< C, V > > & psr::Table< R, C, V >::rowMapView () const inline noexcept
Definition at line 282 of file Table.h.
size()
template<typename R , typename C , typename V > size_t psr::Table< R, C, V >::size () const inline noexcept
Definition at line 84 of file Table.h.
tryGet()
template<typename R , typename C , typename V > std::optional< V > psr::Table< R, C, V >::tryGet (ByConstRef< R > RowKey, ByConstRef< C > ColumnKey) inline
Definition at line 198 of file Table.h.
Friends And Related Symbol Documentation
operator<<
template<typename R , typename C , typename V > llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const Table< R, C, V > & Tab) friend
Definition at line 298 of file Table.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/Table.h