PhASAR: psr::ProjectIRDBBase< Derived > Class Template Reference
psr::ProjectIRDBBase< Derived > Class Template Reference
#include "phasar/DB/ProjectIRDBBase.h"
Public Types
using n_t = typename ProjectIRDBTraits< Derived >::n_t
using f_t = typename ProjectIRDBTraits< Derived >::f_t
using m_t = typename ProjectIRDBTraits< Derived >::m_t
using g_t = typename ProjectIRDBTraits< Derived >::g_t
Public Member Functions
m_t getModule () const noexcept
Returns the managed module.
bool debugInfoAvailable () const
Check if debug information are available.
decltype(auto) getAllFunctions () const
Returns a range of all function definitions and declarations available.
Nullable< f_t > getFunction (llvm::StringRef FunctionName) const
Nullable< f_t > getFunctionDefinition (llvm::StringRef FunctionName) const
Returns the function's definition if available, null otherwise.
bool hasFunction (llvm::StringRef FunctionName) const noexcept
Returns whether the IRDB contains a function with the given name.
Nullable< g_t > getGlobalVariable (llvm::StringRef GlobalVariableName) const
Nullable< g_t > getGlobalVariableDefinition (llvm::StringRef GlobalVariableName) const
size_t getNumInstructions () const noexcept
Returns the number of instruction in the managed module.
size_t getNumGlobals () const noexcept
Returns the number of global variables in the managed module.
size_t getNumFunctions () const noexcept
Returns the number of functions in the managed module.
Nullable< n_t > getInstruction (size_t Id) const
size_t getInstructionId (n_t Inst) const
decltype(auto) getAllInstructions () const
bool isValid () const noexcept
LLVM_DUMP_METHOD void dump () const
ProjectIRDBBase (const ProjectIRDBBase &)=delete
ProjectIRDBBase & operator= (const ProjectIRDBBase &)=delete
ProjectIRDBBase (ProjectIRDBBase &&) noexcept=default
ProjectIRDBBase & operator= (ProjectIRDBBase &&) noexcept=default
~ProjectIRDBBase ()=default
Detailed Description
template<typename Derived>
class psr::ProjectIRDBBase< Derived >
This class owns the IR code of the target being analyzed and some very important information associated with the IR. When an object of this class is destroyed it will clean up all IR related stuff that is stored in it.
m_t - module type f_t - function type n_t - instruction type g_t - global variable type
Remarks
XXX Once we have upgraded to C++20, we might want to use a concept instead...
Definition at line 40 of file ProjectIRDBBase.h.
Member Typedef Documentation
f_t
template<typename Derived > using psr::ProjectIRDBBase< Derived >::f_t = typename ProjectIRDBTraits<Derived>::f_t
Definition at line 43 of file ProjectIRDBBase.h.
g_t
template<typename Derived > using psr::ProjectIRDBBase< Derived >::g_t = typename ProjectIRDBTraits<Derived>::g_t
Definition at line 45 of file ProjectIRDBBase.h.
m_t
template<typename Derived > using psr::ProjectIRDBBase< Derived >::m_t = typename ProjectIRDBTraits<Derived>::m_t
Definition at line 44 of file ProjectIRDBBase.h.
n_t
template<typename Derived > using psr::ProjectIRDBBase< Derived >::n_t = typename ProjectIRDBTraits<Derived>::n_t
Definition at line 42 of file ProjectIRDBBase.h.
Constructor & Destructor Documentation
ProjectIRDBBase() [1/2]
template<typename Derived > psr::ProjectIRDBBase< Derived >::ProjectIRDBBase (const ProjectIRDBBase< Derived > &) delete
ProjectIRDBBase() [2/2]
template<typename Derived > psr::ProjectIRDBBase< Derived >::ProjectIRDBBase (ProjectIRDBBase< Derived > &&) default noexcept
~ProjectIRDBBase()
template<typename Derived > psr::ProjectIRDBBase< Derived >::~ProjectIRDBBase () default
Member Function Documentation
debugInfoAvailable()
template<typename Derived > bool psr::ProjectIRDBBase< Derived >::debugInfoAvailable () const inline
Check if debug information are available.
Definition at line 54 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
dump()
template<typename Derived > LLVM_DUMP_METHOD void psr::ProjectIRDBBase< Derived >::dump () const inline
Dumps the managed module to llvm::dbgs() if isValid(); otherwise prints "<Invalid Module>". This function can be invoked from a debugger.
Definition at line 146 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getAllFunctions()
template<typename Derived > decltype(auto) psr::ProjectIRDBBase< Derived >::getAllFunctions () const inline
Returns a range of all function definitions and declarations available.
Definition at line 60 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
Referenced by psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::emitTextReport().
getAllInstructions()
template<typename Derived > decltype(auto) psr::ProjectIRDBBase< Derived >::getAllInstructions () const inline
Definition at line 129 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getFunction()
template<typename Derived > Nullable< f_t > psr::ProjectIRDBBase< Derived >::getFunction (llvm::StringRef FunctionName) const inline
Definition at line 68 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getFunctionDefinition()
template<typename Derived > Nullable< f_t > psr::ProjectIRDBBase< Derived >::getFunctionDefinition (llvm::StringRef FunctionName) const inline
Returns the function's definition if available, null otherwise.
Definition at line 74 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getGlobalVariable()
template<typename Derived > Nullable< g_t > psr::ProjectIRDBBase< Derived >::getGlobalVariable (llvm::StringRef GlobalVariableName) const inline
Returns the global variable's definition if available, nullptr/nullopt otherwise.
Definition at line 87 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getGlobalVariableDefinition()
template<typename Derived > Nullable< g_t > psr::ProjectIRDBBase< Derived >::getGlobalVariableDefinition (llvm::StringRef GlobalVariableName) const inline
Returns the global variable's definition if available, nullptr/nullopt otherwise.
Definition at line 95 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getInstruction()
template<typename Derived > Nullable< n_t > psr::ProjectIRDBBase< Derived >::getInstruction (size_t Id) const inline
Returns the instruction to the corresponding Id. Returns nullptr/nullopt, if there is no instruction for this Id
Definition at line 118 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getInstructionId()
template<typename Derived > size_t psr::ProjectIRDBBase< Derived >::getInstructionId (n_t Inst) const inline
Returns an instruction's ID. The instruction must belong to the managed module for this function to work
Definition at line 124 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getModule()
template<typename Derived > m_t psr::ProjectIRDBBase< Derived >::getModule () const inline noexcept
Returns the managed module.
Definition at line 48 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getNumFunctions()
template<typename Derived > size_t psr::ProjectIRDBBase< Derived >::getNumFunctions () const inline noexcept
Returns the number of functions in the managed module.
Definition at line 111 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getNumGlobals()
template<typename Derived > size_t psr::ProjectIRDBBase< Derived >::getNumGlobals () const inline noexcept
Returns the number of global variables in the managed module.
Definition at line 106 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
getNumInstructions()
template<typename Derived > size_t psr::ProjectIRDBBase< Derived >::getNumInstructions () const inline noexcept
Returns the number of instruction in the managed module.
Definition at line 101 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
hasFunction()
template<typename Derived > bool psr::ProjectIRDBBase< Derived >::hasFunction (llvm::StringRef FunctionName) const inline noexcept
Returns whether the IRDB contains a function with the given name.
Definition at line 79 of file ProjectIRDBBase.h.
References psr::ProjectIRDBBase< Derived >::isValid().
isValid()
template<typename Derived > bool psr::ProjectIRDBBase< Derived >::isValid () const inline noexcept
Sanity check to verify that th IRDB really manages a Module and all functions work properly. All functions of this IRDB require isValid() to return true, if not stated differently – otherwise, they must not be called. This function (obviously) does not require isValid() to return true.
Definition at line 141 of file ProjectIRDBBase.h.
Referenced by psr::ProjectIRDBBase< Derived >::debugInfoAvailable(), psr::ProjectIRDBBase< Derived >::dump(), psr::ProjectIRDBBase< Derived >::getAllFunctions(), psr::ProjectIRDBBase< Derived >::getAllInstructions(), psr::ProjectIRDBBase< Derived >::getFunction(), psr::ProjectIRDBBase< Derived >::getFunctionDefinition(), psr::ProjectIRDBBase< Derived >::getGlobalVariable(), psr::ProjectIRDBBase< Derived >::getGlobalVariableDefinition(), psr::ProjectIRDBBase< Derived >::getInstruction(), psr::ProjectIRDBBase< Derived >::getInstructionId(), psr::ProjectIRDBBase< Derived >::getModule(), psr::ProjectIRDBBase< Derived >::getNumFunctions(), psr::ProjectIRDBBase< Derived >::getNumGlobals(), psr::ProjectIRDBBase< Derived >::getNumInstructions(), and psr::ProjectIRDBBase< Derived >::hasFunction().
operator=() [1/2]
template<typename Derived > ProjectIRDBBase & psr::ProjectIRDBBase< Derived >::operator= (const ProjectIRDBBase< Derived > &) delete
operator=() [2/2]
template<typename Derived > ProjectIRDBBase & psr::ProjectIRDBBase< Derived >::operator= (ProjectIRDBBase< Derived > &&) default noexcept
The documentation for this class was generated from the following file:
include/phasar/DB/ProjectIRDBBase.h