PhASAR: psr::ICFGBase< Derived > Class Template Reference
psr::ICFGBase< Derived > Class Template Reference
#include "phasar/ControlFlow/ICFGBase.h"
Public Types
using n_t = typename CFGTraits< Derived >::n_t
using f_t = typename CFGTraits< Derived >::f_t
Public Member Functions
decltype(auto) getAllFunctions () const
f_t getFunction (llvm::StringRef Fun) const
bool isIndirectFunctionCall (ByConstRef< n_t > Inst) const
bool isVirtualFunctionCall (ByConstRef< n_t > Inst) const
decltype(auto) allNonCallStartNodes () const
decltype(auto) getCallGraph () const noexcept
Returns a view to the underlying call-graph.
decltype(auto) getCalleesOfCallAt (ByConstRef< n_t > Inst) const
decltype(auto) getCallersOf (ByConstRef< f_t > Fun) const
decltype(auto) getCallsFromWithin (ByConstRef< f_t > Fun) const
Returns an iterable range of all call-instruction in the given function.
decltype(auto) getReturnSitesOfCallAt (ByConstRef< n_t > Inst) const
void print (llvm::raw_ostream &OS=llvm::outs()) const
Prints the underlying call-graph as DOT to the given output-stream.
void printAsJson (llvm::raw_ostream &OS=llvm::outs()) const
Prints the underlying call-graph as Json to the given output-stream.
size_t getNumCallSites () const noexcept
Additional Inherited Members
Protected Member Functions inherited from psr::CRTPBase< Derived >
constexpr CRTPBase () noexcept=default
constexpr Derived & self () &noexcept
constexpr Derived && self () &&noexcept
constexpr const Derived & self () const &noexcept
Detailed Description
template<typename Derived>
class psr::ICFGBase< Derived >
Definition at line 25 of file ICFGBase.h.
Member Typedef Documentation
f_t
template<typename Derived > using psr::ICFGBase< Derived >::f_t = typename CFGTraits<Derived>::f_t
Definition at line 31 of file ICFGBase.h.
n_t
template<typename Derived > using psr::ICFGBase< Derived >::n_t = typename CFGTraits<Derived>::n_t
Definition at line 30 of file ICFGBase.h.
Member Function Documentation
allNonCallStartNodes()
template<typename Derived > decltype(auto) psr::ICFGBase< Derived >::allNonCallStartNodes () const inline
Returns an iterable range of all instructions in all functions of the ICFG that are neither call-sites nor start-points of a function
Definition at line 61 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
getAllFunctions()
template<typename Derived > decltype(auto) psr::ICFGBase< Derived >::getAllFunctions () const inline
Returns an iterable range of all function definitions or declarations in the ICFG
Definition at line 35 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
getCalleesOfCallAt()
template<typename Derived > decltype(auto) psr::ICFGBase< Derived >::getCalleesOfCallAt (ByConstRef< n_t > Inst) const inline
Returns an iterable range of all possible callee candidates at the given call-site induced by the used call-graph.
Definition at line 77 of file ICFGBase.h.
References psr::ICFGBase< Derived >::getCallGraph().
getCallersOf()
template<typename Derived > decltype(auto) psr::ICFGBase< Derived >::getCallersOf (ByConstRef< f_t > Fun) const inline
Returns an iterable range of all possible call-site candidates that may call the given function induced by the used call-graph.
Definition at line 82 of file ICFGBase.h.
References psr::ICFGBase< Derived >::getCallGraph().
getCallGraph()
template<typename Derived > decltype(auto) psr::ICFGBase< Derived >::getCallGraph () const inline noexcept
Returns a view to the underlying call-graph.
Definition at line 68 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
Referenced by psr::ICFGBase< Derived >::getCalleesOfCallAt(), and psr::ICFGBase< Derived >::getCallersOf().
getCallsFromWithin()
template<typename Derived > decltype(auto) psr::ICFGBase< Derived >::getCallsFromWithin (ByConstRef< f_t > Fun) const inline
Returns an iterable range of all call-instruction in the given function.
Definition at line 86 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
getFunction()
template<typename Derived > f_t psr::ICFGBase< Derived >::getFunction (llvm::StringRef Fun) const inline
returns the function definition or declaration with the given name. If there is no such function, returns a default constructed f_t (nullptr for pointers).
Definition at line 42 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
getNumCallSites()
template<typename Derived > size_t psr::ICFGBase< Derived >::getNumCallSites () const inline noexcept
Definition at line 113 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
getReturnSitesOfCallAt()
template<typename Derived > decltype(auto) psr::ICFGBase< Derived >::getReturnSitesOfCallAt (ByConstRef< n_t > Inst) const inline
Returns an iterable range of all return-sites of the given call-instruction. Often the same as getSuccsOf. NOTE: This function is typically called in a hot part of the analysis and should therefore be very fast
Definition at line 96 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
isIndirectFunctionCall()
template<typename Derived > bool psr::ICFGBase< Derived >::isIndirectFunctionCall (ByConstRef< n_t > Inst) const inline
Returns true, iff the given instruction is a call-site where the callee is called via a function-pointer or another kind of virtual call. NOTE: Trivial cases where a bitcast of a function is called may still count as indirect call.
Definition at line 50 of file ICFGBase.h.
isVirtualFunctionCall()
template<typename Derived > bool psr::ICFGBase< Derived >::isVirtualFunctionCall (ByConstRef< n_t > Inst) const inline
Returns true, iff the given instruction is a call-site where the callee is called via virtual dispatch. NOTE: Here, a class-hierarchy is required and a simple function-pointer is not sufficient.
Definition at line 56 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
print()
template<typename Derived > void psr::ICFGBase< Derived >::print (llvm::raw_ostream & OS = llvm::outs()) const inline
Prints the underlying call-graph as DOT to the given output-stream.
Definition at line 104 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
printAsJson()
template<typename Derived > void psr::ICFGBase< Derived >::printAsJson (llvm::raw_ostream & OS = llvm::outs()) const inline
Prints the underlying call-graph as Json to the given output-stream.
Definition at line 109 of file ICFGBase.h.
References psr::CRTPBase< Derived >::self().
The documentation for this class was generated from the following file:
include/phasar/ControlFlow/ICFGBase.h