PhASAR: psr::IDESolverAPIMixin< Derived > Class Template Reference
psr::IDESolverAPIMixin< Derived > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/IDESolverAPIMixin.h"
Public Member Functions
constexpr void initialize ()
constexpr bool next ()
constexpr bool nextN (size_t MaxNumIterations)
constexpr decltype(auto) finalize () &
constexpr decltype(auto) finalize () &&
constexpr decltype(auto) solve () &
constexpr decltype(auto) solve () &&
constexpr decltype(auto) continueSolving () &
constexpr decltype(auto) continueSolving () &&
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &&
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &&
constexpr auto solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &
constexpr auto solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &&
constexpr auto continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &
constexpr auto continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &&
constexpr auto solveWithAsyncCancellation (std::atomic_bool &IsCancelled) &
constexpr auto solveWithAsyncCancellation (std::atomic_bool &IsCancelled) &&
constexpr auto continueWithAsyncCancellation (std::atomic_bool &IsCancelled) &
constexpr auto continueWithAsyncCancellation (std::atomic_bool &IsCancelled) &&
Detailed Description
template<typename Derived>
class psr::IDESolverAPIMixin< Derived >
Definition at line 27 of file IDESolverAPIMixin.h.
Member Function Documentation
continueSolving() [1/2]
template<typename Derived > constexpr decltype(auto) psr::IDESolverAPIMixin< Derived >::continueSolving () & inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. This can take some time and cannot be interrupted. If you need the ability to interrupt the solving process consider using solveUntil() or solveTimeout().
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Returns
A view into the computed analysis results
Definition at line 113 of file IDESolverAPIMixin.h.
References psr::IDESolverAPIMixin< Derived >::finalize().
continueSolving() [2/2]
template<typename Derived > constexpr decltype(auto) psr::IDESolverAPIMixin< Derived >::continueSolving () && inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. This can take some time and cannot be interrupted. If you need the ability to interrupt the solving process consider using solveUntil() or solveTimeout().
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Returns
The computed analysis results
Definition at line 130 of file IDESolverAPIMixin.h.
continueUntil() [1/2]
template<typename Derived > template<typename CancellationRequest > requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>) constexpr auto psr::IDESolverAPIMixin< Derived >::continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval = std::chrono::seconds{1}) & inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. Periodically checks every Interval whether CancellationRequested evaluates to true.
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Note: Shortening the cancellation-check interval will make the cancellation-time more precise (by having more frequent calls to CancellationRequested) but also have negative impact on the solver's performance.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 209 of file IDESolverAPIMixin.h.
Referenced by psr::IDESolverAPIMixin< Derived >::continueWithTimeout().
continueUntil() [2/2]
template<typename Derived > template<typename CancellationRequest > requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>) constexpr auto psr::IDESolverAPIMixin< Derived >::continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval = std::chrono::seconds{1}) && inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. Periodically checks every Interval whether CancellationRequested evaluates to true.
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Note: Shortening the cancellation-check interval will make the cancellation-time more precise (by having more frequent calls to CancellationRequested) but also have negative impact on the solver's performance.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 242 of file IDESolverAPIMixin.h.
continueWithAsyncCancellation() [1/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::continueWithAsyncCancellation (std::atomic_bool & IsCancelled) & inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. Periodically checks whether IsCancelled is true.
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 390 of file IDESolverAPIMixin.h.
References psr::IDESolverAPIMixin< Derived >::finalize().
continueWithAsyncCancellation() [2/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::continueWithAsyncCancellation (std::atomic_bool & IsCancelled) && inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. Periodically checks whether IsCancelled is true.
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 413 of file IDESolverAPIMixin.h.
continueWithTimeout() [1/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) & inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. Periodically checks every Interval whether the Timeout has been exceeded.
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Note: Shortening the timeout-check interval will make the timeout more precise but also have negative impact on the solver's performance.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 307 of file IDESolverAPIMixin.h.
References psr::IDESolverAPIMixin< Derived >::continueUntil().
continueWithTimeout() [2/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) && inline constexpr
Continues running the solver on the configured problem after it got interrupted in a previous run. Periodically checks every Interval whether the Timeout has been exceeded.
Remarks
Please make sure to only call this function on an IDESolver where the solving process is interrupted, i.e. one of the interruptable solving methods returned std::nullopt. It is invalid to call this function on an IDESolver that has not yet started solving or has already flinalized solving.
Note: Shortening the timeout-check interval will make the timeout more precise but also have negative impact on the solver's performance.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 333 of file IDESolverAPIMixin.h.
finalize() [1/2]
template<typename Derived > constexpr decltype(auto) psr::IDESolverAPIMixin< Derived >::finalize () & inline constexpr
Computes the final analysis results after the analysis has reached its fixpoint, i.e. either initialize() returned false or the last next() or nextN() call returned false.
Returns
A view into the computed analysis results
Definition at line 71 of file IDESolverAPIMixin.h.
Referenced by psr::IDESolverAPIMixin< Derived >::continueSolving(), psr::IDESolverAPIMixin< Derived >::continueWithAsyncCancellation(), psr::IDESolverAPIMixin< Derived >::solve(), and psr::IDESolverAPIMixin< Derived >::solveWithAsyncCancellation().
finalize() [2/2]
template<typename Derived > constexpr decltype(auto) psr::IDESolverAPIMixin< Derived >::finalize () && inline constexpr
Computes the final analysis results after the analysis has reached its fixpoint, i.e. either initialize() returned false or the last next() or nextN() call returned false.
Returns
The computed analysis results
Definition at line 77 of file IDESolverAPIMixin.h.
initialize()
template<typename Derived > constexpr void psr::IDESolverAPIMixin< Derived >::initialize () inline constexpr
Initialize the IDE solver for step-wise solving (iteratively calling next() or nextN()). For a more high-level API use solveUntil() or solveTimeout().
Definition at line 32 of file IDESolverAPIMixin.h.
next()
template<typename Derived > constexpr bool psr::IDESolverAPIMixin< Derived >::next () inline constexpr
Performs one tiny step towards the analysis' fixpoint. For a more high-level API use solveUntil() or solveTimeout().
Requires that initialize() has been called before once and that all previous next() or nextN() calls returned true as well.
Returns
True, iff there are more steps to process before calling finalize()
Definition at line 42 of file IDESolverAPIMixin.h.
Referenced by psr::IDESolverAPIMixin< Derived >::nextN().
nextN()
template<typename Derived > constexpr bool psr::IDESolverAPIMixin< Derived >::nextN (size_t MaxNumIterations) inline constexpr
Performs N tiny steps towards the analysis' fixpoint. For a more high-level API use solveUntil() or solveTimeout().
Requires that initialize() has been called before once and that all previous next() or nextN() calls returned true as well.
Returns
True, iff there are more steps to process before calling finalize()
Definition at line 52 of file IDESolverAPIMixin.h.
References psr::IDESolverAPIMixin< Derived >::next(), and PHASAR_LOG_LEVEL.
solve() [1/2]
template<typename Derived > constexpr decltype(auto) psr::IDESolverAPIMixin< Derived >::solve () & inline constexpr
Runs the solver on the configured problem. This can take some time and cannot be interrupted. If you need the ability to interrupt the solving process consider using solveUntil() or solveTimeout().
Returns
A view into the computed analysis results
Definition at line 86 of file IDESolverAPIMixin.h.
References psr::IDESolverAPIMixin< Derived >::finalize().
solve() [2/2]
template<typename Derived > constexpr decltype(auto) psr::IDESolverAPIMixin< Derived >::solve () && inline constexpr
Runs the solver on the configured problem. This can take some time and cannot be interrupted. If you need the ability to interrupt the solving process consider using solveUntil() or solveTimeout().
Returns
The computed analysis results
Definition at line 96 of file IDESolverAPIMixin.h.
solveUntil() [1/2]
template<typename Derived > template<typename CancellationRequest > requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>) constexpr auto psr::IDESolverAPIMixin< Derived >::solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval = std::chrono::seconds{1}) & inline constexpr
Solves the analysis problem and periodically checks every Interval whether CancellationRequested evaluates to true.
Note: Shortening the cancellation-check interval will make the cancellation-time more precise (by having more frequent calls to CancellationRequested) but also have negative impact on the solver's performance.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 150 of file IDESolverAPIMixin.h.
Referenced by psr::IDESolverAPIMixin< Derived >::solveWithTimeout().
solveUntil() [2/2]
template<typename Derived > template<typename CancellationRequest > requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>) constexpr auto psr::IDESolverAPIMixin< Derived >::solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval = std::chrono::seconds{1}) && inline constexpr
Solves the analysis problem and periodically checks every Interval whether CancellationRequested evaluates to true.
Note: Shortening the cancellation-check interval will make the cancellation-time more precise (by having more frequent calls to CancellationRequested) but also have negative impact on the solver's performance.
Returns
An std::optional holding the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 176 of file IDESolverAPIMixin.h.
solveWithAsyncCancellation() [1/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::solveWithAsyncCancellation (std::atomic_bool & IsCancelled) & inline constexpr
Solves the analysis problem and periodically checks whether IsCancelled is true.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 351 of file IDESolverAPIMixin.h.
References psr::IDESolverAPIMixin< Derived >::finalize().
solveWithAsyncCancellation() [2/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::solveWithAsyncCancellation (std::atomic_bool & IsCancelled) && inline constexpr
Solves the analysis problem and periodically checks whether IsCancelled is true.
Returns
An std::optional holding the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 366 of file IDESolverAPIMixin.h.
solveWithTimeout() [1/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) & inline constexpr
Solves the analysis problem and periodically checks every Interval whether the Timeout has been exceeded.
Note: Shortening the timeout-check interval will make the timeout more precise but also have negative impact on the solver's performance.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 263 of file IDESolverAPIMixin.h.
References psr::IDESolverAPIMixin< Derived >::solveUntil().
solveWithTimeout() [2/2]
template<typename Derived > constexpr auto psr::IDESolverAPIMixin< Derived >::solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) && inline constexpr
Solves the analysis problem and periodically checks every Interval whether the Timeout has been exceeded.
Note: Shortening the timeout-check interval will make the timeout more precise but also have negative impact on the solver's performance.
Returns
An std::optional holding a view into the analysis results or std::nullopt if the analysis was cancelled.
Definition at line 282 of file IDESolverAPIMixin.h.
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/IDESolverAPIMixin.h