PhASAR: psr::MemoryLocationAllocator Class Reference
psr::MemoryLocationAllocator Class Reference
A simple custom allocator that is used to allocate, e.g., AbstractMemoryLocation for the IDEExtendedTaintAnalysis.
#include "phasar/Utils/MemoryLocationAllocator.h"
Public Member Functions
constexpr MemoryLocationAllocator () noexcept=default
MemoryLocationAllocator (size_t InitialCapacity, size_t DynamicBlockSize=size_t(1024) *6 - 8)
constexpr MemoryLocationAllocator (MemoryLocationAllocator &&Other) noexcept
MemoryLocationAllocator & operator= (MemoryLocationAllocator &&Other) noexcept
~MemoryLocationAllocator ()
MemoryLocationAllocator (const MemoryLocationAllocator &)=delete
MemoryLocationAllocator & operator= (const MemoryLocationAllocator &)=delete
void swap (MemoryLocationAllocator &Other) noexcept
LLVM_ATTRIBUTE_RETURNS_NONNULL void * allocate (size_t NumBytes)
Allocates a chunk of memory of at least NumBytes bytes, aligned to alignof(void *).
Detailed Description
A simple custom allocator that is used to allocate, e.g., AbstractMemoryLocation for the IDEExtendedTaintAnalysis.
It can be used to allocate trivially destructible objects of variable size, e.g., using llvm::TrailingObjects, that should live as long as the allocator.
Definition at line 25 of file MemoryLocationAllocator.h.
Constructor & Destructor Documentation
MemoryLocationAllocator() [1/4]
constexpr psr::MemoryLocationAllocator::MemoryLocationAllocator () constexpr default noexcept
Referenced by operator=().
MemoryLocationAllocator() [2/4]
psr::MemoryLocationAllocator::MemoryLocationAllocator (size_t InitialCapacity, size_t DynamicBlockSize = size_t(1024) *6 - 8) explicit
MemoryLocationAllocator() [3/4]
constexpr psr::MemoryLocationAllocator::MemoryLocationAllocator (MemoryLocationAllocator && Other) inline constexpr noexcept
Definition at line 33 of file MemoryLocationAllocator.h.
~MemoryLocationAllocator()
psr::MemoryLocationAllocator::~MemoryLocationAllocator ()
MemoryLocationAllocator() [4/4]
psr::MemoryLocationAllocator::MemoryLocationAllocator (const MemoryLocationAllocator &) delete
Member Function Documentation
allocate()
LLVM_ATTRIBUTE_RETURNS_NONNULL void * psr::MemoryLocationAllocator::allocate (size_t NumBytes)
Allocates a chunk of memory of at least NumBytes bytes, aligned to alignof(void *).
Fails with llvm::report_bad_alloc_error(), if memory could not be allocated.
operator=() [1/2]
MemoryLocationAllocator & psr::MemoryLocationAllocator::operator= (const MemoryLocationAllocator &) delete
operator=() [2/2]
MemoryLocationAllocator & psr::MemoryLocationAllocator::operator= (MemoryLocationAllocator && Other) inline noexcept
Definition at line 39 of file MemoryLocationAllocator.h.
References MemoryLocationAllocator(), and swap().
swap()
void psr::MemoryLocationAllocator::swap (MemoryLocationAllocator & Other) inline noexcept
Definition at line 49 of file MemoryLocationAllocator.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
include/phasar/Utils/MemoryLocationAllocator.h