PhASAR: psr::StableVector< T, Allocator > Class Template Reference
psr::StableVector< T, Allocator > Class Template Reference
#include "phasar/Utils/StableVector.h"
Classes
class Iterator
Public Types
using iterator = Iterator< false >
using const_iterator = Iterator< true >
using value_type = T
using reference = value_type &
using const_reference = const value_type &
using difference_type = ptrdiff_t
using size_type = size_t
using allocator_type = typename std::allocator_traits< Allocator >::template rebind_alloc< T >
Public Member Functions
StableVector () noexcept(std::is_nothrow_default_constructible_v< allocator_type >)=default
StableVector (const allocator_type &Alloc) noexcept(std::is_nothrow_copy_constructible_v< allocator_type >)
StableVector (StableVector &&Other) noexcept
StableVector (const StableVector &Other)
void swap (StableVector &Other) noexcept
StableVector & operator= (const StableVector &)=delete
StableVector & operator= (StableVector &&Other) noexcept
~StableVector ()
StableVector clone () const
template<typename... ArgTys>
T & emplace_back (ArgTys &&...Args)
void push_back (const T &Elem)
void push_back (T &&Elem)
T & operator[] (size_t Index) noexcept
const T & operator[] (size_t Index) const noexcept
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
size_t size () const noexcept
bool empty () const noexcept
size_t max_size () const noexcept
size_t capacity () const noexcept
size_t getApproxSizeInBytes () const noexcept
T & front () noexcept
const T & front () const noexcept
T & back () noexcept
const T & back () const noexcept
void pop_back () noexcept
T pop_back_val () noexcept
void clear () noexcept
void pop_back_n (size_t N) noexcept
void shrink_to_fit () noexcept
allocator_type get_allocator () const noexcept(std::is_nothrow_copy_constructible_v< allocator_type >)
Friends
void swap (StableVector &LHS, StableVector &RHS) noexcept
bool operator== (const StableVector &LHS, const StableVector &RHS) noexcept
bool operator!= (const StableVector &LHS, const StableVector &RHS) noexcept
Detailed Description
template<typename T, typename Allocator = std::allocator<T>>
class psr::StableVector< T, Allocator >
A special-purpose container designed for providing the almost complete interface from std::vector, but with the guarantee that references to stored elements are not invalidated by insertion or deletion of other elements.
This container can be used as memory owner for objects of any size providing the allocator properties of std::pmr::monotonoc_buffer_resource but with the convenience of a standard container.
NOTE: This container performs slightly to very much better than std::deque depending on the task.
Definition at line 41 of file StableVector.h.
Member Typedef Documentation
allocator_type
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::allocator_type = typename std::allocator_traits<Allocator>::template rebind_alloc<T>
Definition at line 154 of file StableVector.h.
const_iterator
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::const_iterator = Iterator<true>
Definition at line 148 of file StableVector.h.
const_reference
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::const_reference = const value_type &
Definition at line 151 of file StableVector.h.
difference_type
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::difference_type = ptrdiff_t
Definition at line 152 of file StableVector.h.
iterator
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::iterator = Iterator<false>
Definition at line 147 of file StableVector.h.
reference
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::reference = value_type &
Definition at line 150 of file StableVector.h.
size_type
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::size_type = size_t
Definition at line 153 of file StableVector.h.
value_type
template<typename T , typename Allocator = std::allocator<T>> using psr::StableVector< T, Allocator >::value_type = T
Definition at line 149 of file StableVector.h.
Constructor & Destructor Documentation
StableVector() [1/4]
template<typename T , typename Allocator = std::allocator<T>> psr::StableVector< T, Allocator >::StableVector () const default noexcept
Referenced by psr::StableVector< T, Allocator >::clone().
StableVector() [2/4]
template<typename T , typename Allocator = std::allocator<T>> psr::StableVector< T, Allocator >::StableVector (const allocator_type & Alloc) inline noexcept
Definition at line 160 of file StableVector.h.
StableVector() [3/4]
template<typename T , typename Allocator = std::allocator<T>> psr::StableVector< T, Allocator >::StableVector (StableVector< T, Allocator > && Other) inline noexcept
Definition at line 164 of file StableVector.h.
StableVector() [4/4]
template<typename T , typename Allocator = std::allocator<T>> psr::StableVector< T, Allocator >::StableVector (const StableVector< T, Allocator > & Other) inline explicit
Definition at line 173 of file StableVector.h.
~StableVector()
template<typename T , typename Allocator = std::allocator<T>> psr::StableVector< T, Allocator >::~StableVector () inline
Definition at line 236 of file StableVector.h.
Member Function Documentation
back() [1/2]
template<typename T , typename Allocator = std::allocator<T>> const T & psr::StableVector< T, Allocator >::back () const inline noexcept
Definition at line 352 of file StableVector.h.
References psr::StableVector< T, Allocator >::empty().
back() [2/2]
template<typename T , typename Allocator = std::allocator<T>> T & psr::StableVector< T, Allocator >::back () inline noexcept
Definition at line 347 of file StableVector.h.
References psr::StableVector< T, Allocator >::empty().
Referenced by psr::StableVector< T, Allocator >::pop_back_val().
begin() [1/2]
template<typename T , typename Allocator = std::allocator<T>> const_iterator psr::StableVector< T, Allocator >::begin () const inline noexcept
Definition at line 313 of file StableVector.h.
References psr::StableVector< T, Allocator >::cbegin().
begin() [2/2]
template<typename T , typename Allocator = std::allocator<T>> iterator psr::StableVector< T, Allocator >::begin () inline noexcept
Definition at line 291 of file StableVector.h.
References psr::StableVector< T, Allocator >::empty(), and psr::StableVector< T, Allocator >::end().
capacity()
template<typename T , typename Allocator = std::allocator<T>> size_t psr::StableVector< T, Allocator >::capacity () const inline noexcept
Definition at line 329 of file StableVector.h.
References psr::StableVector< T, Allocator >::size().
Referenced by psr::StableVector< T, Allocator >::getApproxSizeInBytes().
cbegin()
template<typename T , typename Allocator = std::allocator<T>> const_iterator psr::StableVector< T, Allocator >::cbegin () const inline noexcept
Definition at line 302 of file StableVector.h.
References psr::StableVector< T, Allocator >::cend(), and psr::StableVector< T, Allocator >::empty().
Referenced by psr::StableVector< T, Allocator >::begin().
cend()
template<typename T , typename Allocator = std::allocator<T>> const_iterator psr::StableVector< T, Allocator >::cend () const inline noexcept
Definition at line 308 of file StableVector.h.
Referenced by psr::StableVector< T, Allocator >::cbegin(), and psr::StableVector< T, Allocator >::end().
clear()
template<typename T , typename Allocator = std::allocator<T>> void psr::StableVector< T, Allocator >::clear () inline noexcept
Definition at line 388 of file StableVector.h.
clone()
template<typename T , typename Allocator = std::allocator<T>> StableVector psr::StableVector< T, Allocator >::clone () const inline
Due to the 'explicit' copy ctor, creating copies may be cumbersome, i.e. having to specify the whole type. So, provide a utility function for it
Definition at line 264 of file StableVector.h.
References psr::StableVector< T, Allocator >::StableVector().
emplace_back()
template<typename T , typename Allocator = std::allocator<T>> template<typename... ArgTys> T & psr::StableVector< T, Allocator >::emplace_back (ArgTys &&... Args) inline
Definition at line 266 of file StableVector.h.
References psr::Ret.
Referenced by psr::AliasSetOwner< AliasSetTy >::acquire(), psr::CallGraphBuilder< N, F >::addInstructionVertex(), psr::StableVector< T, Allocator >::push_back(), and psr::StableVector< T, Allocator >::push_back().
empty()
template<typename T , typename Allocator = std::allocator<T>> bool psr::StableVector< T, Allocator >::empty () const inline noexcept
Definition at line 317 of file StableVector.h.
Referenced by psr::StableVector< T, Allocator >::back(), psr::StableVector< T, Allocator >::back(), psr::StableVector< T, Allocator >::begin(), psr::StableVector< T, Allocator >::cbegin(), psr::StableVector< T, Allocator >::front(), psr::StableVector< T, Allocator >::front(), and psr::StableVector< T, Allocator >::pop_back().
end() [1/2]
template<typename T , typename Allocator = std::allocator<T>> const_iterator psr::StableVector< T, Allocator >::end () const inline noexcept
Definition at line 314 of file StableVector.h.
References psr::StableVector< T, Allocator >::cend().
end() [2/2]
template<typename T , typename Allocator = std::allocator<T>> iterator psr::StableVector< T, Allocator >::end () inline noexcept
Definition at line 297 of file StableVector.h.
Referenced by psr::StableVector< T, Allocator >::begin().
front() [1/2]
template<typename T , typename Allocator = std::allocator<T>> const T & psr::StableVector< T, Allocator >::front () const inline noexcept
Definition at line 342 of file StableVector.h.
References psr::StableVector< T, Allocator >::empty().
front() [2/2]
template<typename T , typename Allocator = std::allocator<T>> T & psr::StableVector< T, Allocator >::front () inline noexcept
Definition at line 337 of file StableVector.h.
References psr::StableVector< T, Allocator >::empty().
get_allocator()
template<typename T , typename Allocator = std::allocator<T>> allocator_type psr::StableVector< T, Allocator >::get_allocator () const inline noexcept
Definition at line 500 of file StableVector.h.
getApproxSizeInBytes()
template<typename T , typename Allocator = std::allocator<T>> size_t psr::StableVector< T, Allocator >::getApproxSizeInBytes () const inline noexcept
Definition at line 333 of file StableVector.h.
References psr::StableVector< T, Allocator >::capacity().
max_size()
template<typename T , typename Allocator = std::allocator<T>> size_t psr::StableVector< T, Allocator >::max_size () const inline noexcept
In theory, we could allocate as many blocks as necessary, such that the accumulated size of them is exactly SIZE_MAX+1, but this will already overflow the Size field and we still need to store the blocks and the other metadata somewhere, so we will never be able to allocate the last block (with size SIZE_MAX/2). Hence, the maximum number of elements will be SIZE_MAX/2;
Definition at line 319 of file StableVector.h.
operator=() [1/2]
template<typename T , typename Allocator = std::allocator<T>> StableVector & psr::StableVector< T, Allocator >::operator= (const StableVector< T, Allocator > &) delete
operator=() [2/2]
template<typename T , typename Allocator = std::allocator<T>> StableVector & psr::StableVector< T, Allocator >::operator= (StableVector< T, Allocator > && Other) inline noexcept
Definition at line 231 of file StableVector.h.
References psr::StableVector< T, Allocator >::swap.
operator[]() [1/2]
template<typename T , typename Allocator = std::allocator<T>> const T & psr::StableVector< T, Allocator >::operator[] (size_t Index) const inline noexcept
Definition at line 287 of file StableVector.h.
operator[]() [2/2]
template<typename T , typename Allocator = std::allocator<T>> T & psr::StableVector< T, Allocator >::operator[] (size_t Index) inline noexcept
Definition at line 283 of file StableVector.h.
pop_back()
template<typename T , typename Allocator = std::allocator<T>> void psr::StableVector< T, Allocator >::pop_back () inline noexcept
Definition at line 357 of file StableVector.h.
References psr::StableVector< T, Allocator >::empty().
Referenced by psr::StableVector< T, Allocator >::pop_back_val().
pop_back_n()
template<typename T , typename Allocator = std::allocator<T>> void psr::StableVector< T, Allocator >::pop_back_n (size_t N) inline noexcept
Definition at line 409 of file StableVector.h.
pop_back_val()
template<typename T , typename Allocator = std::allocator<T>> T psr::StableVector< T, Allocator >::pop_back_val () inline noexcept
Definition at line 382 of file StableVector.h.
References psr::StableVector< T, Allocator >::back(), psr::StableVector< T, Allocator >::pop_back(), and psr::Ret.
push_back() [1/2]
template<typename T , typename Allocator = std::allocator<T>> void psr::StableVector< T, Allocator >::push_back (const T & Elem) inline
Definition at line 280 of file StableVector.h.
References psr::StableVector< T, Allocator >::emplace_back().
push_back() [2/2]
template<typename T , typename Allocator = std::allocator<T>> void psr::StableVector< T, Allocator >::push_back (T && Elem) inline
Definition at line 281 of file StableVector.h.
References psr::StableVector< T, Allocator >::emplace_back().
shrink_to_fit()
template<typename T , typename Allocator = std::allocator<T>> void psr::StableVector< T, Allocator >::shrink_to_fit () inline noexcept
Definition at line 446 of file StableVector.h.
size()
template<typename T , typename Allocator = std::allocator<T>> size_t psr::StableVector< T, Allocator >::size () const inline noexcept
Definition at line 316 of file StableVector.h.
Referenced by psr::StableVector< T, Allocator >::capacity().
swap()
template<typename T , typename Allocator = std::allocator<T>> void psr::StableVector< T, Allocator >::swap (StableVector< T, Allocator > & Other) inline noexcept
Definition at line 207 of file StableVector.h.
Friends And Related Symbol Documentation
operator!=
template<typename T , typename Allocator = std::allocator<T>> bool operator!= (const StableVector< T, Allocator > & LHS, const StableVector< T, Allocator > & RHS) friend
Definition at line 495 of file StableVector.h.
operator==
template<typename T , typename Allocator = std::allocator<T>> bool operator== (const StableVector< T, Allocator > & LHS, const StableVector< T, Allocator > & RHS) friend
Definition at line 470 of file StableVector.h.
swap
template<typename T , typename Allocator = std::allocator<T>> void swap (StableVector< T, Allocator > & LHS, StableVector< T, Allocator > & RHS) friend
Definition at line 224 of file StableVector.h.
Referenced by psr::StableVector< T, Allocator >::operator=().
The documentation for this class was generated from the following file:
include/phasar/Utils/StableVector.h