PhASAR: psr::IDEIIAFlowFact Class Reference
psr::IDEIIAFlowFact Class Reference
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h"
Public Member Functions
~IDEIIAFlowFact ()=default
IDEIIAFlowFact ()=default
IDEIIAFlowFact (const llvm::Value *BaseVal)
IDEIIAFlowFact (const llvm::Value *BaseVal, llvm::SmallVector< const llvm::GetElementPtrInst *, KLimit > FieldDesc)
Construct a data-flow fact from the base value and field specification.
bool flowFactEqual (const IDEIIAFlowFact &Other) const
const llvm::Value * getBase () const
llvm::SmallVector< const llvm::GetElementPtrInst *, KLimit > getField () const
constexpr unsigned getKLimit () const
void print (llvm::raw_ostream &OS, bool IsForDebug=false) const
bool operator== (const IDEIIAFlowFact &Other) const
bool operator!= (const IDEIIAFlowFact &Other) const
bool operator< (const IDEIIAFlowFact &Other) const
bool operator== (const llvm::Value *V) const
operator const llvm::Value * ()
std::string str () const
Static Public Member Functions
static IDEIIAFlowFact create (const llvm::Value *BaseVal)
Static Public Attributes
static constexpr unsigned KLimit = 2
Detailed Description
Definition at line 104 of file IDEInstInteractionAnalysis.h.
Constructor & Destructor Documentation
~IDEIIAFlowFact()
psr::IDEIIAFlowFact::~IDEIIAFlowFact () default
IDEIIAFlowFact() [1/3]
psr::IDEIIAFlowFact::IDEIIAFlowFact () default
IDEIIAFlowFact() [2/3]
psr::IDEIIAFlowFact::IDEIIAFlowFact (const llvm::Value * BaseVal)
Constructs a data-flow fact from the base value. Fields are ignored. Use the factory function(s) to construct field-sensitive data-flow facts.
IDEIIAFlowFact() [3/3]
psr::IDEIIAFlowFact::IDEIIAFlowFact (const llvm::Value * BaseVal, llvm::SmallVector< const llvm::GetElementPtrInst *, KLimit > FieldDesc)
Construct a data-flow fact from the base value and field specification.
Member Function Documentation
create()
static IDEIIAFlowFact psr::IDEIIAFlowFact::create (const llvm::Value * BaseVal) static
Creates a new data-flow fact of the base value that respects fields. Field accesses that exceed the specified depth will be collapsed and not further distinguished.
flowFactEqual()
bool psr::IDEIIAFlowFact::flowFactEqual (const IDEIIAFlowFact & Other) const
Returns whether this data-flow fact describes the same abstract memory location than the other one.
getBase()
const llvm::Value * psr::IDEIIAFlowFact::getBase () const inline
Definition at line 133 of file IDEInstInteractionAnalysis.h.
Referenced by llvm::DenseMapInfo< psr::IDEIIAFlowFact >::isEqual(), and std::hash< psr::IDEIIAFlowFact >::operator()().
getField()
llvm::SmallVector< const llvm::GetElementPtrInst *, KLimit > psr::IDEIIAFlowFact::getField () const inline
Definition at line 136 of file IDEInstInteractionAnalysis.h.
getKLimit()
constexpr unsigned psr::IDEIIAFlowFact::getKLimit () const inline constexpr
Definition at line 139 of file IDEInstInteractionAnalysis.h.
References KLimit.
operator const llvm::Value *()
psr::IDEIIAFlowFact::operator const llvm::Value * () inline
Definition at line 149 of file IDEInstInteractionAnalysis.h.
operator!=()
bool psr::IDEIIAFlowFact::operator!= (const IDEIIAFlowFact & Other) const
operator<()
bool psr::IDEIIAFlowFact::operator< (const IDEIIAFlowFact & Other) const
operator==() [1/2]
bool psr::IDEIIAFlowFact::operator== (const IDEIIAFlowFact & Other) const
operator==() [2/2]
bool psr::IDEIIAFlowFact::operator== (const llvm::Value * V) const
print()
void psr::IDEIIAFlowFact::print (llvm::raw_ostream & OS, bool IsForDebug = false) const
Referenced by str().
str()
std::string psr::IDEIIAFlowFact::str () const inline
Definition at line 151 of file IDEInstInteractionAnalysis.h.
References print(), and psr::Ret.
Member Data Documentation
KLimit
constexpr unsigned psr::IDEIIAFlowFact::KLimit = 2 static constexpr
Definition at line 107 of file IDEInstInteractionAnalysis.h.
Referenced by getKLimit().
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h