PhASAR: psr::library_summary::LLVMFunctionDataFlowFacts Class Reference
psr::library_summary::LLVMFunctionDataFlowFacts Class Reference
A LLVM-specific mapping of FunctionDataFlowFacts.
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/LLVMFunctionDataFlowFacts.h"
Public Types
using ParameterMappingTy = FunctionDataFlowFacts::ParameterMappingTy
Public Member Functions
LLVMFunctionDataFlowFacts () noexcept=default
void insertSet (const llvm::Function *Fun, uint32_t Index, std::vector< DataFlowFact > OutSet)
insert a set of data flow facts
void insertSet (const llvm::Function *Fun, const llvm::Argument *Arg, std::vector< DataFlowFact > OutSet)
void addElement (const llvm::Function *Fun, uint32_t Index, DataFlowFact Out)
void addElement (const llvm::Function *Fun, const llvm::Argument *Arg, DataFlowFact Out)
bool contains (const llvm::Function *Fn)
const std::vector< DataFlowFact > & getFacts (const llvm::Function *Fun, uint32_t Index)
const std::vector< DataFlowFact > & getFacts (const llvm::Function *Fun, const llvm::Argument *Arg)
const ParameterMappingTy & getFactsForFunction (const llvm::Function *Fun)
Friends
LLVMFunctionDataFlowFacts readFromFDFF (const FunctionDataFlowFacts &Fdff, const LLVMProjectIRDB &Irdb)
Detailed Description
A LLVM-specific mapping of FunctionDataFlowFacts.
Definition at line 30 of file LLVMFunctionDataFlowFacts.h.
Member Typedef Documentation
ParameterMappingTy
using psr::library_summary::LLVMFunctionDataFlowFacts::ParameterMappingTy = FunctionDataFlowFacts::ParameterMappingTy
Definition at line 33 of file LLVMFunctionDataFlowFacts.h.
Constructor & Destructor Documentation
LLVMFunctionDataFlowFacts()
psr::library_summary::LLVMFunctionDataFlowFacts::LLVMFunctionDataFlowFacts () default noexcept
Member Function Documentation
addElement() [1/2]
void psr::library_summary::LLVMFunctionDataFlowFacts::addElement (const llvm::Function * Fun, const llvm::Argument * Arg, DataFlowFact Out) inline
Definition at line 50 of file LLVMFunctionDataFlowFacts.h.
References addElement().
addElement() [2/2]
void psr::library_summary::LLVMFunctionDataFlowFacts::addElement (const llvm::Function * Fun, uint32_t Index, DataFlowFact Out) inline
Definition at line 47 of file LLVMFunctionDataFlowFacts.h.
Referenced by addElement().
contains()
bool psr::library_summary::LLVMFunctionDataFlowFacts::contains (const llvm::Function * Fn) inline
Definition at line 55 of file LLVMFunctionDataFlowFacts.h.
getFacts() [1/2]
const std::vector< DataFlowFact > & psr::library_summary::LLVMFunctionDataFlowFacts::getFacts (const llvm::Function * Fun, const llvm::Argument * Arg) inline
Definition at line 68 of file LLVMFunctionDataFlowFacts.h.
References getFacts().
getFacts() [2/2]
const std::vector< DataFlowFact > & psr::library_summary::LLVMFunctionDataFlowFacts::getFacts (const llvm::Function * Fun, uint32_t Index) inline
Definition at line 60 of file LLVMFunctionDataFlowFacts.h.
Referenced by getFacts().
getFactsForFunction()
const ParameterMappingTy & psr::library_summary::LLVMFunctionDataFlowFacts::getFactsForFunction (const llvm::Function * Fun) inline
Definition at line 73 of file LLVMFunctionDataFlowFacts.h.
insertSet() [1/2]
void psr::library_summary::LLVMFunctionDataFlowFacts::insertSet (const llvm::Function * Fun, const llvm::Argument * Arg, std::vector< DataFlowFact > OutSet) inline
Definition at line 41 of file LLVMFunctionDataFlowFacts.h.
References insertSet().
insertSet() [2/2]
void psr::library_summary::LLVMFunctionDataFlowFacts::insertSet (const llvm::Function * Fun, uint32_t Index, std::vector< DataFlowFact > OutSet) inline
insert a set of data flow facts
Definition at line 36 of file LLVMFunctionDataFlowFacts.h.
Referenced by insertSet().
Friends And Related Symbol Documentation
readFromFDFF
LLVMFunctionDataFlowFacts readFromFDFF (const FunctionDataFlowFacts & Fdff, const LLVMProjectIRDB & Irdb) friend
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/LLVMFunctionDataFlowFacts.h