PhASAR: psr::DenseTable1d< K, V > Class Template Reference
psr::DenseTable1d< K, V > Class Template Reference
#include "phasar/Utils/TableWrappers.h"
Public Types
using value_type = std::pair< K, V >
using iterator = typename llvm::DenseMap< K, V >::iterator
using const_iterator = typename llvm::DenseMap< K, V >::const_iterator
Public Member Functions
DenseTable1d () noexcept=default
template<typename Allocator >
DenseTable1d (Allocator) noexcept
Dummy ctor for compatibility with UnorderedTable1d.
void reserve (size_t Capacity)
bool contains (ByConstRef< K > Key) const noexcept
V & getOrCreate (K Key)
auto insert (K Key, V Value)
V getOr (ByConstRef< K > Key, V Or) const
const V & getOr (ByConstRef< K > Key, const V &Or) const
const V & getOr (ByConstRef< K > Key, V &&Or) const =delete
const_iterator find (ByConstRef< K > Key) const
void erase (ByConstRef< K > Key)
void erase (iterator It)
auto cells () noexcept
auto cells () const noexcept
detail::CellVecSmallVectorTy< value_type > cellVec () const
template<typename FilterFn >
detail::CellVecSmallVectorTy< value_type > cellVec (FilterFn Filter) const
template<typename Projection , typename ResultProjection = IdentityFn>
detail::CellVecSmallVectorTy< std::pair< std::invoke_result_t< ResultProjection, K >, V > > allOf (Projection Proj, ByConstRef< std::invoke_result_t< Projection, K > > Of, ResultProjection ResProj={}) const
void clear () noexcept
size_t size () const noexcept
bool empty () const noexcept
size_t getApproxSizeInBytes () const noexcept
Detailed Description
template<typename K, typename V>
class psr::DenseTable1d< K, V >
Definition at line 459 of file TableWrappers.h.
Member Typedef Documentation
const_iterator
template<typename K , typename V > using psr::DenseTable1d< K, V >::const_iterator = typename llvm::DenseMap<K, V>::const_iterator
Definition at line 464 of file TableWrappers.h.
iterator
template<typename K , typename V > using psr::DenseTable1d< K, V >::iterator = typename llvm::DenseMap<K, V>::iterator
Definition at line 463 of file TableWrappers.h.
value_type
template<typename K , typename V > using psr::DenseTable1d< K, V >::value_type = std::pair<K, V>
Definition at line 462 of file TableWrappers.h.
Constructor & Destructor Documentation
DenseTable1d() [1/2]
template<typename K , typename V > psr::DenseTable1d< K, V >::DenseTable1d () default noexcept
DenseTable1d() [2/2]
template<typename K , typename V > template<typename Allocator > psr::DenseTable1d< K, V >::DenseTable1d (Allocator) inline explicit noexcept
Dummy ctor for compatibility with UnorderedTable1d.
Definition at line 469 of file TableWrappers.h.
Member Function Documentation
allOf()
template<typename K , typename V > template<typename Projection , typename ResultProjection = IdentityFn> detail::CellVecSmallVectorTy< std::pair< std::invoke_result_t< ResultProjection, K >, V > > psr::DenseTable1d< K, V >::allOf (Projection Proj, ByConstRef< std::invoke_result_t< Projection, K > > Of, ResultProjection ResProj = {}) const inline
Definition at line 536 of file TableWrappers.h.
cells() [1/2]
template<typename K , typename V > auto psr::DenseTable1d< K, V >::cells () const inline noexcept
Definition at line 511 of file TableWrappers.h.
cells() [2/2]
template<typename K , typename V > auto psr::DenseTable1d< K, V >::cells () inline noexcept
Definition at line 510 of file TableWrappers.h.
cellVec() [1/2]
template<typename K , typename V > detail::CellVecSmallVectorTy< value_type > psr::DenseTable1d< K, V >::cellVec () const inline
Definition at line 515 of file TableWrappers.h.
References psr::Ret.
cellVec() [2/2]
template<typename K , typename V > template<typename FilterFn > detail::CellVecSmallVectorTy< value_type > psr::DenseTable1d< K, V >::cellVec (FilterFn Filter) const inline
Definition at line 523 of file TableWrappers.h.
References psr::Ret.
clear()
template<typename K , typename V > void psr::DenseTable1d< K, V >::clear () inline noexcept
Definition at line 549 of file TableWrappers.h.
Referenced by psr::FlowFunctionCache< ProblemTy, AutoAddZero >::clear().
contains()
template<typename K , typename V > bool psr::DenseTable1d< K, V >::contains (ByConstRef< K > Key) const inline noexcept
Definition at line 473 of file TableWrappers.h.
empty()
template<typename K , typename V > bool psr::DenseTable1d< K, V >::empty () const inline noexcept
Definition at line 555 of file TableWrappers.h.
erase() [1/2]
template<typename K , typename V > void psr::DenseTable1d< K, V >::erase (ByConstRef< K > Key) inline
Definition at line 507 of file TableWrappers.h.
erase() [2/2]
template<typename K , typename V > void psr::DenseTable1d< K, V >::erase (iterator It) inline
Definition at line 508 of file TableWrappers.h.
find()
template<typename K , typename V > const_iterator psr::DenseTable1d< K, V >::find (ByConstRef< K > Key) const inline
Definition at line 505 of file TableWrappers.h.
getApproxSizeInBytes()
template<typename K , typename V > size_t psr::DenseTable1d< K, V >::getApproxSizeInBytes () const inline noexcept
Definition at line 557 of file TableWrappers.h.
getOr() [1/3]
template<typename K , typename V > const V & psr::DenseTable1d< K, V >::getOr (ByConstRef< K > Key, const V & Or) const inline
Definition at line 492 of file TableWrappers.h.
getOr() [2/3]
template<typename K , typename V > const V & psr::DenseTable1d< K, V >::getOr (ByConstRef< K > Key, V && Or) const delete
getOr() [3/3]
template<typename K , typename V > V psr::DenseTable1d< K, V >::getOr (ByConstRef< K > Key, V Or) const inline
Definition at line 483 of file TableWrappers.h.
getOrCreate()
template<typename K , typename V > V & psr::DenseTable1d< K, V >::getOrCreate (K Key) inline
Definition at line 477 of file TableWrappers.h.
Referenced by psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getRetFlowFunction().
insert()
template<typename K , typename V > auto psr::DenseTable1d< K, V >::insert (K Key, V Value) inline
Definition at line 479 of file TableWrappers.h.
reserve()
template<typename K , typename V > void psr::DenseTable1d< K, V >::reserve (size_t Capacity) inline
Definition at line 471 of file TableWrappers.h.
Referenced by psr::FlowFunctionCache< ProblemTy, AutoAddZero >::reserve().
size()
template<typename K , typename V > size_t psr::DenseTable1d< K, V >::size () const inline noexcept
Definition at line 554 of file TableWrappers.h.
Referenced by psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getStats().
The documentation for this class was generated from the following file:
include/phasar/Utils/TableWrappers.h