PhASAR: psr::TypedVector< IdT, ValueT, SmallSize > Class Template Reference
psr::TypedVector< IdT, ValueT, SmallSize > Class Template Reference
#include "phasar/Utils/TypedVector.h"
Public Member Functions
TypedVector () noexcept=default
TypedVector (std::initializer_list< ValueT > IList)
TypedVector (size_t Size)
TypedVector (size_t Size, ByConstRef< ValueT > Default)
template<typename Iter >
TypedVector (Iter From, Iter To)
TypedVector (llvm::ArrayRef< ValueT > Arr)
void reserve (size_t Capa)
void resize (size_t Sz)
void resize (size_t Sz, ByConstRef< ValueT > Val)
bool empty () const noexcept
bool any () const noexcept
size_t size () const noexcept
size_t capacity () const noexcept
bool inbounds (IdT Id) const noexcept
const ValueT & operator[] (IdT Id) const &
ValueT & operator[] (IdT Id) &
ValueT operator[] (IdT Id) &&
auto begin () noexcept
auto end () noexcept
auto begin () const noexcept
auto end () const noexcept
template<typename... ArgsT>
ValueT & emplace_back (ArgsT &&...Args)
void push_back (ByConstRef< ValueT > Val)
template<typename T = ValueT>
std::enable_if_t<!CanEfficientlyPassByValue< T > > push_back (ValueT &&Val)
void pop_back ()
ValueT pop_back_val ()
bool operator== (const TypedVector &Other) const noexcept
bool operator!= (const TypedVector &Other) const noexcept
llvm::ArrayRef< ValueT > asRef () const &noexcept
llvm::ArrayRef< ValueT > asRef () &&noexcept=delete
llvm::ArrayRef< ValueT > drop_front (size_t Offs) const &noexcept
llvm::ArrayRef< ValueT > drop_front (size_t Offs) &&noexcept=delete
auto enumerate () const noexcept
auto enumerate () noexcept
Detailed Description
template<typename IdT, typename ValueT, unsigned SmallSize = 0>
class psr::TypedVector< IdT, ValueT, SmallSize >
Wraps a llvm::SmallVector, allowing index-based access by IdT, instead of size_t.
Template Parameters
IdT The index-type that should be used for operator[]. Must be losslessly convertible from and to size_t.
ValueT The usual value_type of SmallVector.
SmallSize The size of the inline-storage of SmallVector (default: 0)
Definition at line 36 of file TypedVector.h.
Constructor & Destructor Documentation
TypedVector() [1/6]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> psr::TypedVector< IdT, ValueT, SmallSize >::TypedVector () default noexcept
TypedVector() [2/6]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> psr::TypedVector< IdT, ValueT, SmallSize >::TypedVector (std::initializer_list< ValueT > IList) inline
Definition at line 39 of file TypedVector.h.
TypedVector() [3/6]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> psr::TypedVector< IdT, ValueT, SmallSize >::TypedVector (size_t Size) inline
Definition at line 40 of file TypedVector.h.
TypedVector() [4/6]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> psr::TypedVector< IdT, ValueT, SmallSize >::TypedVector (size_t Size, ByConstRef< ValueT > Default) inline
Definition at line 41 of file TypedVector.h.
TypedVector() [5/6]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> template<typename Iter > psr::TypedVector< IdT, ValueT, SmallSize >::TypedVector (Iter From, Iter To) inline explicit
Definition at line 44 of file TypedVector.h.
TypedVector() [6/6]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> psr::TypedVector< IdT, ValueT, SmallSize >::TypedVector (llvm::ArrayRef< ValueT > Arr) inline explicit
Definition at line 47 of file TypedVector.h.
Member Function Documentation
any()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> bool psr::TypedVector< IdT, ValueT, SmallSize >::any () const inline noexcept
Definition at line 57 of file TypedVector.h.
asRef() [1/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> llvm::ArrayRef< ValueT > psr::TypedVector< IdT, ValueT, SmallSize >::asRef () && delete noexcept
asRef() [2/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> llvm::ArrayRef< ValueT > psr::TypedVector< IdT, ValueT, SmallSize >::asRef () const & inline noexcept
Definition at line 107 of file TypedVector.h.
Referenced by psr::TypedVector< IdT, ValueT, SmallSize >::drop_front().
begin() [1/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> auto psr::TypedVector< IdT, ValueT, SmallSize >::begin () const inline noexcept
Definition at line 83 of file TypedVector.h.
begin() [2/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> auto psr::TypedVector< IdT, ValueT, SmallSize >::begin () inline noexcept
Definition at line 80 of file TypedVector.h.
capacity()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> size_t psr::TypedVector< IdT, ValueT, SmallSize >::capacity () const inline noexcept
Definition at line 59 of file TypedVector.h.
drop_front() [1/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> llvm::ArrayRef< ValueT > psr::TypedVector< IdT, ValueT, SmallSize >::drop_front (size_t Offs) && delete noexcept
drop_front() [2/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> llvm::ArrayRef< ValueT > psr::TypedVector< IdT, ValueT, SmallSize >::drop_front (size_t Offs) const & inline noexcept
Definition at line 112 of file TypedVector.h.
References psr::TypedVector< IdT, ValueT, SmallSize >::asRef().
emplace_back()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> template<typename... ArgsT> ValueT & psr::TypedVector< IdT, ValueT, SmallSize >::emplace_back (ArgsT &&... Args) inline
Definition at line 86 of file TypedVector.h.
empty()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> bool psr::TypedVector< IdT, ValueT, SmallSize >::empty () const inline noexcept
Definition at line 56 of file TypedVector.h.
end() [1/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> auto psr::TypedVector< IdT, ValueT, SmallSize >::end () const inline noexcept
Definition at line 84 of file TypedVector.h.
end() [2/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> auto psr::TypedVector< IdT, ValueT, SmallSize >::end () inline noexcept
Definition at line 81 of file TypedVector.h.
enumerate() [1/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> auto psr::TypedVector< IdT, ValueT, SmallSize >::enumerate () const inline noexcept
Definition at line 118 of file TypedVector.h.
enumerate() [2/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> auto psr::TypedVector< IdT, ValueT, SmallSize >::enumerate () inline noexcept
Definition at line 124 of file TypedVector.h.
inbounds()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> bool psr::TypedVector< IdT, ValueT, SmallSize >::inbounds (IdT Id) const inline noexcept
Definition at line 61 of file TypedVector.h.
References psr::TypedVector< IdT, ValueT, SmallSize >::size().
Referenced by psr::TypedVector< IdT, ValueT, SmallSize >::operator[](), psr::TypedVector< IdT, ValueT, SmallSize >::operator[](), and psr::TypedVector< IdT, ValueT, SmallSize >::operator[]().
operator!=()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> bool psr::TypedVector< IdT, ValueT, SmallSize >::operator!= (const TypedVector< IdT, ValueT, SmallSize > & Other) const inline noexcept
Definition at line 103 of file TypedVector.h.
operator==()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> bool psr::TypedVector< IdT, ValueT, SmallSize >::operator== (const TypedVector< IdT, ValueT, SmallSize > & Other) const inline noexcept
Definition at line 100 of file TypedVector.h.
operator[]() [1/3]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> ValueT & psr::TypedVector< IdT, ValueT, SmallSize >::operator[] (IdT Id) & inline
Definition at line 70 of file TypedVector.h.
References psr::TypedVector< IdT, ValueT, SmallSize >::inbounds().
operator[]() [2/3]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> ValueT psr::TypedVector< IdT, ValueT, SmallSize >::operator[] (IdT Id) && inline
Definition at line 75 of file TypedVector.h.
References psr::TypedVector< IdT, ValueT, SmallSize >::inbounds().
operator[]() [3/3]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> const ValueT & psr::TypedVector< IdT, ValueT, SmallSize >::operator[] (IdT Id) const & inline
Definition at line 65 of file TypedVector.h.
References psr::TypedVector< IdT, ValueT, SmallSize >::inbounds().
pop_back()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> void psr::TypedVector< IdT, ValueT, SmallSize >::pop_back () inline
Definition at line 97 of file TypedVector.h.
pop_back_val()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> ValueT psr::TypedVector< IdT, ValueT, SmallSize >::pop_back_val () inline
Definition at line 98 of file TypedVector.h.
push_back() [1/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> void psr::TypedVector< IdT, ValueT, SmallSize >::push_back (ByConstRef< ValueT > Val) inline
Definition at line 90 of file TypedVector.h.
push_back() [2/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> template<typename T = ValueT> std::enable_if_t<!CanEfficientlyPassByValue< T > > psr::TypedVector< IdT, ValueT, SmallSize >::push_back (ValueT && Val) inline
Definition at line 93 of file TypedVector.h.
reserve()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> void psr::TypedVector< IdT, ValueT, SmallSize >::reserve (size_t Capa) inline
Definition at line 50 of file TypedVector.h.
resize() [1/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> void psr::TypedVector< IdT, ValueT, SmallSize >::resize (size_t Sz) inline
Definition at line 52 of file TypedVector.h.
resize() [2/2]
template<typename IdT , typename ValueT , unsigned SmallSize = 0> void psr::TypedVector< IdT, ValueT, SmallSize >::resize (size_t Sz, ByConstRef< ValueT > Val) inline
Definition at line 54 of file TypedVector.h.
size()
template<typename IdT , typename ValueT , unsigned SmallSize = 0> size_t psr::TypedVector< IdT, ValueT, SmallSize >::size () const inline noexcept
Definition at line 58 of file TypedVector.h.
Referenced by psr::vta::TypeAssignmentGraph::addEdge(), and psr::TypedVector< IdT, ValueT, SmallSize >::inbounds().
The documentation for this class was generated from the following file:
include/phasar/Utils/TypedVector.h