PhASAR: psr::TaintConfigBase< Derived > Class Template Reference
psr::TaintConfigBase< Derived > Class Template Reference
#include "phasar/PhasarLLVM/TaintConfig/TaintConfigBase.h"
Public Types
using n_t = typename TaintConfigTraits< Derived >::n_t
using v_t = typename TaintConfigTraits< Derived >::v_t
using f_t = typename TaintConfigTraits< Derived >::f_t
using TaintDescriptionCallBackTy = llvm::unique_function< std::set< v_t >(n_t) const >
Public Member Functions
void registerSourceCallBack (TaintDescriptionCallBackTy CB) noexcept
void registerSinkCallBack (TaintDescriptionCallBackTy CB) noexcept
void registerSanitizerCallBack (TaintDescriptionCallBackTy CB) noexcept
const TaintDescriptionCallBackTy & getRegisteredSourceCallBack () const noexcept
const TaintDescriptionCallBackTy & getRegisteredSinkCallBack () const noexcept
const TaintDescriptionCallBackTy & getRegisteredSanitizerCallBack () const noexcept
bool isSource (v_t Val) const
bool isSink (v_t Val) const
bool isSanitizer (v_t Val) const
template<typename HandlerFn >
void forAllGeneratedValuesAt (n_t Inst, Nullable< f_t > Callee, HandlerFn &&Handler) const
Calls Handler for all operands of Inst (maybe including Inst itself) that are generated unconditionally as tainted.
template<typename HandlerFn >
void forAllLeakCandidatesAt (n_t Inst, Nullable< f_t > Callee, HandlerFn &&Handler) const
Calls Handler for all operands of Inst that may generate a leak when they are tainted.
template<typename HandlerFn >
void forAllSanitizedValuesAt (n_t Inst, Nullable< f_t > Callee, HandlerFn &&Handler) const
Calls Handler for all operands of Inst that become sanitized after the instruction is completed.
bool generatesValuesAt (n_t Inst, Nullable< f_t > Callee) const
bool mayLeakValuesAt (n_t Inst, Nullable< f_t > Callee) const
bool sanitizesValuesAt (n_t Inst, Nullable< f_t > Callee) const
TaintCategory getCategory (v_t Val) const
std::map< n_t, std::set< v_t > > makeInitialSeeds () const
void print (llvm::raw_ostream &OS=llvm::outs()) const
LLVM_DUMP_METHOD void dump () const
Protected Attributes
TaintDescriptionCallBackTy SourceCallBack {}
TaintDescriptionCallBackTy SinkCallBack {}
TaintDescriptionCallBackTy SanitizerCallBack {}
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const TaintConfigBase &TC)
Detailed Description
template<typename Derived>
class psr::TaintConfigBase< Derived >
Definition at line 35 of file TaintConfigBase.h.
Member Typedef Documentation
f_t
template<typename Derived > using psr::TaintConfigBase< Derived >::f_t = typename TaintConfigTraits<Derived>::f_t
Definition at line 39 of file TaintConfigBase.h.
n_t
template<typename Derived > using psr::TaintConfigBase< Derived >::n_t = typename TaintConfigTraits<Derived>::n_t
Definition at line 37 of file TaintConfigBase.h.
TaintDescriptionCallBackTy
template<typename Derived > using psr::TaintConfigBase< Derived >::TaintDescriptionCallBackTy = llvm::unique_function<std::set<v_t>(n_t) const>
Definition at line 41 of file TaintConfigBase.h.
v_t
template<typename Derived > using psr::TaintConfigBase< Derived >::v_t = typename TaintConfigTraits<Derived>::v_t
Definition at line 38 of file TaintConfigBase.h.
Member Function Documentation
dump()
template<typename Derived > LLVM_DUMP_METHOD void psr::TaintConfigBase< Derived >::dump () const inline
Definition at line 135 of file TaintConfigBase.h.
References psr::TaintConfigBase< Derived >::print().
forAllGeneratedValuesAt()
template<typename Derived > template<typename HandlerFn > void psr::TaintConfigBase< Derived >::forAllGeneratedValuesAt (n_t Inst, Nullable< f_t > Callee, HandlerFn && Handler) const inline
Calls Handler for all operands of Inst (maybe including Inst itself) that are generated unconditionally as tainted.
If Inst is a function-call, the Callee function should be specified explicitly.
Definition at line 83 of file TaintConfigBase.h.
forAllLeakCandidatesAt()
template<typename Derived > template<typename HandlerFn > void psr::TaintConfigBase< Derived >::forAllLeakCandidatesAt (n_t Inst, Nullable< f_t > Callee, HandlerFn && Handler) const inline
Calls Handler for all operands of Inst that may generate a leak when they are tainted.
If Inst is a function-call, the Callee function should be specified explicitly.
Definition at line 95 of file TaintConfigBase.h.
forAllSanitizedValuesAt()
template<typename Derived > template<typename HandlerFn > void psr::TaintConfigBase< Derived >::forAllSanitizedValuesAt (n_t Inst, Nullable< f_t > Callee, HandlerFn && Handler) const inline
Calls Handler for all operands of Inst that become sanitized after the instruction is completed.
If Inst is a function-call, the Callee function should be specified explicitly.
Definition at line 107 of file TaintConfigBase.h.
generatesValuesAt()
template<typename Derived > bool psr::TaintConfigBase< Derived >::generatesValuesAt (n_t Inst, Nullable< f_t > Callee) const inline
Definition at line 113 of file TaintConfigBase.h.
getCategory()
template<typename Derived > TaintCategory psr::TaintConfigBase< Derived >::getCategory (v_t Val) const inline
Definition at line 123 of file TaintConfigBase.h.
getRegisteredSanitizerCallBack()
template<typename Derived > const TaintDescriptionCallBackTy & psr::TaintConfigBase< Derived >::getRegisteredSanitizerCallBack () const inline noexcept
Definition at line 63 of file TaintConfigBase.h.
References psr::TaintConfigBase< Derived >::SanitizerCallBack.
getRegisteredSinkCallBack()
template<typename Derived > const TaintDescriptionCallBackTy & psr::TaintConfigBase< Derived >::getRegisteredSinkCallBack () const inline noexcept
Definition at line 59 of file TaintConfigBase.h.
References psr::TaintConfigBase< Derived >::SinkCallBack.
Referenced by psr::collectLeakedFacts().
getRegisteredSourceCallBack()
template<typename Derived > const TaintDescriptionCallBackTy & psr::TaintConfigBase< Derived >::getRegisteredSourceCallBack () const inline noexcept
Definition at line 55 of file TaintConfigBase.h.
References psr::TaintConfigBase< Derived >::SourceCallBack.
Referenced by psr::collectGeneratedFacts().
isSanitizer()
template<typename Derived > bool psr::TaintConfigBase< Derived >::isSanitizer (v_t Val) const inline
Definition at line 73 of file TaintConfigBase.h.
Referenced by psr::collectSanitizedFacts().
isSink()
template<typename Derived > bool psr::TaintConfigBase< Derived >::isSink (v_t Val) const inline
Definition at line 70 of file TaintConfigBase.h.
Referenced by psr::collectLeakedFacts().
isSource()
template<typename Derived > bool psr::TaintConfigBase< Derived >::isSource (v_t Val) const inline
Definition at line 67 of file TaintConfigBase.h.
Referenced by psr::collectGeneratedFacts().
makeInitialSeeds()
template<typename Derived > std::map< n_t, std::set< v_t > > psr::TaintConfigBase< Derived >::makeInitialSeeds () const inline
Definition at line 127 of file TaintConfigBase.h.
mayLeakValuesAt()
template<typename Derived > bool psr::TaintConfigBase< Derived >::mayLeakValuesAt (n_t Inst, Nullable< f_t > Callee) const inline
Definition at line 116 of file TaintConfigBase.h.
print()
template<typename Derived > void psr::TaintConfigBase< Derived >::print (llvm::raw_ostream & OS = llvm::outs()) const inline
Definition at line 131 of file TaintConfigBase.h.
Referenced by psr::TaintConfigBase< Derived >::dump().
registerSanitizerCallBack()
template<typename Derived > void psr::TaintConfigBase< Derived >::registerSanitizerCallBack (TaintDescriptionCallBackTy CB) inline noexcept
Definition at line 50 of file TaintConfigBase.h.
References psr::TaintConfigBase< Derived >::SanitizerCallBack.
registerSinkCallBack()
template<typename Derived > void psr::TaintConfigBase< Derived >::registerSinkCallBack (TaintDescriptionCallBackTy CB) inline noexcept
Definition at line 47 of file TaintConfigBase.h.
References psr::TaintConfigBase< Derived >::SinkCallBack.
registerSourceCallBack()
template<typename Derived > void psr::TaintConfigBase< Derived >::registerSourceCallBack (TaintDescriptionCallBackTy CB) inline noexcept
Definition at line 44 of file TaintConfigBase.h.
References psr::TaintConfigBase< Derived >::SourceCallBack.
sanitizesValuesAt()
template<typename Derived > bool psr::TaintConfigBase< Derived >::sanitizesValuesAt (n_t Inst, Nullable< f_t > Callee) const inline
Definition at line 119 of file TaintConfigBase.h.
Friends And Related Symbol Documentation
operator<<
template<typename Derived > llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const TaintConfigBase< Derived > & TC) friend
Definition at line 137 of file TaintConfigBase.h.
Member Data Documentation
SanitizerCallBack
template<typename Derived > TaintDescriptionCallBackTy psr::TaintConfigBase< Derived >::SanitizerCallBack {} protected
Definition at line 155 of file TaintConfigBase.h.
Referenced by psr::TaintConfigBase< Derived >::getRegisteredSanitizerCallBack(), and psr::TaintConfigBase< Derived >::registerSanitizerCallBack().
SinkCallBack
template<typename Derived > TaintDescriptionCallBackTy psr::TaintConfigBase< Derived >::SinkCallBack {} protected
Definition at line 154 of file TaintConfigBase.h.
Referenced by psr::TaintConfigBase< Derived >::getRegisteredSinkCallBack(), and psr::TaintConfigBase< Derived >::registerSinkCallBack().
SourceCallBack
template<typename Derived > TaintDescriptionCallBackTy psr::TaintConfigBase< Derived >::SourceCallBack {} protected
Definition at line 153 of file TaintConfigBase.h.
Referenced by psr::TaintConfigBase< Derived >::getRegisteredSourceCallBack(), and psr::TaintConfigBase< Derived >::registerSourceCallBack().
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/TaintConfig/TaintConfigBase.h