PhASAR: psr::IDETypeStateAnalysis< TypeStateDescriptionTy > Class Template Reference
psr::IDETypeStateAnalysis< TypeStateDescriptionTy > Class Template Reference
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETypeStateAnalysis.h"
Public Types
using IDETabProblemType = IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >
using ConfigurationTy = TypeStateDescriptionTy
Public Types inherited from psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >
using ProblemAnalysisDomain = IDETypeStateAnalysisDomain< TypeStateDescriptionTy >
using d_t = typename AnalysisDomainTy::d_t
using n_t = typename AnalysisDomainTy::n_t
using f_t = typename AnalysisDomainTy::f_t
using t_t = typename AnalysisDomainTy::t_t
using v_t = typename AnalysisDomainTy::v_t
using l_t = typename AnalysisDomainTy::l_t
using i_t = typename AnalysisDomainTy::i_t
using db_t = typename AnalysisDomainTy::db_t
using ConfigurationTy = HasNoConfigurationType
Public Types inherited from psr::FlowFunctions< AnalysisDomainTy, Container >
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using n_t = typename AnalysisDomainTy::n_t
using FlowFunctionType = FlowFunction< d_t, Container >
using FlowFunctionPtrType = typename FlowFunctionType::FlowFunctionPtrType
using container_type = typename FlowFunctionType::container_type
Public Types inherited from psr::EdgeFunctions< AnalysisDomainTy >
using n_t = typename AnalysisDomainTy::n_t
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using l_t = typename AnalysisDomainTy::l_t
Public Types inherited from psr::JoinLattice< AnalysisDomainTy, typename >
using l_t = typename AnalysisDomainTy::l_t
Public Types inherited from psr::SemiRing< AnalysisDomainTy >
using l_t = typename AnalysisDomainTy::l_t
Public Member Functions
IDETypeStateAnalysis (const LLVMProjectIRDB *IRDB, LLVMAliasInfoRef PT, const TypeStateDescriptionTy *TSD, std::vector< std::string > EntryPoints={"main"})
FlowFunctionPtrType getNormalFlowFunction (n_t Curr, n_t Succ) override
FlowFunctionPtrType getCallFlowFunction (n_t CallSite, f_t DestFun) override
FlowFunctionPtrType getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitStmt, n_t RetSite) override
FlowFunctionPtrType getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees) override
FlowFunctionPtrType getSummaryFlowFunction (n_t CallSite, f_t DestFun) override
InitialSeeds< n_t, d_t, l_t > initialSeeds () override
d_t createZeroValue () const
bool isZeroValue (d_t Fact) const noexcept override
EdgeFunction< l_t > getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t, d_t SuccNode) override
EdgeFunction< l_t > getCallEdgeFunction (n_t, d_t, f_t, d_t) override
EdgeFunction< l_t > getReturnEdgeFunction (n_t, f_t, n_t, d_t, n_t, d_t) override
EdgeFunction< l_t > getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t, d_t RetSiteNode, llvm::ArrayRef< f_t > Callees) override
EdgeFunction< l_t > getSummaryEdgeFunction (n_t, d_t, n_t, d_t) override
l_t topElement () override
l_t bottomElement () override
l_t join (l_t Lhs, l_t Rhs) override
EdgeFunction< l_t > allTopFunction () override
Returns an edge function that represents the top element of the analysis.
bool isAPIFunction (llvm::StringRef Name) const noexcept override
bool isFactoryFunction (llvm::StringRef Name) const noexcept override
bool isTypeNameOfInterest (llvm::StringRef Name) const noexcept override
void emitTextReport (GenericSolverResults< n_t, d_t, l_t > SR, llvm::raw_ostream &OS=llvm::outs()) override
bool isInteresting (const llvm::Instruction *Inst) const noexcept
Public Member Functions inherited from psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >
IDETabulationProblem (const ProjectIRDBBase< db_t > *IRDB, std::vector< std::string > EntryPoints, std::optional< d_t > ZeroValue) noexcept(std::is_nothrow_move_constructible_v< d_t >)
IDETabulationProblem (IDETabulationProblem &&) noexcept=default
IDETabulationProblem (const IDETabulationProblem &)=delete
IDETabulationProblem & operator= (IDETabulationProblem &&) noexcept=default
IDETabulationProblem & operator= (const IDETabulationProblem &)=delete
~IDETabulationProblem () override=default
void setAnalysisPrinter (MaybeUniquePtr< AnalysisPrinterBase< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > > > P)
ByConstRef< d_t > getZeroValue () const
Returns the special tautological lambda (or zero) fact.
void initializeZeroValue (d_t Zero) noexcept(std::is_nothrow_assignable_v< std::optional< d_t > &, d_t && >)
void setIFDSIDESolverConfig (IFDSIDESolverConfig Config) noexcept
Sets the configuration to be used by the IFDS/IDE solver.
IFDSIDESolverConfig & getIFDSIDESolverConfig () noexcept
Returns the configuration of the IFDS/IDE solver.
virtual void emitGraphicalReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream &OS=llvm::outs())
virtual bool setSoundness (Soundness)
const ProjectIRDBBase< db_t > * getProjectIRDB () const noexcept
Public Member Functions inherited from psr::FlowFunctions< AnalysisDomainTy, Container >
virtual ~FlowFunctions ()=default
virtual void applyUnbalancedRetFlowFunctionSideEffects (f_t CalleeFun, n_t ExitInst, d_t Source)
Public Member Functions inherited from psr::EdgeFunctions< AnalysisDomainTy >
virtual ~EdgeFunctions ()=default
Public Member Functions inherited from psr::JoinLattice< AnalysisDomainTy, typename >
virtual ~JoinLattice ()=default
Public Member Functions inherited from psr::SemiRing< AnalysisDomainTy >
virtual ~SemiRing ()=default
virtual EdgeFunction< l_t > extend (const EdgeFunction< l_t > &L, const EdgeFunction< l_t > &R)
virtual EdgeFunction< l_t > combine (const EdgeFunction< l_t > &L, const EdgeFunction< l_t > &R)
Public Member Functions inherited from psr::AllTopFnProvider< AnalysisDomainTy, typename >
virtual ~AllTopFnProvider ()=default
Additional Inherited Members
Protected Types inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
using d_t = AnalysisDomainTy::d_t
using container_type = Container
Protected Member Functions inherited from psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >
FlowFunctions< IDETypeStateAnalysisDomain< TypeStateDescriptionTy >, std::set< typename AnalysisDomainTy::d_t > >::FlowFunctionPtrType generateFromZero (d_t FactToGenerate)
void onResult (n_t Instr, D &&DfFact, L &&LatticeElement, DataFlowAnalysisType AnalysisType)
std::enable_if_t< std::is_same_v< L, psr::BinaryDomain > > onResult (n_t Instr, D &&DfFact, DataFlowAnalysisType AnalysisType)
InitialSeeds< n_t, d_t, l_t > createDefaultSeeds ()
Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
auto unionFlows (FlowFunctionPtrTypeOf< F1 > OneFF, FlowFunctionPtrTypeOf< F2 > OtherFF)
Static Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
static auto identityFlow ()
static auto lambdaFlow (Fn &&F)
static auto generateFlow (d_t FactToGenerate, d_t From)
static auto generateFlowIf (d_t FactToGenerate, Fn Predicate)
static auto generateManyFlows (Range &&FactsToGenerate, d_t From)
static auto killFlow (d_t FactToKill)
static auto killFlowIf (Fn Predicate)
static auto killManyFlows (Range &&FactsToKill)
static auto killAllFlows ()
static auto generateFlowAndKillAllOthers (d_t FactToGenerate, d_t From)
static auto generateManyFlowsAndKillAllOthers (Range &&FactsToGenerate, d_t From)
static auto transferFlow (d_t FactToGenerate, d_t From)
Protected Attributes inherited from psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >
const ProjectIRDBBase< db_t > * IRDB
std::vector< std::string > EntryPoints
std::optional< d_t > ZeroValue
IFDSIDESolverConfig SolverConfig
Soundness SF
MaybeUniquePtr< AnalysisPrinterBase< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > > > Printer
Detailed Description
template<typename TypeStateDescriptionTy>
class psr::IDETypeStateAnalysis< TypeStateDescriptionTy >
Definition at line 148 of file IDETypeStateAnalysis.h.
Member Typedef Documentation
ConfigurationTy
template<typename TypeStateDescriptionTy > using psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::ConfigurationTy = TypeStateDescriptionTy
Definition at line 165 of file IDETypeStateAnalysis.h.
IDETabProblemType
template<typename TypeStateDescriptionTy > using psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::IDETabProblemType = IDETabulationProblem<IDETypeStateAnalysisDomain<TypeStateDescriptionTy> >
Definition at line 153 of file IDETypeStateAnalysis.h.
Constructor & Destructor Documentation
IDETypeStateAnalysis()
template<typename TypeStateDescriptionTy > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::IDETypeStateAnalysis (const LLVMProjectIRDB * IRDB, LLVMAliasInfoRef PT, const TypeStateDescriptionTy * TSD, std::vector< std::string > EntryPoints = {"main"}) inline
Definition at line 343 of file IDETypeStateAnalysis.h.
Member Function Documentation
allTopFunction()
template<typename TypeStateDescriptionTy > EdgeFunction< l_t > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::allTopFunction () inline override virtual
Returns an edge function that represents the top element of the analysis.
Implements psr::AllTopFnProvider< AnalysisDomainTy, typename >.
Definition at line 490 of file IDETypeStateAnalysis.h.
References psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::topElement().
bottomElement()
template<typename TypeStateDescriptionTy > l_t psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::bottomElement () inline override virtual
Implements psr::JoinLattice< AnalysisDomainTy, typename >.
Definition at line 467 of file IDETypeStateAnalysis.h.
createZeroValue()
template<typename TypeStateDescriptionTy > d_t psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::createZeroValue () const inline
Definition at line 387 of file IDETypeStateAnalysis.h.
References psr::LLVMZeroValue::getInstance().
emitTextReport()
template<typename TypeStateDescriptionTy > void psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::emitTextReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream & OS = llvm::outs()) inline override virtual
Generates a text report of the results that is written to the specified output stream.
Reimplemented from psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >.
Definition at line 513 of file IDETypeStateAnalysis.h.
References psr::ProjectIRDBBase< Derived >::getAllFunctions(), psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >::IRDB, psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >::onResult(), and psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >::Printer.
getCallEdgeFunction()
template<typename TypeStateDescriptionTy > EdgeFunction< l_t > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getCallEdgeFunction (n_t CallInst, d_t SrcNode, f_t CalleeFun, d_t DestNode) inline override virtual
Also refer to FlowFunctions::getCallFlowFunction()
Describes a value computation problem along a call flow. A call edge function is queried for each edge that has been generated by applying the flow function that has been returned by FlowFunctions::getCallFlowFunction. The supergraph edge whose computation is requested is defined by the supergraph nodes SrcNode and DestNode.
The concrete implementation of an edge function e is depending on the analysis problem. In the following, we present a brief, contrived example:
Consider the following flow function implementation (cf. FlowFunctions::getCallFlowFunction()):
f(0) -> {0}       // pass as identity into the callee target
f(o) -> {q}       // map actual o into formal q
f(p) -> {r}       // map actual p into formal r
f(.) -> {}        // kill all other facts that are not visible to the
                  // callee target
The above implementation corresponds to the following edges in the exploded supergraph.
                                       0  o  p   ...
                                        \  \  \  ...
CallInst := x = CalleeFun(o, p, ...)     \  \  +----------------+
                                          \  +----------------  |
                                            +-------------+  +  |
                                                 ...      |  |  |
                                                 ...      |  |  |
                                       0  o  p   ...      |  |  |
                                                          |  |  |
                                                          |  |  |
                                                          |  |  |
                                Ty CalleeFun(q, r, ...)   |  |  |
                                                          v  v  v
                                                          0  q  r   ...
                                            start point
For each edge generated by the respective flow function a call edge function is queried that describes a value computation. This results in the following queries:
getCallEdgeFunction(CallInst, 0, CalleeFun, 0);
getCallEdgeFunction(CallInst, o, CalleeFun, q);
getCallEdgeFunction(CallInst, p, CalleeFun, r);
Implements psr::EdgeFunctions< AnalysisDomainTy >.
Definition at line 410 of file IDETypeStateAnalysis.h.
getCallFlowFunction()
template<typename TypeStateDescriptionTy > FlowFunctionPtrType psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getCallFlowFunction (n_t CallInst, f_t CalleeFun) inline override virtual
Handles call flows: describes the effects of a function call at callInst to the callee target destFun. If a call instruction has multiple callee targets, for instance, because it is an indirect function call that cannot be analyzed precisely in a static manner, the call flow function will be queried for each callee target.
This flow function usually handles parameter passing and maps actual to formal parameters. If an analysis writer does not wish to analyze a given callee target they can return a flow function implementation that kills all data-flow facts (e.g. KillAll) such that call is not followed. A commonly used trick to model the effects of functions that are not present (e.g. library functions such as malloc(), free(), etc.) is to kill all facts at the call to the respective target and plugin the semantics in the call-to-return flow function. In the call-to-return flow function, an analysis writer can check if the function of interest is one of the possible targets and then, return a flow function implementation that describes the special semantics of that function call.
Let start_point be the starting point of the callee target CalleeFun.
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds right before the CallInst. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each target fact that is generated will hold before start_point.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before CallInst. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass as identity into the callee target
f(o) -> {q}       // map actual o into formal q
f(p) -> {r}       // map actual p into formal r
f(.) -> {}        // kill all other facts that are not visible to the
                  // callee target
The above implementation corresponds to the following edges in the exploded supergraph.
                           0  o  p   ...
                            \  \  \  ...
x = CalleeFun(o, p, ...)     \  \  +----------------+
                              \  +----------------  |
                                +-------------+  +  |
                                     ...      |  |  |
                                     ...      |  |  |
                           0  o  p   ...      |  |  |
                                              |  |  |
                                              |  |  |
                                              |  |  |
                    Ty CalleeFun(q, r, ...)   |  |  |
                                              v  v  v
                                              0  q  r   ...
                                start point
Implements psr::FlowFunctions< AnalysisDomainTy, Container >.
Definition at line 358 of file IDETypeStateAnalysis.h.
getCallToRetEdgeFunction()
template<typename TypeStateDescriptionTy > EdgeFunction< l_t > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t RetSite, d_t RetSiteNode, llvm::ArrayRef< f_t > Callees) inline override virtual
Also refer to FlowFunctions::getCallToRetFlowFunction()
Describes a value computation problem along data-flows alongsite a CallSite. A return edge function implementation is queried for each edge that has been generated by applying the flow function that has been returned by FlowFunctions::getCallToRetFlowFunction(). The supergraph edge whose computation is requested is defined by the supergraph nodes CallNode and RetSiteNode.
The concrete implementation of an edge function e is depending on the analysis problem. In the following, we present a brief, contrived example:
Consider the following flow function implementation (cf. FlowFunctions::getCallToRetFlowFunction()):
f(0) -> {0}       // pass lambda as identity alongsite the CallSite
f(o) -> {o}       // assuming that o is passed by value, it is passed
                  // alongsite the CallSite
f(p) -> {}        // assuming that p is a pointer-typed value, we need
                  // to kill p, as it will be handled by the call- and
                  // return-flow functions
f(.) -> {.}       // pass everything that is not involved in the call
                  // as identity
The above implementation corresponds to the following edges in the exploded supergraph.
                                                 0  o   ...
                                                 |  |
                                                 |  +-------+
                                                 +--------+ |
                                                          | |
CallSite = RetSite := x = CalleeFun(o, p, ...)            | |
                                                          | |
                                                 +--------+ |
                                                 |  +-------+
                                                 v  v
                                                 0  o  x   ...
For each edge generated by the respective flow function a call-to-return edge function is queried that describes a value computation. This results in the following queries:
getCallToRetEdgeFunction(CallSite, 0, RetSite, 0, {CalleeFun}); getCallToRetEdgeFunction(CallSite, o, RetSite, o, {CalleeFun});
Implements psr::EdgeFunctions< AnalysisDomainTy >.
Definition at line 425 of file IDETypeStateAnalysis.h.
References psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::isZeroValue(), and PHASAR_LOG_LEVEL.
getCallToRetFlowFunction()
template<typename TypeStateDescriptionTy > FlowFunctionPtrType psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees) inline override virtual
Describes the data-flows alongsite a CallSite.
This flow function usually passes all data-flow facts that are not involved in the function call alongsite the CallSite. Data-flow facts that are not actual parameters or passed by value, modifications to those within a callee are not visible in the caller context, are mostly passed as identity. The call-to-return flow function may also be used to describe special semantics (cf. getCallFlowFunction()).
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds right before the CallSite. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each target fact that is generated will hold after CallSite.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before CallSite. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass lambda as identity alongsite the CallSite
f(o) -> {o}       // assuming that o is passed by value, it is passed
                  // alongsite the CallSite
f(p) -> {}        // assuming that p is a pointer-typed value, we need
                  // to kill p, as it will be handled by the call- and
                  // return-flow functions
f(.) -> {.}       // pass everything that is not involved in the call
                  // as identity
The above implementation corresponds to the following edges in the exploded supergraph.
                           0  o   ...
                           |  |
                           |  +-------+
                           +--------+ |
                                    | |
x = CalleeFun(o, p, ...)            | |
                                    | |
                           +--------+ |
                           |  +-------+
                           v  v
                           0  o  x   ...
Implements psr::FlowFunctions< AnalysisDomainTy, Container >.
Definition at line 371 of file IDETypeStateAnalysis.h.
getNormalEdgeFunction()
template<typename TypeStateDescriptionTy > EdgeFunction< l_t > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t Succ, d_t SuccNode) inline override virtual
Also refer to FlowFunctions::getNormalFlowFunction()
Describes a value computation problem along a normal (non-call, non-return) intra-procedural exploded supergraph edge. A normal edge function implementation is queried for each edge that has been generated by appling the flow function returned by FlowFunctions::getNormalFlowFunction(). The supergraph edge whose computation is requested is defined by the supergraph nodes CurrNode and SuccNode.
Let instruction_1 := Curr, instruction_2 := Succ, and 0 the tautological lambda fact.
The concrete implementation of an edge function e is depending on the analysis problem. In the following, we present a brief, contrived example:
Consider the following flow function implementation (cf. FlowFunctions::getNormalFlowfunction()):
f(0) -> {0}       // pass the lambda (or zero fact) as identity
f(o) -> {o, x}    // generate a new fact x from o
f(.) -> {.}       // pass all other facts that hold before
                  // instruction_1 as identity
The above flow-function implementation corresponds to the following edges in the exploded supergraph.
                                0  o      ...
                                |  |\     ...
Curr := x = instruction_1 o p   |  | \    ...
                                |  |  |   ...
                                v  v  v   ...
                                0  o  x   ...
Succ := y = instruction_2 q r
For each edge generated by the respective flow function a normal edge function is queried that describes a value computation. This results in the following queries:
getNormalEdgeFunction(0, Curr, 0 Succ);
getNormalEdgeFunction(o, Curr, o Succ);
getNormalEdgeFunction(o, Curr, x Succ);
Implements psr::EdgeFunctions< AnalysisDomainTy >.
Definition at line 397 of file IDETypeStateAnalysis.h.
References psr::LLVMZeroValue::isLLVMZeroValue.
getNormalFlowFunction()
template<typename TypeStateDescriptionTy > FlowFunctionPtrType psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getNormalFlowFunction (n_t Curr, n_t Succ) inline override virtual
Describes the effects of the current instruction, i.e. data-flows, along normal (non-call, non-return) instructions. Analysis writers are free to inspect the successor instructions, too, as a lookahead.
Let instruction_1 := Curr, instruction_2 := Succ, and 0 the tautological lambda fact.
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds before the current statement under analysis. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each combination of input fact d_i (given as an input to f) and respective output facts (f(d_i)) represents an edge that must be "drawn" to construct the exploded supergraph for the analysis problem to be solved.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before instruction_1. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass the lambda (or zero fact) as identity
f(o) -> {o, x}    // generate a new fact x from o
f(.) -> {.}       // pass all other facts that hold before
                  // instruction_1 as identity
The above implementation corresponds to the following edges in the exploded supergraph.
                        0  o      ...
                        |  |\     ...
x = instruction_1 o p   |  | \    ...
                        |  |  |   ...
                        v  v  v   ...
                        0  o  x   ...
y = instruction_2 q r
Implements psr::FlowFunctions< AnalysisDomainTy, Container >.
Definition at line 354 of file IDETypeStateAnalysis.h.
getRetFlowFunction()
template<typename TypeStateDescriptionTy > FlowFunctionPtrType psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, n_t RetSite) inline override virtual
Handles return flows: describes the data-flows from an ExitInst to the corresponding RetSite.
This flow function usually handles the returned value of the callee target as well as the parameter mapping back to the caller of CalleeFun for pointer parameters as modifications made by CalleeFun are visible to the caller. Data-flow facts that are not returned or escape via function pointer parameters (or global variables) are usually killed.
The returned flow function implementation f (FlowFunction::computeTargets()) is applied to each data-flow fact d_i that holds right before the ExitInst. f's return type is a set of (target) facts that have to be generated from the source fact d_i by the data-flow solver. Each target fact that is generated will hold after CallSite.
The concrete implementation of f is depending on the analysis problem. In the following, we present a brief, contrived example:
f is applied to each data-flow fact d_i that holds before ExitInst. We assume that f is implemented to produce the following outputs.
f(0) -> {0}       // pass as identity into the callee target
f(r) -> {x}       // map return value to lhs variable at CallSite
f(q) -> {o}       // map pointer-typed formal q to actual o
f(.) -> {}        // kill all other facts that are not visible to the
                  // caller
The above implementation corresponds to the following edges in the exploded supergraph.
                        0  o   ...
x = CalleeFun(o, ...)
                              +------------------+
                           +--|---------------+  |
                        +--|--|------------+  |  |
                        v  v  v   ...      |  |  |
                        0  o  x   ...      |  |  |
                                           |  |  |
                                           |  |  |
                                           |  |  |
                    Ty CalleeFun(q, ...)   |  |  |
                                           |  |  |
                                           0  q  r   ...
                                return r
Implements psr::FlowFunctions< AnalysisDomainTy, Container >.
Definition at line 363 of file IDETypeStateAnalysis.h.
getReturnEdgeFunction()
template<typename TypeStateDescriptionTy > EdgeFunction< l_t > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getReturnEdgeFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, d_t ExitNode, n_t RetSite, d_t RetNode) inline override virtual
Also refer to FlowFunction::getRetFlowFunction()
Describes a value computation problem along a return flow. A return edge function implementation is queried for each edge that has been generated by applying the flow function that has been returned by FlowFunctions::getRetFlowFunction(). The supergraph edge whose computation is requested is defined by the supergraph nodes ExitNode and RetNode.
The concrete implementation of an edge function e is depending on the analysis problem. In the following, we present a brief, contrived example:
Consider the following flow function implementation (cf. FlowFunctions::getRetFlowFunction()):
f(0) -> {0}       // pass as identity into the callee target
f(r) -> {x}       // map return value to lhs variable at CallSite
f(q) -> {o}       // map pointer-typed formal q to actual o
f(.) -> {}        // kill all other facts that are not visible to the
                  // caller
The above implementation corresponds to the following edges in the exploded supergraph.
                                              0  o   ...
CallSite = RetSite := x = CalleeFun(o, ...)
                                                    +------------------+
                                                 +--|---------------+  |
                                              +--|--|------------+  |  |
                                              v  v  v   ...      |  |  |
                                              0  o  x   ...      |  |  |
                                                                 |  |  |
                                                                 |  |  |
                                                                 |  |  |
                                          Ty CalleeFun(q, ...)   |  |  |
                                                                 |  |  |
                                                                 0  q  r
                                          ExitInst := return r
For each edge generated by the respective flow function a return edge function is queried that describes a value computation. This results in the following queries:
getReturnEdgeFunction(CallSite, CalleeFun, ExitInst, 0, RetSite, 0);
getReturnEdgeFunction(CallSite, CalleeFun, ExitInst, q, RetSite, o);
getReturnEdgeFunction(CallSite, CalleeFun, ExitInst, r, RetSite, x);
Implements psr::EdgeFunctions< AnalysisDomainTy >.
Definition at line 416 of file IDETypeStateAnalysis.h.
getSummaryEdgeFunction()
template<typename TypeStateDescriptionTy > EdgeFunction< l_t > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getSummaryEdgeFunction (n_t , d_t , n_t , d_t) inline override virtual
Also refer to FlowFunction::getSummaryFlowFunction()
Describes a value computation problem along a summary data flow. A summary edge function implementation is queried for each edge that has been generated by FlowFunctions::getSummaryFlowFunction(). The supergraph edge whose computation is requested is defined by the supergraph nodes CurrNode and SuccNode.
The default implementation returns a nullptr to indicate that the mechanism should not be used.
Reimplemented from psr::EdgeFunctions< AnalysisDomainTy >.
Definition at line 459 of file IDETypeStateAnalysis.h.
getSummaryFlowFunction()
template<typename TypeStateDescriptionTy > FlowFunctionPtrType psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getSummaryFlowFunction (n_t , f_t) inline override virtual
May be used to encode special sementics of a given callee target (whose call should not be directly followed by the data-flow solver) similar to the getCallFlowFunction() --> getCallToRetFlowFunction() trick (cf. getCallFlowFunction()).
The default implementation returns a nullptr to indicate that the mechanism should not be used.
Reimplemented from psr::FlowFunctions< AnalysisDomainTy, Container >.
Definition at line 377 of file IDETypeStateAnalysis.h.
initialSeeds()
template<typename TypeStateDescriptionTy > InitialSeeds< n_t, d_t, l_t > psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::initialSeeds () inline override virtual
Returns initial seeds to be used for the analysis. This is a mapping of statements to initial analysis facts.
Implements psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >.
Definition at line 383 of file IDETypeStateAnalysis.h.
References psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >::createDefaultSeeds().
isAPIFunction()
template<typename TypeStateDescriptionTy > bool psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::isAPIFunction (llvm::StringRef Name) const inline override noexcept
Definition at line 499 of file IDETypeStateAnalysis.h.
isFactoryFunction()
template<typename TypeStateDescriptionTy > bool psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::isFactoryFunction (llvm::StringRef Name) const inline override noexcept
Definition at line 504 of file IDETypeStateAnalysis.h.
isInteresting()
template<typename TypeStateDescriptionTy > bool psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::isInteresting (const llvm::Instruction * Inst) const inline noexcept
Definition at line 539 of file IDETypeStateAnalysis.h.
References psr::Call.
isTypeNameOfInterest()
template<typename TypeStateDescriptionTy > bool psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::isTypeNameOfInterest (llvm::StringRef Name) const inline override noexcept
Definition at line 509 of file IDETypeStateAnalysis.h.
isZeroValue()
template<typename TypeStateDescriptionTy > bool psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::isZeroValue (d_t FlowFact) const inline override virtual noexcept
Checks if the given data-flow fact is the special tautological lambda (or zero) fact.
Reimplemented from psr::IDETabulationProblem< IDETypeStateAnalysisDomain< TypeStateDescriptionTy > >.
Definition at line 391 of file IDETypeStateAnalysis.h.
References psr::LLVMZeroValue::isLLVMZeroValue.
Referenced by psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::getCallToRetEdgeFunction().
join()
template<typename TypeStateDescriptionTy > l_t psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::join (l_t Lhs, l_t Rhs) inline override virtual
We have a lattice with BOTTOM representing all information and TOP representing no information. The other lattice elements are defined by the type state description, i.e. represented by the states of the finite state machine.
Note
Only one-level lattice's are handled currently
Implements psr::JoinLattice< AnalysisDomainTy, typename >.
Definition at line 477 of file IDETypeStateAnalysis.h.
topElement()
template<typename TypeStateDescriptionTy > l_t psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::topElement () inline override virtual
Implements psr::JoinLattice< AnalysisDomainTy, typename >.
Definition at line 465 of file IDETypeStateAnalysis.h.
Referenced by psr::IDETypeStateAnalysis< TypeStateDescriptionTy >::allTopFunction().
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETypeStateAnalysis.h