PhASAR: psr::InterMonoSolver< AnalysisDomainTy, K > Class Template Reference
psr::InterMonoSolver< AnalysisDomainTy, K > Class Template Reference
A solver class for interprocedual monotone problems (derived from InterMonoProblem). To solve the problem, call solve().
#include "phasar/DataFlow/Mono/Solver/InterMonoSolver.h"
Public Types
using ProblemTy = InterMonoProblem< AnalysisDomainTy >
using n_t = typename AnalysisDomainTy::n_t
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using t_t = typename AnalysisDomainTy::t_t
using v_t = typename AnalysisDomainTy::v_t
using i_t = typename AnalysisDomainTy::i_t
using mono_container_t = typename AnalysisDomainTy::mono_container_t
Public Member Functions
InterMonoSolver (InterMonoProblem< AnalysisDomainTy > &IMP)
InterMonoSolver (const InterMonoSolver &)=delete
InterMonoSolver & operator= (const InterMonoSolver &)=delete
InterMonoSolver (InterMonoSolver &&)=delete
InterMonoSolver & operator= (InterMonoSolver &&)=delete
virtual ~InterMonoSolver ()=default
std::unordered_map< n_t, std::unordered_map< CallStringCTX< n_t, K >, mono_container_t > > getAnalysis ()
void processNormal (std::pair< n_t, n_t > Edge)
void processCall (std::pair< n_t, n_t > Edge)
void processExit (std::pair< n_t, n_t > Edge)
mono_container_t summarize ()
bool isSensibleToSummarize ()
virtual void solve ()
mono_container_t getResultsAt (n_t Stmt)
virtual void dumpResults (llvm::raw_ostream &OS=llvm::outs())
virtual void emitTextReport (llvm::raw_ostream &OS=llvm::outs())
virtual void emitGraphicalReport (llvm::raw_ostream &OS=llvm::outs())
Protected Member Functions
void initialize ()
bool isIntraEdge (std::pair< n_t, n_t > Edge)
bool isCallEdge (std::pair< n_t, n_t > Edge)
bool isReturnEdge (std::pair< n_t, n_t > Edge)
void printWorkList ()
void addCalleesToWorklist (std::pair< n_t, n_t > Edge)
void addToWorklist (std::pair< n_t, n_t > Edge)
Protected Attributes
ProblemTy & IMProblem
std::deque< std::pair< n_t, n_t > > Worklist
std::unordered_map< n_t, std::unordered_map< CallStringCTX< n_t, K >, mono_container_t > > Analysis
std::unordered_set< f_t > AddedFunctions
const i_t * ICF
Detailed Description
template<typename AnalysisDomainTy, unsigned K>
class psr::InterMonoSolver< AnalysisDomainTy, K >
A solver class for interprocedual monotone problems (derived from InterMonoProblem). To solve the problem, call solve().
Template Parameters
AnalysisDomainTy type of the analysis domain.
K An unsigned integer used as the maximum length for call-string contexts.
Definition at line 36 of file InterMonoSolver.h.
Member Typedef Documentation
d_t
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::d_t = typename AnalysisDomainTy::d_t
Definition at line 40 of file InterMonoSolver.h.
f_t
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::f_t = typename AnalysisDomainTy::f_t
Definition at line 41 of file InterMonoSolver.h.
i_t
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::i_t = typename AnalysisDomainTy::i_t
Definition at line 44 of file InterMonoSolver.h.
mono_container_t
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::mono_container_t = typename AnalysisDomainTy::mono_container_t
Definition at line 45 of file InterMonoSolver.h.
n_t
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::n_t = typename AnalysisDomainTy::n_t
Definition at line 39 of file InterMonoSolver.h.
ProblemTy
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::ProblemTy = InterMonoProblem<AnalysisDomainTy>
Definition at line 38 of file InterMonoSolver.h.
t_t
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::t_t = typename AnalysisDomainTy::t_t
Definition at line 42 of file InterMonoSolver.h.
v_t
template<typename AnalysisDomainTy , unsigned K> using psr::InterMonoSolver< AnalysisDomainTy, K >::v_t = typename AnalysisDomainTy::v_t
Definition at line 43 of file InterMonoSolver.h.
Constructor & Destructor Documentation
InterMonoSolver() [1/3]
template<typename AnalysisDomainTy , unsigned K> psr::InterMonoSolver< AnalysisDomainTy, K >::InterMonoSolver (InterMonoProblem< AnalysisDomainTy > & IMP) inline
Definition at line 162 of file InterMonoSolver.h.
InterMonoSolver() [2/3]
template<typename AnalysisDomainTy , unsigned K> psr::InterMonoSolver< AnalysisDomainTy, K >::InterMonoSolver (const InterMonoSolver< AnalysisDomainTy, K > &) delete
InterMonoSolver() [3/3]
template<typename AnalysisDomainTy , unsigned K> psr::InterMonoSolver< AnalysisDomainTy, K >::InterMonoSolver (InterMonoSolver< AnalysisDomainTy, K > &&) delete
~InterMonoSolver()
template<typename AnalysisDomainTy , unsigned K> virtual psr::InterMonoSolver< AnalysisDomainTy, K >::~InterMonoSolver () virtual default
Member Function Documentation
addCalleesToWorklist()
template<typename AnalysisDomainTy , unsigned K> void psr::InterMonoSolver< AnalysisDomainTy, K >::addCalleesToWorklist (std::pair< n_t, n_t > Edge) inline protected
Definition at line 98 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::AddedFunctions, psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis, psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, psr::InterMonoSolver< AnalysisDomainTy, K >::IMProblem, psr::Ret, and psr::InterMonoSolver< AnalysisDomainTy, K >::Worklist.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::solve().
addToWorklist()
template<typename AnalysisDomainTy , unsigned K> void psr::InterMonoSolver< AnalysisDomainTy, K >::addToWorklist (std::pair< n_t, n_t > Edge) inline protected
Definition at line 135 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, and psr::InterMonoSolver< AnalysisDomainTy, K >::Worklist.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::processCall(), and psr::InterMonoSolver< AnalysisDomainTy, K >::processNormal().
dumpResults()
template<typename AnalysisDomainTy , unsigned K> virtual void psr::InterMonoSolver< AnalysisDomainTy, K >::dumpResults (llvm::raw_ostream & OS = llvm::outs()) inline virtual
Definition at line 396 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis, psr::InterMonoSolver< AnalysisDomainTy, K >::IMProblem, and psr::NToString().
emitGraphicalReport()
template<typename AnalysisDomainTy , unsigned K> virtual void psr::InterMonoSolver< AnalysisDomainTy, K >::emitGraphicalReport (llvm::raw_ostream & OS = llvm::outs()) inline virtual
Definition at line 419 of file InterMonoSolver.h.
emitTextReport()
template<typename AnalysisDomainTy , unsigned K> virtual void psr::InterMonoSolver< AnalysisDomainTy, K >::emitTextReport (llvm::raw_ostream & OS = llvm::outs()) inline virtual
Definition at line 417 of file InterMonoSolver.h.
getAnalysis()
template<typename AnalysisDomainTy , unsigned K> std::unordered_map< n_t, std::unordered_map< CallStringCTX< n_t, K >, mono_container_t > > psr::InterMonoSolver< AnalysisDomainTy, K >::getAnalysis () inline
Definition at line 177 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis.
getResultsAt()
template<typename AnalysisDomainTy , unsigned K> mono_container_t psr::InterMonoSolver< AnalysisDomainTy, K >::getResultsAt (n_t Stmt) inline
Definition at line 388 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis.
initialize()
template<typename AnalysisDomainTy , unsigned K> void psr::InterMonoSolver< AnalysisDomainTy, K >::initialize () inline protected
Definition at line 56 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis, psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, psr::InterMonoSolver< AnalysisDomainTy, K >::IMProblem, and psr::InterMonoSolver< AnalysisDomainTy, K >::Worklist.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::solve().
isCallEdge()
template<typename AnalysisDomainTy , unsigned K> bool psr::InterMonoSolver< AnalysisDomainTy, K >::isCallEdge (std::pair< n_t, n_t > Edge) inline protected
Definition at line 82 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, and psr::InterMonoSolver< AnalysisDomainTy, K >::isIntraEdge().
isIntraEdge()
template<typename AnalysisDomainTy , unsigned K> bool psr::InterMonoSolver< AnalysisDomainTy, K >::isIntraEdge (std::pair< n_t, n_t > Edge) inline protected
Definition at line 78 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::ICF.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::isCallEdge(), psr::InterMonoSolver< AnalysisDomainTy, K >::isReturnEdge(), and psr::InterMonoSolver< AnalysisDomainTy, K >::processCall().
isReturnEdge()
template<typename AnalysisDomainTy , unsigned K> bool psr::InterMonoSolver< AnalysisDomainTy, K >::isReturnEdge (std::pair< n_t, n_t > Edge) inline protected
Definition at line 86 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, and psr::InterMonoSolver< AnalysisDomainTy, K >::isIntraEdge().
isSensibleToSummarize()
template<typename AnalysisDomainTy , unsigned K> bool psr::InterMonoSolver< AnalysisDomainTy, K >::isSensibleToSummarize () inline
Definition at line 358 of file InterMonoSolver.h.
operator=() [1/2]
template<typename AnalysisDomainTy , unsigned K> InterMonoSolver & psr::InterMonoSolver< AnalysisDomainTy, K >::operator= (const InterMonoSolver< AnalysisDomainTy, K > &) delete
operator=() [2/2]
template<typename AnalysisDomainTy , unsigned K> InterMonoSolver & psr::InterMonoSolver< AnalysisDomainTy, K >::operator= (InterMonoSolver< AnalysisDomainTy, K > &&) delete
printWorkList()
template<typename AnalysisDomainTy , unsigned K> void psr::InterMonoSolver< AnalysisDomainTy, K >::printWorkList () inline protected
Definition at line 90 of file InterMonoSolver.h.
References psr::NToString(), and psr::InterMonoSolver< AnalysisDomainTy, K >::Worklist.
processCall()
template<typename AnalysisDomainTy , unsigned K> void psr::InterMonoSolver< AnalysisDomainTy, K >::processCall (std::pair< n_t, n_t > Edge) inline
Definition at line 225 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::addToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis, psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, psr::InterMonoSolver< AnalysisDomainTy, K >::IMProblem, psr::InterMonoSolver< AnalysisDomainTy, K >::isIntraEdge(), and psr::NToString().
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::solve().
processExit()
template<typename AnalysisDomainTy , unsigned K> void psr::InterMonoSolver< AnalysisDomainTy, K >::processExit (std::pair< n_t, n_t > Edge) inline
Definition at line 289 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis, psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, psr::InterMonoSolver< AnalysisDomainTy, K >::IMProblem, and psr::NToString().
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::solve().
processNormal()
template<typename AnalysisDomainTy , unsigned K> void psr::InterMonoSolver< AnalysisDomainTy, K >::processNormal (std::pair< n_t, n_t > Edge) inline
Definition at line 181 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::addToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis, psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, psr::InterMonoSolver< AnalysisDomainTy, K >::IMProblem, and psr::NToString().
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::solve().
solve()
template<typename AnalysisDomainTy , unsigned K> virtual void psr::InterMonoSolver< AnalysisDomainTy, K >::solve () inline virtual
Definition at line 364 of file InterMonoSolver.h.
References psr::InterMonoSolver< AnalysisDomainTy, K >::addCalleesToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::ICF, psr::InterMonoSolver< AnalysisDomainTy, K >::initialize(), psr::InterMonoSolver< AnalysisDomainTy, K >::processCall(), psr::InterMonoSolver< AnalysisDomainTy, K >::processExit(), psr::InterMonoSolver< AnalysisDomainTy, K >::processNormal(), and psr::InterMonoSolver< AnalysisDomainTy, K >::Worklist.
summarize()
template<typename AnalysisDomainTy , unsigned K> mono_container_t psr::InterMonoSolver< AnalysisDomainTy, K >::summarize () inline
Definition at line 354 of file InterMonoSolver.h.
Member Data Documentation
AddedFunctions
template<typename AnalysisDomainTy , unsigned K> std::unordered_set<f_t> psr::InterMonoSolver< AnalysisDomainTy, K >::AddedFunctions protected
Definition at line 53 of file InterMonoSolver.h.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::addCalleesToWorklist().
Analysis
template<typename AnalysisDomainTy , unsigned K> std::unordered_map< n_t, std::unordered_map<CallStringCTX<n_t, K>, mono_container_t> > psr::InterMonoSolver< AnalysisDomainTy, K >::Analysis protected
Definition at line 52 of file InterMonoSolver.h.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::addCalleesToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::dumpResults(), psr::InterMonoSolver< AnalysisDomainTy, K >::getAnalysis(), psr::InterMonoSolver< AnalysisDomainTy, K >::getResultsAt(), psr::InterMonoSolver< AnalysisDomainTy, K >::initialize(), psr::InterMonoSolver< AnalysisDomainTy, K >::processCall(), psr::InterMonoSolver< AnalysisDomainTy, K >::processExit(), and psr::InterMonoSolver< AnalysisDomainTy, K >::processNormal().
ICF
template<typename AnalysisDomainTy , unsigned K> const i_t* psr::InterMonoSolver< AnalysisDomainTy, K >::ICF protected
Definition at line 54 of file InterMonoSolver.h.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::addCalleesToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::addToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::initialize(), psr::InterMonoSolver< AnalysisDomainTy, K >::isCallEdge(), psr::InterMonoSolver< AnalysisDomainTy, K >::isIntraEdge(), psr::InterMonoSolver< AnalysisDomainTy, K >::isReturnEdge(), psr::InterMonoSolver< AnalysisDomainTy, K >::processCall(), psr::InterMonoSolver< AnalysisDomainTy, K >::processExit(), psr::InterMonoSolver< AnalysisDomainTy, K >::processNormal(), and psr::InterMonoSolver< AnalysisDomainTy, K >::solve().
IMProblem
template<typename AnalysisDomainTy , unsigned K> ProblemTy& psr::InterMonoSolver< AnalysisDomainTy, K >::IMProblem protected
Definition at line 48 of file InterMonoSolver.h.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::addCalleesToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::dumpResults(), psr::InterMonoSolver< AnalysisDomainTy, K >::initialize(), psr::InterMonoSolver< AnalysisDomainTy, K >::processCall(), psr::InterMonoSolver< AnalysisDomainTy, K >::processExit(), and psr::InterMonoSolver< AnalysisDomainTy, K >::processNormal().
Worklist
template<typename AnalysisDomainTy , unsigned K> std::deque<std::pair<n_t, n_t> > psr::InterMonoSolver< AnalysisDomainTy, K >::Worklist protected
Definition at line 49 of file InterMonoSolver.h.
Referenced by psr::InterMonoSolver< AnalysisDomainTy, K >::addCalleesToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::addToWorklist(), psr::InterMonoSolver< AnalysisDomainTy, K >::initialize(), psr::InterMonoSolver< AnalysisDomainTy, K >::printWorkList(), and psr::InterMonoSolver< AnalysisDomainTy, K >::solve().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/Mono/Solver/InterMonoSolver.h