PhASAR: psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints > Class Template Reference
psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints > Class Template Reference
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h"
Classes
struct IIAAAddLabelsEF
struct IIAAKillOrReplaceEF
Public Types
using AnalysisDomainTy = IDEInstInteractionAnalysisDomain< EdgeFactType >
using IDETabProblemType = IDETabulationProblem< AnalysisDomainTy >
using d_t = typename AnalysisDomainTy::d_t
using n_t = typename AnalysisDomainTy::n_t
using f_t = typename AnalysisDomainTy::f_t
using t_t = typename AnalysisDomainTy::t_t
using v_t = typename AnalysisDomainTy::v_t
using e_t = typename AnalysisDomainTy::e_t
using l_t = typename AnalysisDomainTy::l_t
using i_t = typename AnalysisDomainTy::i_t
using EdgeFunctionType = EdgeFunction< l_t >
using EdgeFactGeneratorTy = std::set< e_t >(std::variant< n_t, const llvm::GlobalVariable * > InstOrGlobal)
Public Types inherited from psr::IDETabulationProblem< AnalysisDomainTy, Container >
using ProblemAnalysisDomain = AnalysisDomainTy
using d_t = typename AnalysisDomainTy::d_t
using n_t = typename AnalysisDomainTy::n_t
using f_t = typename AnalysisDomainTy::f_t
using t_t = typename AnalysisDomainTy::t_t
using v_t = typename AnalysisDomainTy::v_t
using l_t = typename AnalysisDomainTy::l_t
using i_t = typename AnalysisDomainTy::i_t
using db_t = typename AnalysisDomainTy::db_t
using ConfigurationTy = HasNoConfigurationType
Public Types inherited from psr::FlowFunctions< AnalysisDomainTy, Container >
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using n_t = typename AnalysisDomainTy::n_t
using FlowFunctionType = FlowFunction< d_t, Container >
using FlowFunctionPtrType = typename FlowFunctionType::FlowFunctionPtrType
using container_type = typename FlowFunctionType::container_type
Public Types inherited from psr::EdgeFunctions< AnalysisDomainTy >
using n_t = typename AnalysisDomainTy::n_t
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using l_t = typename AnalysisDomainTy::l_t
Public Types inherited from psr::JoinLattice< AnalysisDomainTy >
using l_t = typename AnalysisDomainTy::l_t
Public Types inherited from psr::SemiRing< AnalysisDomainTy >
using l_t = typename AnalysisDomainTy::l_t
Public Member Functions
IDEInstInteractionAnalysisT (const LLVMProjectIRDB *IRDB, const LLVMBasedICFG *ICF, LLVMAliasInfoRef PT, std::vector< std::string > EntryPoints={"main"}, std::function< EdgeFactGeneratorTy > EdgeFactGenerator=nullptr)
~IDEInstInteractionAnalysisT () override=default
void registerEdgeFactGenerator (std::function< EdgeFactGeneratorTy > EdgeFactGenerator)
FlowFunctionPtrType getNormalFlowFunction (n_t Curr, n_t) override
FlowFunctionPtrType getCallFlowFunction (n_t CallSite, f_t DestFun) override
FlowFunctionPtrType getRetFlowFunction (n_t CallSite, f_t, n_t ExitInst, n_t) override
FlowFunctionPtrType getCallToRetFlowFunction (n_t CallSite, n_t, llvm::ArrayRef< f_t > Callees) override
FlowFunctionPtrType getSummaryFlowFunction (n_t, f_t) override
InitialSeeds< n_t, d_t, l_t > initialSeeds () override
d_t createZeroValue () const
bool isZeroValue (d_t d) const noexcept override
EdgeFunctionType getStrongUpdateStoreEF (const llvm::StoreInst *Store, d_t CurrNode, d_t SuccNode, l_t UserEdgeFacts)
EdgeFunctionType getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t, d_t SuccNode) override
EdgeFunctionType getCallEdgeFunction (n_t CallSite, d_t SrcNode, f_t, d_t DestNode) override
EdgeFunctionType getReturnEdgeFunction (n_t CallSite, f_t, n_t ExitInst, d_t ExitNode, n_t, d_t RetNode) override
EdgeFunctionType getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t, d_t RetSiteNode, llvm::ArrayRef< f_t > Callees) override
EdgeFunctionType getSummaryEdgeFunction (n_t, d_t, n_t, d_t) override
l_t join (l_t Lhs, l_t Rhs) override
const auto & getData (const EdgeFunction< l_t > &EF)
EdgeFunction< l_t > extend (const EdgeFunction< l_t > &FirstFunction, const EdgeFunction< l_t > &SecondFunction) override
EdgeFunction< l_t > combine (const EdgeFunction< l_t > &FirstFunction, const EdgeFunction< l_t > &OtherFunction) override
void emitTextReport (GenericSolverResults< n_t, d_t, l_t > SR, llvm::raw_ostream &OS=llvm::outs()) override
std::unordered_set< d_t > getAllVariables (GenericSolverResults< n_t, d_t, l_t >) const
std::unordered_set< d_t > getAllVariablesWithEmptySetValue (GenericSolverResults< n_t, d_t, l_t > Solution) const
Public Member Functions inherited from psr::IDETabulationProblem< AnalysisDomainTy, Container >
IDETabulationProblem (const ProjectIRDBBase< db_t > *IRDB, std::vector< std::string > EntryPoints, std::optional< d_t > ZeroValue) noexcept(std::is_nothrow_move_constructible_v< d_t >)
IDETabulationProblem (IDETabulationProblem &&) noexcept=default
IDETabulationProblem & operator= (IDETabulationProblem &&) noexcept=default
IDETabulationProblem (const IDETabulationProblem &)=delete
IDETabulationProblem & operator= (const IDETabulationProblem &)=delete
~IDETabulationProblem () override=default
void setAnalysisPrinter (MaybeUniquePtr< AnalysisPrinterBase< AnalysisDomainTy > > P)
virtual bool isZeroValue (d_t FlowFact) const noexcept
ByConstRef< d_t > getZeroValue () const
Returns the special tautological lambda (or zero) fact.
void initializeZeroValue (d_t Zero) noexcept(std::is_nothrow_assignable_v< std::optional< d_t > &, d_t && >)
void setIFDSIDESolverConfig (IFDSIDESolverConfig Config) noexcept
Sets the configuration to be used by the IFDS/IDE solver.
IFDSIDESolverConfig & getIFDSIDESolverConfig () noexcept
Returns the configuration of the IFDS/IDE solver.
virtual void emitTextReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream &OS=llvm::outs())
virtual void emitGraphicalReport (GenericSolverResults< n_t, d_t, l_t > Results, llvm::raw_ostream &OS=llvm::outs())
virtual bool setSoundness (Soundness)
const ProjectIRDBBase< db_t > * getProjectIRDB () const noexcept
Public Member Functions inherited from psr::FlowFunctions< AnalysisDomainTy, Container >
virtual ~FlowFunctions ()=default
virtual FlowFunctionPtrType getNormalFlowFunction (n_t Curr, n_t Succ)=0
virtual FlowFunctionPtrType getCallFlowFunction (n_t CallInst, f_t CalleeFun)=0
virtual FlowFunctionPtrType getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, n_t RetSite)=0
virtual void applyUnbalancedRetFlowFunctionSideEffects (f_t CalleeFun, n_t ExitInst, d_t Source)
virtual FlowFunctionPtrType getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees)=0
virtual FlowFunctionPtrType getSummaryFlowFunction (n_t, f_t)
Public Member Functions inherited from psr::EdgeFunctions< AnalysisDomainTy >
virtual ~EdgeFunctions ()=default
virtual EdgeFunction< l_t > getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t Succ, d_t SuccNode)=0
virtual EdgeFunction< l_t > getCallEdgeFunction (n_t CallInst, d_t SrcNode, f_t CalleeFun, d_t DestNode)=0
virtual EdgeFunction< l_t > getReturnEdgeFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, d_t ExitNode, n_t RetSite, d_t RetNode)=0
virtual EdgeFunction< l_t > getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t RetSite, d_t RetSiteNode, llvm::ArrayRef< f_t > Callees)=0
virtual EdgeFunction< l_t > getSummaryEdgeFunction (n_t, d_t, n_t, d_t)
Public Member Functions inherited from psr::JoinLattice< AnalysisDomainTy >
virtual ~JoinLattice ()=default
virtual l_t topElement ()
virtual l_t bottomElement ()
virtual l_t join (l_t Lhs, l_t Rhs)
Public Member Functions inherited from psr::SemiRing< AnalysisDomainTy >
virtual ~SemiRing ()=default
virtual EdgeFunction< l_t > extend (const EdgeFunction< l_t > &L, const EdgeFunction< l_t > &R)
virtual EdgeFunction< l_t > combine (const EdgeFunction< l_t > &L, const EdgeFunction< l_t > &R)
Public Member Functions inherited from psr::AllTopFnProvider< AnalysisDomainTy >
virtual ~AllTopFnProvider ()=default
virtual EdgeFunction< typename AnalysisDomainTy::l_t > allTopFunction ()
Returns an edge function that represents the top element of the analysis.
Static Public Member Functions
static void stripBottomResults (std::unordered_map< d_t, l_t > &Res)
Static Protected Member Functions
static void printEdgeFactImpl (llvm::raw_ostream &OS, ByConstRef< l_t > EdgeFact)
static l_t joinImpl (ByConstRef< l_t > Lhs, ByConstRef< l_t > Rhs)
Static Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
static auto identityFlow ()
static auto lambdaFlow (Fn &&F)
static auto generateFlow (d_t FactToGenerate, d_t From)
static auto generateFlowIf (d_t FactToGenerate, Fn Predicate)
static auto generateManyFlows (Range &&FactsToGenerate, d_t From)
static auto killFlow (d_t FactToKill)
static auto killFlowIf (Fn Predicate)
static auto killManyFlows (Range &&FactsToKill)
static auto killAllFlows ()
static auto generateFlowAndKillAllOthers (d_t FactToGenerate, d_t From)
static auto generateManyFlowsAndKillAllOthers (Range &&FactsToGenerate, d_t From)
static auto transferFlow (d_t FactToGenerate, d_t From)
Static Protected Attributes
static constexpr auto isZeroValueImpl = LLVMZeroValue::isLLVMZeroValue
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const IIAAKillOrReplaceEF &EF)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const IIAAAddLabelsEF &EF)
Additional Inherited Members
Protected Types inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
using d_t = AnalysisDomainTy::d_t
using container_type = Container
Protected Member Functions inherited from psr::IDETabulationProblem< AnalysisDomainTy, Container >
FlowFunctions< AnalysisDomainTy, Container >::FlowFunctionPtrType generateFromZero (d_t FactToGenerate)
template<typename D = d_t, typename L = l_t>
void onResult (n_t Instr, D &&DfFact, L &&LatticeElement, DataFlowAnalysisType AnalysisType)
template<typename D = d_t>
requires std::is_same_v<l_t, BinaryDomain>
void onResult (n_t Instr, D &&DfFact, DataFlowAnalysisType AnalysisType)
InitialSeeds< n_t, d_t, l_t > createDefaultSeeds ()
Protected Member Functions inherited from psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >
auto unionFlows (FlowFunctionPtrTypeOf< F1 > OneFF, FlowFunctionPtrTypeOf< F2 > OtherFF)
Protected Attributes inherited from psr::IDETabulationProblem< AnalysisDomainTy, Container >
const ProjectIRDBBase< db_t > * IRDB {}
std::vector< std::string > EntryPoints
std::optional< d_t > ZeroValue
IFDSIDESolverConfig SolverConfig {}
Soundness SF = Soundness::Soundy
MaybeUniquePtr< AnalysisPrinterBase< AnalysisDomainTy > > Printer
Detailed Description
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false>
class psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >
SyntacticAnalysisOnly: Can be set if a syntactic-only analysis is desired (without using points-to information)
IndirectTaints: Can be set to ensure non-interference
Definition at line 212 of file IDEInstInteractionAnalysis.h.
Member Typedef Documentation
AnalysisDomainTy
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::AnalysisDomainTy = IDEInstInteractionAnalysisDomain<EdgeFactType>
Definition at line 219 of file IDEInstInteractionAnalysis.h.
d_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::d_t = typename AnalysisDomainTy::d_t
Definition at line 225 of file IDEInstInteractionAnalysis.h.
e_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::e_t = typename AnalysisDomainTy::e_t
Definition at line 231 of file IDEInstInteractionAnalysis.h.
EdgeFactGeneratorTy
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::EdgeFactGeneratorTy = std::set<e_t>(std::variant<n_t, const llvm::GlobalVariable *> InstOrGlobal)
Definition at line 236 of file IDEInstInteractionAnalysis.h.
EdgeFunctionType
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::EdgeFunctionType = EdgeFunction<l_t>
Definition at line 234 of file IDEInstInteractionAnalysis.h.
f_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::f_t = typename AnalysisDomainTy::f_t
Definition at line 227 of file IDEInstInteractionAnalysis.h.
i_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::i_t = typename AnalysisDomainTy::i_t
Definition at line 233 of file IDEInstInteractionAnalysis.h.
IDETabProblemType
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::IDETabProblemType = IDETabulationProblem<AnalysisDomainTy>
Definition at line 221 of file IDEInstInteractionAnalysis.h.
l_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::l_t = typename AnalysisDomainTy::l_t
Definition at line 232 of file IDEInstInteractionAnalysis.h.
n_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::n_t = typename AnalysisDomainTy::n_t
Definition at line 226 of file IDEInstInteractionAnalysis.h.
t_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::t_t = typename AnalysisDomainTy::t_t
Definition at line 228 of file IDEInstInteractionAnalysis.h.
v_t
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> using psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::v_t = typename AnalysisDomainTy::v_t
Definition at line 229 of file IDEInstInteractionAnalysis.h.
Constructor & Destructor Documentation
IDEInstInteractionAnalysisT()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::IDEInstInteractionAnalysisT (const LLVMProjectIRDB * IRDB, const LLVMBasedICFG * ICF, LLVMAliasInfoRef PT, std::vector< std::string > EntryPoints = {"main"}, std::function< EdgeFactGeneratorTy > EdgeFactGenerator = nullptr) inline
Definition at line 239 of file IDEInstInteractionAnalysis.h.
~IDEInstInteractionAnalysisT()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::~IDEInstInteractionAnalysisT () override default
Member Function Documentation
combine()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunction< l_t > psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::combine (const EdgeFunction< l_t > & FirstFunction, const EdgeFunction< l_t > & OtherFunction) inline override
XXX: Here, we underapproximate joins with EdgeIdentity
Definition at line 1072 of file IDEInstInteractionAnalysis.h.
References psr::defaultJoinOrNull().
createZeroValue()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> d_t psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::createZeroValue () const inline
Definition at line 656 of file IDEInstInteractionAnalysis.h.
emitTextReport()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> void psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::emitTextReport (GenericSolverResults< n_t, d_t, l_t > SR, llvm::raw_ostream & OS = llvm::outs()) inline override
Definition at line 1110 of file IDEInstInteractionAnalysis.h.
References psr::DToString(), psr::getFunctionNameFromIR(), psr::LToString(), and psr::NToString().
extend()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunction< l_t > psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::extend (const EdgeFunction< l_t > & FirstFunction, const EdgeFunction< l_t > & SecondFunction) inline override
Definition at line 1052 of file IDEInstInteractionAnalysis.h.
References psr::defaultComposeOrNull().
getAllVariables()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> std::unordered_set< d_t > psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getAllVariables (GenericSolverResults< n_t, d_t, l_t >) const inline
Computes all variables where a result set has been computed using the edge functions (and respective value domain).
Definition at line 1146 of file IDEInstInteractionAnalysis.h.
References psr::isHeapAllocatingFunction().
getAllVariablesWithEmptySetValue()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> std::unordered_set< d_t > psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getAllVariablesWithEmptySetValue (GenericSolverResults< n_t, d_t, l_t > Solution) const inline
Computes all variables for which an empty set has been computed using the edge functions (and respective value domain).
Definition at line 1170 of file IDEInstInteractionAnalysis.h.
getCallEdgeFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunctionType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getCallEdgeFunction (n_t CallSite, d_t SrcNode, f_t , d_t DestNode) inline override
Definition at line 817 of file IDEInstInteractionAnalysis.h.
getCallFlowFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> FlowFunctionPtrType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getCallFlowFunction (n_t CallSite, f_t DestFun) inline override
Definition at line 486 of file IDEInstInteractionAnalysis.h.
getCallToRetEdgeFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunctionType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t , d_t RetSiteNode, llvm::ArrayRef< f_t > Callees) inline override
Definition at line 883 of file IDEInstInteractionAnalysis.h.
getCallToRetFlowFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> FlowFunctionPtrType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getCallToRetFlowFunction (n_t CallSite, n_t , llvm::ArrayRef< f_t > Callees) inline override
Definition at line 550 of file IDEInstInteractionAnalysis.h.
References psr::Source.
getData()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> const auto & psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getData (const EdgeFunction< l_t > & EF) inline
Definition at line 1040 of file IDEInstInteractionAnalysis.h.
References psr::to_string().
getNormalEdgeFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunctionType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t , d_t SuccNode) inline override
Definition at line 765 of file IDEInstInteractionAnalysis.h.
References psr::llvmIRToShortString(), psr::llvmIRToString(), and PHASAR_LOG_LEVEL.
getNormalFlowFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> FlowFunctionPtrType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getNormalFlowFunction (n_t Curr, n_t) inline override
Definition at line 264 of file IDEInstInteractionAnalysis.h.
References psr::IDETabulationProblem< AnalysisDomainTy, Container >::generateFromZero(), psr::FlowFunctionTemplates< AnalysisDomainTy::d_t, Container >::lambdaFlow(), and PHASAR_LOG_LEVEL.
getRetFlowFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> FlowFunctionPtrType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getRetFlowFunction (n_t CallSite, f_t , n_t ExitInst, n_t) inline override
Definition at line 524 of file IDEInstInteractionAnalysis.h.
getReturnEdgeFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunctionType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getReturnEdgeFunction (n_t CallSite, f_t , n_t ExitInst, d_t ExitNode, n_t , d_t RetNode) inline override
Definition at line 852 of file IDEInstInteractionAnalysis.h.
References psr::Ret.
getStrongUpdateStoreEF()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunctionType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getStrongUpdateStoreEF (const llvm::StoreInst * Store, d_t CurrNode, d_t SuccNode, l_t UserEdgeFacts) inline
Definition at line 667 of file IDEInstInteractionAnalysis.h.
References IF_LOG_ENABLED, psr::llvmIRToString(), and PHASAR_LOG_LEVEL.
getSummaryEdgeFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> EdgeFunctionType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getSummaryEdgeFunction (n_t , d_t , n_t , d_t) inline override
Definition at line 937 of file IDEInstInteractionAnalysis.h.
getSummaryFlowFunction()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> FlowFunctionPtrType psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getSummaryFlowFunction (n_t , f_t) inline override
Definition at line 623 of file IDEInstInteractionAnalysis.h.
initialSeeds()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> InitialSeeds< n_t, d_t, l_t > psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::initialSeeds () inline override virtual
Returns initial seeds to be used for the analysis. This is a mapping of statements to initial analysis facts.
Implements psr::IDETabulationProblem< AnalysisDomainTy, Container >.
Definition at line 628 of file IDEInstInteractionAnalysis.h.
References psr::InitialSeeds< N, D, L >::addSeed(), and psr::EntryPoints.
isZeroValue()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> bool psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::isZeroValue (d_t d) const inline override noexcept
Definition at line 661 of file IDEInstInteractionAnalysis.h.
join()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> l_t psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::join (l_t Lhs, l_t Rhs) inline override
Definition at line 943 of file IDEInstInteractionAnalysis.h.
joinImpl()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> static l_t psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::joinImpl (ByConstRef< l_t > Lhs, ByConstRef< l_t > Rhs) inline static protected
Definition at line 1195 of file IDEInstInteractionAnalysis.h.
printEdgeFactImpl()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> static void psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::printEdgeFactImpl (llvm::raw_ostream & OS, ByConstRef< l_t > EdgeFact) inline static protected
Definition at line 1180 of file IDEInstInteractionAnalysis.h.
References psr::LToString().
registerEdgeFactGenerator()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> void psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::registerEdgeFactGenerator (std::function< EdgeFactGeneratorTy > EdgeFactGenerator) inline
Offer a special hook to the user that allows to generate additional edge facts on-the-fly. Above the generator function, the ordinary edge facts are generated according to the usual edge functions.
Definition at line 257 of file IDEInstInteractionAnalysis.h.
stripBottomResults()
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> static void psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::stripBottomResults (std::unordered_map< d_t, l_t > & Res) inline static
Definition at line 1100 of file IDEInstInteractionAnalysis.h.
Friends And Related Symbol Documentation
operator<< [1/2]
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const IIAAAddLabelsEF & EF) friend
Definition at line 1033 of file IDEInstInteractionAnalysis.h.
operator<< [2/2]
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const IIAAKillOrReplaceEF & EF) friend
Definition at line 988 of file IDEInstInteractionAnalysis.h.
Member Data Documentation
isZeroValueImpl
template<typename EdgeFactType = std::string, bool SyntacticAnalysisOnly = false, bool EnableIndirectTaints = false> constexpr auto psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::isZeroValueImpl = LLVMZeroValue::isLLVMZeroValue static constexpr protected
Definition at line 1178 of file IDEInstInteractionAnalysis.h.
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h