PhASAR: psr::XTaint::EdgeDomain Class Reference
psr::XTaint::EdgeDomain Class Reference final
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/ExtendedTaintAnalysis/EdgeDomain.h"
Public Types
enum Kind { Bot , Top , Sanitized , WithSanitizer }
Public Member Functions
EdgeDomain () noexcept
EdgeDomain (std::nullptr_t) noexcept
EdgeDomain (psr::Bottom) noexcept
EdgeDomain (psr::Top) noexcept
EdgeDomain (psr::XTaint::Sanitized) noexcept
EdgeDomain (const llvm::Instruction *Sani) noexcept
bool isBottom () const
bool isTop () const
bool isSanitized () const
bool isNotSanitized () const
bool hasSanitizer () const
const llvm::Instruction * getSanitizer () const
bool mayBeSanitized () const
bool operator== (const EdgeDomain &Other) const
bool operator!= (const EdgeDomain &Other) const
bool operator< (const EdgeDomain &Other) const
EdgeDomain join (const EdgeDomain &Other, BasicBlockOrdering *BBO=nullptr) const
Kind getKind () const
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const EdgeDomain &ED)
Detailed Description
Definition at line 28 of file EdgeDomain.h.
Member Enumeration Documentation
Kind
enum psr::XTaint::EdgeDomain::Kind
Enumerator
Bot
Top
Sanitized
WithSanitizer
Definition at line 30 of file EdgeDomain.h.
Constructor & Destructor Documentation
EdgeDomain() [1/6]
psr::XTaint::EdgeDomain::EdgeDomain () inline explicit noexcept
Definition at line 41 of file EdgeDomain.h.
EdgeDomain() [2/6]
psr::XTaint::EdgeDomain::EdgeDomain (std::nullptr_t) inline noexcept
Definition at line 43 of file EdgeDomain.h.
EdgeDomain() [3/6]
psr::XTaint::EdgeDomain::EdgeDomain (psr::Bottom) inline noexcept
Definition at line 46 of file EdgeDomain.h.
EdgeDomain() [4/6]
psr::XTaint::EdgeDomain::EdgeDomain (psr::Top) inline noexcept
Definition at line 49 of file EdgeDomain.h.
EdgeDomain() [5/6]
psr::XTaint::EdgeDomain::EdgeDomain (psr::XTaint::Sanitized) inline noexcept
Definition at line 51 of file EdgeDomain.h.
EdgeDomain() [6/6]
psr::XTaint::EdgeDomain::EdgeDomain (const llvm::Instruction * Sani) inline noexcept
Definition at line 54 of file EdgeDomain.h.
Member Function Documentation
getKind()
Kind psr::XTaint::EdgeDomain::getKind () const inline
Definition at line 92 of file EdgeDomain.h.
Referenced by isBottom(), isNotSanitized(), isSanitized(), and isTop().
getSanitizer()
const llvm::Instruction * psr::XTaint::EdgeDomain::getSanitizer () const inline
Definition at line 68 of file EdgeDomain.h.
Referenced by hasSanitizer(), and isNotSanitized().
hasSanitizer()
bool psr::XTaint::EdgeDomain::hasSanitizer () const inline
Definition at line 65 of file EdgeDomain.h.
References getSanitizer().
Referenced by mayBeSanitized().
isBottom()
bool psr::XTaint::EdgeDomain::isBottom () const inline
Definition at line 57 of file EdgeDomain.h.
References Bot, and getKind().
isNotSanitized()
bool psr::XTaint::EdgeDomain::isNotSanitized () const inline
Definition at line 62 of file EdgeDomain.h.
References getKind(), getSanitizer(), and WithSanitizer.
isSanitized()
bool psr::XTaint::EdgeDomain::isSanitized () const inline
Definition at line 59 of file EdgeDomain.h.
References getKind(), and Sanitized.
Referenced by mayBeSanitized().
isTop()
bool psr::XTaint::EdgeDomain::isTop () const inline
Definition at line 58 of file EdgeDomain.h.
References getKind(), and Top.
join()
EdgeDomain psr::XTaint::EdgeDomain::join (const EdgeDomain & Other, BasicBlockOrdering * BBO = nullptr) const
Referenced by psr::JoinLatticeTraits< XTaint::EdgeDomain >::join().
mayBeSanitized()
bool psr::XTaint::EdgeDomain::mayBeSanitized () const inline
Definition at line 71 of file EdgeDomain.h.
References hasSanitizer(), and isSanitized().
operator!=()
bool psr::XTaint::EdgeDomain::operator!= (const EdgeDomain & Other) const inline
Definition at line 78 of file EdgeDomain.h.
operator<()
bool psr::XTaint::EdgeDomain::operator< (const EdgeDomain & Other) const inline
An arbitrary ordering to be able to insert EdgeDomain values into std::set and as keys into std::map
Definition at line 84 of file EdgeDomain.h.
operator==()
bool psr::XTaint::EdgeDomain::operator== (const EdgeDomain & Other) const inline
Definition at line 75 of file EdgeDomain.h.
Friends And Related Symbol Documentation
operator<<
llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const EdgeDomain & ED) friend
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/ExtendedTaintAnalysis/EdgeDomain.h