PhASAR: psr::FlowFunctionCache< ProblemTy, AutoAddZero > Class Template Reference
psr::FlowFunctionCache< ProblemTy, AutoAddZero > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/FlowFunctionCache.h"
Public Member Functions
FlowFunctionCache () noexcept=default
decltype(auto) getNormalFlowFunction (ProblemTy &Problem, ByConstRef< n_t > Curr, ByConstRef< n_t > Succ, uint64_t CurrSuccId)
decltype(auto) getCallToRetFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< n_t > RetSite, llvm::ArrayRef< f_t > Callees, uint64_t CallRetId)
decltype(auto) getCallFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, uint64_t CSCalleeId)
decltype(auto) getRetFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, ByConstRef< n_t > ExitInst, ByConstRef< n_t > RetSite, uint64_t CSExitId, uint64_t CalleeRSId)
CAUTION: Keep the ID definitions in mind!
decltype(auto) getSummaryFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, uint64_t)
void clear () noexcept
void reserve (size_t NumInsts, size_t NumCalls, size_t NumFuns)
void dumpStats (llvm::raw_ostream &OS) const
FlowFunctionCacheStats getStats () const noexcept
Detailed Description
template<typename ProblemTy, bool AutoAddZero>
class psr::FlowFunctionCache< ProblemTy, AutoAddZero >
This class caches flow and edge functions to avoid their reconstruction. When a flow or edge function must be applied multiple times, a cached version is used if it exists, otherwise a new one is created and inserted into the cache. This class is used within both IDE solver implementations.
Definition at line 145 of file FlowFunctionCache.h.
Constructor & Destructor Documentation
FlowFunctionCache()
template<typename ProblemTy , bool AutoAddZero> psr::FlowFunctionCache< ProblemTy, AutoAddZero >::FlowFunctionCache () default noexcept
Member Function Documentation
clear()
template<typename ProblemTy , bool AutoAddZero> void psr::FlowFunctionCache< ProblemTy, AutoAddZero >::clear () inline noexcept
Definition at line 299 of file FlowFunctionCache.h.
References psr::DenseTable1d< K, V >::clear().
Referenced by psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::clear(), and psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::clearFlowFunctions().
dumpStats()
template<typename ProblemTy , bool AutoAddZero> void psr::FlowFunctionCache< ProblemTy, AutoAddZero >::dumpStats (llvm::raw_ostream & OS) const inline
Definition at line 316 of file FlowFunctionCache.h.
References psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getStats().
getCallFlowFunction()
template<typename ProblemTy , bool AutoAddZero> decltype(auto) psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getCallFlowFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, uint64_t CSCalleeId) inline
Definition at line 239 of file FlowFunctionCache.h.
getCallToRetFlowFunction()
template<typename ProblemTy , bool AutoAddZero> decltype(auto) psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getCallToRetFlowFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< n_t > RetSite, llvm::ArrayRef< f_t > Callees, uint64_t CallRetId) inline
Definition at line 227 of file FlowFunctionCache.h.
getNormalFlowFunction()
template<typename ProblemTy , bool AutoAddZero> decltype(auto) psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getNormalFlowFunction (ProblemTy & Problem, ByConstRef< n_t > Curr, ByConstRef< n_t > Succ, uint64_t CurrSuccId) inline
Definition at line 218 of file FlowFunctionCache.h.
getRetFlowFunction()
template<typename ProblemTy , bool AutoAddZero> decltype(auto) psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getRetFlowFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, ByConstRef< n_t > ExitInst, ByConstRef< n_t > RetSite, uint64_t CSExitId, uint64_t CalleeRSId) inline
CAUTION: Keep the ID definitions in mind!
Definition at line 251 of file FlowFunctionCache.h.
References psr::DenseTable1d< K, V >::getOrCreate(), and psr::Ret.
getStats()
template<typename ProblemTy , bool AutoAddZero> FlowFunctionCacheStats psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getStats () const inline noexcept
TODO (#734): With C++20 use designated aggregate initializers here!
Definition at line 318 of file FlowFunctionCache.h.
References psr::DenseTable1d< K, V >::size().
Referenced by psr::FlowFunctionCache< ProblemTy, AutoAddZero >::dumpStats(), and psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::getStats().
getSummaryFlowFunction()
template<typename ProblemTy , bool AutoAddZero> decltype(auto) psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getSummaryFlowFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, uint64_t) inline
XXX: The old FECache doesn't cache summary FFs, so refrain from doing this here as well. Enable it, once the user-problems reliably return std::nullptr_t such that caching can be disabled automatically
Definition at line 283 of file FlowFunctionCache.h.
reserve()
template<typename ProblemTy , bool AutoAddZero> void psr::FlowFunctionCache< ProblemTy, AutoAddZero >::reserve (size_t NumInsts, size_t NumCalls, size_t NumFuns) inline
Definition at line 308 of file FlowFunctionCache.h.
References psr::DenseTable1d< K, V >::reserve().
Referenced by psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::reserve().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/FlowFunctionCache.h