PhASAR: psr::EdgeFunction< L > Class Template Reference
psr::EdgeFunction< L > Class Template Reference
Ref-counted and type-erased edge function with small-object optimization. Supports caching.
#include "phasar/DataFlow/IfdsIde/EdgeFunction.h"
Public Types
using l_t = L
Public Member Functions
EdgeFunction () noexcept=default
Default-initializes the edge-function with nullptr.
EdgeFunction (std::nullptr_t) noexcept
Default-initializes the edge-function with nullptr.
EdgeFunction (const EdgeFunction &Other) noexcept
Copy constructor. Increments the ref-count, if not small-object-optimized.
EdgeFunction (EdgeFunction &&Other) noexcept
void swap (EdgeFunction &Other) noexcept
Standard swap; does not affect ref-counts.
EdgeFunction & operator= (EdgeFunction Other) noexcept
EdgeFunction & operator= (std::nullptr_t) noexcept
~EdgeFunction () noexcept
template<typename ConcreteEF , typename = std::enable_if_t<!std::is_same_v< EdgeFunction, std::decay_t<ConcreteEF>>>>
EdgeFunction (EdgeFunctionRef< ConcreteEF > CEF) noexcept
template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>>
EdgeFunction (ConcreteEF &&CEF) noexcept(IsSOOCandidate< std::decay_t< ConcreteEF > >)
template<typename ConcreteEF , typename... ArgTys>
EdgeFunction (std::in_place_type_t< ConcreteEF >, ArgTys &&...Args) noexcept(IsSOOCandidate< std::decay_t< ConcreteEF > > &&std::is_nothrow_constructible_v< ConcreteEF, ArgTys... >)
template<typename ConcreteEF , typename = std::enable_if_t< IsEdgeFunction<ConcreteEF> && std::is_move_constructible_v<ConcreteEF>>>
EdgeFunction (CachedEdgeFunction< ConcreteEF > EF)
l_t computeTarget (ByConstRef< l_t > Source) const
EdgeFunction composeWith (const EdgeFunction &SecondEF) const
EdgeFunction joinWith (const EdgeFunction &OtherEF) const
bool referenceEquals (const EdgeFunction< L > &Other) const noexcept
template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>>
bool equals (EdgeFunctionRef< ConcreteEF > Other) const noexcept
bool isConstant () const noexcept
bool isValid () const noexcept
operator bool () const noexcept
Performs a null-check. True, iff thie edge function is not null.
template<typename ConcreteEF >
bool isa () const noexcept
template<typename ConcreteEF >
const ConcreteEF * cast () const noexcept
template<typename ConcreteEF >
const ConcreteEF * dyn_cast () const noexcept
bool isRefCounted () const noexcept
bool isCached () const noexcept
auto getAllocationPolicy () const noexcept
const void * getOpaqueValue () const noexcept
template<typename ConcreteEF >
EdgeFunctionSingletonCache< ConcreteEF > * getCacheOrNull () const noexcept
size_t getHashCode () const noexcept
auto depth () const noexcept
Static Public Member Functions
static EdgeFunction compose (const EdgeFunction &FirstEF, const EdgeFunction &SecondEF)
static EdgeFunction join (const EdgeFunction &FirstEF, const EdgeFunction &SecondEF)
static EdgeFunction getEmptyKey () noexcept
static EdgeFunction getTombstoneKey () noexcept
Friends
void swap (EdgeFunction &LHS, EdgeFunction &RHS) noexcept
Standard swap; does not affect ref-counts.
bool operator== (const EdgeFunction &LHS, const EdgeFunction &RHS) noexcept
template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>>
bool operator== (EdgeFunctionRef< ConcreteEF > LHS, const EdgeFunction &RHS) noexcept
template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>>
bool operator== (const EdgeFunction< L > &LHS, EdgeFunctionRef< ConcreteEF > RHS) noexcept
bool operator== (const EdgeFunction &EF, std::nullptr_t) noexcept
bool operator== (std::nullptr_t, const EdgeFunction &EF) noexcept
bool operator!= (const EdgeFunction &LHS, const EdgeFunction &RHS) noexcept
bool operator!= (const EdgeFunction &EF, std::nullptr_t) noexcept
bool operator!= (std::nullptr_t, const EdgeFunction &EF) noexcept
template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>>
bool operator!= (EdgeFunctionRef< ConcreteEF > LHS, const EdgeFunction< L > &RHS) noexcept
template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>>
bool operator!= (const EdgeFunction< L > &LHS, EdgeFunctionRef< ConcreteEF > RHS) noexcept
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const EdgeFunction &EF)
std::ostream & operator<< (std::ostream &OS, const EdgeFunction &EF)
std::string to_string (const EdgeFunction &EF)
bool operator< (const EdgeFunction &LHS, const EdgeFunction &RHS) noexcept
size_t hash_value (const EdgeFunction &EF) noexcept
Detailed Description
template<typename L>
class psr::EdgeFunction< L >
Ref-counted and type-erased edge function with small-object optimization. Supports caching.
Definition at line 174 of file EdgeFunction.h.
Member Typedef Documentation
l_t
template<typename L > using psr::EdgeFunction< L >::l_t = L
Definition at line 176 of file EdgeFunction.h.
Constructor & Destructor Documentation
EdgeFunction() [1/8]
template<typename L > psr::EdgeFunction< L >::EdgeFunction () default noexcept
Default-initializes the edge-function with nullptr.
EdgeFunction() [2/8]
template<typename L > psr::EdgeFunction< L >::EdgeFunction (std::nullptr_t) inline noexcept
Default-initializes the edge-function with nullptr.
Definition at line 183 of file EdgeFunction.h.
EdgeFunction() [3/8]
template<typename L > psr::EdgeFunction< L >::EdgeFunction (const EdgeFunction< L > & Other) inline noexcept
Copy constructor. Increments the ref-count, if not small-object-optimized.
Definition at line 185 of file EdgeFunction.h.
EdgeFunction() [4/8]
template<typename L > psr::EdgeFunction< L >::EdgeFunction (EdgeFunction< L > && Other) inline noexcept
Move constructor. Does not increment the ref-count, but instead leaves the moved-from edge function in the nullptr state.
Definition at line 189 of file EdgeFunction.h.
~EdgeFunction()
template<typename L > psr::EdgeFunction< L >::~EdgeFunction () inline noexcept
Destructor. Decrements the ref-count if not small-object-optimized and destroyes the held edge function once the ref-count reaches 0.
Definition at line 220 of file EdgeFunction.h.
EdgeFunction() [5/8]
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t<!std::is_same_v< EdgeFunction, std::decay_t<ConcreteEF>>>> psr::EdgeFunction< L >::EdgeFunction (EdgeFunctionRef< ConcreteEF > CEF) inline noexcept
Implicit-conversion constructor from EdgeFunctionRef. Increments the ref-count if not small-object optimized
Definition at line 236 of file EdgeFunction.h.
EdgeFunction() [6/8]
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>> psr::EdgeFunction< L >::EdgeFunction (ConcreteEF && CEF) inline noexcept
Conversion-constructor from any edge function (that satisfies the IsEdgeFunction trait). Stores a type-erased copy of CEF and allocates space for it on the heap if small-object-optimization cannot be applied.
Definition at line 256 of file EdgeFunction.h.
EdgeFunction() [7/8]
template<typename L > template<typename ConcreteEF , typename... ArgTys> psr::EdgeFunction< L >::EdgeFunction (std::in_place_type_t< ConcreteEF > , ArgTys &&... Args) inline explicit noexcept
Emplacement-constructor for any edge function. Constructs a new object of type ConcreteEF with the given constructor arguments and allocates space for it on the heap if small-object-optimization cannot be applied. No extra copy- or move construction/assignment is performed. Use this ctor if even moving is expensive.
Definition at line 267 of file EdgeFunction.h.
References psr::Ret.
EdgeFunction() [8/8]
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t< IsEdgeFunction<ConcreteEF> && std::is_move_constructible_v<ConcreteEF>>> psr::EdgeFunction< L >::EdgeFunction (CachedEdgeFunction< ConcreteEF > EF) inline
Conversion-constructor for any edge function with enabled caching. Stores a type-erased copy of EF.EF and allocates space for it on the heap if small-object-optimization cannot be applied. If a heap allocation is requires, first consults the EF.Cache to check whether an equivalent edge function is already allocated. If so, takes the one from the cache and increases its ref-count. Otherwise, performs a fresh allocation and inserts the edge function into EF.Cache. When all references to this edge function are out-of-scope, the destructor automatically removes the edge function from EF.Cache. Hence, make sure that EF.Cache lives at least as long as the last edge function cached in it.
Definition at line 303 of file EdgeFunction.h.
References psr::CachedEdgeFunction< EdgeFunctionTy >::Cache, psr::CachedEdgeFunction< EdgeFunctionTy >::EF, and psr::Ret.
Member Function Documentation
cast()
template<typename L > template<typename ConcreteEF > const ConcreteEF * psr::EdgeFunction< L >::cast () const inline noexcept
Performs an unchecked typecast to ConcreteEF. In debug builds, asserts isa<ConcreteEF>.
Compatible with the llvm::isa API.
Use with caution!
Definition at line 608 of file EdgeFunction.h.
compose()
template<typename L > static EdgeFunction psr::EdgeFunction< L >::compose (const EdgeFunction< L > & FirstEF, const EdgeFunction< L > & SecondEF) inline static
This function composes the two edge functions this and SecondEF. This function is used to extend an edge function in order to construct so-called jump functions that describe the effects of everlonger sequences of code.
For semantic correctness, please make sure that for all inputs x in l_t, it holds: compose(FirstEF, SecondEF).computeTarget(x) == SecondEF.computeTarget(FirstEF.computeTarget(x)).
Definition at line 367 of file EdgeFunction.h.
composeWith()
template<typename L > EdgeFunction psr::EdgeFunction< L >::composeWith (const EdgeFunction< L > & SecondEF) const inline
This function composes the two edge functions this and SecondEF. This function is used to extend an edge function in order to construct so-called jump functions that describe the effects of everlonger sequences of code.
Calls the static function EF::compose(*this, SecondEF) for your concrete edge function EF.
For semantic correctness, please make sure that for all inputs x in l_t, it holds: this->composeWith(SecondEF).computeTarget(x) == SecondEF.computeTarget(this->computeTarget(x)).
Definition at line 354 of file EdgeFunction.h.
Referenced by psr::EdgeFunctionComposer< L >::compose(), and psr::SemiRing< AnalysisDomainTy >::extend().
computeTarget()
template<typename L > l_t psr::EdgeFunction< L >::computeTarget (ByConstRef< l_t > Source) const inline
This function describes the concrete value computation for its respective exploded supergraph edge. The function(s) will be evaluated once the exploded supergraph has been constructed and the concrete values of the various value computation problems along the supergraph edges are evaluated.
Please also refer to the various edge function factories of the EdgeFunctions interface: EdgeFunctions::get*EdgeFunction() for more details.
Definition at line 337 of file EdgeFunction.h.
References psr::Source.
Referenced by psr::AllBottom< L >::compose(), psr::ConstantEdgeFunction< L >::compose(), psr::EdgeFunctionComposer< L >::computeTarget(), and psr::ConstantEdgeFunction< L >::join().
depth()
template<typename L > auto psr::EdgeFunction< L >::depth () const inline noexcept
Definition at line 674 of file EdgeFunction.h.
Referenced by psr::EdgeFunctionComposer< L >::depth(), and psr::IDESolver< AnalysisDomainTy, Container >::getEdgeFunctionStatistics().
dyn_cast()
template<typename L > template<typename ConcreteEF > const ConcreteEF * psr::EdgeFunction< L >::dyn_cast () const inline noexcept
Performs an checked typecast to ConcreteEF. If this edge function is not exactly of type ConcreteEF, returns nullptr.
Compatible with the llvm::dyn_cast API.
Definition at line 619 of file EdgeFunction.h.
equals()
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>> bool psr::EdgeFunction< L >::equals (EdgeFunctionRef< ConcreteEF > Other) const inline noexcept
Definition at line 445 of file EdgeFunction.h.
getAllocationPolicy()
template<typename L > auto psr::EdgeFunction< L >::getAllocationPolicy () const inline noexcept
Definition at line 640 of file EdgeFunction.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::getEdgeFunctionStatistics().
getCacheOrNull()
template<typename L > template<typename ConcreteEF > EdgeFunctionSingletonCache< ConcreteEF > * psr::EdgeFunction< L >::getCacheOrNull () const inline noexcept
Gets the cache where this edge function is being cached in. If this edge function is not cached (i.e., isCached() returns false), returns nullptr. Assumes that the held edge function is exactly of type ConcreteEF. In debug builds, asserts isa<ConcreteEF>.
Use with caution!
Definition at line 656 of file EdgeFunction.h.
getEmptyKey()
template<typename L > static EdgeFunction psr::EdgeFunction< L >::getEmptyKey () inline static noexcept
Definition at line 683 of file EdgeFunction.h.
Referenced by llvm::DenseMapInfo< psr::EdgeFunction< L > >::getEmptyKey().
getHashCode()
template<typename L > size_t psr::EdgeFunction< L >::getHashCode () const inline noexcept
Definition at line 665 of file EdgeFunction.h.
getOpaqueValue()
template<typename L > const void * psr::EdgeFunction< L >::getOpaqueValue () const inline noexcept
Gets an opaque identifier for this edge function. Only meant for comparisons of object-identity. Do not dereference!
Definition at line 646 of file EdgeFunction.h.
getTombstoneKey()
template<typename L > static EdgeFunction psr::EdgeFunction< L >::getTombstoneKey () inline static noexcept
Definition at line 689 of file EdgeFunction.h.
Referenced by llvm::DenseMapInfo< psr::EdgeFunction< L > >::getTombstoneKey().
isa()
template<typename L > template<typename ConcreteEF > bool psr::EdgeFunction< L >::isa () const inline noexcept
Performs a runtime-typecheck. True, if the concrete type of the held edge function exactly equals ConcreteEF.
CAUTION: This model of isa-relation does not care about inheritance. Edge functions of a base class BaseEF and a derived class DerivedEF are considered unrelated!
Definition at line 592 of file EdgeFunction.h.
isCached()
template<typename L > bool psr::EdgeFunction< L >::isCached () const inline noexcept
True, iff this edge function is cached in a EdgeFunctionSingletonCache.
False for small-object-optimized- and null-EF.
Definition at line 636 of file EdgeFunction.h.
isConstant()
template<typename L > bool psr::EdgeFunction< L >::isConstant () const inline noexcept
True, if the concrete edge function defines itself as constant, i.e. for all x,y in l_t it holds: computeTarget(x) == computeTarget(y).
Allows for better optimizations in compose and join and should be provided, whehever this knowledge is available.
Definition at line 574 of file EdgeFunction.h.
isRefCounted()
template<typename L > bool psr::EdgeFunction< L >::isRefCounted () const inline noexcept
True, iff this edge function is not small-object-optimized and thus its lifetime is managed by ref-counting.
False for null-EF.
Definition at line 629 of file EdgeFunction.h.
isValid()
template<typename L > bool psr::EdgeFunction< L >::isValid () const inline noexcept
Definition at line 579 of file EdgeFunction.h.
join()
template<typename L > static EdgeFunction psr::EdgeFunction< L >::join (const EdgeFunction< L > & FirstEF, const EdgeFunction< L > & SecondEF) inline static
This function describes the join of the two edge functions this and OtherEF. The function is called whenever two edge functions need to be joined, for instance, when two branches lead to a common successor instruction.
For semantic correctness, please make sure that for all inputs x in l_t, it holds (with joinl = JoinLatticeTraits<l_t>::join): joinl(join(FirstEF, SecondEF).computeTarget(x)), joinl(FirstEF.computeTarget(x), SecondEF.computeTarget(x))) == this->joinWith(OtherEF).computeTarget(x) i.e. that joining on edge functions only goes up the lattice that is connected with the value-lattice on l_t
Definition at line 408 of file EdgeFunction.h.
joinWith()
template<typename L > EdgeFunction psr::EdgeFunction< L >::joinWith (const EdgeFunction< L > & OtherEF) const inline
This function describes the join of the two edge functions this and OtherEF. The function is called whenever two edge functions need to be joined, for instance, when two branches lead to a common successor instruction.
Calls the static function EF::join(*this, OtherEF) for your concrete edge function EF.
For semantic correctness, please make sure that for all inputs x in l_t, it holds (with join = JoinLatticeTraits<l_t>::join): join(this->joinWith(OtherEF).computeTarget(x)), join(this->computeTarget(x), OtherEF.computeTarget(x))) == this->joinWith(OtherEF).computeTarget(x) i.e. that joining on edge functions only goes up the lattice that is connected with the value-lattice on l_t
Definition at line 391 of file EdgeFunction.h.
Referenced by psr::SemiRing< AnalysisDomainTy >::combine(), psr::ConstantEdgeFunction< L >::join(), and psr::EdgeIdentity< L >::join().
operator bool()
template<typename L > psr::EdgeFunction< L >::operator bool () const inline explicit noexcept
Performs a null-check. True, iff thie edge function is not null.
Definition at line 584 of file EdgeFunction.h.
operator=() [1/2]
template<typename L > EdgeFunction & psr::EdgeFunction< L >::operator= (EdgeFunction< L > Other) inline noexcept
Combined copy- and move assignment. If the assigned-to edge function is not null, invokes the destructor on it, before overwriting its content.
Definition at line 206 of file EdgeFunction.h.
operator=() [2/2]
template<typename L > EdgeFunction & psr::EdgeFunction< L >::operator= (std::nullptr_t) inline noexcept
Null-assignment operator. Decrements the ref-count if not small-object-optimized or already null. Leaves the assigned-to edge function in the nullptr state.
Definition at line 213 of file EdgeFunction.h.
referenceEquals()
template<typename L > bool psr::EdgeFunction< L >::referenceEquals (const EdgeFunction< L > & Other) const inline noexcept
Definition at line 417 of file EdgeFunction.h.
swap()
template<typename L > void psr::EdgeFunction< L >::swap (EdgeFunction< L > & Other) inline noexcept
Standard swap; does not affect ref-counts.
Definition at line 195 of file EdgeFunction.h.
Friends And Related Symbol Documentation
hash_value
template<typename L > size_t hash_value (const EdgeFunction< L > & EF) friend
Definition at line 679 of file EdgeFunction.h.
operator!= [1/5]
template<typename L > bool operator!= (const EdgeFunction< L > & EF, std::nullptr_t) friend
Definition at line 492 of file EdgeFunction.h.
operator!= [2/5]
template<typename L > bool operator!= (const EdgeFunction< L > & LHS, const EdgeFunction< L > & RHS) friend
Definition at line 488 of file EdgeFunction.h.
operator!= [3/5]
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>> bool operator!= (const EdgeFunction< L > & LHS, EdgeFunctionRef< ConcreteEF > RHS) friend
Definition at line 514 of file EdgeFunction.h.
operator!= [4/5]
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>> bool operator!= (EdgeFunctionRef< ConcreteEF > LHS, const EdgeFunction< L > & RHS) friend
Definition at line 505 of file EdgeFunction.h.
operator!= [5/5]
template<typename L > bool operator!= (std::nullptr_t , const EdgeFunction< L > & EF) friend
Definition at line 496 of file EdgeFunction.h.
operator<
template<typename L > bool operator< (const EdgeFunction< L > & LHS, const EdgeFunction< L > & RHS) friend
Arbitrary partial ordering for being able to sort edge functions.
Definition at line 560 of file EdgeFunction.h.
operator<< [1/2]
template<typename L > llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const EdgeFunction< L > & EF) friend
Printing function. Based on llvm::raw_ostream &operator<<(llvm::raw_ostream &OS, const ConcreteEF &EF) for the concrete type ConcreteEF of EF.
If the ConcreteEF does not define a fitting printing function, defaults to printing the concrete type ConcreteEF.
Definition at line 525 of file EdgeFunction.h.
operator<< [2/2]
template<typename L > std::ostream & operator<< (std::ostream & OS, const EdgeFunction< L > & EF) friend
Printing function. Based on llvm::raw_ostream &operator<<(llvm::raw_ostream &OS, const EdgeFunction &EF).
Useful for unittests (gtest works with std::ostream instead of llvm::raw_ostream).
Definition at line 540 of file EdgeFunction.h.
operator== [1/5]
template<typename L > bool operator== (const EdgeFunction< L > & EF, std::nullptr_t) friend
Definition at line 480 of file EdgeFunction.h.
operator== [2/5]
template<typename L > bool operator== (const EdgeFunction< L > & LHS, const EdgeFunction< L > & RHS) friend
Checks for equality of two edge functions. Equality requires exact type-equality and value-equality based on operator== of the concrete edge functions that are compared.
If the concrete edge function has no nonstatic data members, the equality is defaulted to only compare the types. However, by explicitly defining operator==, this behavior can be overridden.
Definition at line 429 of file EdgeFunction.h.
operator== [3/5]
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>> bool operator== (const EdgeFunction< L > & LHS, EdgeFunctionRef< ConcreteEF > RHS) friend
Definition at line 476 of file EdgeFunction.h.
operator== [4/5]
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t< !std::is_same_v<EdgeFunction, std::decay_t<ConcreteEF>> && IsEdgeFunction<ConcreteEF>>> bool operator== (EdgeFunctionRef< ConcreteEF > LHS, const EdgeFunction< L > & RHS) friend
Definition at line 466 of file EdgeFunction.h.
operator== [5/5]
template<typename L > bool operator== (std::nullptr_t , const EdgeFunction< L > & EF) friend
Definition at line 484 of file EdgeFunction.h.
swap
template<typename L > void swap (EdgeFunction< L > & LHS, EdgeFunction< L > & RHS) friend
Standard swap; does not affect ref-counts.
Definition at line 200 of file EdgeFunction.h.
to_string
template<typename L > std::string to_string (const EdgeFunction< L > & EF) friend
Stringify function. Based on llvm::raw_ostream &operator<<(llvm::raw_ostream &OS, const EdgeFunction &EF).
Useful for ADL calls to to_string (overloads with all the to_string functions of the STL). Do not rename!
Definition at line 551 of file EdgeFunction.h.
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/EdgeFunction.h