PhASAR: psr::DenseSet< T, DSI > Class Template Reference
psr::DenseSet< T, DSI > Class Template Reference
#include "phasar/Utils/TableWrappers.h"
Public Types
using value_type = T
Public Member Functions
DenseSet () noexcept=default
template<typename Allocator >
DenseSet (Allocator) noexcept
void reserve (size_t Capacity)
auto insert (T Val)
bool contains (ByConstRef< T > Val) const noexcept
bool erase (ByConstRef< T > Val)
auto begin () const noexcept
auto end () const noexcept
void clear () noexcept
auto cells () const noexcept
detail::CellVecSmallVectorTy< T > cellVec () const
template<typename FilterFn >
detail::CellVecSmallVectorTy< T > cellVec (FilterFn Filter) const
template<typename Projection >
detail::CellVecSmallVectorTy< std::invoke_result_t< Projection, T > > allOf (Projection Proj, ByConstRef< std::invoke_result_t< Projection, T > > Of) const
size_t size () const noexcept
bool empty () const noexcept
size_t getApproxSizeInBytes () const noexcept
Detailed Description
template<typename T, typename DSI = llvm::DenseMapInfo<T>>
class psr::DenseSet< T, DSI >
Definition at line 968 of file TableWrappers.h.
Member Typedef Documentation
value_type
template<typename T , typename DSI = llvm::DenseMapInfo<T>> using psr::DenseSet< T, DSI >::value_type = T
Definition at line 970 of file TableWrappers.h.
Constructor & Destructor Documentation
DenseSet() [1/2]
template<typename T , typename DSI = llvm::DenseMapInfo<T>> psr::DenseSet< T, DSI >::DenseSet () default noexcept
DenseSet() [2/2]
template<typename T , typename DSI = llvm::DenseMapInfo<T>> template<typename Allocator > psr::DenseSet< T, DSI >::DenseSet (Allocator) inline noexcept
Definition at line 972 of file TableWrappers.h.
Member Function Documentation
allOf()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> template<typename Projection > detail::CellVecSmallVectorTy< std::invoke_result_t< Projection, T > > psr::DenseSet< T, DSI >::allOf (Projection Proj, ByConstRef< std::invoke_result_t< Projection, T > > Of) const inline
Definition at line 1012 of file TableWrappers.h.
References psr::Ret.
begin()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> auto psr::DenseSet< T, DSI >::begin () const inline noexcept
Definition at line 982 of file TableWrappers.h.
Referenced by psr::DenseSet< T, DSI >::cells().
cells()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> auto psr::DenseSet< T, DSI >::cells () const inline noexcept
Definition at line 990 of file TableWrappers.h.
References psr::DenseSet< T, DSI >::begin(), and psr::DenseSet< T, DSI >::end().
cellVec() [1/2]
template<typename T , typename DSI = llvm::DenseMapInfo<T>> detail::CellVecSmallVectorTy< T > psr::DenseSet< T, DSI >::cellVec () const inline
Definition at line 992 of file TableWrappers.h.
References psr::Ret.
cellVec() [2/2]
template<typename T , typename DSI = llvm::DenseMapInfo<T>> template<typename FilterFn > detail::CellVecSmallVectorTy< T > psr::DenseSet< T, DSI >::cellVec (FilterFn Filter) const inline
Definition at line 1000 of file TableWrappers.h.
References psr::Ret.
clear()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> void psr::DenseSet< T, DSI >::clear () inline noexcept
Definition at line 985 of file TableWrappers.h.
contains()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> bool psr::DenseSet< T, DSI >::contains (ByConstRef< T > Val) const inline noexcept
Definition at line 978 of file TableWrappers.h.
empty()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> bool psr::DenseSet< T, DSI >::empty () const inline noexcept
Definition at line 1025 of file TableWrappers.h.
end()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> auto psr::DenseSet< T, DSI >::end () const inline noexcept
Definition at line 983 of file TableWrappers.h.
Referenced by psr::DenseSet< T, DSI >::cells().
erase()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> bool psr::DenseSet< T, DSI >::erase (ByConstRef< T > Val) inline
Definition at line 980 of file TableWrappers.h.
getApproxSizeInBytes()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> size_t psr::DenseSet< T, DSI >::getApproxSizeInBytes () const inline noexcept
Definition at line 1027 of file TableWrappers.h.
insert()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> auto psr::DenseSet< T, DSI >::insert (T Val) inline
Definition at line 976 of file TableWrappers.h.
reserve()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> void psr::DenseSet< T, DSI >::reserve (size_t Capacity) inline
Definition at line 974 of file TableWrappers.h.
size()
template<typename T , typename DSI = llvm::DenseMapInfo<T>> size_t psr::DenseSet< T, DSI >::size () const inline noexcept
Definition at line 1024 of file TableWrappers.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/TableWrappers.h