PhASAR: psr::InitialSeeds< N, D, L > Class Template Reference
psr::InitialSeeds< N, D, L > Class Template Reference
Represent the starting points of the analysis.
#include "phasar/DataFlow/IfdsIde/InitialSeeds.h"
Public Types
using GeneralizedSeeds = std::map< N, std::map< D, L > >
using n_t = N
using d_t = D
using l_t = L
Public Member Functions
InitialSeeds ()=default
template<typename LL = L, typename = std::enable_if_t<std::is_same_v<LL, BinaryDomain>>>
InitialSeeds (const std::map< N, std::set< D > > &Seeds)
InitialSeeds (GeneralizedSeeds Seeds)
template<typename LL = L, typename = std::enable_if_t<std::is_same_v<LL, BinaryDomain>>>
void addSeed (N Node, D Fact)
void addSeed (N Node, D Fact, L Value)
size_t countInitialSeeds () const
size_t countInitialSeeds (N Node) const
bool containsInitialSeedsFor (N Node) const
bool empty () const
const GeneralizedSeeds & getSeeds () const &
GeneralizedSeeds getSeeds () &&
void dump (llvm::raw_ostream &OS=llvm::errs()) const
Detailed Description
template<typename N, typename D, typename L>
class psr::InitialSeeds< N, D, L >
Represent the starting points of the analysis.
The initial facts that should hold at the entry points.
Definition at line 28 of file InitialSeeds.h.
Member Typedef Documentation
d_t
template<typename N , typename D , typename L > using psr::InitialSeeds< N, D, L >::d_t = D
Definition at line 33 of file InitialSeeds.h.
GeneralizedSeeds
template<typename N , typename D , typename L > using psr::InitialSeeds< N, D, L >::GeneralizedSeeds = std::map<N, std::map<D, L> >
Definition at line 30 of file InitialSeeds.h.
l_t
template<typename N , typename D , typename L > using psr::InitialSeeds< N, D, L >::l_t = L
Definition at line 34 of file InitialSeeds.h.
n_t
template<typename N , typename D , typename L > using psr::InitialSeeds< N, D, L >::n_t = N
Definition at line 32 of file InitialSeeds.h.
Constructor & Destructor Documentation
InitialSeeds() [1/3]
template<typename N , typename D , typename L > psr::InitialSeeds< N, D, L >::InitialSeeds () default
InitialSeeds() [2/3]
template<typename N , typename D , typename L > template<typename LL = L, typename = std::enable_if_t<std::is_same_v<LL, BinaryDomain>>> psr::InitialSeeds< N, D, L >::InitialSeeds (const std::map< N, std::set< D > > & Seeds) inline
Definition at line 40 of file InitialSeeds.h.
References psr::BOTTOM.
InitialSeeds() [3/3]
template<typename N , typename D , typename L > psr::InitialSeeds< N, D, L >::InitialSeeds (GeneralizedSeeds Seeds) inline
Definition at line 48 of file InitialSeeds.h.
Member Function Documentation
addSeed() [1/2]
template<typename N , typename D , typename L > template<typename LL = L, typename = std::enable_if_t<std::is_same_v<LL, BinaryDomain>>> void psr::InitialSeeds< N, D, L >::addSeed (N Node, D Fact) inline
Definition at line 52 of file InitialSeeds.h.
References psr::InitialSeeds< N, D, L >::addSeed(), and psr::BOTTOM.
Referenced by psr::InitialSeeds< N, D, L >::addSeed(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::initialSeeds(), and psr::IDESolver< AnalysisDomainTy, Container >::submitInitialSeeds().
addSeed() [2/2]
template<typename N , typename D , typename L > void psr::InitialSeeds< N, D, L >::addSeed (N Node, D Fact, L Value) inline
Definition at line 56 of file InitialSeeds.h.
containsInitialSeedsFor()
template<typename N , typename D , typename L > bool psr::InitialSeeds< N, D, L >::containsInitialSeedsFor (N Node) const inline
Definition at line 76 of file InitialSeeds.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::valuePropagationTask().
countInitialSeeds() [1/2]
template<typename N , typename D , typename L > size_t psr::InitialSeeds< N, D, L >::countInitialSeeds () const inline
Definition at line 60 of file InitialSeeds.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::submitInitialSeeds().
countInitialSeeds() [2/2]
template<typename N , typename D , typename L > size_t psr::InitialSeeds< N, D, L >::countInitialSeeds (N Node) const inline
Definition at line 68 of file InitialSeeds.h.
dump()
template<typename N , typename D , typename L > void psr::InitialSeeds< N, D, L >::dump (llvm::raw_ostream & OS = llvm::errs()) const inline
Definition at line 85 of file InitialSeeds.h.
References psr::DToString(), psr::LToString(), and psr::NToString().
empty()
template<typename N , typename D , typename L > bool psr::InitialSeeds< N, D, L >::empty () const inline
Definition at line 80 of file InitialSeeds.h.
getSeeds() [1/2]
template<typename N , typename D , typename L > GeneralizedSeeds psr::InitialSeeds< N, D, L >::getSeeds () && inline
Definition at line 83 of file InitialSeeds.h.
getSeeds() [2/2]
template<typename N , typename D , typename L > const GeneralizedSeeds & psr::InitialSeeds< N, D, L >::getSeeds () const & inline
Definition at line 82 of file InitialSeeds.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::submitInitialSeeds(), and psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/InitialSeeds.h