PhASAR: psr::CRTPBase< Derived > Class Template Reference
psr::CRTPBase< Derived > Class Template Reference
#include "phasar/Utils/CRTPUtils.h"
Protected Member Functions
constexpr CRTPBase () noexcept=default
constexpr Derived & self () &noexcept
constexpr Derived && self () &&noexcept
constexpr const Derived & self () const &noexcept
Detailed Description
template<typename Derived>
class psr::CRTPBase< Derived >
Definition at line 14 of file CRTPUtils.h.
Constructor & Destructor Documentation
CRTPBase()
template<typename Derived > constexpr psr::CRTPBase< Derived >::CRTPBase () constexpr protected default noexcept
Member Function Documentation
self() [1/3]
template<typename Derived > constexpr Derived && psr::CRTPBase< Derived >::self () && inline constexpr protected noexcept
Definition at line 23 of file CRTPUtils.h.
self() [2/3]
template<typename Derived > constexpr Derived & psr::CRTPBase< Derived >::self () & inline constexpr protected noexcept
Definition at line 20 of file CRTPUtils.h.
Referenced by psr::ICFGBase< Derived >::allNonCallStartNodes(), psr::PointsToInfoBase< Derived >::asAbstractObject(), psr::PointsToInfoBase< Derived >::asPointerOrNull(), psr::CFGBase< Derived >::getAllControlFlowEdges(), psr::ICFGBase< Derived >::getAllFunctions(), psr::CFGBase< Derived >::getAllInstructionsOf(), psr::CallGraphBase< Derived >::getAllVertexCallSites(), psr::CallGraphBase< Derived >::getAllVertexFunctions(), psr::CallGraphBase< Derived >::getCalleesOfCallAt(), psr::CallGraphBase< Derived >::getCallersOf(), psr::ICFGBase< Derived >::getCallGraph(), psr::ICFGBase< Derived >::getCallsFromWithin(), psr::CFGBase< Derived >::getDemangledFunctionName(), psr::CFGBase< Derived >::getExitPointsOf(), psr::ICFGBase< Derived >::getFunction(), psr::CFGBase< Derived >::getFunctionName(), psr::CFGBase< Derived >::getFunctionOf(), psr::ICFGBase< Derived >::getNumCallSites(), psr::CallGraphBase< Derived >::getNumVertexCallSites(), psr::CallGraphBase< Derived >::getNumVertexFunctions(), psr::PointsToInfoBase< Derived >::getPointsToSet(), psr::PointsToInfoBase< Derived >::getPointsToSet(), psr::CFGBase< Derived >::getPredsOf(), psr::ICFGBase< Derived >::getReturnSitesOfCallAt(), psr::CFGBase< Derived >::getSpecialMemberFunctionType(), psr::CFGBase< Derived >::getStartPointsOf(), psr::CFGBase< Derived >::getStatementId(), psr::CFGBase< Derived >::getSuccsOf(), psr::CFGBase< Derived >::isBranchTarget(), psr::CFGBase< Derived >::isCallSite(), psr::CFGBase< Derived >::isExitInst(), psr::CFGBase< Derived >::isFallThroughSuccessor(), psr::CFGBase< Derived >::isFieldLoad(), psr::CFGBase< Derived >::isFieldStore(), psr::CFGBase< Derived >::isHeapAllocatingFunction(), psr::CFGBase< Derived >::isSpecialMemberFunction(), psr::CFGBase< Derived >::isStartPoint(), psr::ICFGBase< Derived >::isVirtualFunctionCall(), psr::PointsToInfoBase< Derived >::mayPointsTo(), psr::PointsToInfoBase< Derived >::mayPointsTo(), psr::SparseCFGBase< Derived >::nextUserOrNull(), psr::CFGBase< Derived >::print(), psr::ICFGBase< Derived >::print(), and psr::ICFGBase< Derived >::printAsJson().
self() [3/3]
template<typename Derived > constexpr const Derived & psr::CRTPBase< Derived >::self () const & inline constexpr protected noexcept
Definition at line 26 of file CRTPUtils.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/CRTPUtils.h