PhASAR: psr::MaybeUniquePtr< T, RequireAlignment > Class Template Reference
psr::MaybeUniquePtr< T, RequireAlignment > Class Template Reference
#include "phasar/Utils/MaybeUniquePtr.h"
Public Member Functions
constexpr MaybeUniquePtr () noexcept=default
constexpr MaybeUniquePtr (T *Pointer, bool Owns=false) noexcept
constexpr MaybeUniquePtr (std::unique_ptr< T > &&Owner) noexcept
template<typename TT >
requires (!std::is_same_v<T, TT> && std::is_convertible_v<TT *, T *>)
constexpr MaybeUniquePtr (std::unique_ptr< TT > &&Owner) noexcept
constexpr MaybeUniquePtr (MaybeUniquePtr &&Other) noexcept
constexpr void swap (MaybeUniquePtr &Other) noexcept
constexpr MaybeUniquePtr & operator= (MaybeUniquePtr &&Other) noexcept
constexpr MaybeUniquePtr & operator= (std::unique_ptr< T > &&Owner) noexcept
template<typename TT >
requires (!std::is_same_v<T, TT> && std::is_convertible_v<TT *, T *>)
constexpr MaybeUniquePtr & operator= (std::unique_ptr< TT > &&Owner) noexcept
MaybeUniquePtr (const MaybeUniquePtr &)=delete
MaybeUniquePtr & operator= (const MaybeUniquePtr &)=delete
constexpr ~MaybeUniquePtr ()
constexpr T * get () const noexcept
constexpr T * operator-> () const noexcept
constexpr T & operator* () const noexcept
constexpr T * release () noexcept
constexpr void reset () noexcept
template<typename TT >
constexpr void reset (MaybeUniquePtr< TT > &&Other) noexcept
template<typename TT >
constexpr void reset (std::unique_ptr< TT > &&Other) noexcept
constexpr bool owns () const noexcept
constexpr operator bool () const noexcept
Friends
constexpr friend void swap (MaybeUniquePtr &LHS, MaybeUniquePtr &RHS) noexcept
constexpr friend bool operator== (const MaybeUniquePtr &LHS, const MaybeUniquePtr &RHS) noexcept
constexpr friend bool operator!= (const MaybeUniquePtr &LHS, const MaybeUniquePtr &RHS) noexcept
constexpr friend bool operator== (const MaybeUniquePtr &LHS, const T *RHS) noexcept
constexpr friend bool operator!= (const MaybeUniquePtr &LHS, const T *RHS) noexcept
constexpr friend bool operator== (const T *LHS, const MaybeUniquePtr &RHS) noexcept
constexpr friend bool operator!= (const T *LHS, const MaybeUniquePtr &RHS) noexcept
Detailed Description
template<typename T, bool RequireAlignment = false>
class psr::MaybeUniquePtr< T, RequireAlignment >
A smart-pointer, similar to std::unique_ptr, that can optionally own an object.
Template Parameters
T The pointee type
RequireAlignment If true, the datastructure only works if alignof(T) > 1 holds. Enables incomplete T types
Definition at line 62 of file MaybeUniquePtr.h.
Constructor & Destructor Documentation
MaybeUniquePtr() [1/6]
template<typename T , bool RequireAlignment = false> constexpr psr::MaybeUniquePtr< T, RequireAlignment >::MaybeUniquePtr () constexpr default noexcept
MaybeUniquePtr() [2/6]
template<typename T , bool RequireAlignment = false> constexpr psr::MaybeUniquePtr< T, RequireAlignment >::MaybeUniquePtr (T * Pointer, bool Owns = false) inline constexpr noexcept
Definition at line 69 of file MaybeUniquePtr.h.
MaybeUniquePtr() [3/6]
template<typename T , bool RequireAlignment = false> constexpr psr::MaybeUniquePtr< T, RequireAlignment >::MaybeUniquePtr (std::unique_ptr< T > && Owner) inline constexpr noexcept
Definition at line 73 of file MaybeUniquePtr.h.
MaybeUniquePtr() [4/6]
template<typename T , bool RequireAlignment = false> template<typename TT > requires (!std::is_same_v<T, TT> && std::is_convertible_v<TT *, T *>) constexpr psr::MaybeUniquePtr< T, RequireAlignment >::MaybeUniquePtr (std::unique_ptr< TT > && Owner) inline constexpr noexcept
Definition at line 78 of file MaybeUniquePtr.h.
MaybeUniquePtr() [5/6]
template<typename T , bool RequireAlignment = false> constexpr psr::MaybeUniquePtr< T, RequireAlignment >::MaybeUniquePtr (MaybeUniquePtr< T, RequireAlignment > && Other) inline constexpr noexcept
Definition at line 81 of file MaybeUniquePtr.h.
MaybeUniquePtr() [6/6]
template<typename T , bool RequireAlignment = false> psr::MaybeUniquePtr< T, RequireAlignment >::MaybeUniquePtr (const MaybeUniquePtr< T, RequireAlignment > &) delete
~MaybeUniquePtr()
template<typename T , bool RequireAlignment = false> constexpr psr::MaybeUniquePtr< T, RequireAlignment >::~MaybeUniquePtr () inline constexpr
Definition at line 123 of file MaybeUniquePtr.h.
Member Function Documentation
get()
template<typename T , bool RequireAlignment = false> constexpr T * psr::MaybeUniquePtr< T, RequireAlignment >::get () const inline constexpr noexcept
Definition at line 130 of file MaybeUniquePtr.h.
Referenced by psr::LLVMProjectIRDB::getModule().
operator bool()
template<typename T , bool RequireAlignment = false> constexpr psr::MaybeUniquePtr< T, RequireAlignment >::operator bool () const inline explicit constexpr noexcept
Definition at line 193 of file MaybeUniquePtr.h.
operator*()
template<typename T , bool RequireAlignment = false> constexpr T & psr::MaybeUniquePtr< T, RequireAlignment >::operator* () const inline constexpr noexcept
Definition at line 134 of file MaybeUniquePtr.h.
operator->()
template<typename T , bool RequireAlignment = false> constexpr T * psr::MaybeUniquePtr< T, RequireAlignment >::operator-> () const inline constexpr noexcept
Definition at line 132 of file MaybeUniquePtr.h.
operator=() [1/4]
template<typename T , bool RequireAlignment = false> MaybeUniquePtr & psr::MaybeUniquePtr< T, RequireAlignment >::operator= (const MaybeUniquePtr< T, RequireAlignment > &) delete
operator=() [2/4]
template<typename T , bool RequireAlignment = false> constexpr MaybeUniquePtr & psr::MaybeUniquePtr< T, RequireAlignment >::operator= (MaybeUniquePtr< T, RequireAlignment > && Other) inline constexpr noexcept
Definition at line 95 of file MaybeUniquePtr.h.
operator=() [3/4]
template<typename T , bool RequireAlignment = false> constexpr MaybeUniquePtr & psr::MaybeUniquePtr< T, RequireAlignment >::operator= (std::unique_ptr< T > && Owner) inline constexpr noexcept
Definition at line 100 of file MaybeUniquePtr.h.
References psr::MaybeUniquePtr< T, RequireAlignment >::release().
operator=() [4/4]
template<typename T , bool RequireAlignment = false> template<typename TT > requires (!std::is_same_v<T, TT> && std::is_convertible_v<TT *, T *>) constexpr MaybeUniquePtr & psr::MaybeUniquePtr< T, RequireAlignment >::operator= (std::unique_ptr< TT > && Owner) inline constexpr noexcept
Definition at line 111 of file MaybeUniquePtr.h.
References psr::MaybeUniquePtr< T, RequireAlignment >::release().
owns()
template<typename T , bool RequireAlignment = false> constexpr bool psr::MaybeUniquePtr< T, RequireAlignment >::owns () const inline constexpr noexcept
Definition at line 161 of file MaybeUniquePtr.h.
release()
template<typename T , bool RequireAlignment = false> constexpr T * psr::MaybeUniquePtr< T, RequireAlignment >::release () inline constexpr noexcept
Definition at line 139 of file MaybeUniquePtr.h.
Referenced by psr::MaybeUniquePtr< T, RequireAlignment >::operator=(), and psr::MaybeUniquePtr< T, RequireAlignment >::operator=().
reset() [1/3]
template<typename T , bool RequireAlignment = false> constexpr void psr::MaybeUniquePtr< T, RequireAlignment >::reset () inline constexpr noexcept
Definition at line 144 of file MaybeUniquePtr.h.
reset() [2/3]
template<typename T , bool RequireAlignment = false> template<typename TT > constexpr void psr::MaybeUniquePtr< T, RequireAlignment >::reset (MaybeUniquePtr< TT > && Other) inline constexpr noexcept
Definition at line 152 of file MaybeUniquePtr.h.
reset() [3/3]
template<typename T , bool RequireAlignment = false> template<typename TT > constexpr void psr::MaybeUniquePtr< T, RequireAlignment >::reset (std::unique_ptr< TT > && Other) inline constexpr noexcept
Definition at line 157 of file MaybeUniquePtr.h.
swap()
template<typename T , bool RequireAlignment = false> constexpr void psr::MaybeUniquePtr< T, RequireAlignment >::swap (MaybeUniquePtr< T, RequireAlignment > & Other) inline constexpr noexcept
Definition at line 86 of file MaybeUniquePtr.h.
Friends And Related Symbol Documentation
operator!= [1/3]
template<typename T , bool RequireAlignment = false> constexpr friend bool operator!= (const MaybeUniquePtr< T, RequireAlignment > & LHS, const MaybeUniquePtr< T, RequireAlignment > & RHS) friend
Definition at line 170 of file MaybeUniquePtr.h.
operator!= [2/3]
template<typename T , bool RequireAlignment = false> constexpr friend bool operator!= (const MaybeUniquePtr< T, RequireAlignment > & LHS, const T * RHS) friend
Definition at line 179 of file MaybeUniquePtr.h.
operator!= [3/3]
template<typename T , bool RequireAlignment = false> constexpr friend bool operator!= (const T * LHS, const MaybeUniquePtr< T, RequireAlignment > & RHS) friend
Definition at line 188 of file MaybeUniquePtr.h.
operator== [1/3]
template<typename T , bool RequireAlignment = false> constexpr friend bool operator== (const MaybeUniquePtr< T, RequireAlignment > & LHS, const MaybeUniquePtr< T, RequireAlignment > & RHS) friend
Definition at line 166 of file MaybeUniquePtr.h.
operator== [2/3]
template<typename T , bool RequireAlignment = false> constexpr friend bool operator== (const MaybeUniquePtr< T, RequireAlignment > & LHS, const T * RHS) friend
Definition at line 175 of file MaybeUniquePtr.h.
operator== [3/3]
template<typename T , bool RequireAlignment = false> constexpr friend bool operator== (const T * LHS, const MaybeUniquePtr< T, RequireAlignment > & RHS) friend
Definition at line 184 of file MaybeUniquePtr.h.
swap
template<typename T , bool RequireAlignment = false> constexpr friend void swap (MaybeUniquePtr< T, RequireAlignment > & LHS, MaybeUniquePtr< T, RequireAlignment > & RHS) friend
Definition at line 90 of file MaybeUniquePtr.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/MaybeUniquePtr.h