PhASAR: psr::IDESolver< AnalysisDomainTy, Container > Class Template Reference
psr::IDESolver< AnalysisDomainTy, Container > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/IDESolver.h"
Public Types
using ProblemTy = IDETabulationProblem< AnalysisDomainTy, Container >
using container_type = typename ProblemTy::container_type
using FlowFunctionPtrType = typename ProblemTy::FlowFunctionPtrType
using l_t = typename AnalysisDomainTy::l_t
using n_t = typename AnalysisDomainTy::n_t
using i_t = typename AnalysisDomainTy::i_t
using d_t = typename AnalysisDomainTy::d_t
using f_t = typename AnalysisDomainTy::f_t
using t_t = typename AnalysisDomainTy::t_t
using v_t = typename AnalysisDomainTy::v_t
Public Member Functions
template<typename I >
IDESolver (IDETabulationProblem< AnalysisDomainTy, Container > &Problem, const I *ICF)
IDESolver (IDETabulationProblem< AnalysisDomainTy, Container > *Problem, const i_t *ICF)
IDESolver (const IDESolver &)=delete
IDESolver & operator= (const IDESolver &)=delete
IDESolver (IDESolver &&)=delete
IDESolver & operator= (IDESolver &&)=delete
virtual ~IDESolver ()=default
nlohmann::json getAsJson ()
l_t resultAt (n_t Stmt, d_t Value)
Returns the L-type result for the given value at the given statement.
template<typename NTy = n_t>
std::enable_if_t< std::is_same_v< std::remove_reference_t< NTy >, llvm::Instruction * >, l_t > resultAtInLLVMSSA (NTy Stmt, d_t Value)
virtual std::unordered_map< d_t, l_t > resultsAt (n_t Stmt, bool StripZero=false)
template<typename NTy = n_t>
std::enable_if_t< std::is_same_v< std::remove_reference_t< NTy >, llvm::Instruction * >, std::unordered_map< d_t, l_t > > resultsAtInLLVMSSA (NTy Stmt, bool StripZero=false)
virtual void emitTextReport (llvm::raw_ostream &OS=llvm::outs())
virtual void emitGraphicalReport (llvm::raw_ostream &OS=llvm::outs())
void dumpResults (llvm::raw_ostream &OS=llvm::outs())
void dumpAllInterPathEdges ()
void dumpAllIntraPathEdges ()
SolverResults< n_t, d_t, l_t > getSolverResults () noexcept
OwningSolverResults< n_t, d_t, l_t > consumeSolverResults () noexcept(std::is_nothrow_move_constructible_v< d_t >)
EdgeFunctionStats getEdgeFunctionStatistics () const
void printEdgeFunctionStatistics (llvm::raw_ostream &OS=llvm::outs()) const
void enableESGAsDot ()
void emitESGAsDot (llvm::raw_ostream &OS=llvm::outs(), llvm::StringRef DotConfigDir=PhasarConfig::PhasarDirectory())
Public Member Functions inherited from psr::IDESolverAPIMixin< Derived >
bool initialize ()
bool next ()
bool nextN (size_t MaxNumIterations)
decltype(auto) finalize () &
decltype(auto) finalize () &&
decltype(auto) solve () &
decltype(auto) solve () &&
decltype(auto) continueSolving () &
decltype(auto) continueSolving () &&
template<typename CancellationRequest , typename = std::enable_if_t< std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>>>
auto solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &
template<typename CancellationRequest , typename = std::enable_if_t< std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>>>
auto solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &&
template<typename CancellationRequest , typename = std::enable_if_t< std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>>>
auto continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{ 1}) &
template<typename CancellationRequest , typename = std::enable_if_t< std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>>>
auto continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{ 1}) &&
auto solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &
auto solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &&
auto continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &
auto continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &&
auto solveWithAsyncCancellation (std::atomic_bool &IsCancelled) &
auto solveWithAsyncCancellation (std::atomic_bool &IsCancelled) &&
auto continueWithAsyncCancellation (std::atomic_bool &IsCancelled) &
auto continueWithAsyncCancellation (std::atomic_bool &IsCancelled) &&
Protected Member Functions
Nullable< n_t > getNextUserOrNull (ByConstRef< f_t > Fun, ByConstRef< d_t > d3, ByConstRef< n_t > n)
virtual void processCall (const PathEdge< n_t, d_t > Edge)
virtual void processNormalFlow (PathEdge< n_t, d_t > Edge)
void propagateValueAtStart (const std::pair< n_t, d_t > NAndD, n_t Stmt)
void propagateValueAtCall (const std::pair< n_t, d_t > NAndD, n_t Stmt)
void propagateValue (n_t NHashN, d_t NHashD, const l_t &L)
l_t val (n_t NHashN, d_t NHashD)
void setVal (n_t NHashN, d_t NHashD, l_t L)
EdgeFunction< l_t > jumpFunction (const PathEdge< n_t, d_t > Edge)
void addEndSummary (n_t SP, d_t d1, n_t eP, d_t d2, EdgeFunction< l_t > f)
void pathEdgeProcessingTask (PathEdge< n_t, d_t > Edge)
void valuePropagationTask (std::pair< n_t, d_t > NAndD)
void valueComputationTask (const std::vector< n_t > &Values)
virtual void saveEdges (n_t SourceNode, n_t SinkStmt, d_t SourceVal, const container_type &DestVals, ESGEdgeKind Kind)
void submitInitialValues ()
void computeValues ()
Computes the final values for edge functions.
void submitInitialSeeds ()
virtual void processExit (const PathEdge< n_t, d_t > Edge)
void propagteUnbalancedReturnFlow (n_t RetSiteC, d_t TargetVal, EdgeFunction< l_t > EdgeFunc, n_t)
d_t restoreContextOnReturnedFact (n_t, d_t, d_t d5)
container_type computeNormalFlowFunction (const FlowFunctionPtrType &FlowFunc, d_t, d_t d2)
container_type computeSummaryFlowFunction (const FlowFunctionPtrType &SummaryFlowFunction, d_t, d_t d2)
container_type computeCallFlowFunction (const FlowFunctionPtrType &CallFlowFunction, d_t, d_t d2)
container_type computeCallToReturnFlowFunction (const FlowFunctionPtrType &CallToReturnFlowFunction, d_t, d_t d2)
container_type computeReturnFlowFunction (const FlowFunctionPtrType &RetFlowFunction, d_t, d_t d2, n_t, const Container &)
void propagate (d_t SourceVal, n_t Target, d_t TargetVal, EdgeFunction< l_t > f)
l_t joinValueAt (n_t, d_t, l_t Curr, l_t NewVal)
std::set< typename Table< n_t, d_t, EdgeFunction< l_t > >::Cell > endSummary (n_t SP, d_t d3)
std::map< n_t, container_type > incoming (d_t d1, n_t SP)
void addIncoming (n_t SP, d_t d3, n_t n, d_t d2)
void printIncomingTab () const
void printEndSummaryTab () const
void printComputedPathEdges ()
void computeAndPrintStatistics ()
Computes and prints statistics of the analysis run, e.g. number of generated/killed facts, number of summary-reuses etc.
Detailed Description
template<typename AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>>
class psr::IDESolver< AnalysisDomainTy, Container >
Solves the given IDETabulationProblem as described in the 1996 paper by Sagiv, Horwitz and Reps. To solve the problem, call solve(). Results can then be queried by using resultAt() and resultsAt().
Definition at line 72 of file IDESolver.h.
Member Typedef Documentation
container_type
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::container_type = typename ProblemTy::container_type
Definition at line 78 of file IDESolver.h.
d_t
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::d_t = typename AnalysisDomainTy::d_t
Definition at line 84 of file IDESolver.h.
f_t
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::f_t = typename AnalysisDomainTy::f_t
Definition at line 85 of file IDESolver.h.
FlowFunctionPtrType
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::FlowFunctionPtrType = typename ProblemTy::FlowFunctionPtrType
Definition at line 79 of file IDESolver.h.
i_t
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::i_t = typename AnalysisDomainTy::i_t
Definition at line 83 of file IDESolver.h.
l_t
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::l_t = typename AnalysisDomainTy::l_t
Definition at line 81 of file IDESolver.h.
n_t
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::n_t = typename AnalysisDomainTy::n_t
Definition at line 82 of file IDESolver.h.
ProblemTy
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::ProblemTy = IDETabulationProblem<AnalysisDomainTy, Container>
Definition at line 77 of file IDESolver.h.
t_t
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::t_t = typename AnalysisDomainTy::t_t
Definition at line 86 of file IDESolver.h.
v_t
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> using psr::IDESolver< AnalysisDomainTy, Container >::v_t = typename AnalysisDomainTy::v_t
Definition at line 87 of file IDESolver.h.
Constructor & Destructor Documentation
IDESolver() [1/4]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> template<typename I > psr::IDESolver< AnalysisDomainTy, Container >::IDESolver (IDETabulationProblem< AnalysisDomainTy, Container > & Problem, const I * ICF) inline
Definition at line 90 of file IDESolver.h.
IDESolver() [2/4]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::IDESolver< AnalysisDomainTy, Container >::IDESolver (IDETabulationProblem< AnalysisDomainTy, Container > * Problem, const i_t * ICF) inline
Definition at line 109 of file IDESolver.h.
IDESolver() [3/4]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::IDESolver< AnalysisDomainTy, Container >::IDESolver (const IDESolver< AnalysisDomainTy, Container > &) delete
IDESolver() [4/4]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::IDESolver< AnalysisDomainTy, Container >::IDESolver (IDESolver< AnalysisDomainTy, Container > &&) delete
~IDESolver()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual psr::IDESolver< AnalysisDomainTy, Container >::~IDESolver () virtual default
Member Function Documentation
addEndSummary()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::addEndSummary (n_t SP, d_t d1, n_t eP, d_t d2, EdgeFunction< l_t > f) inline protected
Definition at line 751 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processExit().
addIncoming()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::addIncoming (n_t SP, d_t d3, n_t n, d_t d2) inline protected
Definition at line 1277 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall().
computeAndPrintStatistics()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::computeAndPrintStatistics () inline protected
Computes and prints statistics of the analysis run, e.g. number of generated/killed facts, number of summary-reuses etc.
The invariant for computing the number of generated (gen) and killed (kill) facts: (1) Valid facts at the last statement <= gen - kill (2) gen >= kill
The total number of valid facts can be smaller than the difference of generated and killed facts, due to set semantics, i.e., a fact can be generated multiple times but appears only once.
Zero value is not counted!
Definition at line 1394 of file IDESolver.h.
References psr::Core, psr::DToString(), psr::Full, GET_COUNTER, IF_LOG_LEVEL_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, PHASAR_LOG_LEVEL, and PRINT_TIMER.
computeCallFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> container_type psr::IDESolver< AnalysisDomainTy, Container >::computeCallFlowFunction (const FlowFunctionPtrType & CallFlowFunction, d_t , d_t d2) inline protected
Computes the call flow function for the given call-site abstraction
Parameters
callFlowFunction The call flow function to compute
d1 The abstraction at the current method's start node.
d2 The abstraction at the call site
Returns
The set of caller-side abstractions at the callee's start node
Definition at line 1147 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall().
computeCallToReturnFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> container_type psr::IDESolver< AnalysisDomainTy, Container >::computeCallToReturnFlowFunction (const FlowFunctionPtrType & CallToReturnFlowFunction, d_t , d_t d2) inline protected
Computes the call-to-return flow function for the given call-site abstraction
Parameters
callToReturnFlowFunction The call-to-return flow function to compute
d1 The abstraction at the current method's start node.
d2 The abstraction at the call site
Returns
The set of caller-side abstractions at the return site
Definition at line 1160 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall().
computeNormalFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> container_type psr::IDESolver< AnalysisDomainTy, Container >::computeNormalFlowFunction (const FlowFunctionPtrType & FlowFunc, d_t , d_t d2) inline protected
Computes the normal flow function for the given set of start and end abstractions-
Parameters
flowFunction The normal flow function to compute
d1 The abstraction at the method's start node
d2 The abstraction at the current node
Returns
The set of abstractions at the successor node
Definition at line 1129 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow().
computeReturnFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> container_type psr::IDESolver< AnalysisDomainTy, Container >::computeReturnFlowFunction (const FlowFunctionPtrType & RetFlowFunction, d_t , d_t d2, n_t , const Container &) inline protected
Computes the return flow function for the given set of caller-side abstractions.
Parameters
retFunction The return flow function to compute
d1 The abstraction at the beginning of the callee
d2 The abstraction at the exit node in the callee
callSite The call site
callerSideDs The abstractions at the call site
Returns
The set of caller-side abstractions at the return site
Definition at line 1175 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall(), and psr::IDESolver< AnalysisDomainTy, Container >::processExit().
computeSummaryFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> container_type psr::IDESolver< AnalysisDomainTy, Container >::computeSummaryFlowFunction (const FlowFunctionPtrType & SummaryFlowFunction, d_t , d_t d2) inline protected
Definition at line 1135 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall().
computeValues()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::computeValues () inline protected
Computes the final values for edge functions.
Definition at line 870 of file IDESolver.h.
References PHASAR_LOG_LEVEL, psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues(), psr::IDESolver< AnalysisDomainTy, Container >::valueComputationTask(), and psr::IDESolver< AnalysisDomainTy, Container >::valuePropagationTask().
consumeSolverResults()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> OwningSolverResults< n_t, d_t, l_t > psr::IDESolver< AnalysisDomainTy, Container >::consumeSolverResults () inline noexcept
Moves the computed solver-results out of this solver such that the solver can be destroyed without that the analysis results are lost. Do not call any function (including getSolverResults()) on this IDESolver instance after that.
Definition at line 276 of file IDESolver.h.
dumpAllInterPathEdges()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::dumpAllInterPathEdges () inline
Definition at line 221 of file IDESolver.h.
dumpAllIntraPathEdges()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::dumpAllIntraPathEdges () inline
Definition at line 241 of file IDESolver.h.
dumpResults()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::dumpResults (llvm::raw_ostream & OS = llvm::outs()) inline
Definition at line 217 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults().
emitESGAsDot()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::emitESGAsDot (llvm::raw_ostream & OS = llvm::outs(), llvm::StringRef DotConfigDir = PhasarConfig::PhasarDirectory()) inline
Definition at line 1563 of file IDESolver.h.
References psr::DToString(), psr::DOTConfig::importDOTConfig(), psr::NToString(), PHASAR_LOG_LEVEL, and psr::to_string().
emitGraphicalReport()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDESolver< AnalysisDomainTy, Container >::emitGraphicalReport (llvm::raw_ostream & OS = llvm::outs()) inline virtual
Definition at line 213 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults().
emitTextReport()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDESolver< AnalysisDomainTy, Container >::emitTextReport (llvm::raw_ostream & OS = llvm::outs()) inline virtual
Definition at line 209 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults().
enableESGAsDot()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::enableESGAsDot () inline
Definition at line 1560 of file IDESolver.h.
References psr::IFDSIDESolverConfig::setEmitESG().
endSummary()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> std::set< typename Table< n_t, d_t, EdgeFunction< l_t > >::Cell > psr::IDESolver< AnalysisDomainTy, Container >::endSummary (n_t SP, d_t d3) inline protected
Definition at line 1260 of file IDESolver.h.
References psr::Core.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall().
getAsJson()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> nlohmann::json psr::IDESolver< AnalysisDomainTy, Container >::getAsJson () inline
Definition at line 120 of file IDESolver.h.
References psr::Table< R, C, V >::cellSet(), psr::DToString(), psr::LToString(), and psr::NToString().
getEdgeFunctionStatistics()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> EdgeFunctionStats psr::IDESolver< AnalysisDomainTy, Container >::getEdgeFunctionStatistics () const inline
Definition at line 281 of file IDESolver.h.
References psr::EdgeFunction< L >::depth(), and psr::EdgeFunction< L >::getAllocationPolicy().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::printEdgeFunctionStatistics().
getNextUserOrNull()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> Nullable< n_t > psr::IDESolver< AnalysisDomainTy, Container >::getNextUserOrNull (ByConstRef< f_t > Fun, ByConstRef< d_t > d3, ByConstRef< n_t > n) inline protected
Definition at line 357 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::processExit(), and psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow().
getSolverResults()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> SolverResults< n_t, d_t, l_t > psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults () inline noexcept
Returns a view into the computed solver-results.
NOTE: The SolverResults store a reference into this IDESolver, so its lifetime is also bound to the lifetime of this solver. If you want to use the solverResults beyond the lifetime of this solver, use comsumeSolverResults() instead.
Definition at line 267 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::dumpResults(), psr::IDESolver< AnalysisDomainTy, Container >::emitGraphicalReport(), psr::IDESolver< AnalysisDomainTy, Container >::emitTextReport(), psr::IDESolver< AnalysisDomainTy, Container >::resultAt(), psr::IDESolver< AnalysisDomainTy, Container >::resultAtInLLVMSSA(), psr::IDESolver< AnalysisDomainTy, Container >::resultsAt(), and psr::IDESolver< AnalysisDomainTy, Container >::resultsAtInLLVMSSA().
incoming()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> std::map< n_t, container_type > psr::IDESolver< AnalysisDomainTy, Container >::incoming (d_t d1, n_t SP) inline protected
Definition at line 1273 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processExit().
joinValueAt()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> l_t psr::IDESolver< AnalysisDomainTy, Container >::joinValueAt (n_t , d_t , l_t Curr, l_t NewVal) inline protected
Definition at line 1255 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::propagateValue().
jumpFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> EdgeFunction< l_t > psr::IDESolver< AnalysisDomainTy, Container >::jumpFunction (const PathEdge< n_t, d_t > Edge) inline protected
Definition at line 723 of file IDESolver.h.
References psr::DToString(), IF_LOG_LEVEL_ENABLED, psr::NToString(), and PHASAR_LOG_LEVEL.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::processExit(), and psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow().
operator=() [1/2]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> IDESolver & psr::IDESolver< AnalysisDomainTy, Container >::operator= (const IDESolver< AnalysisDomainTy, Container > &) delete
operator=() [2/2]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> IDESolver & psr::IDESolver< AnalysisDomainTy, Container >::operator= (IDESolver< AnalysisDomainTy, Container > &&) delete
pathEdgeProcessingTask()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::pathEdgeProcessingTask (PathEdge< n_t, d_t > Edge) inline protected
Definition at line 759 of file IDESolver.h.
References psr::DToString(), psr::Full, IF_LOG_LEVEL_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, PHASAR_LOG_LEVEL, psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::processExit(), and psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::propagate().
printComputedPathEdges()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::printComputedPathEdges () inline protected
Definition at line 1321 of file IDESolver.h.
References psr::DToString(), and psr::NToString().
printEdgeFunctionStatistics()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::printEdgeFunctionStatistics (llvm::raw_ostream & OS = llvm::outs()) const inline
Definition at line 352 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getEdgeFunctionStatistics().
printEndSummaryTab()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::printEndSummaryTab () const inline protected
Definition at line 1299 of file IDESolver.h.
References psr::DToString(), IF_LOG_LEVEL_ENABLED, psr::NToString(), and PHASAR_LOG_LEVEL.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processExit().
printIncomingTab()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::printIncomingTab () const inline protected
Definition at line 1281 of file IDESolver.h.
References psr::DToString(), IF_LOG_LEVEL_ENABLED, psr::NToString(), and PHASAR_LOG_LEVEL.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processExit().
processCall()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDESolver< AnalysisDomainTy, Container >::processCall (const PathEdge< n_t, d_t > Edge) inline protected virtual
Lines 13-20 of the algorithm; processing a call site in the caller's context.
For each possible callee, registers incoming call edges. Also propagates call-to-return flows and summarized callee flows within the caller.
The following cases must be considered and handled:
1. Process as usual and just process the call
2. Create a new summary for that function (which shall be done
  by the problem)
3. Just use an existing summary provided by the problem
4. If a special function is called, use a special summary
  function
Parameters
edge an edge whose target node resembles a method call
Definition at line 383 of file IDESolver.h.
References ADD_TO_HISTOGRAM, psr::IDESolver< AnalysisDomainTy, Container >::addIncoming(), psr::Call, psr::CallToRet, psr::IDESolver< AnalysisDomainTy, Container >::computeCallFlowFunction(), psr::IDESolver< AnalysisDomainTy, Container >::computeCallToReturnFlowFunction(), psr::IDESolver< AnalysisDomainTy, Container >::computeReturnFlowFunction(), psr::IDESolver< AnalysisDomainTy, Container >::computeSummaryFlowFunction(), psr::DToString(), psr::IFDSIDESolverConfig::emitESG(), psr::IDESolver< AnalysisDomainTy, Container >::endSummary(), psr::Full, psr::IDESolver< AnalysisDomainTy, Container >::getNextUserOrNull(), IF_LOG_LEVEL_ENABLED, INC_COUNTER, psr::IDESolver< AnalysisDomainTy, Container >::jumpFunction(), psr::NToString(), PAMM_GET_INSTANCE, PHASAR_LOG_LEVEL, PSR_FWD, psr::IDESolver< AnalysisDomainTy, Container >::restoreContextOnReturnedFact(), psr::Ret, psr::IDESolver< AnalysisDomainTy, Container >::saveEdges(), psr::SkipUnknownFn, psr::Summary, and psr::unwrapNullable().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::pathEdgeProcessingTask().
processExit()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDESolver< AnalysisDomainTy, Container >::processExit (const PathEdge< n_t, d_t > Edge) inline protected virtual
Lines 21-32 of the algorithm.
Stores callee-side summaries. Also, at the side of the caller, propagates intra-procedural flows to return sites using those newly computed summaries.
Parameters
edge an edge whose target node resembles a method exit
TODO: Add a check for "d1 is seed in functionOf(n)"
Definition at line 939 of file IDESolver.h.
References ADD_TO_HISTOGRAM, psr::IDESolver< AnalysisDomainTy, Container >::addEndSummary(), psr::IDESolver< AnalysisDomainTy, Container >::computeReturnFlowFunction(), psr::IFDSIDESolverConfig::emitESG(), psr::IFDSIDESolverConfig::followReturnsPastSeeds(), psr::Full, psr::IDESolver< AnalysisDomainTy, Container >::getNextUserOrNull(), INC_COUNTER, psr::IDESolver< AnalysisDomainTy, Container >::incoming(), psr::IDESolver< AnalysisDomainTy, Container >::jumpFunction(), psr::NToString(), PAMM_GET_INSTANCE, PHASAR_LOG_LEVEL, psr::IDESolver< AnalysisDomainTy, Container >::printEndSummaryTab(), psr::IDESolver< AnalysisDomainTy, Container >::printIncomingTab(), psr::IDESolver< AnalysisDomainTy, Container >::propagteUnbalancedReturnFlow(), PSR_FWD, psr::IDESolver< AnalysisDomainTy, Container >::restoreContextOnReturnedFact(), psr::Ret, psr::IDESolver< AnalysisDomainTy, Container >::saveEdges(), and psr::unwrapNullable().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::pathEdgeProcessingTask().
processNormalFlow()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow (PathEdge< n_t, d_t > Edge) inline protected virtual
Lines 33-37 of the algorithm. Simply propagate normal, intra-procedural flows.
Parameters
edge
Definition at line 596 of file IDESolver.h.
References ADD_TO_HISTOGRAM, psr::IDESolver< AnalysisDomainTy, Container >::computeNormalFlowFunction(), psr::IFDSIDESolverConfig::emitESG(), psr::Full, psr::IDESolver< AnalysisDomainTy, Container >::getNextUserOrNull(), INC_COUNTER, psr::IDESolver< AnalysisDomainTy, Container >::jumpFunction(), psr::Normal, psr::NToString(), PAMM_GET_INSTANCE, PHASAR_LOG_LEVEL, PSR_FWD, psr::IDESolver< AnalysisDomainTy, Container >::saveEdges(), and psr::unwrapNullable().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::pathEdgeProcessingTask().
propagate()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::propagate (d_t SourceVal, n_t Target, d_t TargetVal, EdgeFunction< l_t > f) inline protected
Propagates the flow further down the exploded super graph, merging any edge function that might already have been computed for TargetVal at Target.
Parameters
SourceVal the source value of the propagated summary edge
Target the target statement
TargetVal the target value at the target statement
f the new edge function computed from (s0,SourceVal) to (Target,TargetVal)
relatedCallSite for call and return flows the related call statement, nullptr otherwise (this value is not used within this implementation but may be useful for subclasses of IDESolver)
isUnbalancedReturn true if this edge is propagating an unbalanced return (this value is not used within this implementation but may be useful for subclasses of IDESolver)
Definition at line 1197 of file IDESolver.h.
References psr::DToString(), IF_LOG_LEVEL_ENABLED, psr::NToString(), psr::IDESolver< AnalysisDomainTy, Container >::pathEdgeProcessingTask(), and PHASAR_LOG_LEVEL.
propagateValue()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::propagateValue (n_t NHashN, d_t NHashD, const l_t & L) inline protected
Definition at line 688 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::joinValueAt(), psr::IDESolver< AnalysisDomainTy, Container >::setVal(), and psr::IDESolver< AnalysisDomainTy, Container >::val().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtCall(), and psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtStart().
propagateValueAtCall()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtCall (const std::pair< n_t, d_t > NAndD, n_t Stmt) inline protected
Definition at line 661 of file IDESolver.h.
References psr::IFDSIDESolverConfig::emitESG(), psr::Full, INC_COUNTER, PAMM_GET_INSTANCE, PHASAR_LOG_LEVEL, psr::IDESolver< AnalysisDomainTy, Container >::propagateValue(), and psr::IDESolver< AnalysisDomainTy, Container >::val().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::valuePropagationTask().
propagateValueAtStart()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtStart (const std::pair< n_t, d_t > NAndD, n_t Stmt) inline protected
Definition at line 640 of file IDESolver.h.
References psr::Full, INC_COUNTER, PAMM_GET_INSTANCE, psr::IDESolver< AnalysisDomainTy, Container >::propagateValue(), and psr::IDESolver< AnalysisDomainTy, Container >::val().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::valuePropagationTask().
propagteUnbalancedReturnFlow()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::propagteUnbalancedReturnFlow (n_t RetSiteC, d_t TargetVal, EdgeFunction< l_t > EdgeFunc, n_t) inline protected
Definition at line 1090 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processExit().
restoreContextOnReturnedFact()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> d_t psr::IDESolver< AnalysisDomainTy, Container >::restoreContextOnReturnedFact (n_t , d_t , d_t d5) inline protected
This method will be called for each incoming edge and can be used to transfer knowledge from the calling edge to the returning edge, without affecting the summary edges at the callee.
Parameters
callSite
d4 Fact stored with the incoming edge, i.e., present at the caller side
d5 Fact that originally should be propagated to the caller.
Returns
Fact that will be propagated to the caller.
Definition at line 1110 of file IDESolver.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall(), and psr::IDESolver< AnalysisDomainTy, Container >::processExit().
resultAt()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> l_t psr::IDESolver< AnalysisDomainTy, Container >::resultAt (n_t Stmt, d_t Value) inline
Returns the L-type result for the given value at the given statement.
Definition at line 152 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults().
resultAtInLLVMSSA()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> template<typename NTy = n_t> std::enable_if_t< std::is_same_v< std::remove_reference_t< NTy >, llvm::Instruction * >, l_t > psr::IDESolver< AnalysisDomainTy, Container >::resultAtInLLVMSSA (NTy Stmt, d_t Value) inline
Returns the L-type result at the given statement for the given data-flow fact while respecting LLVM's SSA semantics.
An example: when a value is loaded and the location loaded from, here variable 'i', is a data-flow fact that holds, then the loaded value '%0' will usually be generated and also holds. However, due to the underlying theory (and respective implementation) this load instruction causes the loaded value to be generated and thus, it will be valid only AFTER the load instruction, i.e., at the successor instruction.
%0 = load i32, i32* i, align 4
This result accessor function returns the results at the successor instruction(s) reflecting that the expression on the left-hand side holds if the expression on the right-hand side holds.
Definition at line 174 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults().
resultsAt()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual std::unordered_map< d_t, l_t > psr::IDESolver< AnalysisDomainTy, Container >::resultsAt (n_t Stmt, bool StripZero = false) inline virtual
Returns the resulting environment for the given statement. The artificial zero value can be automatically stripped. TOP values are never returned.
Definition at line 182 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults().
Referenced by psr::IFDSSolver< AnalysisDomainTy, Container >::ifdsResultsAt(), and psr::IFDSSolver< AnalysisDomainTy, Container >::ifdsResultsAtInLLVMSSA().
resultsAtInLLVMSSA()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> template<typename NTy = n_t> std::enable_if_t< std::is_same_v< std::remove_reference_t< NTy >, llvm::Instruction * >, std::unordered_map< d_t, l_t > > psr::IDESolver< AnalysisDomainTy, Container >::resultsAtInLLVMSSA (NTy Stmt, bool StripZero = false) inline
Returns the data-flow results at the given statement while respecting LLVM's SSA semantics.
An example: when a value is loaded and the location loaded from, here variable 'i', is a data-flow fact that holds, then the loaded value '%0' will usually be generated and also holds. However, due to the underlying theory (and respective implementation) this load instruction causes the loaded value to be generated and thus, it will be valid only AFTER the load instruction, i.e., at the successor instruction.
%0 = load i32, i32* i, align 4
This result accessor function returns the results at the successor instruction(s) reflecting that the expression on the left-hand side holds if the expression on the right-hand side holds.
Definition at line 205 of file IDESolver.h.
References psr::IDESolver< AnalysisDomainTy, Container >::getSolverResults().
saveEdges()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> virtual void psr::IDESolver< AnalysisDomainTy, Container >::saveEdges (n_t SourceNode, n_t SinkStmt, d_t SourceVal, const container_type & DestVals, ESGEdgeKind Kind) inline protected virtual
Definition at line 832 of file IDESolver.h.
References psr::isInterProc(), and psr::IFDSIDESolverConfig::recordEdges().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::processExit(), and psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow().
setVal()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::setVal (n_t NHashN, d_t NHashD, l_t L) inline protected
Definition at line 705 of file IDESolver.h.
References psr::DToString(), IF_LOG_LEVEL_ENABLED, psr::Table< R, C, V >::insert(), psr::LToString(), psr::NToString(), and PHASAR_LOG_LEVEL.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::propagateValue(), psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues(), and psr::IDESolver< AnalysisDomainTy, Container >::valueComputationTask().
submitInitialSeeds()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::submitInitialSeeds () inline protected
Schedules the processing of initial seeds, initiating the analysis. Clients should only call this methods if performing synchronization on their own. Normally, solve() should be called instead.
If statically disabling the logger, Fact and Value are unused. To prevent the copilation to fail with -Werror, add the [[maybe_unused]] attribute
Definition at line 890 of file IDESolver.h.
References psr::InitialSeeds< N, D, L >::addSeed(), psr::Core, psr::InitialSeeds< N, D, L >::countInitialSeeds(), psr::DToString(), psr::InitialSeeds< N, D, L >::getSeeds(), INC_COUNTER, psr::LToString(), psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
submitInitialValues()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues () inline protected
Definition at line 843 of file IDESolver.h.
References psr::DToString(), psr::InitialSeeds< N, D, L >::getSeeds(), psr::LToString(), psr::NToString(), PHASAR_LOG_LEVEL, psr::IDESolver< AnalysisDomainTy, Container >::setVal(), psr::IDESolver< AnalysisDomainTy, Container >::val(), and psr::IDESolver< AnalysisDomainTy, Container >::valuePropagationTask().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::computeValues().
val()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> l_t psr::IDESolver< AnalysisDomainTy, Container >::val (n_t NHashN, d_t NHashD) inline protected
Definition at line 697 of file IDESolver.h.
References psr::Table< R, C, V >::contains(), and psr::Table< R, C, V >::get().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::propagateValue(), psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtCall(), psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtStart(), psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues(), and psr::IDESolver< AnalysisDomainTy, Container >::valueComputationTask().
valueComputationTask()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::valueComputationTask (const std::vector< n_t > & Values) inline protected
Definition at line 810 of file IDESolver.h.
References psr::Full, INC_COUNTER, PAMM_GET_INSTANCE, psr::IDESolver< AnalysisDomainTy, Container >::setVal(), and psr::IDESolver< AnalysisDomainTy, Container >::val().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::computeValues().
valuePropagationTask()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::IDESolver< AnalysisDomainTy, Container >::valuePropagationTask (std::pair< n_t, d_t > NAndD) inline protected
Definition at line 792 of file IDESolver.h.
References psr::InitialSeeds< N, D, L >::containsInitialSeedsFor(), psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtCall(), and psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtStart().
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::computeValues(), and psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/IDESolver.h