PhASAR: psr::PointsToInfoBase< Derived > Class Template Reference
psr::PointsToInfoBase< Derived > Class Template Reference
#include "phasar/Pointer/PointsToInfoBase.h"
Public Types
using v_t = typename PointsToTraits< Derived >::v_t
using n_t = typename PointsToTraits< Derived >::n_t
using o_t = typename PointsToTraits< Derived >::o_t
using PointsToSetTy = typename PointsToTraits< Derived >::PointsToSetTy
using PointsToSetPtrTy = typename PointsToTraits< Derived >::PointsToSetPtrTy
Public Member Functions
o_t asAbstractObject (ByConstRef< v_t > Pointer) const noexcept
Creates an abstract object corresponding to the given pointer.
std::optional< v_t > asPointerOrNull (ByConstRef< o_t > Obj) const noexcept
bool mayPointsTo (ByConstRef< o_t > Pointer, ByConstRef< o_t > Obj, ByConstRef< n_t > AtInstruction) const
bool mayPointsTo (ByConstRef< v_t > Pointer, ByConstRef< o_t > Obj, ByConstRef< n_t > AtInstruction) const
PointsToSetPtrTy getPointsToSet (ByConstRef< o_t > Pointer, ByConstRef< n_t > AtInstruction) const
PointsToSetPtrTy getPointsToSet (ByConstRef< v_t > Pointer, ByConstRef< n_t > AtInstruction) const
Additional Inherited Members
Protected Member Functions inherited from psr::CRTPBase< Derived >
constexpr CRTPBase () noexcept=default
constexpr Derived & self () &noexcept
constexpr Derived && self () &&noexcept
constexpr const Derived & self () const &noexcept
Detailed Description
template<typename Derived>
class psr::PointsToInfoBase< Derived >
Base class of all points-to analysis implementations. Don't use this class directly. For a type-erased variant, use PointsToInfoRef or PointsToInfo.
Definition at line 54 of file PointsToInfoBase.h.
Member Typedef Documentation
n_t
template<typename Derived > using psr::PointsToInfoBase< Derived >::n_t = typename PointsToTraits<Derived>::n_t
Definition at line 60 of file PointsToInfoBase.h.
o_t
template<typename Derived > using psr::PointsToInfoBase< Derived >::o_t = typename PointsToTraits<Derived>::o_t
Definition at line 61 of file PointsToInfoBase.h.
PointsToSetPtrTy
template<typename Derived > using psr::PointsToInfoBase< Derived >::PointsToSetPtrTy = typename PointsToTraits<Derived>::PointsToSetPtrTy
Definition at line 63 of file PointsToInfoBase.h.
PointsToSetTy
template<typename Derived > using psr::PointsToInfoBase< Derived >::PointsToSetTy = typename PointsToTraits<Derived>::PointsToSetTy
Definition at line 62 of file PointsToInfoBase.h.
v_t
template<typename Derived > using psr::PointsToInfoBase< Derived >::v_t = typename PointsToTraits<Derived>::v_t
Definition at line 59 of file PointsToInfoBase.h.
Member Function Documentation
asAbstractObject()
template<typename Derived > o_t psr::PointsToInfoBase< Derived >::asAbstractObject (ByConstRef< v_t > Pointer) const inline noexcept
Creates an abstract object corresponding to the given pointer.
Definition at line 66 of file PointsToInfoBase.h.
References psr::CRTPBase< Derived >::self().
asPointerOrNull()
template<typename Derived > std::optional< v_t > psr::PointsToInfoBase< Derived >::asPointerOrNull (ByConstRef< o_t > Obj) const inline noexcept
Inverse function of asAbstractObject. If Obj does not directly correspond to a pointer, this function may return nullopt.
Definition at line 73 of file PointsToInfoBase.h.
References psr::CRTPBase< Derived >::self().
getPointsToSet() [1/2]
template<typename Derived > PointsToSetPtrTy psr::PointsToInfoBase< Derived >::getPointsToSet (ByConstRef< o_t > Pointer, ByConstRef< n_t > AtInstruction) const inline
Definition at line 90 of file PointsToInfoBase.h.
References psr::CRTPBase< Derived >::self().
getPointsToSet() [2/2]
template<typename Derived > PointsToSetPtrTy psr::PointsToInfoBase< Derived >::getPointsToSet (ByConstRef< v_t > Pointer, ByConstRef< n_t > AtInstruction) const inline
Definition at line 95 of file PointsToInfoBase.h.
References psr::CRTPBase< Derived >::self().
mayPointsTo() [1/2]
template<typename Derived > bool psr::PointsToInfoBase< Derived >::mayPointsTo (ByConstRef< o_t > Pointer, ByConstRef< o_t > Obj, ByConstRef< n_t > AtInstruction) const inline
Definition at line 77 of file PointsToInfoBase.h.
References psr::CRTPBase< Derived >::self().
mayPointsTo() [2/2]
template<typename Derived > bool psr::PointsToInfoBase< Derived >::mayPointsTo (ByConstRef< v_t > Pointer, ByConstRef< o_t > Obj, ByConstRef< n_t > AtInstruction) const inline
Definition at line 82 of file PointsToInfoBase.h.
References psr::CRTPBase< Derived >::self().
The documentation for this class was generated from the following file:
include/phasar/Pointer/PointsToInfoBase.h