PhASAR: psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero > Class Template Reference
psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/FlowEdgeFunctionCacheNG.h"
Public Member Functions
FlowEdgeFunctionCacheNG (ProblemTy &)
void clearFlowFunctions ()
void clear ()
void reserve (size_t NumInsts, size_t NumCalls, size_t NumFuns)
FlowEdgeFunctionCacheStats getStats () const noexcept
void dumpStats (llvm::raw_ostream &OS) const
Public Member Functions inherited from psr::FlowFunctionCache< ProblemTy, AutoAddZero >
FlowFunctionCache () noexcept=default
decltype(auto) getNormalFlowFunction (ProblemTy &Problem, ByConstRef< n_t > Curr, ByConstRef< n_t > Succ, uint64_t CurrSuccId)
decltype(auto) getCallToRetFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< n_t > RetSite, llvm::ArrayRef< f_t > Callees, uint64_t CallRetId)
decltype(auto) getCallFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, uint64_t CSCalleeId)
decltype(auto) getRetFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, ByConstRef< n_t > ExitInst, ByConstRef< n_t > RetSite, uint64_t CSExitId, uint64_t CalleeRSId)
CAUTION: Keep the ID definitions in mind!
decltype(auto) getSummaryFlowFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, uint64_t)
void clear () noexcept
void reserve (size_t NumInsts, size_t NumCalls, size_t NumFuns)
void dumpStats (llvm::raw_ostream &OS) const
FlowFunctionCacheStats getStats () const noexcept
Public Member Functions inherited from psr::EdgeFunctionCache< ProblemTy >
EdgeFunctionCache () noexcept=default
EdgeFunctionPtrType getNormalEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > Curr, ByConstRef< d_t > CurrNode, ByConstRef< n_t > Succ, ByConstRef< d_t > SuccNode, uint64_t CurrSuccId, uint64_t CurrNodeSuccNodeId)
EdgeFunctionPtrType getCallToRetEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > CallNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, llvm::ArrayRef< f_t > Callees, uint64_t CallRetId, uint64_t CallNodeRetNodeId)
EdgeFunctionPtrType getCallEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > SrcNode, ByConstRef< f_t > Callee, ByConstRef< d_t > DestNode, uint64_t CSCalleeId, uint64_t SrcDestNodeId)
EdgeFunctionPtrType getReturnEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, ByConstRef< n_t > ExitInst, ByConstRef< d_t > ExitNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, uint32_t ExitId, uint64_t CSRSId, uint64_t ExitRSNodeId)
EdgeFunctionPtrType getSummaryEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > CallNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, uint64_t CSRSId, uint64_t CSNodeRSNodeId)
void clear ()
void dumpStats (llvm::raw_ostream &OS) const
EdgeFunctionCacheStats getStats () const noexcept
Additional Inherited Members
Public Types inherited from psr::EdgeFunctionCache< ProblemTy >
using EdgeFunctionPtrType = EdgeFunction< l_t >
Detailed Description
template<typename ProblemTy, bool AutoAddZero>
class psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >
Definition at line 13 of file FlowEdgeFunctionCacheNG.h.
Constructor & Destructor Documentation
FlowEdgeFunctionCacheNG()
template<typename ProblemTy , bool AutoAddZero> psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::FlowEdgeFunctionCacheNG (ProblemTy &) inline explicit
Definition at line 17 of file FlowEdgeFunctionCacheNG.h.
Member Function Documentation
clear()
template<typename ProblemTy , bool AutoAddZero> void psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::clear () inline
Definition at line 25 of file FlowEdgeFunctionCacheNG.h.
References psr::EdgeFunctionCache< ProblemTy >::clear(), and psr::FlowFunctionCache< ProblemTy, AutoAddZero >::clear().
clearFlowFunctions()
template<typename ProblemTy , bool AutoAddZero> void psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::clearFlowFunctions () inline
Definition at line 21 of file FlowEdgeFunctionCacheNG.h.
References psr::FlowFunctionCache< ProblemTy, AutoAddZero >::clear().
dumpStats()
template<typename ProblemTy , bool AutoAddZero> void psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::dumpStats (llvm::raw_ostream & OS) const inline
Definition at line 41 of file FlowEdgeFunctionCacheNG.h.
References psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::getStats().
getStats()
template<typename ProblemTy , bool AutoAddZero> FlowEdgeFunctionCacheStats psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::getStats () const inline noexcept
Definition at line 36 of file FlowEdgeFunctionCacheNG.h.
References psr::EdgeFunctionCache< ProblemTy >::getStats(), and psr::FlowFunctionCache< ProblemTy, AutoAddZero >::getStats().
Referenced by psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::dumpStats().
reserve()
template<typename ProblemTy , bool AutoAddZero> void psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::reserve (size_t NumInsts, size_t NumCalls, size_t NumFuns) inline
XXX: reserve edge functions as well, once possible!
Definition at line 30 of file FlowEdgeFunctionCacheNG.h.
References psr::FlowFunctionCache< ProblemTy, AutoAddZero >::reserve().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/FlowEdgeFunctionCacheNG.h