PhASAR: psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator > Class Template Reference
psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator > Class Template Reference
#include "phasar/Utils/EquivalenceClassMap.h"
Classes
class const_iterator
Public Member Functions
EquivalenceClassMapNG () noexcept=default
void reserve (size_t InitialCapacity)
template<typename KK , typename VV >
std::pair< const_iterator, bool > insert (KK &&Key, VV &&Value)
template<typename KK , typename VCtor >
const TValue & getOrInsertLazy (KK &&Key, VCtor &&MakeV)
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator find (const TKey &Ky) const
size_t numEquivalenceClasses () const noexcept
size_t size () const noexcept
Returns the size of the map, i.e., the number of equivalence classes.
bool empty () const noexcept
void clear () noexcept
Detailed Description
template<typename TKey, typename TValue, typename ValueComparator = std::equal_to<TValue>>
class psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >
Definition at line 180 of file EquivalenceClassMap.h.
Constructor & Destructor Documentation
EquivalenceClassMapNG()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::EquivalenceClassMapNG () default noexcept
Member Function Documentation
begin()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> const_iterator psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::begin () const inline noexcept
Definition at line 258 of file EquivalenceClassMap.h.
clear()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> void psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::clear () inline noexcept
Definition at line 284 of file EquivalenceClassMap.h.
empty()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> bool psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::empty () const inline noexcept
Definition at line 282 of file EquivalenceClassMap.h.
end()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> const_iterator psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::end () const inline noexcept
Definition at line 261 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::find().
find()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> const_iterator psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::find (const TKey & Ky) const inline
Definition at line 263 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::end().
getOrInsertLazy()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> template<typename KK , typename VCtor > const TValue & psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::getOrInsertLazy (KK && Key, VCtor && MakeV) inline
Definition at line 249 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::insert().
insert()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> template<typename KK , typename VV > std::pair< const_iterator, bool > psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::insert (KK && Key, VV && Value) inline
Definition at line 235 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::getOrInsertLazy().
numEquivalenceClasses()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> size_t psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::numEquivalenceClasses () const inline noexcept
Definition at line 273 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::size().
reserve()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> void psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::reserve (size_t InitialCapacity) inline
Definition at line 229 of file EquivalenceClassMap.h.
size()
template<typename TKey , typename TValue , typename ValueComparator = std::equal_to<TValue>> size_t psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::size () const inline noexcept
Returns the size of the map, i.e., the number of equivalence classes.
Definition at line 278 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMapNG< TKey, TValue, ValueComparator >::numEquivalenceClasses().
The documentation for this class was generated from the following file:
include/phasar/Utils/EquivalenceClassMap.h