PhASAR: psr::GenericSolverResults< N, D, L > Class Template Reference
psr::GenericSolverResults< N, D, L > Class Template Reference final
A type-erased version of the main functionality of SolverResults. Can be accepted by consumers that don't need deep access to the internals (so, the usual ones). As we have now two kinds of solver-results (SolverResults and IdBasedSolverResults), we need a common way of accessing them.
#include "phasar/DataFlow/IfdsIde/Solver/GenericSolverResults.h"
Public Types
using n_t = N
using d_t = D
using l_t = L
Public Member Functions
template<typename T >
requires (!std::is_same_v<GenericSolverResults, std::decay_t<T>>)
GenericSolverResults (const T &SR) noexcept
l_t resultAt (ByConstRef< n_t > Stmt, ByConstRef< d_t > Node) const
std::unordered_map< d_t, l_t > resultsAt (ByConstRef< n_t > Stmt, bool StripZero=false) const
std::set< d_t > ifdsResultsAt (ByConstRef< n_t > Stmt) const
size_t size () const noexcept
bool containsNode (ByConstRef< n_t > Stmt) const
l_t resultAtInLLVMSSA (const llvm::Instruction *Stmt, ByConstRef< d_t > Node) const
std::unordered_map< d_t, l_t > resultsAtInLLVMSSA (const llvm::Instruction *Stmt, bool StripZero=false) const
void foreachResultEntry (llvm::function_ref< void(std::tuple< n_t, d_t, l_t >)> Handler) const
Detailed Description
template<typename N, typename D, typename L>
class psr::GenericSolverResults< N, D, L >
A type-erased version of the main functionality of SolverResults. Can be accepted by consumers that don't need deep access to the internals (so, the usual ones). As we have now two kinds of solver-results (SolverResults and IdBasedSolverResults), we need a common way of accessing them.
XXX (#734): When upgrading to C++20, create a concept checking valid SolverResults types
Definition at line 29 of file GenericSolverResults.h.
Member Typedef Documentation
d_t
template<typename N , typename D , typename L > using psr::GenericSolverResults< N, D, L >::d_t = D
Definition at line 32 of file GenericSolverResults.h.
l_t
template<typename N , typename D , typename L > using psr::GenericSolverResults< N, D, L >::l_t = L
Definition at line 33 of file GenericSolverResults.h.
n_t
template<typename N , typename D , typename L > using psr::GenericSolverResults< N, D, L >::n_t = N
Definition at line 31 of file GenericSolverResults.h.
Constructor & Destructor Documentation
GenericSolverResults()
template<typename N , typename D , typename L > template<typename T > requires (!std::is_same_v<GenericSolverResults, std::decay_t<T>>) psr::GenericSolverResults< N, D, L >::GenericSolverResults (const T & SR) inline noexcept
NOTE: Don't provide an operator= that constructs a GenericSolverResults from a concrete SolverResults object to prevent issues with object lifetime. Probably that can be mitigated with use of std::launder, but for now, we don't need this complexity
NOTE: We reinterpret the bytes of the Buffer as type, so it better be properly aligned
Definition at line 42 of file GenericSolverResults.h.
Member Function Documentation
containsNode()
template<typename N , typename D , typename L > bool psr::GenericSolverResults< N, D, L >::containsNode (ByConstRef< n_t > Stmt) const inline
Definition at line 88 of file GenericSolverResults.h.
foreachResultEntry()
template<typename N , typename D , typename L > void psr::GenericSolverResults< N, D, L >::foreachResultEntry (llvm::function_ref< void(std::tuple< n_t, d_t, l_t >)> Handler) const inline
Definition at line 114 of file GenericSolverResults.h.
ifdsResultsAt()
template<typename N , typename D , typename L > std::set< d_t > psr::GenericSolverResults< N, D, L >::ifdsResultsAt (ByConstRef< n_t > Stmt) const inline
Definition at line 75 of file GenericSolverResults.h.
resultAt()
template<typename N , typename D , typename L > l_t psr::GenericSolverResults< N, D, L >::resultAt (ByConstRef< n_t > Stmt, ByConstRef< d_t > Node) const inline
Definition at line 64 of file GenericSolverResults.h.
Referenced by psr::GenericSolverResults< N, D, L >::resultAtInLLVMSSA().
resultAtInLLVMSSA()
template<typename N , typename D , typename L > l_t psr::GenericSolverResults< N, D, L >::resultAtInLLVMSSA (const llvm::Instruction * Stmt, ByConstRef< d_t > Node) const inline
Definition at line 93 of file GenericSolverResults.h.
References psr::GenericSolverResults< N, D, L >::resultAt().
resultsAt()
template<typename N , typename D , typename L > std::unordered_map< d_t, l_t > psr::GenericSolverResults< N, D, L >::resultsAt (ByConstRef< n_t > Stmt, bool StripZero = false) const inline
Definition at line 70 of file GenericSolverResults.h.
Referenced by psr::GenericSolverResults< N, D, L >::resultsAtInLLVMSSA().
resultsAtInLLVMSSA()
template<typename N , typename D , typename L > std::unordered_map< d_t, l_t > psr::GenericSolverResults< N, D, L >::resultsAtInLLVMSSA (const llvm::Instruction * Stmt, bool StripZero = false) const inline
Definition at line 104 of file GenericSolverResults.h.
References psr::GenericSolverResults< N, D, L >::resultsAt().
size()
template<typename N , typename D , typename L > size_t psr::GenericSolverResults< N, D, L >::size () const inline noexcept
Definition at line 83 of file GenericSolverResults.h.
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/GenericSolverResults.h