PhASAR: psr::glca::EdgeValue Class Reference
psr::glca::EdgeValue Class Reference
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEGeneralizedLCA/EdgeValue.h"
Public Types
enum Type { Top , Integer , String , FloatingPoint }
Public Member Functions
EdgeValue (const llvm::Value *Val)
EdgeValue (const EdgeValue &EV)
EdgeValue (llvm::APInt &&VI)
EdgeValue (const llvm::APInt &VI)
EdgeValue (llvm::APFloat &&VF)
EdgeValue (long long VI)
EdgeValue (int VI)
EdgeValue (double Double)
EdgeValue (float Float)
EdgeValue (std::string &&VS)
EdgeValue (std::nullptr_t)
~EdgeValue ()
bool tryGetInt (int64_t &Res) const
bool tryGetFP (double &Res) const
bool tryGetString (std::string &Res) const
bool isTop () const
bool isNumeric () const
bool isString () const
Type getKind () const
bool sqSubsetEq (const EdgeValue &Other) const
EdgeValue performBinOp (llvm::BinaryOperator::BinaryOps Op, const EdgeValue &Other) const
EdgeValue typecast (Type Dest, unsigned Bits) const
EdgeValue & operator= (const EdgeValue &EV)
operator bool ()
EdgeValue operator- () const
EdgeValue operator~ () const
Static Public Member Functions
static int compare (const EdgeValue &Lhs, const EdgeValue &Rhs)
static std::string typeToString (Type Ty)
Static Public Attributes
static const EdgeValue TopValue
Friends
bool operator== (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator+ (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator- (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator* (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator/ (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator% (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator& (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator| (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator^ (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator<< (const EdgeValue &Lhs, const EdgeValue &Rhs)
EdgeValue operator>> (const EdgeValue &Lhs, const EdgeValue &Rhs)
llvm::raw_ostream & operator<< (llvm::raw_ostream &Os, const EdgeValue &EV)
std::string to_string (const EdgeValue &EV)
Detailed Description
Definition at line 28 of file EdgeValue.h.
Member Enumeration Documentation
Type
enum psr::glca::EdgeValue::Type
Enumerator
Top
Integer
String
FloatingPoint
Definition at line 30 of file EdgeValue.h.
Constructor & Destructor Documentation
EdgeValue() [1/11]
psr::glca::EdgeValue::EdgeValue (const llvm::Value * Val)
EdgeValue() [2/11]
psr::glca::EdgeValue::EdgeValue (const EdgeValue & EV)
EdgeValue() [3/11]
psr::glca::EdgeValue::EdgeValue (llvm::APInt && VI)
EdgeValue() [4/11]
psr::glca::EdgeValue::EdgeValue (const llvm::APInt & VI)
EdgeValue() [5/11]
psr::glca::EdgeValue::EdgeValue (llvm::APFloat && VF)
EdgeValue() [6/11]
psr::glca::EdgeValue::EdgeValue (long long VI)
EdgeValue() [7/11]
psr::glca::EdgeValue::EdgeValue (int VI)
EdgeValue() [8/11]
psr::glca::EdgeValue::EdgeValue (double Double)
EdgeValue() [9/11]
psr::glca::EdgeValue::EdgeValue (float Float)
EdgeValue() [10/11]
psr::glca::EdgeValue::EdgeValue (std::string && VS)
EdgeValue() [11/11]
psr::glca::EdgeValue::EdgeValue (std::nullptr_t)
~EdgeValue()
psr::glca::EdgeValue::~EdgeValue ()
Member Function Documentation
compare()
static int psr::glca::EdgeValue::compare (const EdgeValue & Lhs, const EdgeValue & Rhs) static
getKind()
Type psr::glca::EdgeValue::getKind () const
Referenced by std::hash< psr::glca::EdgeValue >::operator()().
isNumeric()
bool psr::glca::EdgeValue::isNumeric () const
isString()
bool psr::glca::EdgeValue::isString () const
isTop()
bool psr::glca::EdgeValue::isTop () const
operator bool()
psr::glca::EdgeValue::operator bool ()
operator-()
EdgeValue psr::glca::EdgeValue::operator- () const
operator=()
EdgeValue & psr::glca::EdgeValue::operator= (const EdgeValue & EV)
operator~()
EdgeValue psr::glca::EdgeValue::operator~ () const
performBinOp()
EdgeValue psr::glca::EdgeValue::performBinOp (llvm::BinaryOperator::BinaryOps Op, const EdgeValue & Other) const
sqSubsetEq()
bool psr::glca::EdgeValue::sqSubsetEq (const EdgeValue & Other) const
tryGetFP()
bool psr::glca::EdgeValue::tryGetFP (double & Res) const
Referenced by std::hash< psr::glca::EdgeValue >::operator()().
tryGetInt()
bool psr::glca::EdgeValue::tryGetInt (int64_t & Res) const
Referenced by std::hash< psr::glca::EdgeValue >::operator()().
tryGetString()
bool psr::glca::EdgeValue::tryGetString (std::string & Res) const
Referenced by std::hash< psr::glca::EdgeValue >::operator()().
typecast()
EdgeValue psr::glca::EdgeValue::typecast (Type Dest, unsigned Bits) const
typeToString()
static std::string psr::glca::EdgeValue::typeToString (Type Ty) static
Friends And Related Symbol Documentation
operator%
EdgeValue operator% (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator&
EdgeValue operator& (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator*
EdgeValue operator* (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator+
EdgeValue operator+ (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator-
EdgeValue operator- (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator/
EdgeValue operator/ (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator<< [1/2]
EdgeValue operator<< (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator<< [2/2]
llvm::raw_ostream & operator<< (llvm::raw_ostream & Os, const EdgeValue & EV) friend
operator==
bool operator== (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator>>
EdgeValue operator>> (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator^
EdgeValue operator^ (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
operator|
EdgeValue operator| (const EdgeValue & Lhs, const EdgeValue & Rhs) friend
to_string
std::string to_string (const EdgeValue & EV) friend
Definition at line 88 of file EdgeValue.h.
Member Data Documentation
TopValue
const EdgeValue psr::glca::EdgeValue::TopValue static
Definition at line 50 of file EdgeValue.h.
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEGeneralizedLCA/EdgeValue.h