PhASAR: psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename > Class Template Reference
psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename > Class Template Reference
An extension of the path-reconstruction mechanism of the PathSensitivityManager that provides means to extract concrete combined control- and data-flow paths.
#include "phasar/PhasarLLVM/DataFlow/PathSensitivity/Z3BasedPathSensitvityManager.h"
Public Types
using n_t = typename AnalysisDomainTy::n_t
using d_t = typename AnalysisDomainTy::d_t
using MaybeFlowPathSeq = std::variant< FlowPathSequence< n_t >, z3::expr >
Public Types inherited from psr::Z3BasedPathSensitivityManagerBase
using n_t = const llvm::Instruction *
Public Types inherited from psr::PathSensitivityManagerBase< const llvm::Instruction * >
using n_t = const llvm::Instruction *
using graph_type = AdjacencyList< llvm::SmallVector< n_t, 0 > >
Public Member Functions
Z3BasedPathSensitivityManager (const ExplodedSuperGraph< AnalysisDomainTy > *ESG, Z3BasedPathSensitivityConfig Config, LLVMPathConstraints *LPC=nullptr)
FlowPathSequence< n_t > pathsTo (n_t Inst, d_t Fact) const
Public Member Functions inherited from psr::PathSensitivityManagerMixin< Z3BasedPathSensitivityManager< AnalysisDomainTy >, AnalysisDomainTy, Z3BasedPathSensitivityManagerBase::graph_type >
Z3BasedPathSensitivityManagerBase::graph_type pathsDagToAll (n_t Inst, FactsRangeTy FactsRange, const PathSensitivityConfigBase< ConfigTy > &Config, const Filter &PFilter={}) const
Z3BasedPathSensitivityManagerBase::graph_type pathsDagTo (n_t Inst, const SolverResults< n_t, d_t, L > &SR, const PathSensitivityConfigBase< ConfigTy > &Config, const Filter &PFilter={}) const
Z3BasedPathSensitivityManagerBase::graph_type pathsDagTo (n_t Inst, d_t Fact, const PathSensitivityConfigBase< ConfigTy > &Config, const Filter &PFilter={}) const
Z3BasedPathSensitivityManagerBase::graph_type pathsDagToInLLVMSSA (n_t Inst, d_t Fact, const PathSensitivityConfigBase< ConfigTy > &Config, const Filter &PFilter={}) const
Additional Inherited Members
Protected Types inherited from psr::PathSensitivityManagerBase< const llvm::Instruction * >
using graph_traits_t = GraphTraits< graph_type >
using vertex_t = typename graph_traits_t::vertex_t
Protected Member Functions inherited from psr::Z3BasedPathSensitivityManagerBase
z3::expr filterOutUnreachableNodes (graph_type &RevDAG, vertex_t Leaf, const Z3BasedPathSensitivityConfig &Config, LLVMPathConstraints &LPC) const
FlowPathSequence< n_t > filterAndFlattenRevDag (graph_type &RevDAG, vertex_t Leaf, n_t FinalInst, const Z3BasedPathSensitivityConfig &Config, LLVMPathConstraints &LPC) const
Protected Member Functions inherited from psr::PathSensitivityManagerMixin< Z3BasedPathSensitivityManager< AnalysisDomainTy >, AnalysisDomainTy, Z3BasedPathSensitivityManagerBase::graph_type >
PathSensitivityManagerMixin (const ExplodedSuperGraph< AnalysisDomainTy > *ESG) noexcept
Static Protected Member Functions inherited from psr::Z3BasedPathSensitivityManagerBase
static void deduplicatePaths (FlowPathSequence< n_t > &Paths)
Detailed Description
template<typename AnalysisDomainTy, typename = std::enable_if_t<std::is_same_v< typename AnalysisDomainTy::n_t, const llvm::Instruction *>>>
class psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename >
An extension of the path-reconstruction mechanism of the PathSensitivityManager that provides means to extract concrete combined control- and data-flow paths.
Filters out paths that are considered infeasible by the Z3 constraint solver.
Definition at line 73 of file Z3BasedPathSensitvityManager.h.
Member Typedef Documentation
d_t
template<typename AnalysisDomainTy , typename = std::enable_if_t<std::is_same_v< typename AnalysisDomainTy::n_t, const llvm::Instruction *>>> using psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename >::d_t = typename AnalysisDomainTy::d_t
Definition at line 85 of file Z3BasedPathSensitvityManager.h.
MaybeFlowPathSeq
template<typename AnalysisDomainTy , typename = std::enable_if_t<std::is_same_v< typename AnalysisDomainTy::n_t, const llvm::Instruction *>>> using psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename >::MaybeFlowPathSeq = std::variant<FlowPathSequence<n_t>, z3::expr>
Definition at line 87 of file Z3BasedPathSensitvityManager.h.
n_t
template<typename AnalysisDomainTy , typename = std::enable_if_t<std::is_same_v< typename AnalysisDomainTy::n_t, const llvm::Instruction *>>> using psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename >::n_t = typename AnalysisDomainTy::n_t
Definition at line 84 of file Z3BasedPathSensitvityManager.h.
Constructor & Destructor Documentation
Z3BasedPathSensitivityManager()
template<typename AnalysisDomainTy , typename = std::enable_if_t<std::is_same_v< typename AnalysisDomainTy::n_t, const llvm::Instruction *>>> psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename >::Z3BasedPathSensitivityManager (const ExplodedSuperGraph< AnalysisDomainTy > * ESG, Z3BasedPathSensitivityConfig Config, LLVMPathConstraints * LPC = nullptr) inline explicit
Definition at line 89 of file Z3BasedPathSensitvityManager.h.
Member Function Documentation
pathsTo()
template<typename AnalysisDomainTy , typename = std::enable_if_t<std::is_same_v< typename AnalysisDomainTy::n_t, const llvm::Instruction *>>> FlowPathSequence< n_t > psr::Z3BasedPathSensitivityManager< AnalysisDomainTy, typename >::pathsTo (n_t Inst, d_t Fact) const inline
Reconstruct the feasible control- and data-flow paths the lead to the given data-flow fact Fact holding right after Inst.
The result is given as list of paths, where cycles are unrolled once in an implementation-defined way. It is strongly recommended to Use the Z3BasedPathSensitivityConfig in the Z3BasedPathSensitivityManager's ctor to limit the returned paths; otherwise this function quickly becomes a performance bottleneck.
Definition at line 106 of file Z3BasedPathSensitvityManager.h.
References psr::PathSensitivityConfigBase< DerivedConfig >::DAGDepthThreshold, psr::PathSensitivityConfigBase< DerivedConfig >::DAGSizeThreshold, psr::Z3BasedPathSensitivityManagerBase::deduplicatePaths(), psr::Z3BasedPathSensitivityManagerBase::filterAndFlattenRevDag(), psr::Z3BasedPathSensitivityManagerBase::filterOutUnreachableNodes(), psr::getFilePathFromIR(), psr::getMetaDataID(), psr::PathSensitivityManagerMixin< Z3BasedPathSensitivityManager< AnalysisDomainTy >, AnalysisDomainTy, Z3BasedPathSensitivityManagerBase::graph_type >::pathsDagTo(), PHASAR_LOG_LEVEL, PHASAR_LOG_LEVEL_CAT, psr::printGraph(), and psr::Ret.
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/PathSensitivity/Z3BasedPathSensitvityManager.h