PhASAR: psr::BitSet< IdT, BitVectorTy > Class Template Reference
psr::BitSet< IdT, BitVectorTy > Class Template Reference
A set-type that can compactly store sets of sequential integer-like types.
#include "phasar/Utils/BitSet.h"
Classes
class Iterator
Public Types
using iterator = Iterator
using value_type = IdT
Public Member Functions
BitSet () noexcept=default
BitSet (size_t InitialCapacity)
BitSet (size_t InitialCapacity, bool InitialValue)
void reserve (size_t Cap)
bool contains (IdT Id) const noexcept
void insert (IdT Id)
bool tryInsert (IdT Id)
Same as insert(), but returns, whether the set was changed.
void erase (IdT Id) noexcept
bool tryErase (IdT Id) noexcept
Same as erase(), but returns, whether the set was changed.
void mergeWith (const BitSet &Other)
bool tryMergeWith (const BitSet &Other)
Same as mergeWith(), but returns, whether the set was changed.
void clear () noexcept
bool any () const noexcept
iterator begin () const noexcept
iterator end () const noexcept
template<std::invocable< IdT > HandlerFn>
void foreach (HandlerFn Handler) const noexcept(std::is_nothrow_invocable_v< HandlerFn &, IdT >)
void operator|= (const BitSet &Other)
Same as mergeWith()
void operator-= (const BitSet &Other)
BitSet operator- (const BitSet &Other) const
BitSet & insertAllOf (const BitSet &Other)
Same as mergeWith(), but returns *this to allow a fluent interface.
BitSet & eraseAllOf (const BitSet &Other)
Same as operator-=, but returns *this to allow a fluent interface.
bool isSubsetOf (const BitSet &Of) const
bool isSupersetOf (const BitSet &Of) const
size_t capacity () const noexcept
The number of bits available. This operation is O(1)
size_t size () const noexcept
bool empty () const noexcept
Friends
bool operator== (const BitSet &Lhs, const BitSet &Rhs) noexcept
bool operator!= (const BitSet &Lhs, const BitSet &Rhs) noexcept
Detailed Description
template<typename IdT, typename BitVectorTy = llvm::BitVector>
class psr::BitSet< IdT, BitVectorTy >
A set-type that can compactly store sets of sequential integer-like types.
Use this type for sequential (unsigned) integers and ids that can convert from and to uint32_t.
Template Parameters
IdT The type of elements to store in this set. Must be losslessly convertible from and to uint32_t.
BitVectorTy The underlying bit-vector to use. Must be either llvm::BitVector or llvm::SmallBitVector.
Definition at line 37 of file BitSet.h.
Member Typedef Documentation
iterator
template<typename IdT , typename BitVectorTy = llvm::BitVector> using psr::BitSet< IdT, BitVectorTy >::iterator = Iterator
Definition at line 83 of file BitSet.h.
value_type
template<typename IdT , typename BitVectorTy = llvm::BitVector> using psr::BitSet< IdT, BitVectorTy >::value_type = IdT
Definition at line 84 of file BitSet.h.
Constructor & Destructor Documentation
BitSet() [1/3]
template<typename IdT , typename BitVectorTy = llvm::BitVector> psr::BitSet< IdT, BitVectorTy >::BitSet () default noexcept
BitSet() [2/3]
template<typename IdT , typename BitVectorTy = llvm::BitVector> psr::BitSet< IdT, BitVectorTy >::BitSet (size_t InitialCapacity) inline explicit
Definition at line 87 of file BitSet.h.
BitSet() [3/3]
template<typename IdT , typename BitVectorTy = llvm::BitVector> psr::BitSet< IdT, BitVectorTy >::BitSet (size_t InitialCapacity, bool InitialValue) inline explicit
Definition at line 88 of file BitSet.h.
Member Function Documentation
any()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::any () const inline noexcept
Definition at line 174 of file BitSet.h.
begin()
template<typename IdT , typename BitVectorTy = llvm::BitVector> iterator psr::BitSet< IdT, BitVectorTy >::begin () const inline noexcept
Definition at line 176 of file BitSet.h.
capacity()
template<typename IdT , typename BitVectorTy = llvm::BitVector> size_t psr::BitSet< IdT, BitVectorTy >::capacity () const inline noexcept
The number of bits available. This operation is O(1)
Definition at line 251 of file BitSet.h.
clear()
template<typename IdT , typename BitVectorTy = llvm::BitVector> void psr::BitSet< IdT, BitVectorTy >::clear () inline noexcept
Definition at line 145 of file BitSet.h.
contains()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::contains (IdT Id) const inline noexcept
Definition at line 97 of file BitSet.h.
Referenced by psr::BitSet< IdT, BitVectorTy >::tryErase().
empty()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::empty () const inline noexcept
Whether this set contains no elements. In contrast to most other containers, this operation is linear in O(capacity())
Definition at line 257 of file BitSet.h.
end()
template<typename IdT , typename BitVectorTy = llvm::BitVector> iterator psr::BitSet< IdT, BitVectorTy >::end () const inline noexcept
Definition at line 179 of file BitSet.h.
erase()
template<typename IdT , typename BitVectorTy = llvm::BitVector> void psr::BitSet< IdT, BitVectorTy >::erase (IdT Id) inline noexcept
Definition at line 123 of file BitSet.h.
Referenced by psr::computeSCCDependencies().
eraseAllOf()
template<typename IdT , typename BitVectorTy = llvm::BitVector> BitSet & psr::BitSet< IdT, BitVectorTy >::eraseAllOf (const BitSet< IdT, BitVectorTy > & Other) inline
Same as operator-=, but returns *this to allow a fluent interface.
Definition at line 219 of file BitSet.h.
foreach()
template<typename IdT , typename BitVectorTy = llvm::BitVector> template<std::invocable< IdT > HandlerFn> void psr::BitSet< IdT, BitVectorTy >::foreach (HandlerFn Handler) const inline noexcept
Calls the given handler function for each sert bit in the bitset.
This is likely faster than using iterators.
Definition at line 185 of file BitSet.h.
Referenced by psr::computeSCCDependencies().
insert()
template<typename IdT , typename BitVectorTy = llvm::BitVector> void psr::BitSet< IdT, BitVectorTy >::insert (IdT Id) inline
Definition at line 102 of file BitSet.h.
insertAllOf()
template<typename IdT , typename BitVectorTy = llvm::BitVector> BitSet & psr::BitSet< IdT, BitVectorTy >::insertAllOf (const BitSet< IdT, BitVectorTy > & Other) inline
Same as mergeWith(), but returns *this to allow a fluent interface.
Definition at line 214 of file BitSet.h.
isSubsetOf()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::isSubsetOf (const BitSet< IdT, BitVectorTy > & Of) const inline
Definition at line 224 of file BitSet.h.
isSupersetOf()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::isSupersetOf (const BitSet< IdT, BitVectorTy > & Of) const inline
Definition at line 246 of file BitSet.h.
Referenced by psr::BitSet< IdT, BitVectorTy >::tryMergeWith().
mergeWith()
template<typename IdT , typename BitVectorTy = llvm::BitVector> void psr::BitSet< IdT, BitVectorTy >::mergeWith (const BitSet< IdT, BitVectorTy > & Other) inline
Definition at line 137 of file BitSet.h.
Referenced by psr::BitSet< IdT, BitVectorTy >::tryMergeWith().
operator-()
template<typename IdT , typename BitVectorTy = llvm::BitVector> BitSet psr::BitSet< IdT, BitVectorTy >::operator- (const BitSet< IdT, BitVectorTy > & Other) const inline
Definition at line 205 of file BitSet.h.
References psr::Ret.
operator-=()
template<typename IdT , typename BitVectorTy = llvm::BitVector> void psr::BitSet< IdT, BitVectorTy >::operator-= (const BitSet< IdT, BitVectorTy > & Other) inline
Definition at line 203 of file BitSet.h.
operator|=()
template<typename IdT , typename BitVectorTy = llvm::BitVector> void psr::BitSet< IdT, BitVectorTy >::operator|= (const BitSet< IdT, BitVectorTy > & Other) inline
Same as mergeWith()
Definition at line 202 of file BitSet.h.
reserve()
template<typename IdT , typename BitVectorTy = llvm::BitVector> void psr::BitSet< IdT, BitVectorTy >::reserve (size_t Cap) inline
Definition at line 91 of file BitSet.h.
size()
template<typename IdT , typename BitVectorTy = llvm::BitVector> size_t psr::BitSet< IdT, BitVectorTy >::size () const inline noexcept
The number of bits set to 1. In contrast to most other containers, this operation is linear in O(capacity())
Definition at line 254 of file BitSet.h.
Referenced by psr::computeSCCDependencies().
tryErase()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::tryErase (IdT Id) inline noexcept
Same as erase(), but returns, whether the set was changed.
Definition at line 129 of file BitSet.h.
References psr::BitSet< IdT, BitVectorTy >::contains().
tryInsert()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::tryInsert (IdT Id) inline
Same as insert(), but returns, whether the set was changed.
Definition at line 112 of file BitSet.h.
References psr::Ret.
tryMergeWith()
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool psr::BitSet< IdT, BitVectorTy >::tryMergeWith (const BitSet< IdT, BitVectorTy > & Other) inline
Same as mergeWith(), but returns, whether the set was changed.
TODO: Make this more efficient
Definition at line 140 of file BitSet.h.
References psr::BitSet< IdT, BitVectorTy >::isSupersetOf(), and psr::BitSet< IdT, BitVectorTy >::mergeWith().
Friends And Related Symbol Documentation
operator!=
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool operator!= (const BitSet< IdT, BitVectorTy > & Lhs, const BitSet< IdT, BitVectorTy > & Rhs) friend
Definition at line 169 of file BitSet.h.
operator==
template<typename IdT , typename BitVectorTy = llvm::BitVector> bool operator== (const BitSet< IdT, BitVectorTy > & Lhs, const BitSet< IdT, BitVectorTy > & Rhs) friend
Definition at line 147 of file BitSet.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/BitSet.h