PhASAR: psr::CallGraph< N, F > Class Template Reference
psr::CallGraph< N, F > Class Template Reference
#include "phasar/ControlFlow/CallGraph.h"
Public Types
using FunctionVertexTy = llvm::SmallVector< n_t >
using InstructionVertexTy = llvm::SmallVector< f_t >
Public Types inherited from psr::CallGraphBase< CallGraph< N, F > >
using n_t = typename CGTraits< CallGraph< N, F > >::n_t
using f_t = typename CGTraits< CallGraph< N, F > >::f_t
Public Member Functions
CallGraph () noexcept=default
Creates a new, empty call-graph.
auto getAllVertexFunctions () const noexcept
auto getAllVertexCallSites () const noexcept
size_t getNumVertexFunctions () const noexcept
size_t getNumVertexCallSites () const noexcept
size_t size () const noexcept
The number of functions within this call-graph.
bool empty () const noexcept
template<typename FunctionIdGetter , typename InstIdGetter >
void printAsJson (llvm::raw_ostream &OS, FunctionIdGetter GetFunctionId, InstIdGetter GetInstructionId) const
template<typename FunctionLabelGetter , typename InstParentGetter , typename InstLabelGetter >
void printAsDot (llvm::raw_ostream &OS, FunctionLabelGetter GetFunctionLabel, InstParentGetter GetFunctionFromInst, InstLabelGetter GetInstLabel) const
template<typename FunctionGetter , typename InstructionGetter >
CallGraph< N, F > deserialize (const CallGraphData &PrecomputedCG, FunctionGetter GetFunctionFromName, InstructionGetter GetInstructionFromId)
Public Member Functions inherited from psr::CallGraphBase< CallGraph< N, F > >
decltype(auto) getCalleesOfCallAt (ByConstRef< n_t > Inst) const noexcept(noexcept(self().getCalleesOfCallAtImpl(Inst)))
decltype(auto) getCallersOf (ByConstRef< f_t > Fun) const
Static Public Member Functions
template<typename FunctionGetter , typename InstructionGetter >
static CallGraph deserialize (const CallGraphData &PrecomputedCG, FunctionGetter GetFunctionFromName, InstructionGetter GetInstructionFromId)
Deserializes a previously computed call-graph.
Friends
class CallGraphBuilder< N, F >
Additional Inherited Members
Protected Member Functions inherited from psr::CRTPBase< Derived >
constexpr CRTPBase () noexcept=default
constexpr Derived & self () &noexcept
constexpr Derived && self () &&noexcept
constexpr const Derived & self () const &noexcept
Detailed Description
template<typename N, typename F>
class psr::CallGraph< N, F >
An explicit graph-representation of a call-graph. Only represents the data, not the call-graph analysis that creates it.
This type is immutable. To incrementally build it from your call-graph analysis, use the CallGraphBuilder
Definition at line 41 of file CallGraph.h.
Member Typedef Documentation
FunctionVertexTy
template<typename N , typename F > using psr::CallGraph< N, F >::FunctionVertexTy = llvm::SmallVector<n_t>
Definition at line 49 of file CallGraph.h.
InstructionVertexTy
template<typename N , typename F > using psr::CallGraph< N, F >::InstructionVertexTy = llvm::SmallVector<f_t>
Definition at line 50 of file CallGraph.h.
Constructor & Destructor Documentation
CallGraph()
template<typename N , typename F > psr::CallGraph< N, F >::CallGraph () default noexcept
Creates a new, empty call-graph.
Member Function Documentation
deserialize() [1/2]
template<typename N , typename F > template<typename FunctionGetter , typename InstructionGetter > static CallGraph psr::CallGraph< N, F >::deserialize (const CallGraphData & PrecomputedCG, FunctionGetter GetFunctionFromName, InstructionGetter GetInstructionFromId) static
Deserializes a previously computed call-graph.
deserialize() [2/2]
template<typename N , typename F > template<typename FunctionGetter , typename InstructionGetter > CallGraph< N, F > psr::CallGraph< N, F >::deserialize (const CallGraphData & PrecomputedCG, FunctionGetter GetFunctionFromName, InstructionGetter GetInstructionFromId)
Definition at line 253 of file CallGraph.h.
References psr::CallGraphData::FToFunctionVertexTy, and PHASAR_LOG_LEVEL_CAT.
empty()
template<typename N , typename F > bool psr::CallGraph< N, F >::empty () const inline noexcept
Definition at line 84 of file CallGraph.h.
getAllVertexCallSites()
template<typename N , typename F > auto psr::CallGraph< N, F >::getAllVertexCallSites () const inline noexcept
A range of all call-sites that are vertices in the call-graph. The number of vertex-callsites can be retrived by getNumVertexCallSites().
Definition at line 70 of file CallGraph.h.
getAllVertexFunctions()
template<typename N , typename F > auto psr::CallGraph< N, F >::getAllVertexFunctions () const inline noexcept
A range of all functions that are vertices in the call-graph. The number of vertex functions can be retrieved by getNumVertexFunctions().
Definition at line 64 of file CallGraph.h.
Referenced by psr::LLVMBasedICFG::getAllVertexFunctions(), and psr::CallGraph< N, F >::printAsDot().
getNumVertexCallSites()
template<typename N , typename F > size_t psr::CallGraph< N, F >::getNumVertexCallSites () const inline noexcept
Definition at line 77 of file CallGraph.h.
getNumVertexFunctions()
template<typename N , typename F > size_t psr::CallGraph< N, F >::getNumVertexFunctions () const inline noexcept
Definition at line 74 of file CallGraph.h.
Referenced by psr::LLVMBasedICFG::getNumVertexFunctions(), and psr::CallGraph< N, F >::size().
printAsDot()
template<typename N , typename F > template<typename FunctionLabelGetter , typename InstParentGetter , typename InstLabelGetter > void psr::CallGraph< N, F >::printAsDot (llvm::raw_ostream & OS, FunctionLabelGetter GetFunctionLabel, InstParentGetter GetFunctionFromInst, InstLabelGetter GetInstLabel) const inline
Definition at line 107 of file CallGraph.h.
References psr::CallGraph< N, F >::getAllVertexFunctions().
printAsJson()
template<typename N , typename F > template<typename FunctionIdGetter , typename InstIdGetter > void psr::CallGraph< N, F >::printAsJson (llvm::raw_ostream & OS, FunctionIdGetter GetFunctionId, InstIdGetter GetInstructionId) const inline
Definition at line 87 of file CallGraph.h.
References psr::CallGraphData::FToFunctionVertexTy, and psr::CallGraphData::printAsJson().
size()
template<typename N , typename F > size_t psr::CallGraph< N, F >::size () const inline noexcept
The number of functions within this call-graph.
Definition at line 82 of file CallGraph.h.
References psr::CallGraph< N, F >::getNumVertexFunctions().
Friends And Related Symbol Documentation
CallGraphBuilder< N, F >
template<typename N , typename F > friend class CallGraphBuilder< N, F > friend
Definition at line 43 of file CallGraph.h.
The documentation for this class was generated from the following file:
include/phasar/ControlFlow/CallGraph.h