PhASAR: psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy > Class Template Reference
psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/IterativeIDESolver.h"
Public Types
using domain_t = typename ProblemTy::ProblemAnalysisDomain
using d_t = typename domain_t::d_t
using n_t = typename domain_t::n_t
using f_t = typename domain_t::f_t
using t_t = typename domain_t::t_t
using v_t = typename domain_t::v_t
using l_t = std::conditional_t< StaticSolverConfigTy::ComputeValues, typename domain_t::l_t, BinaryDomain >
using i_t = typename domain_t::i_t
using config_t = StaticSolverConfigTy
Public Types inherited from psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >
using EdgeFunctionPtrType = std::conditional_t< ComputeValues, EdgeFunPtrTy, EmptyType >
Public Member Functions
IterativeIDESolver (ProblemTy *Problem, const i_t *ICFG) noexcept
auto solve () &
auto solve () &&
auto getSolverResults () const noexcept
auto consumeSolverResults () noexcept
void dumpResults (llvm::raw_ostream &OS=llvm::outs()) const
IterativeIDESolverStats getStats () const noexcept
void dumpStats (llvm::raw_ostream &OS=llvm::outs()) const
Public Member Functions inherited from psr::IDESolverAPIMixin< Derived >
constexpr void initialize ()
constexpr bool next ()
constexpr bool nextN (size_t MaxNumIterations)
constexpr decltype(auto) finalize () &
constexpr decltype(auto) finalize () &&
constexpr decltype(auto) solve () &
constexpr decltype(auto) solve () &&
constexpr decltype(auto) continueSolving () &
constexpr decltype(auto) continueSolving () &&
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto solveUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &&
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &
template<typename CancellationRequest >
requires (std::is_invocable_r_v<bool, CancellationRequest> || std::is_invocable_r_v<bool, CancellationRequest, std::chrono::steady_clock::time_point>)
constexpr auto continueUntil (CancellationRequest CancellationRequested, std::chrono::milliseconds Interval=std::chrono::seconds{1}) &&
constexpr auto solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &
constexpr auto solveWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &&
constexpr auto continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &
constexpr auto continueWithTimeout (std::chrono::milliseconds Timeout, std::chrono::milliseconds Interval) &&
constexpr auto solveWithAsyncCancellation (std::atomic_bool &IsCancelled) &
constexpr auto solveWithAsyncCancellation (std::atomic_bool &IsCancelled) &&
constexpr auto continueWithAsyncCancellation (std::atomic_bool &IsCancelled) &
constexpr auto continueWithAsyncCancellation (std::atomic_bool &IsCancelled) &&
Additional Inherited Members
Static Public Attributes inherited from psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >
static constexpr bool ComputeValues = StaticSolverConfigTy::ComputeValues
static constexpr bool EnableStatistics
Protected Types inherited from psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >
template<typename K , typename V >
using map_t = typename StaticSolverConfigTy::template map_t< K, V >
template<typename T >
using set_t = typename StaticSolverConfigTy::template set_t< T >
template<typename T >
using worklist_t = typename StaticSolverConfigTy::template worklist_t< T >
template<typename ProblemTy , bool AutoAddZero>
using flow_edge_function_cache_t = typename StaticSolverConfigTy::template flow_edge_function_cache_t< ProblemTy, AutoAddZero >
using PropagationJob = IterIDEPropagationJob< EdgeFunctionPtrType >
using SummaryEdges = SmallDenseTable1d< uint64_t, EdgeFunctionPtrType, 4 >
Key is TargetFact.
using SummaryEdges_JF1 = std::conditional_t< ComputeValues, llvm::SmallDenseMap< uint32_t, EdgeFunctionPtrType >, llvm::SmallDenseSet< DummyPair< uint32_t > > >
using summaries_t = detail::CellVecSmallVectorTy< std::conditional_t< ComputeValues, std::pair< uint32_t, EdgeFunctionPtrType >, DummyPair< uint32_t > > >
Detailed Description
template<typename ProblemTy, typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>>
class psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >
Solves the given IDETabulationProblem as described in the 1996 paper by Sagiv, Horwitz and Reps. To solve the problem, call solve().
This solver implements the optimizations and the $JF_N$ layout from the paper "Scaling Interprocedural Static Data-Flow Analysis to Large C/C++ Applications: An Experience Report" (https://doi.org/10.4230/LIPIcs.ECOOP.2024.36) by Schiebel, Sattler, Schubert, Apel, and Bodden.
Definition at line 58 of file IterativeIDESolver.h.
Member Typedef Documentation
config_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::config_t = StaticSolverConfigTy
Definition at line 86 of file IterativeIDESolver.h.
d_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::d_t = typename domain_t::d_t
Definition at line 77 of file IterativeIDESolver.h.
domain_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::domain_t = typename ProblemTy::ProblemAnalysisDomain
Definition at line 76 of file IterativeIDESolver.h.
f_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::f_t = typename domain_t::f_t
Definition at line 79 of file IterativeIDESolver.h.
i_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::i_t = typename domain_t::i_t
Definition at line 84 of file IterativeIDESolver.h.
l_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::l_t = std::conditional_t<StaticSolverConfigTy::ComputeValues, typename domain_t::l_t, BinaryDomain>
Definition at line 82 of file IterativeIDESolver.h.
n_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::n_t = typename domain_t::n_t
Definition at line 78 of file IterativeIDESolver.h.
t_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::t_t = typename domain_t::t_t
Definition at line 80 of file IterativeIDESolver.h.
v_t
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> using psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::v_t = typename domain_t::v_t
Definition at line 81 of file IterativeIDESolver.h.
Constructor & Destructor Documentation
IterativeIDESolver()
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::IterativeIDESolver (ProblemTy * Problem, const i_t * ICFG) inline noexcept
Definition at line 150 of file IterativeIDESolver.h.
Member Function Documentation
consumeSolverResults()
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> auto psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::consumeSolverResults () inline noexcept
Definition at line 166 of file IterativeIDESolver.h.
Referenced by psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::solve().
dumpResults()
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> void psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::dumpResults (llvm::raw_ostream & OS = llvm::outs()) const inline
Definition at line 172 of file IterativeIDESolver.h.
dumpStats()
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> void psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::dumpStats (llvm::raw_ostream & OS = llvm::outs()) const inline
Definition at line 229 of file IterativeIDESolver.h.
getSolverResults()
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> auto psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::getSolverResults () const inline noexcept
Definition at line 162 of file IterativeIDESolver.h.
Referenced by psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::solve().
getStats()
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> IterativeIDESolverStats psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::getStats () const inline noexcept
Definition at line 223 of file IterativeIDESolver.h.
solve() [1/2]
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> auto psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::solve () & inline
Definition at line 153 of file IterativeIDESolver.h.
References psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::getSolverResults().
solve() [2/2]
template<typename ProblemTy , typename StaticSolverConfigTy = DefaultIDESolverConfig<ProblemTy>> auto psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::solve () && inline
Definition at line 157 of file IterativeIDESolver.h.
References psr::IterativeIDESolver< ProblemTy, StaticSolverConfigTy >::consumeSolverResults().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/IterativeIDESolver.h