PhASAR: psr::cfl_fieldsens::FieldStringManager Class Reference
psr::cfl_fieldsens::FieldStringManager Class Reference
Interns the Store- and Load field-strings.
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/CFLFieldSensIFDSProblem.h"
Public Member Functions
FieldStringManager ()
FieldStringNodeId intern (FieldStringNode Nod)
FieldStringNodeId prepend (int32_t Head, FieldStringNodeId Tail)
FieldStringNode operator[] (FieldStringNodeId NId) const
llvm::SmallVector< int32_t > getFullFieldString (FieldStringNodeId NId) const
FieldStringNodeId fromFullFieldString (llvm::ArrayRef< int32_t > FieldString)
uint32_t depth (FieldStringNodeId NId) const
Detailed Description
Interns the Store- and Load field-strings.
Definition at line 93 of file CFLFieldSensIFDSProblem.h.
Constructor & Destructor Documentation
FieldStringManager()
psr::cfl_fieldsens::FieldStringManager::FieldStringManager ()
Member Function Documentation
depth()
uint32_t psr::cfl_fieldsens::FieldStringManager::depth (FieldStringNodeId NId) const inline
Definition at line 125 of file CFLFieldSensIFDSProblem.h.
fromFullFieldString()
FieldStringNodeId psr::cfl_fieldsens::FieldStringManager::fromFullFieldString (llvm::ArrayRef< int32_t > FieldString)
getFullFieldString()
llvm::SmallVector< int32_t > psr::cfl_fieldsens::FieldStringManager::getFullFieldString (FieldStringNodeId NId) const
intern()
FieldStringNodeId psr::cfl_fieldsens::FieldStringManager::intern (FieldStringNode Nod) inline
Definition at line 97 of file CFLFieldSensIFDSProblem.h.
References psr::TypedVector< IdT, ValueT, SmallSize >::push_back().
Referenced by prepend().
operator[]()
FieldStringNode psr::cfl_fieldsens::FieldStringManager::operator[] (FieldStringNodeId NId) const inline
Definition at line 115 of file CFLFieldSensIFDSProblem.h.
prepend()
FieldStringNodeId psr::cfl_fieldsens::FieldStringManager::prepend (int32_t Head, FieldStringNodeId Tail) inline
Definition at line 107 of file CFLFieldSensIFDSProblem.h.
References intern(), psr::cfl_fieldsens::FieldStringNode::Next, PHASAR_LOG_LEVEL, and psr::Ret.
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/CFLFieldSensIFDSProblem.h