PhASAR: psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container > Class Template Reference
psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/FlowEdgeFunctionCache.h"
Public Member Functions
FlowEdgeFunctionCache (IDETabulationProblem< AnalysisDomainTy, Container > &Problem)
~FlowEdgeFunctionCache ()=default
FlowEdgeFunctionCache (const FlowEdgeFunctionCache &FEFC)=default
FlowEdgeFunctionCache & operator= (const FlowEdgeFunctionCache &FEFC)=default
FlowEdgeFunctionCache (FlowEdgeFunctionCache &&FEFC) noexcept=default
FlowEdgeFunctionCache & operator= (FlowEdgeFunctionCache &&FEFC) noexcept=default
FlowFunctionPtrType getNormalFlowFunction (n_t Curr, n_t Succ)
FlowFunctionPtrType getCallFlowFunction (n_t CallSite, f_t DestFun)
FlowFunctionPtrType getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, n_t RetSite)
FlowFunctionPtrType getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees)
FlowFunctionPtrType getSummaryFlowFunction (n_t CallSite, f_t DestFun)
EdgeFunction< l_t > getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t Succ, d_t SuccNode)
EdgeFunction< l_t > getCallEdgeFunction (n_t CallSite, d_t SrcNode, f_t DestinationFunction, d_t DestNode)
EdgeFunction< l_t > getReturnEdgeFunction (n_t CallSite, f_t CalleeFunction, n_t ExitInst, d_t ExitNode, n_t RetSite, d_t RetNode)
EdgeFunction< l_t > getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t RetSite, d_t RetSiteNode, llvm::ArrayRef< f_t > Callees)
EdgeFunction< l_t > getSummaryEdgeFunction (n_t CallSite, d_t CallNode, n_t RetSite, d_t RetSiteNode)
void print ()
template<typename Handler >
void foreachCachedEdgeFunction (Handler Fn) const
Detailed Description
template<typename AnalysisDomainTy, typename Container = std::set<typename AnalysisDomainTy::d_t>>
class psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >
This class caches flow and edge functions to avoid their reconstruction. When a flow or edge function must be applied to multiple times, a cached version is used if existend, otherwise a new one is created and inserted into the cache.
Definition at line 77 of file FlowEdgeFunctionCache.h.
Constructor & Destructor Documentation
FlowEdgeFunctionCache() [1/3]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::FlowEdgeFunctionCache (IDETabulationProblem< AnalysisDomainTy, Container > & Problem) inline
Definition at line 146 of file FlowEdgeFunctionCache.h.
References psr::AutoAddZero, psr::Full, PAMM_GET_INSTANCE, and REG_COUNTER.
~FlowEdgeFunctionCache()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::~FlowEdgeFunctionCache () default
FlowEdgeFunctionCache() [2/3]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::FlowEdgeFunctionCache (const FlowEdgeFunctionCache< AnalysisDomainTy, Container > & FEFC) default
FlowEdgeFunctionCache() [3/3]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::FlowEdgeFunctionCache (FlowEdgeFunctionCache< AnalysisDomainTy, Container > && FEFC) default noexcept
Member Function Documentation
foreachCachedEdgeFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> template<typename Handler > void psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::foreachCachedEdgeFunction (Handler Fn) const inline
Definition at line 610 of file FlowEdgeFunctionCache.h.
References psr::Call, psr::CallToReturn, psr::Normal, psr::Return, and psr::Summary.
getCallEdgeFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> EdgeFunction< l_t > psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallEdgeFunction (n_t CallSite, d_t SrcNode, f_t DestinationFunction, d_t DestNode) inline
Definition at line 379 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::DToString(), psr::FToString(), psr::Full, psr::EdgeFunctions< AnalysisDomainTy >::getCallEdgeFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getCallFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowFunctionPtrType psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallFlowFunction (n_t CallSite, f_t DestFun) inline
Definition at line 226 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::AutoAddZero, psr::FToString(), psr::Full, psr::FlowFunctions< AnalysisDomainTy, Container >::getCallFlowFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getCallToRetEdgeFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> EdgeFunction< l_t > psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetEdgeFunction (n_t CallSite, d_t CallNode, n_t RetSite, d_t RetSiteNode, llvm::ArrayRef< f_t > Callees) inline
Definition at line 449 of file FlowEdgeFunctionCache.h.
References psr::assertAllNotNull(), psr::assertNotNull(), psr::DToString(), psr::FToString(), psr::Full, psr::EdgeFunctions< AnalysisDomainTy >::getCallToRetEdgeFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getCallToRetFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowFunctionPtrType psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetFlowFunction (n_t CallSite, n_t RetSite, llvm::ArrayRef< f_t > Callees) inline
Definition at line 284 of file FlowEdgeFunctionCache.h.
References psr::assertAllNotNull(), psr::assertNotNull(), psr::AutoAddZero, psr::FToString(), psr::Full, psr::FlowFunctions< AnalysisDomainTy, Container >::getCallToRetFlowFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getNormalEdgeFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> EdgeFunction< l_t > psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalEdgeFunction (n_t Curr, d_t CurrNode, n_t Succ, d_t SuccNode) inline
Definition at line 332 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::DToString(), psr::Full, psr::EdgeFunctions< AnalysisDomainTy >::getNormalEdgeFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getNormalFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowFunctionPtrType psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalFlowFunction (n_t Curr, n_t Succ) inline
Definition at line 192 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::AutoAddZero, psr::Full, psr::FlowFunctions< AnalysisDomainTy, Container >::getNormalFlowFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getRetFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowFunctionPtrType psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getRetFlowFunction (n_t CallSite, f_t CalleeFun, n_t ExitInst, n_t RetSite) inline
Definition at line 251 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::AutoAddZero, psr::FToString(), psr::Full, psr::FlowFunctions< AnalysisDomainTy, Container >::getRetFlowFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getReturnEdgeFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> EdgeFunction< l_t > psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getReturnEdgeFunction (n_t CallSite, f_t CalleeFunction, n_t ExitInst, d_t ExitNode, n_t RetSite, d_t RetNode) inline
Definition at line 412 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::DToString(), psr::FToString(), psr::Full, psr::EdgeFunctions< AnalysisDomainTy >::getReturnEdgeFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getSummaryEdgeFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> EdgeFunction< l_t > psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryEdgeFunction (n_t CallSite, d_t CallNode, n_t RetSite, d_t RetSiteNode) inline
Definition at line 507 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::DToString(), psr::Full, psr::EdgeFunctions< AnalysisDomainTy >::getSummaryEdgeFunction(), IF_LOG_ENABLED, INC_COUNTER, psr::NToString(), PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
getSummaryFlowFunction()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowFunctionPtrType psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryFlowFunction (n_t CallSite, f_t DestFun) inline
Definition at line 318 of file FlowEdgeFunctionCache.h.
References psr::assertNotNull(), psr::FToString(), psr::FlowFunctions< AnalysisDomainTy, Container >::getSummaryFlowFunction(), IF_LOG_ENABLED, psr::NToString(), and PHASAR_LOG_LEVEL.
operator=() [1/2]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowEdgeFunctionCache & psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::operator= (const FlowEdgeFunctionCache< AnalysisDomainTy, Container > & FEFC) default
operator=() [2/2]
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> FlowEdgeFunctionCache & psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::operator= (FlowEdgeFunctionCache< AnalysisDomainTy, Container > && FEFC) default noexcept
print()
template<typename AnalysisDomainTy , typename Container = std::set<typename AnalysisDomainTy::d_t>> void psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::print () inline
Definition at line 538 of file FlowEdgeFunctionCache.h.
References psr::Full, GET_COUNTER, GET_SUM_COUNT, PAMM_GET_INSTANCE, and PHASAR_LOG_LEVEL.
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/FlowEdgeFunctionCache.h