PhASAR: psr::BoxedConstPtr< T > Class Template Reference
psr::BoxedConstPtr< T > Class Template Reference
#include "phasar/Utils/BoxedPointer.h"
Public Member Functions
constexpr BoxedConstPtr (BoxedPtr< T > Other) noexcept
constexpr const value_type * get () const noexcept
constexpr const value_type * operator-> () const noexcept
constexpr const value_type & operator* () const noexcept
constexpr value_type const *const * value () const noexcept
Friends
constexpr llvm::hash_code hash_value (BoxedConstPtr Ptr) noexcept
constexpr bool operator== (BoxedConstPtr LHS, BoxedConstPtr RHS) noexcept
constexpr bool operator!= (BoxedConstPtr LHS, BoxedConstPtr RHS) noexcept
constexpr bool operator< (BoxedConstPtr LHS, BoxedConstPtr RHS) noexcept
constexpr bool operator> (BoxedConstPtr LHS, BoxedConstPtr RHS) noexcept
constexpr bool operator<= (BoxedConstPtr LHS, BoxedConstPtr RHS) noexcept
constexpr bool operator>= (BoxedConstPtr LHS, BoxedConstPtr RHS) noexcept
Detailed Description
template<typename T>
class psr::BoxedConstPtr< T >
A T const** that behaves like a const T*. NOTE: This is different to const BoxedPtr<T> which propagates the const through all known layers of indirection
Definition at line 102 of file BoxedPointer.h.
Constructor & Destructor Documentation
BoxedConstPtr()
template<typename T > constexpr psr::BoxedConstPtr< T >::BoxedConstPtr (BoxedPtr< T > Other) inline constexpr noexcept
Definition at line 108 of file BoxedPointer.h.
Member Function Documentation
get()
template<typename T > constexpr const value_type * psr::BoxedConstPtr< T >::get () const inline constexpr noexcept
Definition at line 110 of file BoxedPointer.h.
References psr::BoxedPtr< T >::get().
Referenced by psr::BoxedConstPtr< T >::operator->().
operator*()
template<typename T > constexpr const value_type & psr::BoxedConstPtr< T >::operator* () const inline constexpr noexcept
Definition at line 116 of file BoxedPointer.h.
References psr::BoxedPtr< T >::get().
operator->()
template<typename T > constexpr const value_type * psr::BoxedConstPtr< T >::operator-> () const inline constexpr noexcept
Definition at line 114 of file BoxedPointer.h.
References psr::BoxedConstPtr< T >::get().
value()
template<typename T > constexpr value_type const *const * psr::BoxedConstPtr< T >::value () const inline constexpr noexcept
Definition at line 120 of file BoxedPointer.h.
References psr::BoxedPtr< T >::value().
Friends And Related Symbol Documentation
hash_value
template<typename T > constexpr llvm::hash_code hash_value (BoxedConstPtr< T > Ptr) friend
Definition at line 125 of file BoxedPointer.h.
operator!=
template<typename T > constexpr bool operator!= (BoxedConstPtr< T > LHS, BoxedConstPtr< T > RHS) friend
Definition at line 134 of file BoxedPointer.h.
operator<
template<typename T > constexpr bool operator< (BoxedConstPtr< T > LHS, BoxedConstPtr< T > RHS) friend
Definition at line 139 of file BoxedPointer.h.
operator<=
template<typename T > constexpr bool operator<= (BoxedConstPtr< T > LHS, BoxedConstPtr< T > RHS) friend
Definition at line 148 of file BoxedPointer.h.
operator==
template<typename T > constexpr bool operator== (BoxedConstPtr< T > LHS, BoxedConstPtr< T > RHS) friend
Definition at line 130 of file BoxedPointer.h.
operator>
template<typename T > constexpr bool operator> (BoxedConstPtr< T > LHS, BoxedConstPtr< T > RHS) friend
Definition at line 143 of file BoxedPointer.h.
operator>=
template<typename T > constexpr bool operator>= (BoxedConstPtr< T > LHS, BoxedConstPtr< T > RHS) friend
Definition at line 152 of file BoxedPointer.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/BoxedPointer.h