PhASAR: psr::CallGraphBase< Derived > Class Template Reference
psr::CallGraphBase< Derived > Class Template Reference
#include "phasar/ControlFlow/CallGraphBase.h"
Public Types
using n_t = typename CGTraits< Derived >::n_t
using f_t = typename CGTraits< Derived >::f_t
Public Member Functions
constexpr decltype(auto) getCalleesOfCallAt (ByConstRef< n_t > Inst) const noexcept(noexcept(this->self().getCalleesOfCallAtImpl(Inst)))
constexpr decltype(auto) getCallersOf (ByConstRef< f_t > Fun) const
constexpr decltype(auto) getAllVertexFunctions () const noexcept
constexpr auto getAllVertexCallSites () const noexcept
constexpr size_t getNumVertexFunctions () const noexcept
constexpr size_t getNumVertexCallSites () const noexcept
constexpr size_t size () const noexcept
The number of functions within this call-graph.
constexpr bool empty () const noexcept
Additional Inherited Members
Protected Member Functions inherited from psr::CRTPBase< Derived >
constexpr CRTPBase () noexcept=default
constexpr Derived & self () &noexcept
constexpr Derived && self () &&noexcept
constexpr const Derived & self () const &noexcept
Detailed Description
template<typename Derived>
class psr::CallGraphBase< Derived >
Base class of all CallGraph implementations within phasar (currently only CallGraph<N, F>). Only represents the data, not how to create it.
Definition at line 26 of file CallGraphBase.h.
Member Typedef Documentation
f_t
template<typename Derived > using psr::CallGraphBase< Derived >::f_t = typename CGTraits<Derived>::f_t
Definition at line 32 of file CallGraphBase.h.
n_t
template<typename Derived > using psr::CallGraphBase< Derived >::n_t = typename CGTraits<Derived>::n_t
Definition at line 31 of file CallGraphBase.h.
Member Function Documentation
empty()
template<typename Derived > constexpr bool psr::CallGraphBase< Derived >::empty () const inline constexpr noexcept
Definition at line 81 of file CallGraphBase.h.
References psr::CallGraphBase< Derived >::size().
getAllVertexCallSites()
template<typename Derived > constexpr auto psr::CallGraphBase< Derived >::getAllVertexCallSites () const inline constexpr noexcept
A range of all call-sites that are vertices in the call-graph. The number of vertex-callsites can be retrived by getNumVertexCallSites().
Definition at line 65 of file CallGraphBase.h.
References psr::CRTPBase< Derived >::self().
getAllVertexFunctions()
template<typename Derived > constexpr decltype(auto) psr::CallGraphBase< Derived >::getAllVertexFunctions () const inline constexpr noexcept
A range of all functions that are vertices in the call-graph. The number of vertex functions can be retrieved by getNumVertexFunctions().
Definition at line 59 of file CallGraphBase.h.
References psr::CRTPBase< Derived >::self().
Referenced by psr::LLVMBasedICFG::getAllVertexFunctions().
getCalleesOfCallAt()
template<typename Derived > constexpr decltype(auto) psr::CallGraphBase< Derived >::getCalleesOfCallAt (ByConstRef< n_t > Inst) const inline constexpr noexcept
Returns an iterable range of all possible callee candidates at the given call-site induced by the used call-graph.
NOTE: This function is typically called in a hot part of the analysis and should therefore be very fast
Definition at line 40 of file CallGraphBase.h.
References psr::CRTPBase< Derived >::self().
getCallersOf()
template<typename Derived > constexpr decltype(auto) psr::CallGraphBase< Derived >::getCallersOf (ByConstRef< f_t > Fun) const inline constexpr
Returns an iterable range of all possible call-site candidates that may call the given function induced by the used call-graph.
Definition at line 50 of file CallGraphBase.h.
References psr::CRTPBase< Derived >::self().
getNumVertexCallSites()
template<typename Derived > constexpr size_t psr::CallGraphBase< Derived >::getNumVertexCallSites () const inline constexpr noexcept
Definition at line 72 of file CallGraphBase.h.
References psr::CRTPBase< Derived >::self().
getNumVertexFunctions()
template<typename Derived > constexpr size_t psr::CallGraphBase< Derived >::getNumVertexFunctions () const inline constexpr noexcept
Definition at line 69 of file CallGraphBase.h.
References psr::CRTPBase< Derived >::self().
Referenced by psr::LLVMBasedICFG::getNumVertexFunctions(), and psr::CallGraphBase< Derived >::size().
size()
template<typename Derived > constexpr size_t psr::CallGraphBase< Derived >::size () const inline constexpr noexcept
The number of functions within this call-graph.
Definition at line 77 of file CallGraphBase.h.
References psr::CallGraphBase< Derived >::getNumVertexFunctions().
Referenced by psr::CallGraphBase< Derived >::empty().
The documentation for this class was generated from the following file:
include/phasar/ControlFlow/CallGraphBase.h