PhASAR: psr::BoxedPtr< T > Class Template Reference
psr::BoxedPtr< T > Class Template Reference
A T** that behaves like a T*. Used as AliasSetPtr in LLVMAliasSet.
#include "phasar/Utils/BoxedPointer.h"
Public Types
using value_type = T
Public Member Functions
constexpr BoxedPtr () noexcept=default
constexpr BoxedPtr (std::nullptr_t) noexcept
constexpr BoxedPtr (value_type **Value) noexcept
constexpr BoxedPtr (const BoxedPtr &) noexcept=default
constexpr BoxedPtr & operator= (const BoxedPtr &) noexcept=default
~BoxedPtr () noexcept=default
constexpr value_type * get () noexcept
constexpr const value_type * get () const noexcept
constexpr value_type * operator-> () noexcept
constexpr const value_type * operator-> () const noexcept
constexpr value_type & operator* () noexcept
constexpr const value_type & operator* () const noexcept
constexpr operator bool () const noexcept
constexpr value_type ** value () noexcept
constexpr value_type const *const * value () const noexcept
Friends
class BoxedConstPtr< value_type >
constexpr llvm::hash_code hash_value (BoxedPtr Ptr) noexcept
constexpr bool operator== (BoxedPtr LHS, BoxedPtr RHS) noexcept
constexpr bool operator!= (BoxedPtr LHS, BoxedPtr RHS) noexcept
constexpr bool operator< (BoxedPtr LHS, BoxedPtr RHS) noexcept
constexpr bool operator> (BoxedPtr LHS, BoxedPtr RHS) noexcept
constexpr bool operator<= (BoxedPtr LHS, BoxedPtr RHS) noexcept
constexpr bool operator>= (BoxedPtr LHS, BoxedPtr RHS) noexcept
Detailed Description
template<typename T>
class psr::BoxedPtr< T >
A T** that behaves like a T*. Used as AliasSetPtr in LLVMAliasSet.
Definition at line 27 of file BoxedPointer.h.
Member Typedef Documentation
value_type
template<typename T > using psr::BoxedPtr< T >::value_type = T
Definition at line 29 of file BoxedPointer.h.
Constructor & Destructor Documentation
BoxedPtr() [1/4]
template<typename T > constexpr psr::BoxedPtr< T >::BoxedPtr () constexpr default noexcept
BoxedPtr() [2/4]
template<typename T > constexpr psr::BoxedPtr< T >::BoxedPtr (std::nullptr_t) inline constexpr noexcept
Definition at line 32 of file BoxedPointer.h.
BoxedPtr() [3/4]
template<typename T > constexpr psr::BoxedPtr< T >::BoxedPtr (value_type ** Value) inline constexpr noexcept
Definition at line 33 of file BoxedPointer.h.
BoxedPtr() [4/4]
template<typename T > constexpr psr::BoxedPtr< T >::BoxedPtr (const BoxedPtr< T > &) constexpr default noexcept
~BoxedPtr()
template<typename T > psr::BoxedPtr< T >::~BoxedPtr () default noexcept
Member Function Documentation
get() [1/2]
template<typename T > constexpr const value_type * psr::BoxedPtr< T >::get () const inline constexpr noexcept
Definition at line 41 of file BoxedPointer.h.
get() [2/2]
template<typename T > constexpr value_type * psr::BoxedPtr< T >::get () inline constexpr noexcept
Definition at line 40 of file BoxedPointer.h.
Referenced by psr::BoxedConstPtr< T >::get(), psr::BoxedConstPtr< T >::operator*(), psr::BoxedPtr< T >::operator->(), and psr::BoxedPtr< T >::operator->().
operator bool()
template<typename T > constexpr psr::BoxedPtr< T >::operator bool () const inline constexpr noexcept
Definition at line 51 of file BoxedPointer.h.
operator*() [1/2]
template<typename T > constexpr const value_type & psr::BoxedPtr< T >::operator* () const inline constexpr noexcept
Definition at line 49 of file BoxedPointer.h.
operator*() [2/2]
template<typename T > constexpr value_type & psr::BoxedPtr< T >::operator* () inline constexpr noexcept
Definition at line 48 of file BoxedPointer.h.
operator->() [1/2]
template<typename T > constexpr const value_type * psr::BoxedPtr< T >::operator-> () const inline constexpr noexcept
Definition at line 46 of file BoxedPointer.h.
References psr::BoxedPtr< T >::get().
operator->() [2/2]
template<typename T > constexpr value_type * psr::BoxedPtr< T >::operator-> () inline constexpr noexcept
Definition at line 45 of file BoxedPointer.h.
References psr::BoxedPtr< T >::get().
operator=()
template<typename T > constexpr BoxedPtr & psr::BoxedPtr< T >::operator= (const BoxedPtr< T > &) constexpr default noexcept
value() [1/2]
template<typename T > constexpr value_type const *const * psr::BoxedPtr< T >::value () const inline constexpr noexcept
Definition at line 56 of file BoxedPointer.h.
value() [2/2]
template<typename T > constexpr value_type ** psr::BoxedPtr< T >::value () inline constexpr noexcept
Definition at line 55 of file BoxedPointer.h.
Referenced by psr::BoxedConstPtr< T >::value().
Friends And Related Symbol Documentation
BoxedConstPtr< value_type >
template<typename T > friend class BoxedConstPtr< value_type > friend
Definition at line 88 of file BoxedPointer.h.
hash_value
template<typename T > constexpr llvm::hash_code hash_value (BoxedPtr< T > Ptr) friend
Definition at line 61 of file BoxedPointer.h.
operator!=
template<typename T > constexpr bool operator!= (BoxedPtr< T > LHS, BoxedPtr< T > RHS) friend
Definition at line 70 of file BoxedPointer.h.
operator<
template<typename T > constexpr bool operator< (BoxedPtr< T > LHS, BoxedPtr< T > RHS) friend
Definition at line 75 of file BoxedPointer.h.
operator<=
template<typename T > constexpr bool operator<= (BoxedPtr< T > LHS, BoxedPtr< T > RHS) friend
Definition at line 84 of file BoxedPointer.h.
operator==
template<typename T > constexpr bool operator== (BoxedPtr< T > LHS, BoxedPtr< T > RHS) friend
Definition at line 66 of file BoxedPointer.h.
operator>
template<typename T > constexpr bool operator> (BoxedPtr< T > LHS, BoxedPtr< T > RHS) friend
Definition at line 79 of file BoxedPointer.h.
operator>=
template<typename T > constexpr bool operator>= (BoxedPtr< T > LHS, BoxedPtr< T > RHS) friend
Definition at line 88 of file BoxedPointer.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/BoxedPointer.h