PhASAR: psr::DOTConfig Class Reference
psr::DOTConfig Class Reference
#include "phasar/Utils/DOTGraph.h"
Public Member Functions
~DOTConfig ()=default
DOTConfig (const DOTConfig &)=delete
DOTConfig (DOTConfig &&)=delete
DOTConfig & operator= (const DOTConfig &)=delete
DOTConfig & operator= (const DOTConfig &&)=delete
Static Public Member Functions
static const std::string CFNodeAttr ()
static const std::string CFIntraEdgeAttr ()
static const std::string CFInterEdgeAttr ()
static const std::string FactNodeAttr ()
static const std::string FactIDEdgeAttr ()
static const std::string FactCrossEdgeAttr ()
static const std::string FactInterEdgeAttr ()
static const std::string LambdaNodeAttr ()
static const std::string LambdaIDEdgeAttr ()
static const std::string LambdaInterEdgeAttr ()
static void importDOTConfig (llvm::StringRef ConfigPath=PhasarConfig::PhasarDirectory())
static DOTConfig & getDOTConfig ()
Detailed Description
Definition at line 29 of file DOTGraph.h.
Constructor & Destructor Documentation
~DOTConfig()
psr::DOTConfig::~DOTConfig () default
DOTConfig() [1/2]
psr::DOTConfig::DOTConfig (const DOTConfig &) delete
DOTConfig() [2/2]
psr::DOTConfig::DOTConfig (DOTConfig &&) delete
Member Function Documentation
CFInterEdgeAttr()
static const std::string psr::DOTConfig::CFInterEdgeAttr () inline static
Definition at line 33 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::str().
CFIntraEdgeAttr()
static const std::string psr::DOTConfig::CFIntraEdgeAttr () inline static
Definition at line 32 of file DOTGraph.h.
CFNodeAttr()
static const std::string psr::DOTConfig::CFNodeAttr () inline static
Definition at line 31 of file DOTGraph.h.
FactCrossEdgeAttr()
static const std::string psr::DOTConfig::FactCrossEdgeAttr () inline static
Definition at line 37 of file DOTGraph.h.
FactIDEdgeAttr()
static const std::string psr::DOTConfig::FactIDEdgeAttr () inline static
Definition at line 36 of file DOTGraph.h.
FactInterEdgeAttr()
static const std::string psr::DOTConfig::FactInterEdgeAttr () inline static
Definition at line 40 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::str().
FactNodeAttr()
static const std::string psr::DOTConfig::FactNodeAttr () inline static
Definition at line 35 of file DOTGraph.h.
getDOTConfig()
static DOTConfig & psr::DOTConfig::getDOTConfig () static
importDOTConfig()
static void psr::DOTConfig::importDOTConfig (llvm::StringRef ConfigPath = PhasarConfig::PhasarDirectory()) static
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::emitESGAsDot().
LambdaIDEdgeAttr()
static const std::string psr::DOTConfig::LambdaIDEdgeAttr () inline static
Definition at line 45 of file DOTGraph.h.
LambdaInterEdgeAttr()
static const std::string psr::DOTConfig::LambdaInterEdgeAttr () inline static
Definition at line 46 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::str().
LambdaNodeAttr()
static const std::string psr::DOTConfig::LambdaNodeAttr () inline static
Definition at line 44 of file DOTGraph.h.
operator=() [1/2]
DOTConfig & psr::DOTConfig::operator= (const DOTConfig &&) delete
operator=() [2/2]
DOTConfig & psr::DOTConfig::operator= (const DOTConfig &) delete
The documentation for this class was generated from the following file:
include/phasar/Utils/DOTGraph.h