PhASAR: psr::Z3BasedPathSensitivityManagerBase Class Reference
psr::Z3BasedPathSensitivityManagerBase Class Reference
#include "phasar/PhasarLLVM/DataFlow/PathSensitivity/Z3BasedPathSensitvityManager.h"
Public Types
using n_t = const llvm::Instruction *
Public Types inherited from psr::PathSensitivityManagerBase< const llvm::Instruction * >
using n_t = const llvm::Instruction *
using graph_type = AdjacencyList< llvm::SmallVector< n_t, 0 > >
Protected Member Functions
z3::expr filterOutUnreachableNodes (graph_type &RevDAG, vertex_t Leaf, const Z3BasedPathSensitivityConfig &Config, LLVMPathConstraints &LPC) const
FlowPathSequence< n_t > filterAndFlattenRevDag (graph_type &RevDAG, vertex_t Leaf, n_t FinalInst, const Z3BasedPathSensitivityConfig &Config, LLVMPathConstraints &LPC) const
Static Protected Member Functions
static void deduplicatePaths (FlowPathSequence< n_t > &Paths)
Additional Inherited Members
Protected Types inherited from psr::PathSensitivityManagerBase< const llvm::Instruction * >
using graph_traits_t = GraphTraits< graph_type >
using vertex_t = typename graph_traits_t::vertex_t
Detailed Description
Definition at line 43 of file Z3BasedPathSensitvityManager.h.
Member Typedef Documentation
n_t
using psr::Z3BasedPathSensitivityManagerBase::n_t = const llvm::Instruction *
Definition at line 46 of file Z3BasedPathSensitvityManager.h.
Member Function Documentation
deduplicatePaths()
static void psr::Z3BasedPathSensitivityManagerBase::deduplicatePaths (FlowPathSequence< n_t > & Paths) static protected
Referenced by psr::Z3BasedPathSensitivityManager< AnalysisDomainTy >::pathsTo().
filterAndFlattenRevDag()
FlowPathSequence< n_t > psr::Z3BasedPathSensitivityManagerBase::filterAndFlattenRevDag (graph_type & RevDAG, vertex_t Leaf, n_t FinalInst, const Z3BasedPathSensitivityConfig & Config, LLVMPathConstraints & LPC) const protected
Referenced by psr::Z3BasedPathSensitivityManager< AnalysisDomainTy >::pathsTo().
filterOutUnreachableNodes()
z3::expr psr::Z3BasedPathSensitivityManagerBase::filterOutUnreachableNodes (graph_type & RevDAG, vertex_t Leaf, const Z3BasedPathSensitivityConfig & Config, LLVMPathConstraints & LPC) const protected
Referenced by psr::Z3BasedPathSensitivityManager< AnalysisDomainTy >::pathsTo().
The documentation for this class was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/PathSensitivity/Z3BasedPathSensitvityManager.h