PhASAR: psr::JumpFunctions< AnalysisDomainTy, Container > Class Template Reference
psr::JumpFunctions< AnalysisDomainTy, Container > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/JumpFunctions.h"
Public Types
using l_t = typename AnalysisDomainTy::l_t
using d_t = typename AnalysisDomainTy::d_t
using n_t = typename AnalysisDomainTy::n_t
Public Member Functions
JumpFunctions () noexcept=default
~JumpFunctions ()=default
JumpFunctions (const JumpFunctions &JFs)=default
JumpFunctions & operator= (const JumpFunctions &JFs)=default
JumpFunctions (JumpFunctions &&JFs) noexcept=default
JumpFunctions & operator= (JumpFunctions &&JFs) noexcept=default
void addFunction (d_t SourceVal, n_t Target, d_t TargetVal, EdgeFunction< l_t > EdgeFunc)
std::optional< std::reference_wrapper< llvm::SmallVectorImpl< std::pair< d_t, EdgeFunction< l_t > > > > > reverseLookup (n_t Target, d_t TargetVal)
std::optional< std::reference_wrapper< llvm::SmallVectorImpl< std::pair< d_t, EdgeFunction< l_t > > > > > forwardLookup (d_t SourceVal, n_t Target)
Table< d_t, d_t, EdgeFunction< l_t > > & lookupByTarget (n_t Target)
template<typename HandlerFn >
void foreachEdgeFunction (HandlerFn Handler) const
bool removeFunction (d_t SourceVal, n_t Target, d_t TargetVal)
void clear ()
void printJumpFunctions (llvm::raw_ostream &OS)
void printNonEmptyReverseLookup (llvm::raw_ostream &OS)
void printNonEmptyForwardLookup (llvm::raw_ostream &OS)
void printNonEmptyLookupByTargetNode (llvm::raw_ostream &OS)
Protected Attributes
Table< n_t, d_t, llvm::SmallVector< std::pair< d_t, EdgeFunction< l_t > >, 1 > > NonEmptyReverseLookup
Table< d_t, n_t, llvm::SmallVector< std::pair< d_t, EdgeFunction< l_t > >, 1 > > NonEmptyForwardLookup
std::unordered_map< n_t, Table< d_t, d_t, EdgeFunction< l_t > > > NonEmptyLookupByTargetNode
Detailed Description
template<typename AnalysisDomainTy, typename Container>
class psr::JumpFunctions< AnalysisDomainTy, Container >
Definition at line 41 of file JumpFunctions.h.
Member Typedef Documentation
d_t
template<typename AnalysisDomainTy , typename Container > using psr::JumpFunctions< AnalysisDomainTy, Container >::d_t = typename AnalysisDomainTy::d_t
Definition at line 44 of file JumpFunctions.h.
l_t
template<typename AnalysisDomainTy , typename Container > using psr::JumpFunctions< AnalysisDomainTy, Container >::l_t = typename AnalysisDomainTy::l_t
Definition at line 43 of file JumpFunctions.h.
n_t
template<typename AnalysisDomainTy , typename Container > using psr::JumpFunctions< AnalysisDomainTy, Container >::n_t = typename AnalysisDomainTy::n_t
Definition at line 45 of file JumpFunctions.h.
Constructor & Destructor Documentation
JumpFunctions() [1/3]
template<typename AnalysisDomainTy , typename Container > psr::JumpFunctions< AnalysisDomainTy, Container >::JumpFunctions () default noexcept
~JumpFunctions()
template<typename AnalysisDomainTy , typename Container > psr::JumpFunctions< AnalysisDomainTy, Container >::~JumpFunctions () default
JumpFunctions() [2/3]
template<typename AnalysisDomainTy , typename Container > psr::JumpFunctions< AnalysisDomainTy, Container >::JumpFunctions (const JumpFunctions< AnalysisDomainTy, Container > & JFs) default
JumpFunctions() [3/3]
template<typename AnalysisDomainTy , typename Container > psr::JumpFunctions< AnalysisDomainTy, Container >::JumpFunctions (JumpFunctions< AnalysisDomainTy, Container > && JFs) default noexcept
Member Function Documentation
addFunction()
template<typename AnalysisDomainTy , typename Container > void psr::JumpFunctions< AnalysisDomainTy, Container >::addFunction (d_t SourceVal, n_t Target, d_t TargetVal, EdgeFunction< l_t > EdgeFunc) inline
Records a jump function. The source statement is implicit.
See also
PathEdge
Definition at line 77 of file JumpFunctions.h.
References psr::DToString(), psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyForwardLookup, psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyLookupByTargetNode, psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyReverseLookup, psr::NToString(), and PHASAR_LOG_LEVEL.
clear()
template<typename AnalysisDomainTy , typename Container > void psr::JumpFunctions< AnalysisDomainTy, Container >::clear () inline
Removes all jump functions
Definition at line 204 of file JumpFunctions.h.
References psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyForwardLookup, psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyLookupByTargetNode, and psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyReverseLookup.
foreachEdgeFunction()
template<typename AnalysisDomainTy , typename Container > template<typename HandlerFn > void psr::JumpFunctions< AnalysisDomainTy, Container >::foreachEdgeFunction (HandlerFn Handler) const inline
Definition at line 162 of file JumpFunctions.h.
References psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyForwardLookup.
forwardLookup()
template<typename AnalysisDomainTy , typename Container > std::optional< std::reference_wrapper< llvm::SmallVectorImpl< std::pair< d_t, EdgeFunction< l_t > > > > > psr::JumpFunctions< AnalysisDomainTy, Container >::forwardLookup (d_t SourceVal, n_t Target) inline
Returns, for a given source value and target statement all associated target values, and for each the associated edge function. The return value is a mapping from target value to function.
Definition at line 144 of file JumpFunctions.h.
References psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyForwardLookup.
lookupByTarget()
template<typename AnalysisDomainTy , typename Container > Table< d_t, d_t, EdgeFunction< l_t > > & psr::JumpFunctions< AnalysisDomainTy, Container >::lookupByTarget (n_t Target) inline
Returns for a given target statement all jump function records with this target. The return value is a set of records of the form (sourceVal,targetVal,edgeFunction).
Definition at line 157 of file JumpFunctions.h.
References psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyLookupByTargetNode.
operator=() [1/2]
template<typename AnalysisDomainTy , typename Container > JumpFunctions & psr::JumpFunctions< AnalysisDomainTy, Container >::operator= (const JumpFunctions< AnalysisDomainTy, Container > & JFs) default
operator=() [2/2]
template<typename AnalysisDomainTy , typename Container > JumpFunctions & psr::JumpFunctions< AnalysisDomainTy, Container >::operator= (JumpFunctions< AnalysisDomainTy, Container > && JFs) default noexcept
printJumpFunctions()
template<typename AnalysisDomainTy , typename Container > void psr::JumpFunctions< AnalysisDomainTy, Container >::printJumpFunctions (llvm::raw_ostream & OS) inline
Definition at line 210 of file JumpFunctions.h.
References psr::DToString(), psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyLookupByTargetNode, and psr::NToString().
printNonEmptyForwardLookup()
template<typename AnalysisDomainTy , typename Container > void psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyForwardLookup (llvm::raw_ostream & OS) inline
Definition at line 241 of file JumpFunctions.h.
References psr::DToString(), psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyForwardLookup, and psr::NToString().
printNonEmptyLookupByTargetNode()
template<typename AnalysisDomainTy , typename Container > void psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyLookupByTargetNode (llvm::raw_ostream & OS) inline
Definition at line 256 of file JumpFunctions.h.
References psr::Table< R, C, V >::cellVec(), psr::DToString(), psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyLookupByTargetNode, and psr::NToString().
printNonEmptyReverseLookup()
template<typename AnalysisDomainTy , typename Container > void psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyReverseLookup (llvm::raw_ostream & OS) inline
Definition at line 226 of file JumpFunctions.h.
References psr::DToString(), psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyReverseLookup, and psr::NToString().
removeFunction()
template<typename AnalysisDomainTy , typename Container > bool psr::JumpFunctions< AnalysisDomainTy, Container >::removeFunction (d_t SourceVal, n_t Target, d_t TargetVal) inline
Removes a jump function. The source statement is implicit.
See also
PathEdge
Returns
True if the function has actually been removed. False if it was not there anyway.
Definition at line 179 of file JumpFunctions.h.
References psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyForwardLookup, psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyLookupByTargetNode, and psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyReverseLookup.
reverseLookup()
template<typename AnalysisDomainTy , typename Container > std::optional< std::reference_wrapper< llvm::SmallVectorImpl< std::pair< d_t, EdgeFunction< l_t > > > > > psr::JumpFunctions< AnalysisDomainTy, Container >::reverseLookup (n_t Target, d_t TargetVal) inline
Returns, for a given target statement and value all associated source values, and for each the associated edge function. The return value is a mapping from source value to function.
Definition at line 130 of file JumpFunctions.h.
References psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyReverseLookup.
Member Data Documentation
NonEmptyForwardLookup
template<typename AnalysisDomainTy , typename Container > Table<d_t, n_t, llvm::SmallVector<std::pair<d_t, EdgeFunction<l_t> >, 1> > psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyForwardLookup protected
Definition at line 57 of file JumpFunctions.h.
Referenced by psr::JumpFunctions< AnalysisDomainTy, Container >::addFunction(), psr::JumpFunctions< AnalysisDomainTy, Container >::clear(), psr::JumpFunctions< AnalysisDomainTy, Container >::foreachEdgeFunction(), psr::JumpFunctions< AnalysisDomainTy, Container >::forwardLookup(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyForwardLookup(), and psr::JumpFunctions< AnalysisDomainTy, Container >::removeFunction().
NonEmptyLookupByTargetNode
template<typename AnalysisDomainTy , typename Container > std::unordered_map<n_t, Table<d_t, d_t, EdgeFunction<l_t> > > psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyLookupByTargetNode protected
Definition at line 62 of file JumpFunctions.h.
Referenced by psr::JumpFunctions< AnalysisDomainTy, Container >::addFunction(), psr::JumpFunctions< AnalysisDomainTy, Container >::clear(), psr::JumpFunctions< AnalysisDomainTy, Container >::lookupByTarget(), psr::JumpFunctions< AnalysisDomainTy, Container >::printJumpFunctions(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyLookupByTargetNode(), and psr::JumpFunctions< AnalysisDomainTy, Container >::removeFunction().
NonEmptyReverseLookup
template<typename AnalysisDomainTy , typename Container > Table<n_t, d_t, llvm::SmallVector<std::pair<d_t, EdgeFunction<l_t> >, 1> > psr::JumpFunctions< AnalysisDomainTy, Container >::NonEmptyReverseLookup protected
Definition at line 52 of file JumpFunctions.h.
Referenced by psr::JumpFunctions< AnalysisDomainTy, Container >::addFunction(), psr::JumpFunctions< AnalysisDomainTy, Container >::clear(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyReverseLookup(), psr::JumpFunctions< AnalysisDomainTy, Container >::removeFunction(), and psr::JumpFunctions< AnalysisDomainTy, Container >::reverseLookup().
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/JumpFunctions.h