PhASAR: psr::BitVectorSet< T, BitVectorTy > Class Template Reference
psr::BitVectorSet< T, BitVectorTy > Class Template Reference
Implements a set that requires minimal space.
#include "phasar/Utils/BitVectorSet.h"
Public Types
using const_iterator = IteratorTy
using iterator = const_iterator
using value_type = T
Public Member Functions
BitVectorSet ()=default
BitVectorSet (size_t Count)
BitVectorSet (std::initializer_list< T > IList)
template<typename InputIt >
BitVectorSet (InputIt First, InputIt Last)
BitVectorSet< T > setUnion (const BitVectorSet< T > &Other) const
BitVectorSet< T > setIntersect (const BitVectorSet< T > &Other) const
void setIntersectWith (const BitVectorSet< T > &Other)
void setUnionWith (const BitVectorSet< T > &Other)
bool includes (const BitVectorSet< T > &Other) const
void insert (const T &Data)
void insert (const BitVectorSet< T > &Other)
template<typename InputIt >
void insert (InputIt First, InputIt Last)
void erase (const T &Data) noexcept
void erase (const BitVectorSet< T > &Other)
void clear () noexcept
bool empty () const noexcept
void reserve (size_t NewCap)
bool find (const T &Data) const noexcept
size_t count (const T &Data) const noexcept
size_t size () const noexcept
const BitVectorTy & getBits () const &noexcept
BitVectorTy & getBits () &noexcept
BitVectorTy && getBits () &&noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
iterator begin () noexcept
iterator end () noexcept
Static Public Member Functions
static BitVectorSet fromBits (BitVectorTy Bits)
static void clearPosition () noexcept
Friends
bool operator== (const BitVectorSet &Lhs, const BitVectorSet &Rhs)
bool operator!= (const BitVectorSet &Lhs, const BitVectorSet &Rhs)
bool operator< (const BitVectorSet &Lhs, const BitVectorSet &Rhs)
llvm::hash_code hash_value (const BitVectorSet &BV) noexcept
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const BitVectorSet &B)
Detailed Description
template<typename T, typename BitVectorTy = llvm::BitVector>
class psr::BitVectorSet< T, BitVectorTy >
Implements a set that requires minimal space.
BitVectorSet implements a set that requires minimal space. Elements are kept in a static map and the set itself only stores a vector of bits which indicate whether elements are contained in the set.
Attention
This data-structure is NOT thread-safe, since it relies on static storage!
Definition at line 76 of file BitVectorSet.h.
Member Typedef Documentation
const_iterator
template<typename T , typename BitVectorTy = llvm::BitVector> using psr::BitVectorSet< T, BitVectorTy >::const_iterator = IteratorTy
Definition at line 127 of file BitVectorSet.h.
iterator
template<typename T , typename BitVectorTy = llvm::BitVector> using psr::BitVectorSet< T, BitVectorTy >::iterator = const_iterator
Definition at line 128 of file BitVectorSet.h.
value_type
template<typename T , typename BitVectorTy = llvm::BitVector> using psr::BitVectorSet< T, BitVectorTy >::value_type = T
Definition at line 129 of file BitVectorSet.h.
Constructor & Destructor Documentation
BitVectorSet() [1/4]
template<typename T , typename BitVectorTy = llvm::BitVector> psr::BitVectorSet< T, BitVectorTy >::BitVectorSet () default
BitVectorSet() [2/4]
template<typename T , typename BitVectorTy = llvm::BitVector> psr::BitVectorSet< T, BitVectorTy >::BitVectorSet (size_t Count) inline explicit
Definition at line 133 of file BitVectorSet.h.
BitVectorSet() [3/4]
template<typename T , typename BitVectorTy = llvm::BitVector> psr::BitVectorSet< T, BitVectorTy >::BitVectorSet (std::initializer_list< T > IList) inline
Definition at line 135 of file BitVectorSet.h.
References psr::BitVectorSet< T, BitVectorTy >::insert().
BitVectorSet() [4/4]
template<typename T , typename BitVectorTy = llvm::BitVector> template<typename InputIt > psr::BitVectorSet< T, BitVectorTy >::BitVectorSet (InputIt First, InputIt Last) inline explicit
Definition at line 140 of file BitVectorSet.h.
References psr::BitVectorSet< T, BitVectorTy >::insert().
Member Function Documentation
begin() [1/2]
template<typename T , typename BitVectorTy = llvm::BitVector> const_iterator psr::BitVectorSet< T, BitVectorTy >::begin () const inline noexcept
Definition at line 292 of file BitVectorSet.h.
begin() [2/2]
template<typename T , typename BitVectorTy = llvm::BitVector> iterator psr::BitVectorSet< T, BitVectorTy >::begin () inline noexcept
Definition at line 299 of file BitVectorSet.h.
clear()
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::clear () inline noexcept
Definition at line 212 of file BitVectorSet.h.
Referenced by psr::BitVectorSet< T, BitVectorTy >::erase().
clearPosition()
template<typename T , typename BitVectorTy = llvm::BitVector> static void psr::BitVectorSet< T, BitVectorTy >::clearPosition () inline static noexcept
Definition at line 304 of file BitVectorSet.h.
count()
template<typename T , typename BitVectorTy = llvm::BitVector> size_t psr::BitVectorSet< T, BitVectorTy >::count (const T & Data) const inline noexcept
Definition at line 223 of file BitVectorSet.h.
Referenced by psr::BitVectorSet< T, BitVectorTy >::find().
empty()
template<typename T , typename BitVectorTy = llvm::BitVector> bool psr::BitVectorSet< T, BitVectorTy >::empty () const inline noexcept
Definition at line 217 of file BitVectorSet.h.
end() [1/2]
template<typename T , typename BitVectorTy = llvm::BitVector> const_iterator psr::BitVectorSet< T, BitVectorTy >::end () const inline noexcept
Definition at line 295 of file BitVectorSet.h.
end() [2/2]
template<typename T , typename BitVectorTy = llvm::BitVector> iterator psr::BitVectorSet< T, BitVectorTy >::end () inline noexcept
Definition at line 302 of file BitVectorSet.h.
erase() [1/2]
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::erase (const BitVectorSet< T > & Other) inline
Definition at line 204 of file BitVectorSet.h.
References psr::BitVectorSet< T, BitVectorTy >::clear().
erase() [2/2]
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::erase (const T & Data) inline noexcept
Definition at line 196 of file BitVectorSet.h.
find()
template<typename T , typename BitVectorTy = llvm::BitVector> bool psr::BitVectorSet< T, BitVectorTy >::find (const T & Data) const inline noexcept
Definition at line 221 of file BitVectorSet.h.
References psr::BitVectorSet< T, BitVectorTy >::count().
fromBits()
template<typename T , typename BitVectorTy = llvm::BitVector> static BitVectorSet psr::BitVectorSet< T, BitVectorTy >::fromBits (BitVectorTy Bits) inline static
Definition at line 144 of file BitVectorSet.h.
References psr::Ret.
Referenced by psr::FeatureTaintGenerator::createEdgeFactPrinter(), psr::IDEFeatureTaintEdgeFact::str(), and psr::IDEFeatureTaintEdgeFact::toBVSet().
getBits() [1/3]
template<typename T , typename BitVectorTy = llvm::BitVector> BitVectorTy && psr::BitVectorSet< T, BitVectorTy >::getBits () && inline noexcept
Definition at line 235 of file BitVectorSet.h.
getBits() [2/3]
template<typename T , typename BitVectorTy = llvm::BitVector> BitVectorTy & psr::BitVectorSet< T, BitVectorTy >::getBits () & inline noexcept
Definition at line 234 of file BitVectorSet.h.
getBits() [3/3]
template<typename T , typename BitVectorTy = llvm::BitVector> const BitVectorTy & psr::BitVectorSet< T, BitVectorTy >::getBits () const & inline noexcept
Definition at line 233 of file BitVectorSet.h.
includes()
template<typename T , typename BitVectorTy = llvm::BitVector> bool psr::BitVectorSet< T, BitVectorTy >::includes (const BitVectorSet< T > & Other) const inline
Definition at line 173 of file BitVectorSet.h.
insert() [1/3]
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::insert (const BitVectorSet< T > & Other) inline
Definition at line 187 of file BitVectorSet.h.
insert() [2/3]
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::insert (const T & Data) inline
Definition at line 177 of file BitVectorSet.h.
Referenced by psr::BitVectorSet< T, BitVectorTy >::BitVectorSet(), psr::BitVectorSet< T, BitVectorTy >::BitVectorSet(), and psr::BitVectorSet< T, BitVectorTy >::insert().
insert() [3/3]
template<typename T , typename BitVectorTy = llvm::BitVector> template<typename InputIt > void psr::BitVectorSet< T, BitVectorTy >::insert (InputIt First, InputIt Last) inline
Definition at line 189 of file BitVectorSet.h.
References psr::BitVectorSet< T, BitVectorTy >::insert().
reserve()
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::reserve (size_t NewCap) inline
Definition at line 219 of file BitVectorSet.h.
setIntersect()
template<typename T , typename BitVectorTy = llvm::BitVector> BitVectorSet< T > psr::BitVectorSet< T, BitVectorTy >::setIntersect (const BitVectorSet< T > & Other) const inline
Definition at line 160 of file BitVectorSet.h.
setIntersectWith()
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::setIntersectWith (const BitVectorSet< T > & Other) inline
Definition at line 169 of file BitVectorSet.h.
Referenced by psr::intersectWith().
setUnion()
template<typename T , typename BitVectorTy = llvm::BitVector> BitVectorSet< T > psr::BitVectorSet< T, BitVectorTy >::setUnion (const BitVectorSet< T > & Other) const inline
Definition at line 150 of file BitVectorSet.h.
setUnionWith()
template<typename T , typename BitVectorTy = llvm::BitVector> void psr::BitVectorSet< T, BitVectorTy >::setUnionWith (const BitVectorSet< T > & Other) inline
Definition at line 171 of file BitVectorSet.h.
size()
template<typename T , typename BitVectorTy = llvm::BitVector> size_t psr::BitVectorSet< T, BitVectorTy >::size () const inline noexcept
Definition at line 231 of file BitVectorSet.h.
Friends And Related Symbol Documentation
hash_value
template<typename T , typename BitVectorTy = llvm::BitVector> llvm::hash_code hash_value (const BitVectorSet< T, BitVectorTy > & BV) friend
Definition at line 271 of file BitVectorSet.h.
operator!=
template<typename T , typename BitVectorTy = llvm::BitVector> bool operator!= (const BitVectorSet< T, BitVectorTy > & Lhs, const BitVectorSet< T, BitVectorTy > & Rhs) friend
Definition at line 262 of file BitVectorSet.h.
operator<
template<typename T , typename BitVectorTy = llvm::BitVector> bool operator< (const BitVectorSet< T, BitVectorTy > & Lhs, const BitVectorSet< T, BitVectorTy > & Rhs) friend
Definition at line 266 of file BitVectorSet.h.
operator<<
template<typename T , typename BitVectorTy = llvm::BitVector> llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const BitVectorSet< T, BitVectorTy > & B) friend
Definition at line 285 of file BitVectorSet.h.
operator==
template<typename T , typename BitVectorTy = llvm::BitVector> bool operator== (const BitVectorSet< T, BitVectorTy > & Lhs, const BitVectorSet< T, BitVectorTy > & Rhs) friend
Definition at line 237 of file BitVectorSet.h.
The documentation for this class was generated from the following file:
include/phasar/Utils/BitVectorSet.h