PhASAR: psr::EdgeFunctionCache< ProblemTy > Class Template Reference
psr::EdgeFunctionCache< ProblemTy > Class Template Reference
#include "phasar/DataFlow/IfdsIde/Solver/EdgeFunctionCache.h"
Public Types
using EdgeFunctionPtrType = EdgeFunction< l_t >
Public Member Functions
EdgeFunctionCache () noexcept=default
EdgeFunctionPtrType getNormalEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > Curr, ByConstRef< d_t > CurrNode, ByConstRef< n_t > Succ, ByConstRef< d_t > SuccNode, uint64_t CurrSuccId, uint64_t CurrNodeSuccNodeId)
EdgeFunctionPtrType getCallToRetEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > CallNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, llvm::ArrayRef< f_t > Callees, uint64_t CallRetId, uint64_t CallNodeRetNodeId)
EdgeFunctionPtrType getCallEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > SrcNode, ByConstRef< f_t > Callee, ByConstRef< d_t > DestNode, uint64_t CSCalleeId, uint64_t SrcDestNodeId)
EdgeFunctionPtrType getReturnEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, ByConstRef< n_t > ExitInst, ByConstRef< d_t > ExitNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, uint32_t ExitId, uint64_t CSRSId, uint64_t ExitRSNodeId)
EdgeFunctionPtrType getSummaryEdgeFunction (ProblemTy &Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > CallNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, uint64_t CSRSId, uint64_t CSNodeRSNodeId)
void clear ()
void dumpStats (llvm::raw_ostream &OS) const
EdgeFunctionCacheStats getStats () const noexcept
Detailed Description
template<typename ProblemTy>
class psr::EdgeFunctionCache< ProblemTy >
Definition at line 18 of file EdgeFunctionCache.h.
Member Typedef Documentation
EdgeFunctionPtrType
template<typename ProblemTy > using psr::EdgeFunctionCache< ProblemTy >::EdgeFunctionPtrType = EdgeFunction<l_t>
Definition at line 28 of file EdgeFunctionCache.h.
Constructor & Destructor Documentation
EdgeFunctionCache()
template<typename ProblemTy > psr::EdgeFunctionCache< ProblemTy >::EdgeFunctionCache () default noexcept
Member Function Documentation
clear()
template<typename ProblemTy > void psr::EdgeFunctionCache< ProblemTy >::clear () inline
Definition at line 110 of file EdgeFunctionCache.h.
Referenced by psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::clear().
dumpStats()
template<typename ProblemTy > void psr::EdgeFunctionCache< ProblemTy >::dumpStats (llvm::raw_ostream & OS) const inline
Definition at line 119 of file EdgeFunctionCache.h.
References psr::EdgeFunctionCache< ProblemTy >::getStats().
getCallEdgeFunction()
template<typename ProblemTy > EdgeFunctionPtrType psr::EdgeFunctionCache< ProblemTy >::getCallEdgeFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > SrcNode, ByConstRef< f_t > Callee, ByConstRef< d_t > DestNode, uint64_t CSCalleeId, uint64_t SrcDestNodeId) inline
Definition at line 63 of file EdgeFunctionCache.h.
References psr::EdgeFunctionCacheStats::CallEFCacheCumulSize.
getCallToRetEdgeFunction()
template<typename ProblemTy > EdgeFunctionPtrType psr::EdgeFunctionCache< ProblemTy >::getCallToRetEdgeFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > CallNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, llvm::ArrayRef< f_t > Callees, uint64_t CallRetId, uint64_t CallNodeRetNodeId) inline
Definition at line 46 of file EdgeFunctionCache.h.
References psr::EdgeFunctionCacheStats::NormalAndCtrEFCacheCumulSize.
getNormalEdgeFunction()
template<typename ProblemTy > EdgeFunctionPtrType psr::EdgeFunctionCache< ProblemTy >::getNormalEdgeFunction (ProblemTy & Problem, ByConstRef< n_t > Curr, ByConstRef< d_t > CurrNode, ByConstRef< n_t > Succ, ByConstRef< d_t > SuccNode, uint64_t CurrSuccId, uint64_t CurrNodeSuccNodeId) inline
Definition at line 31 of file EdgeFunctionCache.h.
References psr::EdgeFunctionCacheStats::NormalAndCtrEFCacheCumulSize.
getReturnEdgeFunction()
template<typename ProblemTy > EdgeFunctionPtrType psr::EdgeFunctionCache< ProblemTy >::getReturnEdgeFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< f_t > Callee, ByConstRef< n_t > ExitInst, ByConstRef< d_t > ExitNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, uint32_t ExitId, uint64_t CSRSId, uint64_t ExitRSNodeId) inline
Definition at line 78 of file EdgeFunctionCache.h.
References psr::EdgeFunctionCacheStats::RetEFCacheCumulSize.
getStats()
template<typename ProblemTy > EdgeFunctionCacheStats psr::EdgeFunctionCache< ProblemTy >::getStats () const inline noexcept
Definition at line 121 of file EdgeFunctionCache.h.
References psr::EdgeFunctionCacheStats::NormalAndCtrEFCacheCumulSizeReduced, and psr::Ret.
Referenced by psr::EdgeFunctionCache< ProblemTy >::dumpStats(), and psr::FlowEdgeFunctionCacheNG< ProblemTy, AutoAddZero >::getStats().
getSummaryEdgeFunction()
template<typename ProblemTy > EdgeFunctionPtrType psr::EdgeFunctionCache< ProblemTy >::getSummaryEdgeFunction (ProblemTy & Problem, ByConstRef< n_t > CallSite, ByConstRef< d_t > CallNode, ByConstRef< n_t > RetSite, ByConstRef< d_t > RetSiteNode, uint64_t CSRSId, uint64_t CSNodeRSNodeId) inline
Definition at line 95 of file EdgeFunctionCache.h.
References psr::EdgeFunctionCacheStats::SummaryEFCacheCumulSize.
The documentation for this class was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/EdgeFunctionCache.h