PhASAR: psr Namespace Reference
psr Namespace Reference
Namespaces
namespace detail
A class that implements a control flow graph. Conforms to the CFGBase CRTP interface.
namespace glca
namespace internal
namespace library_summary
namespace vta
namespace XTaint
Classes
class AbstractMemoryLocation
class AbstractMemoryLocationFactory
class AbstractMemoryLocationFactory< AbstractMemoryLocation >
struct AdjacencyList
struct AdjacencyList< EmptyType, VtxId, EdgeTy >
class AliasAnalysisView
class AliasInfo
Similar to AliasInfoRef, but exclusively owns the held reference. Use this, if you need to decide dynamically, which alias info implementation to use.
class AliasInfoBaseUtils
class AliasInfoRef
A type-erased reference to any object implementing the IsAliasInfo interface. Use this, if your analysis is not tied to a specific alias info implementation.
struct AliasInfoTraits
struct AliasInfoTraits< AliasInfo< V, N > >
struct AliasInfoTraits< AliasInfoRef< V, N > >
struct AliasInfoTraits< CachedLLVMAliasIterator >
struct AliasInfoTraits< FilteredLLVMAliasSet >
struct AliasInfoTraits< LLVMAliasSet >
class AliasIteratorRef
A type-erased reference to any object implementing the IsAliasIterator interface. Use this, if your alias-aware analysis just needs a minimal interface to work with aliases and does not require the versatility of AliasInfoRef.
class AliasSetOwner
struct AlignNum
struct AlignStr
struct AllBottom
struct AllTop
class AllTopFnProvider
class AllTopFnProvider< AnalysisDomainTy >
struct AnalysisDomain
class AnalysisPrinterBase
A generic class that serves as the basis for a custom analysis printer implementation.
class AnalysisPropertiesMixin
struct AnalysisSetup
class BasicBlockOrdering
class BitSet
A set-type that can compactly store sets of sequential integer-like types.
class BitVectorSet
Implements a set that requires minimal space.
struct Bottom
class BoxedConstPtr
class BoxedPtr
A T** that behaves like a T*. Used as AliasSetPtr in LLVMAliasSet.
struct CachedEdgeFunction
class CachedLLVMAliasIterator
A wrapper over a LLVMAliasIteratorRef that adds caching to make it conform to the LLVMAliasInfoRef interface.
class CallGraph
class CallGraphBase
class CallGraphBuilder
struct CallGraphData
class CallStringCTX
class CFG
class CFGBase
struct CFGTraits
struct CFGTraits< LLVMBasedBackwardCFG >
struct CFGTraits< LLVMBasedBackwardICFG >
struct CFGTraits< LLVMBasedCFG >
struct CFGTraits< LLVMBasedICFG >
struct CFGTraits< SparseLLVMBasedCFG >
struct CFGTraits< SparseLLVMBasedICFGView >
struct CGTraits
struct CGTraits< CallGraph< N, F > >
class CHAResolver
A resolver that performs Class Hierarchy Analysis to resolve calls to C++ virtual functions. Requires debug information.
class ClangController
class Compressor
class Compressor< T, IdT >
A utility class that assigns a sequential Id to every inserted object.
struct ConstantEdgeFunction
class CRTPBase
class CSTDFILEIOTypeStateDescription
struct DebugLocation
Minimal source-code information, based on LLVM debug information.
struct DefaultAATraits
class DefaultAliasAwareIDEProblem
class DefaultAliasAwareIFDSProblem
class DefaultAnalysisPrinter
A default implementation of the AnalysisPrinterBase. Aggregates all analysis results in a vector and prints them when the analysis is finished.
struct DefaultAnalysisPrinterSelector
struct DefaultAnalysisPrinterSelector< LLVMIFDSAnalysisDomainDefault >
struct DefaultAnalysisSetup
struct DefaultConstruct
Delegates to the ctor of T.
class DefaultDominatorTreeAnalysis
class DefaultEdgeFunctionSingletonCache
class DefaultEdgeFunctionSingletonCache< EdgeFunctionTy >
class DefaultEdgeFunctionSingletonCacheImpl
struct DefaultIDESolverConfig
struct DefaultIDESolverConfig< ProblemTy >
class DefaultLLVMAnalysisPrinter
class DefaultMapKeyCompressor
class DefaultNoAliasIDEProblem
class DefaultNoAliasIFDSProblem
struct DefaultNodeTransform
class DefaultReachableAllocationSitesIDEProblem
class DefaultReachableAllocationSitesIFDSProblem
class DemandDrivenAnalysis
class DenseSet
class DenseTable1d
class DenseTable1d< K, EmptyType >
class DequeWorkList
class DIBasedTypeHierarchy
Represents the type hierarchy of the target program.
struct DIBasedTypeHierarchyData
A structure that is used to store already calculated type hierarchy data, serialize that data or deserialize a json file with a previously serialized type hierarchy.
class DOTConfig
struct DOTEdge
struct DOTFactSubGraph
struct DOTFunctionSubGraph
struct DOTGraph
struct DOTNode
class DummyDenseTable1d
A set that appears as map mapping to a constant.
struct DummyPair
A wrapper over a single object that pretends to be a std::pair.
class DummyUnorderedTable1d
class EdgeFunction
Ref-counted and type-erased edge function with small-object optimization. Supports caching.
class EdgeFunctionBase
class EdgeFunctionCache
struct EdgeFunctionCacheStats
struct EdgeFunctionComposer
class EdgeFunctionRef
Non-null reference to an edge function that is guarenteed to be managed by an EdgeFunction object.
class EdgeFunctions
class EdgeFunctionSingletonCache
class EdgeFunctionStats
struct EdgeIdentity
struct EmptyType
struct EnumFlagAutoBool
struct EquivalenceClassMap
EquivalenceClassMap is a special map type that splits the keys into equivalence classes regarding their mapped values.
class EquivalenceClassMapNG
class ExampleModulePass
struct FalseFn
class FeatureTaintGenerator
class FilteredLLVMAliasIterator
class FilteredLLVMAliasSet
class FlowEdgeFunctionCache
class FlowEdgeFunctionCacheNG
struct FlowEdgeFunctionCacheStats
class FlowFunction
class FlowFunctionCache
struct FlowFunctionCacheStats
class FlowFunctions
class FlowFunctionTemplates
struct FlowPath
struct fn_t
A helper that transforms a statically known function pointer into a type.
class FunctionAliasView
struct FunctionData
struct GeneralStatistics
class GeneralStatisticsAnalysis
Computes general statistics for a Module.
class GenericFlowFunction
Encapsulates a managed pointer to a FlowFunction.
class GenericFlowFunctionView
Encapsulates an unmanaged pointer to a FlowFunction.
class GenericSolverResults
A type-erased version of the main functionality of SolverResults. Can be accepted by consumers that don't need deep access to the internals (so, the usual ones). As we have now two kinds of solver-results (SolverResults and IdBasedSolverResults), we need a common way of accessing them.
class GlobalAnnotation
class GlobalCtorsDtorsModel
Provides utilities to inject a function into the IR under analysis that captures global constructors and destructors as described in the 2021 Paper "Modeling the Effects of Global Variables in Data-Flow Analysis for C/C++" by Schubert et al.
struct GraphTraits
struct GraphTraits< AdjacencyList< T, VtxId, EdgeTy > >
A simple graph implementation based on an adjacency list.
struct GraphTraits< SCCDependencyGraph< GraphNodeId > >
Implements the is_const_graph concept for SCCDependencyGraph.
struct GraphTraits< vta::TypeAssignmentGraph >
struct has_getAsJson
struct has_getAsJson< T, std::void_t< decltype(std::declval< const T >() .getAsJson())> >
struct has_getHashCode
struct has_getHashCode< T, decltype(std::declval< const T >().getHashCode())>
struct has_std_hash
struct has_std_hash< T, decltype(std::hash< T >{}(std::declval< const T >))>
struct HasNoConfigurationType
Indicates that an analysis does not need a special configuration (file).
class HelperAnalyses
struct HelperAnalysisConfig
struct hms
class ICFG
class ICFGBase
class IdBasedSolverResults
class IDEExtendedTaintAnalysis
struct IDEExtendedTaintAnalysisDomain
class IDEFeatureTaintAnalysis
struct IDEFeatureTaintAnalysisDomain
struct IDEFeatureTaintEdgeFact
class IDEGeneralizedLCA
An implementation of a linear constant analysis, similar to IDELinearConstantAnalysis, but with an extended edge-Value domain. Instead of using single Values, we use a bounded set of cadidates to increase precision.
struct IDEGeneralizedLCADomain
class IDEIIAFlowFact
struct IDEInstInteractionAnalysisDomain
class IDEInstInteractionAnalysisT
class IDELinearConstantAnalysis
struct IDELinearConstantAnalysisDomain
struct identity
struct IdentityFn
class IDEProtoAnalysis
struct IDEProtoAnalysisDomain
class IDESecureHeapPropagation
struct IDESecureHeapPropagationAnalysisDomain
class IDESolver
class IDESolverAPIMixin
struct IDESolverConfigBase
class IDESolverTest
struct IDESolverTestAnalysisDomain
class IDETabulationProblem
The analysis problem interface for IDE problems (solvable by the IDESolver). Create a subclass from this and override all pure-virtual functions to create your own IDE analysis.
class IDETypeStateAnalysis
struct IDETypeStateAnalysisDomain
class IFDSConstAnalysis
Computes all possibly mutable memory locations.
struct IFDSIDESolverConfig
Configuration options for the solving process of IFDS/IDE problems.
class IFDSProtoAnalysis
class IFDSSignAnalysis
class IFDSSolver
Solves the given IFDSTabulationProblem as described in the 1995 paper by Reps, Horwitz and Sagiv. To solve the problem, call solve(). Results can then be queried by using resultAt() and resultsAt().
class IFDSSolverTest
class IFDSTabulationProblem
The analysis problem interface for IFDS problems (solvable by the IFDSSolver). Create a subclass from this and override all pure-virtual functions to create your own IFDS analysis.
class IFDSTaintAnalysis
class IFDSTypeAnalysis
class IFDSUninitializedVariables
struct IgnoreArgs
class IncrementalUpdateAnalysis
class InitialSeeds
Represent the starting points of the analysis.
class InitPhasar
class InterMonoFullConstantPropagation
class InterMonoProblem
The analysis problem interface for interprocedural monotone problems (solvable by the InterMonoSolver). Create a subclass from this and override all pure-virtual functions to create your own inter-mono analysis.
class InterMonoSolver
A solver class for interprocedual monotone problems (derived from InterMonoProblem). To solve the problem, call solve().
class InterMonoSolverTest
struct InterMonoSolverTestDomain
class InterMonoTaintAnalysis
struct InterMonoTaintAnalysisDomain
struct IntraMonoFCAFact
class IntraMonoFullConstantPropagation
struct IntraMonoFullConstantPropagationAnalysisDomain
class IntraMonoProblem
The analysis problem interface for intraprocedural monotone problems (solvable by the IntraMonoSolver). Create a subclass from this and override all pure-virtual functions to create your own mono analysis.
class IntraMonoSolver
A solver class for intraprocedual monotone problems. To solve the problem, call solve().
class IntraMonoSolverTest
struct IntraMonoSolverTestAnalysisDomain
class IntraMonoUninitVariables
struct IntraMonoUninitVariablesDomain
class IotaIterator
struct is_pathtracingfilter_for
struct is_pathtracingfilter_for< PathTracingFilter< EndFilter, ErrFilter >, NodeRef >
struct is_variant
struct is_variant< std::variant< Args... > >
struct IsFlowFunction
class IterativeIDESolver
class IterativeIDESolverBase
struct IterativeIDESolverStats
struct IterIDEPropagationJob
struct JoinEdgeFunction
class JoinLattice
class JoinLattice< AnalysisDomainTy >
struct JoinLatticeTraits
struct JoinLatticeTraits< BinaryDomain >
struct JoinLatticeTraits< CSTDFILEIOState >
struct JoinLatticeTraits< glca::EdgeValueSet >
struct JoinLatticeTraits< IDEFeatureTaintEdgeFact >
struct JoinLatticeTraits< LatticeDomain< L > >
struct JoinLatticeTraits< SecureHeapValue >
struct JoinLatticeTraits< XTaint::EdgeDomain >
class JumpFunctions
struct LatticeDomain
A easy shorthand to construct a complete lattice of L.
class LLVMAliasSet
struct LLVMAliasSetData
struct LLVMAnalysisDomainDefault
An AnalysisDomain that specializes sensible defaults for LLVM-based analysis.
class LLVMBasedBackwardCFG
A class that represents a backwards control flow graph. Conforms to the CFGBase CRTP interface.
class LLVMBasedBackwardICFG
A class that represents a backwards interprocedural control flow graph. Conforms to the ICFGBase CRTP interface.
class LLVMBasedCFG
class LLVMBasedICFG
A class that implements a inter-procedural control flow graph. Conforms to the ICFGBase CRTP interface.
class LLVMMapKeyCompressor
class LLVMPathConstraints
class LLVMProjectIRDB
Project IR Database that manages a LLVM IR module.
class LLVMSourceManager
class LLVMTaintConfig
struct LLVMValueIDLess
Does less-than comparison based on the annotated ID.
class LLVMVFTable
Represents a virtual method table.
struct LLVMVFTableData
class LLVMVFTableProvider
A class that provides access to all C++ virtual function tables (VTables) found in the target program.
class LLVMZeroValue
This class may be used to represent the special zero value (aka. Λ) for IFDS and IDE problems. The LLVMZeroValue is implemented as a singleton.
class Logger
struct ManagedDebugLocation
class MapKeyCompressorCombinator
class MaybeUniquePtr
class ModulesToSlotTracker
class ModuleWiseAnalysis
struct NodeCompressorTraits
struct NoneCompressor
struct NonTopBotValue
struct NonTopBotValue< LatticeDomain< L > >
struct NonTopBotValue< XTaint::EdgeDomain >
class NOResolver
A resolver that doesn't resolve indirect- and virtual calls.
class NullAnalysisPrinter
class OnTheFlyAnalysisPrinter
class OpenSSLEVPKDFCTXDescription
class OpenSSLEVPKDFDescription
class OpenSSLSecureHeapDescription
class OpenSSLSecureMemoryDescription
class OTFResolver
A resolver that uses alias information to resolve indirect and virtual calls.
struct Overloaded
class OwningSolverResults
struct PairHash
class PAMM
This class offers functionality to assist a performance analysis of the PhASAR framework.
class PathAwareIDESolver
class PathEdge
struct PathSensitivityConfig
struct PathSensitivityConfigBase
class PathSensitivityManager
A utility class that allows path-reconstruction for IFDS/IDE solver results.
class PathSensitivityManagerBase
class PathSensitivityManagerMixin
struct PathTracingFilter
class PhasarConfig
class PhasarPass
PhasarPass is an implementation of llvm passes for the PhASAR framework.
class PhasarPrinterPass
class PointsToInfo
class PointsToInfo< PTATraits >
class PointsToInfoBase
class PointsToInfoRef
class PointsToInfoRef< PTATraits >
class PointsToIterator
Owning version of PointsToIteratorRef.
class PointsToIteratorRef
struct PointsToTraits
struct PointsToTraits< PointsToInfo< PTATraits > >
struct PointsToTraits< PointsToInfoRef< PTATraits > >
class PrecomputedResolver
A Resolver that uses a pre-computed call-graph to resolve indirect calls.
struct PrettyPrinter
class ProjectIRDBBase
struct ProjectIRDBTraits
struct ProjectIRDBTraits< LLVMProjectIRDB >
class RandomChangeASTConsumer
class RandomChangeFrontendAction
class RandomChangeVisitor
struct Ref2PointerConverter
class RepeatIterator
An iterator that iterates over the same value a specified number of times.
class Resolver
A base class for call-target resolvers. Used to build call graphs.
class RTAResolver
A resolver that performs Rapid Type Analysis to resolve calls to C++ virtual functions. Requires debug information.
struct Sampler
struct SCCDependencyGraph
Holds a graph where the SCCs are collapsed to a single node. Conforms to the is_const_graph concept.
struct SCCHolder
Holds the SCCs of a given graph. Each SCC is assigned a unique sequential id.
struct SCCId
The Id of a strongly-connected component in a graph.
struct SCCOrder
Holds topologically sorted SCCDependencyGraph nodes.
class scope_exit
See https://en.cppreference.com/w/cpp/experimental/scope_exit/scope_exit
class SemiRing
class SimpleTimer
class SmallDenseTable1d
class SmallDenseTable1d< K, EmptyType, N >
class SmallVectorWorkList
class SolverResults
struct SolverStatsSelector
struct SolverStatsSelector< StaticSolverConfigTy >
struct SourceCodeInfo
A struct that contains information about a source code line, function name, file name corresponding to the IR statement.
class SourceMgrPrinter
class SparseCFGBase
class SparseCFGProvider
class SparseLLVMBasedCFG
A class that implements a sparse control flow graph. Conforms to the CFGBase CRTP interface.
class SparseLLVMBasedICFG
A class that implements a sparse interprocedural control flow graph. Conforms to the ICFGBase CRTP interface.
class SparseLLVMBasedICFGView
Similar to SparseLLVMBasedICFG; the only difference is that this one is no LLVMBasedICFG – it contains a pointer to an already existing one. It still owns the sparse value-flow graphs.
class StableVector
struct StringIDLess
struct SVFPointsToInfoTraits
class Table
class TaintConfigBase
struct TaintConfigData
struct TaintConfigTraits
struct TaintConfigTraits< LLVMTaintConfig >
class Timer
struct Top
struct TrueFn
class TypedVector
struct TypeErasureUtils
class TypeHierarchy
struct TypeStateDescription
struct TypeStateDescriptionBase
class UnorderedSet
class UnorderedTable1d
class UnorderedTable1d< K, EmptyType >
struct ValCompressorTraits
struct ValCompressorTraits< T >
class ValueAnnotationPass
Annotates every Instruction with a unique ID.
class VarAnnotation
struct VariableData
class VariationalAnalysis
class VectorWorkList
class VFTable
A generic class to represent a virtual function table.
class VTAResolver
A Resolver that uses a variant of the Variable Type Analysis to resolver indirect calls.
struct Warning
struct WithComputeValues
struct WithEndSummaryTab
struct WithGCMode
struct WithStats
struct WithWorkList
struct Z3BasedPathSensitivityConfig
class Z3BasedPathSensitivityManager
An extension of the path-reconstruction mechanism of the PathSensitivityManager that provides means to extract concrete combined control- and data-flow paths.
class Z3BasedPathSensitivityManagerBase
class ZeroedFlowFunction
Concepts
concept is_cfg_v
concept is_icfg_v
concept IsEdgeFunction
concept is_flowfunction_v
concept is_pathtracingfilter_for_v
concept IsAliasInfo
concept IsAliasIterator
concept is_PointsToTraits_v
concept is_equivalent_PointsToTraits_v
concept IsPointsToIterator
concept CanEfficientlyPassByValue
concept is_graph_edge
concept is_const_graph_trait
concept is_graph_trait
concept is_weighted_const_graph_trait
concept is_weighted_graph_trait
concept is_const_graph
concept is_graph
concept is_weighted_const_graph
concept is_weighted_graph
concept is_reservable_graph_trait_v
concept is_removable_graph_trait_v
concept HasJoinLatticeTraits
concept same_as_decay
concept derived_from_decay
concept is_iterable_v
concept is_iterable_over_v
concept is_pair_v
concept is_tuple_v
concept is_printable_v
concept is_llvm_printable_v
concept is_std_printable_v
concept has_str_v
concept has_adl_to_string_v
concept has_erase_iterator_v
concept is_std_hashable_v
concept is_llvm_hashable_v
concept is_variant_v
concept is_string_like_v
concept is_crtp_base_of_v
concept HasIsConstant
concept HasDepth
concept IsEqualityComparable
concept AreEqualityComparable
concept IsLessComparable
concept has_isInteresting_v
concept is_explicitly_convertible_to
concept has_reserve_v
Typedefs
template<is_flowfunction_v FF>
using FlowFunctionPtrTypeOf = std::shared_ptr< FF >
Given a flow-function type FF, returns a (smart) pointer type pointing to FF.
template<typename D , typename Container = std::set<D>>
using FlowFunctionPtrType = FlowFunctionPtrTypeOf< FlowFunction< D, Container > >
template<typename Problem >
using IDESolver_P = IDESolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
template<typename Problem >
using IFDSSolver_P = IFDSSolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
using IDESolverConfig = WithComputeValues< IDESolverConfigBase, true >
using IFDSSolverConfig = WithComputeValues< IDESolverConfigBase, false >
using IDESolverConfigWithStats = WithStats< IDESolverConfig, true >
using IFDSSolverConfigWithStats = WithStats< IFDSSolverConfig, true >
using IFDSSolverConfigWithStatsAndGC = WithGCMode< IFDSSolverConfigWithStats, JumpFunctionGCMode::Enabled >
template<typename Problem , unsigned K>
using InterMonoSolver_P = InterMonoSolver< typename Problem::ProblemAnalysisDomain, K >
template<typename Problem >
using IntraMonoSolver_P = IntraMonoSolver< typename Problem::ProblemAnalysisDomain >
template<typename N >
using FlowPathSequence = std::vector< FlowPath< N > >
using DefaultPathTracingFilter = PathTracingFilter< detail::False2, detail::False2 >
template<typename AnalysisDomainTy >
using WithBinaryValueDomain = std::conditional_t< detail::HasBinaryValueDomain< AnalysisDomainTy >::value, AnalysisDomainTy, detail::WithBinaryValueDomainExtender< AnalysisDomainTy > >
using LLVMBasedCallGraph = CallGraph< const llvm::Instruction *, const llvm::Function * >
template<typename Derived >
using SparseLLVMBasedCFGProvider = SparseCFGProvider< Derived, const llvm::Function *, const llvm::Value * >
using IDEInstInteractionAnalysis = IDEInstInteractionAnalysisT<>
using LLVMIFDSAnalysisDomainDefault = WithBinaryValueDomain< LLVMAnalysisDomainDefault >
An AnalysisDomain that specializes sensible defaults for LLVM-based IFDS analysis.
using LLVMAliasIteratorRef = AliasIteratorRef< const llvm::Value *, const llvm::Instruction * >
using LLVMAliasInfoRef = AliasInfoRef< const llvm::Value *, const llvm::Instruction * >
using LLVMAliasInfo = AliasInfo< const llvm::Value *, const llvm::Instruction * >
using LLVMPointsToIteratorRef = PointsToIteratorRef< const llvm::Value *, const llvm::Value *, const llvm::Instruction * >
using LLVMPointsToIterator = PointsToIterator< const llvm::Value *, const llvm::Value *, const llvm::Instruction * >
using SVFBasedPointsToInfo = PointsToInfo< SVFPointsToInfoTraits >
using SVFBasedPointsToInfoRef = PointsToInfoRef< SVFPointsToInfoTraits >
using SVFBasedPointsToIterator = PointsToIterator< const llvm::Value *, uint32_t, const llvm::Instruction * >
using SVFBasedPointsToIteratorRef = PointsToIteratorRef< const llvm::Value *, uint32_t, const llvm::Instruction * >
using FunctionRange = llvm::iterator_range< llvm::mapped_iterator< llvm::Module::const_iterator, Ref2PointerConverter< llvm::Function > > >
template<typename T >
using ByConstRef = std::conditional_t< CanEfficientlyPassByValue< T >, T, const T & >
template<typename T >
using ByMoveRef = std::conditional_t< CanEfficientlyPassByValue< T >, T, T && >
template<typename IdT >
using IotaRangeType = llvm::iterator_range< IotaIterator< IdT > >
template<typename T >
using Nullable = std::conditional_t< std::is_convertible_v< T, bool >, T, std::optional< T > >
template<typename T >
using RepeatRangeType = llvm::iterator_range< RepeatIterator< T > >
template<typename Container >
using ElementType = typename detail::ElementType< Container >::type
Enumerations
enum class AnalysisStrategy { None , ANALYSIS_STRATEGY_TYPES }
enum class CallGraphAnalysisType { CALL_GRAPH_ANALYSIS_TYPE , Invalid }
enum class SpecialMemberFunctionType { SPECIAL_MEMBER_FUNCTION_TYPES }
enum class EdgeFunctionAllocationPolicy { SmallObjectOptimized , DefaultHeapAllocated , CustomHeapAllocated }
enum class SolverConfigOptions : uint32_t {
None = 0 , FollowReturnsPastSeeds = 1 , AutoAddZero = 2 , ComputeValues = 4 ,
RecordEdges = 8 , EmitESG = 16 , ComputePersistedSummaries = 32 , All = ~0U
}
enum class ESGEdgeKind {
Normal , Call , CallToRet , SkipUnknownFn ,
Ret , Summary
}
enum class EdgeFunctionKind {
Normal , Call , Return , CallToReturn ,
Summary
}
enum class JumpFunctionGCMode { Disabled , Enabled , EnabledAggressively }
enum class BinaryDomain { BOTTOM = 0 , TOP = 1 }
enum class SecureHeapFact { ZERO , INITIALIZED }
enum class SecureHeapValue { TOP , INITIALIZED , BOT }
enum class CSTDFILEIOState {
TOP = 42 , UNINIT = 0 , OPENED = 1 , CLOSED = 2 ,
ERROR = 3 , BOT = 4
}
enum class OpenSSLEVPKDFCTXState {
TOP = 42 , UNINIT = 5 , CTX_ATTACHED = 1 , PARAM_INIT = 2 ,
DERIVED = 3 , ERROR = 4 , BOT = 0
}
enum class OpenSSLEVPKDFState {
TOP = 42 , UNINIT = 0 , KDF_FETCHED = 1 , ERROR = 2 ,
BOT = 3
}
enum class OpenSSLSecureHeapState {
TOP = 42 , BOT = 0 , UNINIT = 1 , ALLOCATED = 2 ,
ZEROED = 3 , FREED = 4 , ERROR = 5
}
enum class SVFPointsToAnalysisType { DDA = int(AliasAnalysisType::SVFDDA) , VFS = int(AliasAnalysisType::SVFVFS) }
enum class TaintCategory { None , Source , Sink , Sanitizer }
enum class DataFlowAnalysisType { None , DATA_FLOW_ANALYSIS_TYPES }
enum class AliasAnalysisType { ALIAS_ANALYSIS_TYPE , Invalid }
enum class AliasResult { ALIAS_RESULT_TYPE }
enum class AnalysisProperties { None = 0 , FlowSensitive = (1 << 0) , ContextSensitive = (1 << 1) , FieldSensitive = (1 << 2) }
enum SeverityLevel { INVALID }
enum class PAMM_SEVERITY_LEVEL { Off = 0 , Core , Full }
Defines the different level of severity of PAMM's performance evaluation.
enum class Soundness { SOUNDNESS_FLAG_TYPE , Invalid }
Functions
std::string toString (const AnalysisStrategy &S)
AnalysisStrategy toAnalysisStrategy (llvm::StringRef S)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, AnalysisStrategy S)
std::string toString (CallGraphAnalysisType CGA)
CallGraphAnalysisType toCallGraphAnalysisType (llvm::StringRef S)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, CallGraphAnalysisType CGA)
template<typename T >
T valueOf (T Val)
std::string toString (SpecialMemberFunctionType SMFT)
SpecialMemberFunctionType toSpecialMemberFunctionType (llvm::StringRef SMFT)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, SpecialMemberFunctionType SMFT)
template<typename EdgeFunctionTy >
CachedEdgeFunction (EdgeFunctionTy, EdgeFunctionSingletonCache< EdgeFunctionTy > *) -> CachedEdgeFunction< EdgeFunctionTy >
template<typename L >
requires CanEfficientlyPassByValue<ConstantEdgeFunction<L>>
constexpr bool operator== (ConstantEdgeFunction< L > LHS, ConstantEdgeFunction< L > RHS) noexcept
template<typename L >
requires (!CanEfficientlyPassByValue<ConstantEdgeFunction<L>>)
constexpr bool operator== (const ConstantEdgeFunction< L > &LHS, const ConstantEdgeFunction< L > &RHS) noexcept
template<typename L >
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, ByConstRef< ConstantEdgeFunction< L > > Id)
template<typename L , typename ConcreteEF >
EdgeFunction< L > defaultComposeOrNull (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< L > &SecondFunction) noexcept
template<typename L >
EdgeFunction< L > defaultComposeOrNull (const EdgeFunction< L > &This, const EdgeFunction< L > &SecondFunction) noexcept
template<typename L , uint8_t N = 0, typename ConcreteEF >
EdgeFunction< L > defaultJoinOrNull (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< L > &OtherFunction)
template<typename L , uint8_t N = 0>
EdgeFunction< L > defaultJoinOrNull (const EdgeFunction< L > &This, const EdgeFunction< L > &OtherFunction)
template<typename EntryRange , typename C , typename DB , typename HandlerFn >
void forallStartingPoints (const EntryRange &EntryPoints, const ProjectIRDBBase< DB > *IRDB, const CFGBase< C > &CFG, HandlerFn Handler)
template<typename EntryRange , typename I , typename HandlerFn >
void forallStartingPoints (const EntryRange &EntryPoints, const I *ICF, HandlerFn Handler)
template<typename EntryRange , typename C , typename DB , typename SeedsT , typename D , typename L >
requires (std::is_convertible_v<L, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>)
void addSeedsForStartingPoints (const EntryRange &EntryPoints, const ProjectIRDBBase< DB > *IRDB, const CFGBase< C > &CFG, SeedsT &Seeds, const D &ZeroValue, const L &BottomValue)
template<typename EntryRange , typename I , typename SeedsT , typename D , typename L >
requires (std::is_convertible_v<L, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>)
void addSeedsForStartingPoints (const EntryRange &EntryPoints, const I *ICF, SeedsT &Seeds, const D &ZeroValue, const L &BottomValue)
template<typename EntryRange , typename C , typename DB , typename SeedsT , typename D >
requires (std::is_same_v<BinaryDomain, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>)
void addSeedsForStartingPoints (const EntryRange &EntryPoints, const ProjectIRDBBase< DB > *IRDB, const CFGBase< C > &CFG, SeedsT &Seeds, const D &ZeroValue)
Simplification for IFDS, passing BinaryDomain::BOTTOM as L.
template<typename EntryRange , typename I , typename SeedsT , typename D >
requires (std::is_same_v<BinaryDomain, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>)
void addSeedsForStartingPoints (const EntryRange &EntryPoints, const I *ICF, SeedsT &Seeds, const D &ZeroValue)
Simplification for IFDS, passing BinaryDomain::BOTTOM as L.
constexpr bool isInterProc (ESGEdgeKind Kind) noexcept
template<typename SR1 , typename SR2 >
bool ifdsEqual (const SR1 &LHS, const SR2 &RHS)
template<typename SR1 , typename SR2 >
bool checkSREquality (const SR1 &LHS, const SR2 &RHS)
template<typename AnalysisDomainTy , typename Container >
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const IDESolver< AnalysisDomainTy, Container > &Solver)
template<typename Problem , typename ICF >
IDESolver (Problem &, ICF *) -> IDESolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
template<typename Problem , typename ICF >
IDESolver (Problem *, ICF *) -> IDESolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
template<typename AnalysisDomainTy , typename Container >
OwningSolverResults< typename AnalysisDomainTy::n_t, typename AnalysisDomainTy::d_t, typename AnalysisDomainTy::l_t > solveIDEProblem (IDETabulationProblem< AnalysisDomainTy, Container > &Problem, const typename AnalysisDomainTy::i_t &ICF)
template<typename Problem , typename ICF >
IFDSSolver (Problem &, ICF *) -> IFDSSolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
template<typename Problem , typename ICF >
IFDSSolver (Problem *, ICF *) -> IFDSSolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
template<typename AnalysisDomainTy , typename Container >
OwningSolverResults< typename AnalysisDomainTy::n_t, typename AnalysisDomainTy::d_t, BinaryDomain > solveIFDSProblem (IFDSTabulationProblem< AnalysisDomainTy, Container > &Problem, const typename AnalysisDomainTy::i_t &ICF)
template<typename ProblemTy >
PathAwareIDESolver (ProblemTy &) -> PathAwareIDESolver< typename ProblemTy::ProblemAnalysisDomain >
std::string getMetaDataID (const llvm::Value *V)
Returns the ID of a given LLVM Value.
template<typename Problem >
IntraMonoSolver (Problem &) -> IntraMonoSolver< typename Problem::ProblemAnalysisDomain >
template<typename DB >
auto IRDBGetFunctionDef (const ProjectIRDBBase< DB > *IRDB) noexcept
std::string to_string (BinaryDomain B)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, BinaryDomain B)
template<typename L >
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const LatticeDomain< L > &LD)
template<typename L >
std::ostream & operator<< (std::ostream &OS, const LatticeDomain< L > &LD)
template<typename L >
bool operator== (const LatticeDomain< L > &Lhs, const LatticeDomain< L > &Rhs)
template<typename L , typename LL >
requires AreEqualityComparable<LL, L>
bool operator== (const LL &Lhs, const LatticeDomain< L > &Rhs)
template<typename L , typename LL >
requires AreEqualityComparable<LL, L>
bool operator== (const LatticeDomain< L > &Lhs, const LL &Rhs)
template<typename L >
bool operator== (const LatticeDomain< L > &Lhs, Bottom) noexcept
template<typename L >
bool operator== (const LatticeDomain< L > &Lhs, Top) noexcept
template<typename L >
bool operator== (Bottom, const LatticeDomain< L > &Rhs) noexcept
template<typename L >
bool operator== (Top, const LatticeDomain< L > &Rhs) noexcept
template<typename L >
bool operator< (const LatticeDomain< L > &Lhs, const LatticeDomain< L > &Rhs)
std::vector< const llvm::Function * > getEntryFunctions (const LLVMProjectIRDB &IRDB, llvm::ArrayRef< std::string > EntryPoints)
std::vector< llvm::Function * > getEntryFunctionsMut (LLVMProjectIRDB &IRDB, llvm::ArrayRef< std::string > EntryPoints)
std::vector< std::string > getDefaultEntryPoints (const LLVMProjectIRDB &IRDB)
LLVMBasedCallGraph buildLLVMBasedCallGraph (const LLVMProjectIRDB &IRDB, Resolver &CGResolver, llvm::ArrayRef< const llvm::Function * > EntryPoints, Soundness S=Soundness::Soundy)
LLVMBasedCallGraph buildLLVMBasedCallGraph (const LLVMProjectIRDB &IRDB, Resolver &CGResolver, llvm::ArrayRef< std::string > EntryPoints, Soundness S=Soundness::Soundy)
LLVMBasedCallGraph buildLLVMBasedCallGraph (LLVMProjectIRDB &IRDB, CallGraphAnalysisType CGType, llvm::ArrayRef< const llvm::Function * > EntryPoints, DIBasedTypeHierarchy &TH, LLVMVFTableProvider &VTP, LLVMAliasInfoRef PT=nullptr, Soundness S=Soundness::Soundy)
LLVMBasedCallGraph buildLLVMBasedCallGraph (LLVMProjectIRDB &IRDB, CallGraphAnalysisType CGType, llvm::ArrayRef< std::string > EntryPoints, DIBasedTypeHierarchy &TH, LLVMVFTableProvider &VTP, LLVMAliasInfoRef PT=nullptr, Soundness S=Soundness::Soundy)
bool isHeapAllocatingFunction (const llvm::Function *F) noexcept
std::optional< unsigned > getVFTIndex (const llvm::CallBase *CallSite)
std::optional< std::pair< const llvm::Value *, uint64_t > > getVFTIndexAndVT (const llvm::CallBase *CallSite)
Similar to getVFTIndex(), but also returns a pointer to the vtable.
const llvm::DIType * getReceiverType (const llvm::CallBase *CallSite)
const llvm::Function * getNonPureVirtualVFTEntry (const llvm::DIType *T, unsigned Idx, const llvm::CallBase *CallSite, const psr::LLVMVFTableProvider &VTP, const llvm::DIType *ReceiverType)
std::string getReceiverTypeName (const llvm::CallBase *CallSite)
bool isConsistentCall (const llvm::CallBase *CallSite, const llvm::Function *DestFun)
bool isVirtualCall (const llvm::Instruction *Inst, const LLVMVFTableProvider &VTP)
bool isAddressTakenFunction (const llvm::Function *F)
constexpr const llvm::Value * valueOf (const llvm::Value *V) noexcept
const library_summary::FunctionDataFlowFacts & getLibCSummary ()
template<typename D = const llvm::Value *, typename Container = std::set<D>, typename Fn = TrueFn, typename DCtor = DefaultConstruct<D>>
requires std::is_invocable_r_v<bool, Fn, const llvm::Value *>
auto mapFactsAlongsideCallSite (const llvm::CallBase *CallSite, Fn &&PropagateArgs={}, bool PropagateGlobals=true, DCtor &&FactConstructor={})
template<typename D = const llvm::Value *, typename Container = std::set<D>, typename Fn = std::equal_to<D>, typename DCtor = DefaultConstruct<D>>
requires std::is_invocable_r_v<bool, Fn, const llvm::Value *, D>
FlowFunctionPtrType< D, Container > mapFactsToCallee (const llvm::CallBase *CallSite, const llvm::Function *DestFun, Fn &&PropagateArgumentWithSource={}, DCtor &&FactConstructor={}, bool PropagateGlobals=true, bool PropagateZeroToCallee=true)
template<typename D = const llvm::Value *, typename Container = std::set<D>, typename FnParam = std::equal_to<D>, typename FnRet = std::equal_to<D>, typename DCtor = DefaultConstruct<D>, typename PostProcessFn = IgnoreArgs>
requires (std::is_invocable_r_v<bool, FnParam, const llvm::Value *, D> && std::is_invocable_r_v<bool, FnRet, const llvm::Value *, D>)
FlowFunctionPtrType< D, Container > mapFactsToCaller (const llvm::CallBase *CallSite, const llvm::Instruction *ExitInst, FnParam &&PropagateParameter={}, FnRet &&PropagateRet={}, DCtor &&FactConstructor={}, bool PropagateGlobals=true, bool PropagateZeroToCaller=true, PostProcessFn &&PostProcess={})
template<typename Fn , typename Container = std::set<const llvm::Value *>>
requires std::is_invocable_r_v<bool, Fn, const llvm::Value *>
FlowFunctionPtrType< const llvm::Value *, Container > strongUpdateStore (const llvm::StoreInst *Store, Fn &&GeneratePointerOpIf)
template<typename Container = std::set<const llvm::Value *>>
FlowFunctionPtrType< const llvm::Value *, Container > strongUpdateStore (const llvm::StoreInst *Store)
std::string DToString (const AbstractMemoryLocation &AML)
llvm::hash_code hash_value (psr::AbstractMemoryLocation Val)
std::string LToString (const IDEFeatureTaintEdgeFact &EdgeFact)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const IDEIIAFlowFact &FlowFact)
std::ostream & operator<< (std::ostream &OS, const IDEIIAFlowFact &FlowFact)
llvm::StringRef DToString (SecureHeapFact Fact) noexcept
llvm::StringRef LToString (SecureHeapValue Val) noexcept
template<typename TypeStateDescriptionTy >
IDETypeStateAnalysis (const LLVMProjectIRDB *, LLVMAliasInfoRef, const TypeStateDescriptionTy *, std::vector< std::string > EntryPoints) -> IDETypeStateAnalysis< TypeStateDescriptionTy >
llvm::StringRef to_string (CSTDFILEIOState State) noexcept
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, CSTDFILEIOState State)
llvm::StringRef to_string (OpenSSLEVPKDFCTXState State) noexcept
llvm::StringRef to_string (OpenSSLEVPKDFState State) noexcept
llvm::StringRef to_string (OpenSSLSecureHeapState State) noexcept
llvm::StringRef to_string (OpenSSLSecureMemoryState State) noexcept
std::string DToString (const IntraMonoFCAFact &Fact)
const llvm::Value * fromMetaDataId (const LLVMProjectIRDB &IRDB, llvm::StringRef Id)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const GeneralStatistics &Statistics)
bool isInReachableAllocationSitesTy (const llvm::Value *V, const llvm::Value *PotentialValue, bool IntraProcOnly, const llvm::Function *VFun=nullptr, const llvm::GlobalObject *VG=nullptr)
bool isInterestingPointer (const llvm::Value *V)
Returns true if the given pointer is an interesting pointer, i.e. not a constant null pointer.
SVFBasedPointsToInfo createSVFVFSPointsToInfo (LLVMProjectIRDB &IRDB)
SVFBasedPointsToInfo createSVFDDAPointsToInfo (LLVMProjectIRDB &IRDB)
SVFBasedPointsToInfo createSVFPointsToInfo (LLVMProjectIRDB &IRDB, SVFPointsToAnalysisType PTATy)
LLVMPointsToIterator createLLVMSVFPointsToIterator (LLVMProjectIRDB &IRDB, SVFPointsToAnalysisType PTATy)
LLVMAliasInfo createLLVMSVFDDAAliasInfo (LLVMProjectIRDB &IRDB)
template<typename ProblemTy , typename... ArgTys>
ProblemTy createAnalysisProblem (HelperAnalyses &HA, ArgTys &&...Args)
llvm::StringRef to_string (TaintCategory Cat) noexcept
TaintCategory toTaintCategory (llvm::StringRef Str) noexcept
TaintConfigData parseTaintConfig (const llvm::Twine &Path)
std::optional< TaintConfigData > parseTaintConfigOrNull (const llvm::Twine &Path) noexcept
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
void collectGeneratedFacts (ContainerTy &Dest, const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee)
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
void collectLeakedFacts (ContainerTy &Dest, const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee, std::invocable< const llvm::Value * > auto &&LeakIf)
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
void collectLeakedFacts (ContainerTy &Dest, const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee)
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
void collectSanitizedFacts (ContainerTy &Dest, const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee)
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
ContainerTy getGeneratedFacts (const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee)
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
ContainerTy getLeakedFacts (const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee, std::invocable< const llvm::Value * > auto &&LeakIf)
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
ContainerTy getLeakedFacts (const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee)
template<typename ContainerTy >
requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *>
ContainerTy getSanitizedFacts (const LLVMTaintConfig &Config, const llvm::CallBase *CB, const llvm::Function *Callee)
std::vector< const llvm::DICompositeType * > collectAllocatedTypes (const llvm::Module &Mod)
std::string toString (DataFlowAnalysisType D)
DataFlowAnalysisType toDataFlowAnalysisType (llvm::StringRef S)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, DataFlowAnalysisType D)
bool isTouchVTableInst (const llvm::StoreInst *Store)
llvm::DILocalVariable * getDILocalVariable (const llvm::Value *V)
llvm::DILocation * getDILocation (const llvm::Value *V)
std::string getVarNameFromIR (const llvm::Value *V)
llvm::DIType * getVarTypeFromIR (const llvm::Value *V)
std::string getFunctionNameFromIR (const llvm::Value *V)
std::string getFilePathFromIR (const llvm::Value *V)
std::string getFilePathFromIR (const llvm::DIFile *DIF)
std::string getDirectoryFromIR (const llvm::Value *V)
const llvm::DIFile * getDIFileFromIR (const llvm::Value *V)
unsigned int getLineFromIR (const llvm::Value *V)
unsigned int getColumnFromIR (const llvm::Value *V)
std::pair< unsigned, unsigned > getLineAndColFromIR (const llvm::Value *V)
std::string getSrcCodeFromIR (const llvm::Value *V, bool Trim=true)
std::string getSrcCodeFromIR (DebugLocation Loc, bool Trim=true)
std::string getModuleIDFromIR (const llvm::Value *V)
void from_json (const nlohmann::json &J, SourceCodeInfo &Info)
void to_json (nlohmann::json &J, const SourceCodeInfo &Info)
SourceCodeInfo getSrcCodeInfoFromIR (const llvm::Value *V)
std::optional< DebugLocation > getDebugLocation (const llvm::Value *V)
bool isIntegerLikeType (const llvm::Type *T) noexcept
Checks if the given LLVM Type is a integer like struct.
bool isAllocaInstOrHeapAllocaFunction (const llvm::Value *V) noexcept
Checks if the given LLVM Value is either a alloca instruction or a heap allocation function, e.g. new, new[], malloc, realloc or calloc.
bool matchesSignature (const llvm::Function *F, const llvm::FunctionType *FType, bool ExactMatch=true)
bool matchesSignature (const llvm::FunctionType *FType1, const llvm::FunctionType *FType2)
llvm::ModuleSlotTracker & getModuleSlotTrackerFor (const llvm::Value *V)
std::string llvmIRToString (const llvm::Value *V)
Returns a string representation of a LLVM Value.
std::string llvmIRToStableString (const llvm::Value *V)
Similar to llvmIRToString, but removes the metadata from the output as they are not always stable. Prefer this function over llvmIRToString, if you are comparing the string representations of LLVM iR instructions.
std::string llvmIRToShortString (const llvm::Value *V)
Same as llvmIRToString) but tries to shorten the resulting string.
std::string llvmTypeToString (const llvm::Type *Ty, bool Shorten=false)
Returns a string-representation of a LLVM type.
std::string llvmTypeToString (const llvm::DIType *Ty, bool Shorten=false)
Returns a string-representation of a LLVM Debug-Info type.
LLVM_DUMP_METHOD void dumpIRValue (const llvm::Value *V)
LLVM_DUMP_METHOD void dumpIRValue (const llvm::Instruction *V)
LLVM_DUMP_METHOD void dumpIRValue (const llvm::Function *V)
LLVM_DUMP_METHOD void dumpDIType (const llvm::DIType *Ty)
LLVM_DUMP_METHOD void dumpDIType (const llvm::DIDerivedType *Ty)
std::vector< const llvm::Value * > globalValuesUsedinFunction (const llvm::Function *F)
Returns all LLVM Global Values that are used in the given LLVM Function.
int getFunctionArgumentNr (const llvm::Argument *Arg)
Returns position of a formal function argument.
const llvm::Argument * getNthFunctionArgument (const llvm::Function *F, unsigned ArgNo)
Returns the n-th LLVM Argument of a given LLVM Function.
const llvm::Instruction * getNthInstruction (const llvm::Function *F, unsigned Idx)
Returns the n-th LLVM Instruction of a given LLVM Function.
const llvm::Instruction * getLastInstructionOf (const llvm::Function *F)
const llvm::Instruction * getNthTermInstruction (const llvm::Function *F, unsigned TermInstNo)
Returns the n-th LLVM Termination Instruction of a given LLVM Function.
const llvm::StoreInst * getNthStoreInstruction (const llvm::Function *F, unsigned StoNo)
Returns the n-th LLVM Store Instruction of a given LLVM Function.
llvm::SmallVector< const llvm::Instruction *, 2 > getAllExitPoints (const llvm::Function *F, bool IncludeResume=true)
void appendAllExitPoints (const llvm::Function *F, llvm::SmallVectorImpl< const llvm::Instruction * > &ExitPoints, bool IncludeResume=true)
const llvm::Module * getModuleFromVal (const llvm::Value *V)
Returns the LLVM Module to which the given LLVM Value belongs to.
std::string getModuleNameFromVal (const llvm::Value *V)
Returns the name of the LLVM Module to which the given LLVM Value belongs to.
std::size_t computeModuleHash (llvm::Module *M, bool ConsiderIdentifier)
Computes a hash value for a given LLVM Module.
std::size_t computeModuleHash (const llvm::Module *M)
Computes a hash value for a given LLVM Module.
bool isGuardVariable (const llvm::Value *V)
True, iff V is the compiler-generated guard variable for the thread-safe initialization of function-local static variables.
bool isStaticVariableLazyInitializationBranch (const llvm::BranchInst *Inst)
True, iff V is the compiler-generated branch that leads to the lazy initialization of a function-local static variable.
bool isVarAnnotationIntrinsic (const llvm::Function *F)
llvm::StringRef getVarAnnotationIntrinsicName (const llvm::CallInst *CallInst)
const llvm::AllocaInst * getVaListTagOrNull (const llvm::Function &Fun)
bool isVaListAlloca (const llvm::AllocaInst &Alloc)
const llvm::DIType * stripPointerTypes (const llvm::DIType *DITy)
std::string toString (AliasAnalysisType PA)
AliasAnalysisType toAliasAnalysisType (llvm::StringRef S)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, AliasAnalysisType PA)
std::string toString (AliasResult AR)
AliasResult toAliasResult (llvm::StringRef S)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, AliasResult AR)
template<typename T , typename F >
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const TypeHierarchy< T, F > &TH)
template<typename T , typename F >
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const VFTable< F > &Table)
template<typename T >
AlignNum (llvm::StringRef, T) -> AlignNum< T >
AlignNum (llvm::StringRef, size_t, size_t) -> AlignNum< double >
std::string to_string (AnalysisProperties Prop)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, AnalysisProperties Prop)
template<typename T >
void intersectWith (BitVectorSet< T > &Dest, const BitVectorSet< T > &Src)
template<typename T >
std::ostream & operator<< (std::ostream &OS, const PrettyPrinter< T > &P)
template<typename T >
PrettyPrinter (const T &) -> PrettyPrinter< T >
template<typename T >
requires std::is_default_constructible_v<T>
ByConstRef< T > getDefaultValue () noexcept(std::is_nothrow_default_constructible_v< T >)
template<is_graph GraphTy>
std::decay_t< GraphTy > createEquivalentGraphFrom (GraphTy &&G, const llvm::IntEqClasses &Eq)
template<is_graph GraphTy>
llvm::IntEqClasses minimizeGraph (const GraphTy &G)
bool operator< (const DOTNode &Lhs, const DOTNode &Rhs)
bool operator== (const DOTNode &Lhs, const DOTNode &Rhs)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const DOTNode &Node)
bool operator< (const DOTEdge &Lhs, const DOTEdge &Rhs)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const DOTEdge &Edge)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const DOTFactSubGraph &FactSG)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const DOTFunctionSubGraph &FunctionSG)
template<detail::is_enum T>
constexpr EnumFlagAutoBool< T > operator& (T Lhs, T Rhs) noexcept
template<detail::is_enum T>
constexpr void operator&= (T &Lhs, T Rhs) noexcept
template<detail::is_enum T>
constexpr T operator| (T Lhs, T Rhs) noexcept
template<detail::is_enum T>
constexpr void operator|= (T &Lhs, T Rhs) noexcept
template<detail::is_enum T>
constexpr T operator^ (T Lhs, T Rhs) noexcept
template<detail::is_enum T>
constexpr void operator^= (T &Lhs, T Rhs) noexcept
template<detail::is_enum T>
constexpr T operator~ (T Rhs) noexcept
template<detail::is_enum T>
constexpr void setFlag (T &This, T Flag) noexcept
template<detail::is_enum T>
constexpr void unsetFlag (T &This, T Flag) noexcept
template<detail::is_enum T>
constexpr void setFlag (T &This, T Flag, bool Set) noexcept
template<detail::is_enum T>
constexpr bool hasFlag (T This, T Flag) noexcept
template<typename T >
T getOrThrow (llvm::ErrorOr< T > ValOrErr)
template<typename T >
std::optional< T > getOrNull (llvm::ErrorOr< T > ValOrErr) noexcept(std::is_nothrow_move_constructible_v< T >)
template<typename T >
requires std::is_default_constructible_v<T>
T getOrEmpty (llvm::ErrorOr< T > ValOrErr) noexcept(std::is_nothrow_move_constructible_v< T >)
template<typename T , typename MapFn >
llvm::ErrorOr< std::invoke_result_t< MapFn, const T & > > mapValue (const llvm::ErrorOr< T > &ValOrErr, MapFn Mapper) noexcept(std::is_nothrow_invocable_v< MapFn, const T & >)
template<typename T , typename MapFn >
llvm::ErrorOr< std::invoke_result_t< MapFn, T > > mapValue (llvm::ErrorOr< T > &&ValOrErr, MapFn Mapper) noexcept(std::is_nothrow_invocable_v< MapFn, T >)
template<is_graph GraphTy>
std::decay_t< GraphTy > reverseGraph (GraphTy &&G)
template<is_const_graph GraphTy, typename NodeTransform = DefaultNodeTransform>
void printGraph (const GraphTy &G, llvm::raw_ostream &OS, llvm::StringRef Name="", NodeTransform NodeToString={})
Prints the given graph G as dot.
llvm::ErrorOr< std::string > readTextFileOrErr (const llvm::Twine &Path)
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > readFileOrErr (const llvm::Twine &Path) noexcept
std::string readTextFile (const llvm::Twine &Path)
std::unique_ptr< llvm::MemoryBuffer > readFile (const llvm::Twine &Path)
std::optional< std::string > readTextFileOrNull (const llvm::Twine &Path)
std::unique_ptr< llvm::MemoryBuffer > readFileOrNull (const llvm::Twine &Path) noexcept
nlohmann::json readJsonFile (const llvm::Twine &Path)
void writeTextFile (const llvm::Twine &Path, llvm::StringRef Content)
std::unique_ptr< llvm::raw_fd_ostream > openFileStream (const llvm::Twine &Filename)
template<typename IdT >
constexpr auto iota (IdT From, type_identity_t< IdT > To) noexcept
template<typename IdT >
constexpr auto iota (size_t To) noexcept
bool isHeapAllocatingFunction (llvm::StringRef FName) noexcept
bool isSingletonReturningFunction (llvm::StringRef FName) noexcept
SeverityLevel parseSeverityLevel (llvm::StringRef Str) noexcept
llvm::StringRef to_string (SeverityLevel Level) noexcept
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const nlohmann::json &J)
template<typename T >
requires std::is_convertible_v<T, bool>
constexpr T unwrapNullable (T &&Val) noexcept
template<typename T >
requires (!std::is_convertible_v<T, bool>)
constexpr T unwrapNullable (std::optional< T > &&Val) noexcept
template<typename T >
requires (!std::is_convertible_v<T, bool>)
constexpr const T & unwrapNullable (const std::optional< T > &Val) noexcept
template<typename T >
requires (!std::is_convertible_v<T, bool>)
constexpr T & unwrapNullable (std::optional< T > &Val) noexcept
template<typename T >
requires (!std::is_pointer_v<T>)
constexpr T * getPointerFrom (T &Ref) noexcept
template<typename T >
requires (!std::is_pointer_v<T>)
constexpr const T * getPointerFrom (const T &Ref) noexcept
template<typename T >
requires (!std::is_pointer_v<T>)
constexpr T * getPointerFrom (T &&Ref) noexcept=delete
template<typename T >
T * getPointerFrom (T *Ptr) noexcept
template<typename T >
constexpr T * getPointerFrom (const std::unique_ptr< T > &Ptr) noexcept
template<typename T >
constexpr T * getPointerFrom (std::unique_ptr< T > &Ptr) noexcept
template<typename T >
constexpr T * getPointerFrom (std::unique_ptr< T > &&Ptr) noexcept=delete
template<typename T , bool RequireAlignment>
constexpr T * getPointerFrom (const MaybeUniquePtr< T, RequireAlignment > &Ptr) noexcept
template<typename T , bool RequireAlignment>
constexpr T * getPointerFrom (MaybeUniquePtr< T, RequireAlignment > &Ptr) noexcept
template<typename T , bool RequireAlignment>
constexpr T * getPointerFrom (MaybeUniquePtr< T, RequireAlignment > &&Ptr) noexcept=delete
template<typename T >
constexpr T * getPointerFrom (const std::shared_ptr< T > &Ptr) noexcept
template<typename T >
constexpr T * getPointerFrom (std::shared_ptr< T > &Ptr) noexcept
template<typename T >
constexpr T * getPointerFrom (std::shared_ptr< T > &&Ptr) noexcept=delete
template<typename T >
constexpr T * getPointerFrom (const llvm::IntrusiveRefCntPtr< T > &Ptr) noexcept
template<typename T >
constexpr T * getPointerFrom (llvm::IntrusiveRefCntPtr< T > &Ptr) noexcept
template<typename T >
constexpr T * getPointerFrom (llvm::IntrusiveRefCntPtr< T > &&Ptr) noexcept
template<typename T >
constexpr BoxedPtr< T > getPointerFrom (BoxedPtr< T > Ptr) noexcept
template<typename T >
constexpr BoxedConstPtr< T > getPointerFrom (BoxedConstPtr< T > Ptr) noexcept
template<detail::IsSomehowPrintable N>
decltype(auto) NToString (const N &Node)
template<detail::IsSomehowPrintable D>
decltype(auto) DToString (const D &Fact)
template<detail::IsSomehowPrintable L>
decltype(auto) LToString (const L &Value)
template<detail::IsSomehowPrintable F>
std::string FToString (const F &Fun)
std::string NToString (const llvm::Value *V)
std::string NToString (const llvm::Instruction *V)
std::string DToString (const llvm::Value *V)
llvm::StringRef FToString (const llvm::Function *V)
template<typename T >
auto repeat (T &&Elem, size_t Num)
template<typename G >
SCCDependencyGraph< typename GraphTraits< G >::vertex_t > computeSCCDependencies (const G &Graph, const SCCHolder< typename GraphTraits< G >::vertex_t > &SCCs)
Creates a graph based on the given input Graph, collapsing all SCCs to single nodes. The resulting graph is always a DAG, i.e., it contains no cycles.
template<typename GraphNodeId >
SCCOrder< GraphNodeId > computeSCCOrder (const SCCHolder< GraphNodeId > &SCCs, const SCCDependencyGraph< GraphNodeId > &Callers)
Computes a topological order of the nodes in the given dependency-graph.
template<typename G , bool Iterative = true>
SCCHolder< typename GraphTraits< G >::vertex_t > computeSCCs (const G &Graph, std::bool_constant< Iterative >={})
template<typename G , bool Iterative = true>
std::pair< SCCHolder< typename GraphTraits< G >::vertex_t >, SCCOrder< typename GraphTraits< G >::vertex_t > > computeSCCsAndTopologicalOrder (const G &Graph, std::bool_constant< Iterative >={})
std::string toString (Soundness S)
Soundness toSoundness (llvm::StringRef S)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, Soundness S)
template<typename T >
void reserveIfPossible (T &Container, size_t Capacity)
template<has_adl_to_string_v T>
decltype(auto) adl_to_string (const T &Val)
std::string createTimeStamp ()
bool isConstructor (llvm::StringRef MangledName)
bool isMangled (llvm::StringRef Name)
template<typename T >
std::set< std::set< T > > computePowerSet (const std::set< T > &S)
template<typename ContainerTy , typename OtherContainerTy >
requires (!has_erase_iterator_v<ContainerTy>)
void intersectWith (ContainerTy &Dest, const OtherContainerTy &Src)
Computes the set-intersection of the potentially unordered sets Dest and Src and stores the result back in Dest.
template<has_erase_iterator_v ContainerTy, typename OtherContainerTy >
void intersectWith (ContainerTy &Dest, const OtherContainerTy &Src)
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const std::vector< bool > &Bits)
template<typename Fn >
scope_exit (Fn) -> scope_exit< Fn >
template<class... Ts>
Overloaded (Ts...) -> Overloaded< Ts... >
template<typename It , typename EndIt , typename IdxIt , typename IdxEndIt >
It remove_by_index (It First, EndIt Last, IdxIt FirstIndex, IdxEndIt LastIndex)
template<typename Container , typename IdxIt , typename IdxEndIt >
auto remove_by_index (Container &Cont, IdxIt FirstIndex, IdxEndIt LastIndex)
template<typename Container , typename Indices >
auto remove_by_index (Container &Cont, const Indices &Idx)
template<class T , class U >
LLVM_ATTRIBUTE_ALWAYS_INLINE constexpr auto && forward_like (U &&X) noexcept
See https://en.cppreference.com/w/cpp/utility/forward_like
template<is_llvm_printable_v T>
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const std::optional< T > &Opt)
template<typename T >
requires (!std::is_pointer_v<T>)
LLVM_ATTRIBUTE_ALWAYS_INLINE T & assertNotNull (T &Value)
template<typename T >
LLVM_ATTRIBUTE_ALWAYS_INLINE const T & assertNotNull (const std::optional< T > &Value)
template<typename T >
LLVM_ATTRIBUTE_ALWAYS_INLINE T & assertNotNull (std::optional< T > &Value)
template<typename T >
LLVM_ATTRIBUTE_ALWAYS_INLINE T & assertNotNull (T *Value)
template<typename T >
void assertAllNotNull (const T &Range)
Variables
template<typename ICF , typename Domain >
constexpr bool is_sparse_cfg_v
template<typename T , typename D >
constexpr bool has_getSparseCFG_v
std::string DataFlowAnalysis
std::string PointerAnalysis
std::string CallGraphAnalysis
std::vector< std::string > EntryPoints
std::string PammOutputFile
bool PrintEdgeRecorder
bool InitLogger
bool DumpResults
template<typename T >
constexpr bool has_llvm_dense_map_info
template<typename Var , typename T >
constexpr size_t variant_idx = detail::variant_idx<Var, T>::value
Typedef Documentation
ByConstRef
template<typename T > using psr::ByConstRef = typedef std::conditional_t<CanEfficientlyPassByValue<T>, T, const T &>
Definition at line 24 of file ByRef.h.
ByMoveRef
template<typename T > using psr::ByMoveRef = typedef std::conditional_t<CanEfficientlyPassByValue<T>, T, T &&>
Definition at line 27 of file ByRef.h.
DefaultPathTracingFilter
using psr::DefaultPathTracingFilter = typedef PathTracingFilter<detail::False2, detail::False2>
Definition at line 33 of file PathTracingFilter.h.
ElementType
template<typename Container > using psr::ElementType = typedef typename detail::ElementType<Container>::type
Definition at line 202 of file TypeTraits.h.
FlowFunctionPtrType
template<typename D , typename Container = std::set<D>> using psr::FlowFunctionPtrType = typedef FlowFunctionPtrTypeOf<FlowFunction<D, Container> >
Given a dataflow-fact type and optionally a container-type, returns a (smart) pointer type pointing to a FlowFunction with the specified flow-fact- and container type.
Equivalent to FlowFunctionPtrTypeOf<FlowFunction<D, Container>>
Definition at line 98 of file FlowFunctions.h.
FlowFunctionPtrTypeOf
template<is_flowfunction_v FF> using psr::FlowFunctionPtrTypeOf = typedef std::shared_ptr<FF>
Given a flow-function type FF, returns a (smart) pointer type pointing to FF.
Definition at line 90 of file FlowFunctions.h.
FlowPathSequence
template<typename N > using psr::FlowPathSequence = typedef std::vector<FlowPath<N> >
Definition at line 55 of file FlowPath.h.
FunctionRange
using psr::FunctionRange = typedef llvm::iterator_range<llvm::mapped_iterator< llvm::Module::const_iterator, Ref2PointerConverter<llvm::Function> >>
Definition at line 28 of file LLVMBasedContainerConfig.h.
IDEInstInteractionAnalysis
using psr::IDEInstInteractionAnalysis = typedef IDEInstInteractionAnalysisT<>
Definition at line 1248 of file IDEInstInteractionAnalysis.h.
IDESolver_P
template<typename Problem > using psr::IDESolver_P = typedef IDESolver<typename Problem::ProblemAnalysisDomain, typename Problem::container_type>
Definition at line 1933 of file IDESolver.h.
IDESolverConfig
using psr::IDESolverConfig = typedef WithComputeValues<IDESolverConfigBase, true>
Definition at line 83 of file StaticIDESolverConfig.h.
IDESolverConfigWithStats
using psr::IDESolverConfigWithStats = typedef WithStats<IDESolverConfig, true>
Definition at line 85 of file StaticIDESolverConfig.h.
IFDSSolver_P
template<typename Problem > using psr::IFDSSolver_P = typedef IFDSSolver<typename Problem::ProblemAnalysisDomain, typename Problem::container_type>
Definition at line 119 of file IFDSSolver.h.
IFDSSolverConfig
using psr::IFDSSolverConfig = typedef WithComputeValues<IDESolverConfigBase, false>
Definition at line 84 of file StaticIDESolverConfig.h.
IFDSSolverConfigWithStats
using psr::IFDSSolverConfigWithStats = typedef WithStats<IFDSSolverConfig, true>
Definition at line 86 of file StaticIDESolverConfig.h.
IFDSSolverConfigWithStatsAndGC
using psr::IFDSSolverConfigWithStatsAndGC = typedef WithGCMode<IFDSSolverConfigWithStats, JumpFunctionGCMode::Enabled>
Definition at line 87 of file StaticIDESolverConfig.h.
InterMonoSolver_P
template<typename Problem , unsigned K> using psr::InterMonoSolver_P = typedef InterMonoSolver<typename Problem::ProblemAnalysisDomain, K>
Definition at line 423 of file InterMonoSolver.h.
IntraMonoSolver_P
template<typename Problem > using psr::IntraMonoSolver_P = typedef IntraMonoSolver<typename Problem::ProblemAnalysisDomain>
Definition at line 172 of file IntraMonoSolver.h.
IotaRangeType
template<typename IdT > using psr::IotaRangeType = typedef llvm::iterator_range<IotaIterator<IdT> >
Definition at line 75 of file IotaIterator.h.
LLVMAliasInfo
using psr::LLVMAliasInfo = typedef AliasInfo<const llvm::Value *, const llvm::Instruction *>
Definition at line 30 of file LLVMAliasInfo.h.
LLVMAliasInfoRef
using psr::LLVMAliasInfoRef = typedef AliasInfoRef<const llvm::Value *, const llvm::Instruction *>
Definition at line 27 of file LLVMAliasInfo.h.
LLVMAliasIteratorRef
using psr::LLVMAliasIteratorRef = typedef AliasIteratorRef<const llvm::Value *, const llvm::Instruction *>
Definition at line 24 of file LLVMAliasInfo.h.
LLVMBasedCallGraph
using psr::LLVMBasedCallGraph = typedef CallGraph<const llvm::Instruction *, const llvm::Function *>
Definition at line 21 of file LLVMBasedCallGraph.h.
LLVMIFDSAnalysisDomainDefault
using psr::LLVMIFDSAnalysisDomainDefault = typedef WithBinaryValueDomain<LLVMAnalysisDomainDefault>
An AnalysisDomain that specializes sensible defaults for LLVM-based IFDS analysis.
Definition at line 46 of file LLVMAnalysisDomain.h.
LLVMPointsToIterator
using psr::LLVMPointsToIterator = typedef PointsToIterator<const llvm::Value *, const llvm::Value *, const llvm::Instruction *>
Definition at line 26 of file LLVMPointsToInfo.h.
LLVMPointsToIteratorRef
using psr::LLVMPointsToIteratorRef = typedef PointsToIteratorRef<const llvm::Value *, const llvm::Value *, const llvm::Instruction *>
Definition at line 22 of file LLVMPointsToInfo.h.
Nullable
template<typename T > using psr::Nullable = typedef std::conditional_t<std::is_convertible_v<T, bool>, T, std::optional<T> >
Definition at line 21 of file Nullable.h.
RepeatRangeType
template<typename T > using psr::RepeatRangeType = typedef llvm::iterator_range<RepeatIterator<T> >
Definition at line 71 of file RepeatIterator.h.
SparseLLVMBasedCFGProvider
template<typename Derived > using psr::SparseLLVMBasedCFGProvider = typedef SparseCFGProvider<Derived, const llvm::Function *, const llvm::Value *>
Definition at line 23 of file SparseLLVMBasedCFGProvider.h.
SVFBasedPointsToInfo
using psr::SVFBasedPointsToInfo = typedef PointsToInfo<SVFPointsToInfoTraits>
Definition at line 51 of file SVFPointsToSet.h.
SVFBasedPointsToInfoRef
using psr::SVFBasedPointsToInfoRef = typedef PointsToInfoRef<SVFPointsToInfoTraits>
Definition at line 52 of file SVFPointsToSet.h.
SVFBasedPointsToIterator
using psr::SVFBasedPointsToIterator = typedef PointsToIterator<const llvm::Value *, uint32_t, const llvm::Instruction *>
Definition at line 53 of file SVFPointsToSet.h.
SVFBasedPointsToIteratorRef
using psr::SVFBasedPointsToIteratorRef = typedef PointsToIteratorRef<const llvm::Value *, uint32_t, const llvm::Instruction *>
Definition at line 55 of file SVFPointsToSet.h.
WithBinaryValueDomain
template<typename AnalysisDomainTy > using psr::WithBinaryValueDomain = typedef std::conditional_t<detail::HasBinaryValueDomain<AnalysisDomainTy>::value, AnalysisDomainTy, detail::WithBinaryValueDomainExtender<AnalysisDomainTy> >
Definition at line 81 of file AnalysisDomain.h.
Enumeration Type Documentation
AliasAnalysisType
enum class psr::AliasAnalysisType strong
Enumerator
ALIAS_ANALYSIS_TYPE
Invalid
Definition at line 13 of file AliasAnalysisType.h.
AliasResult
enum class psr::AliasResult strong
Enumerator
ALIAS_RESULT_TYPE
Definition at line 18 of file AliasResult.h.
AnalysisProperties
enum class psr::AnalysisProperties strong
Enumerator
None
FlowSensitive
ContextSensitive
FieldSensitive
Definition at line 19 of file AnalysisProperties.h.
AnalysisStrategy
enum class psr::AnalysisStrategy strong
Enumerator
None
ANALYSIS_STRATEGY_TYPES
Definition at line 24 of file Strategies.h.
BinaryDomain
enum class psr::BinaryDomain strong
Enumerator
BOTTOM
TOP
Definition at line 30 of file BinaryDomain.h.
CallGraphAnalysisType
enum class psr::CallGraphAnalysisType strong
Enumerator
CALL_GRAPH_ANALYSIS_TYPE
Invalid
Definition at line 19 of file CallGraphAnalysisType.h.
CSTDFILEIOState
enum class psr::CSTDFILEIOState strong
Enumerator
TOP
UNINIT
OPENED
CLOSED
ERROR
BOT
Definition at line 23 of file CSTDFILEIOTypeStateDescription.h.
DataFlowAnalysisType
enum class psr::DataFlowAnalysisType strong
Enumerator
None
DATA_FLOW_ANALYSIS_TYPES
Definition at line 19 of file DataFlowAnalysisType.h.
EdgeFunctionAllocationPolicy
enum class psr::EdgeFunctionAllocationPolicy strong
Enumerator
SmallObjectOptimized
DefaultHeapAllocated
CustomHeapAllocated
Definition at line 49 of file EdgeFunction.h.
EdgeFunctionKind
enum class psr::EdgeFunctionKind strong
Enumerator
Normal
Call
Return
CallToReturn
Summary
Definition at line 36 of file FlowEdgeFunctionCache.h.
ESGEdgeKind
enum class psr::ESGEdgeKind strong
Enumerator
Normal
Call
CallToRet
SkipUnknownFn
Ret
Summary
Definition at line 14 of file ESGEdgeKind.h.
JumpFunctionGCMode
enum class psr::JumpFunctionGCMode strong
Enumerator
Disabled
Perform no semantic garbage collection on jump functions.
Enabled
Perform JF GC, but do not delete any elements from the SolverResults, so all SolverResults are still present, only the edge-values are not computed everywhere
EnabledAggressively
Perform JF GC as in 'Enabled', but also delete entries from the SolverResults
Definition at line 14 of file StaticIDESolverConfig.h.
OpenSSLEVPKDFCTXState
enum class psr::OpenSSLEVPKDFCTXState strong
We use the following lattice BOT = all information
UNINIT CTX_ATTACHED PARAM_INIT DERIVED ERROR
           TOP = no information
Enumerator
TOP
UNINIT
CTX_ATTACHED
PARAM_INIT
DERIVED
ERROR
BOT
Definition at line 37 of file OpenSSLEVPKDFCTXDescription.h.
OpenSSLEVPKDFState
enum class psr::OpenSSLEVPKDFState strong
We use the following lattice BOT = all information
UNINIT KDF_FETCHED ERROR
   TOP = no information
Enumerator
TOP
UNINIT
KDF_FETCHED
ERROR
BOT
Definition at line 28 of file OpenSSLEVPKDFDescription.h.
OpenSSLSecureHeapState
enum class psr::OpenSSLSecureHeapState strong
Enumerator
TOP
BOT
UNINIT
ALLOCATED
ZEROED
FREED
ERROR
Definition at line 21 of file OpenSSLSecureHeapDescription.h.
PAMM_SEVERITY_LEVEL
enum class psr::PAMM_SEVERITY_LEVEL strong
Defines the different level of severity of PAMM's performance evaluation.
Enumerator
Off
Core
Full
Definition at line 24 of file PAMMMacros.h.
SecureHeapFact
enum class psr::SecureHeapFact strong
Enumerator
ZERO
INITIALIZED
Definition at line 20 of file IDESecureHeapPropagation.h.
SecureHeapValue
enum class psr::SecureHeapValue strong
Enumerator
TOP
INITIALIZED
BOT
Definition at line 21 of file IDESecureHeapPropagation.h.
SeverityLevel
enum psr::SeverityLevel
Enumerator
INVALID
Definition at line 24 of file Logger.h.
SolverConfigOptions
enum class psr::SolverConfigOptions : uint32_t strong
Enumerator
None
FollowReturnsPastSeeds
AutoAddZero
ComputeValues
RecordEdges
EmitESG
ComputePersistedSummaries
All
Definition at line 30 of file IFDSIDESolverConfig.h.
Soundness
enum class psr::Soundness strong
Enumerator
SOUNDNESS_FLAG_TYPE
Invalid
Definition at line 24 of file Soundness.h.
SpecialMemberFunctionType
enum class psr::SpecialMemberFunctionType strong
Enumerator
SPECIAL_MEMBER_FUNCTION_TYPES
Definition at line 30 of file SpecialMemberFunctionType.h.
SVFPointsToAnalysisType
enum class psr::SVFPointsToAnalysisType strong
Enumerator
DDA
VFS
Definition at line 46 of file SVFPointsToSet.h.
TaintCategory
enum class psr::TaintCategory strong
Enumerator
None
Source
Sink
Sanitizer
Definition at line 28 of file TaintConfigBase.h.
Function Documentation
addSeedsForStartingPoints() [1/4]
template<typename EntryRange , typename I , typename SeedsT , typename D > requires (std::is_same_v<BinaryDomain, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>) void psr::addSeedsForStartingPoints (const EntryRange & EntryPoints, const I * ICF, SeedsT & Seeds, const D & ZeroValue)
Simplification for IFDS, passing BinaryDomain::BOTTOM as L.
Definition at line 118 of file EntryPointUtils.h.
References addSeedsForStartingPoints(), BOTTOM, and EntryPoints.
addSeedsForStartingPoints() [2/4]
template<typename EntryRange , typename I , typename SeedsT , typename D , typename L > requires (std::is_convertible_v<L, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>) void psr::addSeedsForStartingPoints (const EntryRange & EntryPoints, const I * ICF, SeedsT & Seeds, const D & ZeroValue, const L & BottomValue)
Definition at line 92 of file EntryPointUtils.h.
References EntryPoints, and forallStartingPoints().
addSeedsForStartingPoints() [3/4]
template<typename EntryRange , typename C , typename DB , typename SeedsT , typename D > requires (std::is_same_v<BinaryDomain, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>) void psr::addSeedsForStartingPoints (const EntryRange & EntryPoints, const ProjectIRDBBase< DB > * IRDB, const CFGBase< C > & CFG, SeedsT & Seeds, const D & ZeroValue)
Simplification for IFDS, passing BinaryDomain::BOTTOM as L.
Definition at line 106 of file EntryPointUtils.h.
References addSeedsForStartingPoints(), BOTTOM, and EntryPoints.
addSeedsForStartingPoints() [4/4]
template<typename EntryRange , typename C , typename DB , typename SeedsT , typename D , typename L > requires (std::is_convertible_v<L, typename SeedsT::l_t> && std::is_convertible_v<D, typename SeedsT::d_t>) void psr::addSeedsForStartingPoints (const EntryRange & EntryPoints, const ProjectIRDBBase< DB > * IRDB, const CFGBase< C > & CFG, SeedsT & Seeds, const D & ZeroValue, const L & BottomValue)
Definition at line 78 of file EntryPointUtils.h.
References EntryPoints, and forallStartingPoints().
Referenced by addSeedsForStartingPoints(), addSeedsForStartingPoints(), and psr::IDETabulationProblem< AnalysisDomainTy, Container >::createDefaultSeeds().
adl_to_string()
template<has_adl_to_string_v T> decltype(auto) psr::adl_to_string (const T & Val)
Definition at line 250 of file TypeTraits.h.
References to_string().
Referenced by psr::detail::printSomehow().
AlignNum() [1/2]
psr::AlignNum (llvm::StringRef , size_t , size_t) -> AlignNum< double >
AlignNum() [2/2]
template<typename T > psr::AlignNum (llvm::StringRef , T) -> AlignNum< T >
appendAllExitPoints()
void psr::appendAllExitPoints (const llvm::Function * F, llvm::SmallVectorImpl< const llvm::Instruction * > & ExitPoints, bool IncludeResume = true)
assertAllNotNull()
template<typename T > void psr::assertAllNotNull (const T & Range)
Definition at line 313 of file Utilities.h.
References assertNotNull().
Referenced by psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetEdgeFunction(), and psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetFlowFunction().
assertNotNull() [1/4]
template<typename T > LLVM_ATTRIBUTE_ALWAYS_INLINE const T & psr::assertNotNull (const std::optional< T > & Value)
Definition at line 298 of file Utilities.h.
assertNotNull() [2/4]
template<typename T > LLVM_ATTRIBUTE_ALWAYS_INLINE T & psr::assertNotNull (std::optional< T > & Value)
Definition at line 303 of file Utilities.h.
assertNotNull() [3/4]
template<typename T > requires (!std::is_pointer_v<T>) LLVM_ATTRIBUTE_ALWAYS_INLINE T & psr::assertNotNull (T & Value)
Definition at line 292 of file Utilities.h.
Referenced by assertAllNotNull(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getRetFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getReturnEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryEdgeFunction(), and psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryFlowFunction().
assertNotNull() [4/4]
template<typename T > LLVM_ATTRIBUTE_ALWAYS_INLINE T & psr::assertNotNull (T * Value)
Definition at line 308 of file Utilities.h.
buildLLVMBasedCallGraph() [1/4]
LLVMBasedCallGraph psr::buildLLVMBasedCallGraph (const LLVMProjectIRDB & IRDB, Resolver & CGResolver, llvm::ArrayRef< const llvm::Function * > EntryPoints, Soundness S = Soundness::Soundy)
Constructs a call-graph using the given CGResolver to resolve indirect calls.
Uses a fixpoint iteration, if CGResolver.mutatesHelperAnalysisInformation() returns true and the soundness S is not Soundness::Unsound.
Parameters
IRDB The IR code where the call-graph should be based on
CGResolver The resolver to use for resolving indirect calls.
EntryPoints The functions, where the call-graph construction should start. The resulting call-graph will only contain functions that are (transitively) reachable from the entry-points.
S The soundness level. May be used to trade soundness for performance.
buildLLVMBasedCallGraph() [2/4]
LLVMBasedCallGraph psr::buildLLVMBasedCallGraph (const LLVMProjectIRDB & IRDB, Resolver & CGResolver, llvm::ArrayRef< std::string > EntryPoints, Soundness S = Soundness::Soundy)
Constructs a call-graph using the given CGResolver to resolve indirect calls.
Uses a fixpoint iteration, if CGResolver.mutatesHelperAnalysisInformation() returns true and the soundness S is not Soundness::Unsound.
Parameters
IRDB The IR code where the call-graph should be based on
CGResolver The resolver to use for resolving indirect calls.
EntryPoints Names of the functions, where the call-graph construction should start. The resulting call-graph will only contain functions that are (transitively) reachable from the entry-points.
S The soundness level. May be used to trade soundness for performance.
buildLLVMBasedCallGraph() [3/4]
LLVMBasedCallGraph psr::buildLLVMBasedCallGraph (LLVMProjectIRDB & IRDB, CallGraphAnalysisType CGType, llvm::ArrayRef< const llvm::Function * > EntryPoints, DIBasedTypeHierarchy & TH, LLVMVFTableProvider & VTP, LLVMAliasInfoRef PT = nullptr, Soundness S = Soundness::Soundy)
Kept for compatibility with LLVMBasedICFG. See the constructor of LLVMBasedICFG::LLVMBasedICFG(LLVMProjectIRDB *, CallGraphAnalysisType, llvm::ArrayRef<std::string>, DIBasedTypeHierarchy *, LLVMAliasInfoRef, Soundness, bool) for more information.
buildLLVMBasedCallGraph() [4/4]
LLVMBasedCallGraph psr::buildLLVMBasedCallGraph (LLVMProjectIRDB & IRDB, CallGraphAnalysisType CGType, llvm::ArrayRef< std::string > EntryPoints, DIBasedTypeHierarchy & TH, LLVMVFTableProvider & VTP, LLVMAliasInfoRef PT = nullptr, Soundness S = Soundness::Soundy)
Kept for compatibility with LLVMBasedICFG. See the constructor of LLVMBasedICFG::LLVMBasedICFG(LLVMProjectIRDB *, CallGraphAnalysisType, llvm::ArrayRef<std::string>, DIBasedTypeHierarchy *, LLVMAliasInfoRef, Soundness, bool) for more information.
CachedEdgeFunction()
template<typename EdgeFunctionTy > psr::CachedEdgeFunction (EdgeFunctionTy , EdgeFunctionSingletonCache< EdgeFunctionTy > *) -> CachedEdgeFunction< EdgeFunctionTy >
checkSREquality()
template<typename SR1 , typename SR2 > bool psr::checkSREquality (const SR1 & LHS, const SR2 & RHS)
Definition at line 191 of file GenericSolverResults.h.
References llvmIRToString().
collectAllocatedTypes()
std::vector< const llvm::DICompositeType * > psr::collectAllocatedTypes (const llvm::Module & Mod)
collectGeneratedFacts()
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> void psr::collectGeneratedFacts (ContainerTy & Dest, const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee)
Definition at line 27 of file TaintConfigUtilities.h.
References psr::TaintConfigBase< Derived >::getRegisteredSourceCallBack(), and psr::TaintConfigBase< Derived >::isSource().
Referenced by getGeneratedFacts().
collectLeakedFacts() [1/2]
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> void psr::collectLeakedFacts (ContainerTy & Dest, const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee) inline
Definition at line 69 of file TaintConfigUtilities.h.
References collectLeakedFacts().
collectLeakedFacts() [2/2]
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> void psr::collectLeakedFacts (ContainerTy & Dest, const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee, std::invocable< const llvm::Value * > auto && LeakIf)
Definition at line 49 of file TaintConfigUtilities.h.
References psr::TaintConfigBase< Derived >::getRegisteredSinkCallBack(), and psr::TaintConfigBase< Derived >::isSink().
Referenced by collectLeakedFacts(), getLeakedFacts(), and getLeakedFacts().
collectSanitizedFacts()
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> void psr::collectSanitizedFacts (ContainerTy & Dest, const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee)
Definition at line 78 of file TaintConfigUtilities.h.
References psr::TaintConfigBase< Derived >::isSanitizer().
Referenced by getSanitizedFacts().
computeModuleHash() [1/2]
std::size_t psr::computeModuleHash (const llvm::Module * M)
Computes a hash value for a given LLVM Module.
Note
Hash computation will consider the module identifier.
Parameters
M
Returns
computeModuleHash() [2/2]
std::size_t psr::computeModuleHash (llvm::Module * M, bool ConsiderIdentifier)
Computes a hash value for a given LLVM Module.
Parameters
M LLVM Module.
considerIdentifier If true, module identifier will be considered for hash computation.
Returns
Hash value.
computePowerSet()
template<typename T > std::set< std::set< T > > psr::computePowerSet (const std::set< T > & S)
Definition at line 39 of file Utilities.h.
computeSCCDependencies()
template<typename G > SCCDependencyGraph< typename GraphTraits< G >::vertex_t > psr::computeSCCDependencies (const G & Graph, const SCCHolder< typename GraphTraits< G >::vertex_t > & SCCs)
Creates a graph based on the given input Graph, collapsing all SCCs to single nodes. The resulting graph is always a DAG, i.e., it contains no cycles.
Definition at line 237 of file SCCGeneric.h.
References psr::BitSet< IdT, BitVectorTy >::erase(), psr::BitSet< IdT, BitVectorTy >::foreach(), Ret, and psr::BitSet< IdT, BitVectorTy >::size().
computeSCCOrder()
template<typename GraphNodeId > SCCOrder< GraphNodeId > psr::computeSCCOrder (const SCCHolder< GraphNodeId > & SCCs, const SCCDependencyGraph< GraphNodeId > & Callers)
Computes a topological order of the nodes in the given dependency-graph.
Uses a simple, recursive postorder-DFS search to find a topological ordering.
Definition at line 274 of file SCCGeneric.h.
References Ret, and psr::SCCHolder< GraphNodeId >::size().
computeSCCs()
template<typename G , bool Iterative = true> SCCHolder< typename GraphTraits< G >::vertex_t > psr::computeSCCs (const G & Graph, std::bool_constant< Iterative > = {})
Compute SCCs adapted from the paper "A Space-Efficient Algorithm for Finding Strongly Connected Components", Pearce 2015, DOI: https://doi.org/10.1016/j.ipl.2015.08.010
Template Parameters
G The graph-type
Iterative Whether to use the iterative or recursive variant of the algorithm (default: true)
Parameters
Graph The graph for with to compute SCCs and topological ordering
Definition at line 499 of file SCCGeneric.h.
computeSCCsAndTopologicalOrder()
template<typename G , bool Iterative = true> std::pair< SCCHolder< typename GraphTraits< G >::vertex_t >, SCCOrder< typename GraphTraits< G >::vertex_t > > psr::computeSCCsAndTopologicalOrder (const G & Graph, std::bool_constant< Iterative > = {})
Compute SCCs and a topological ordering on the SCCs, adapted from the paper "A Space-Efficient Algorithm for Finding Strongly Connected Components", Pearce 2015, DOI: https://doi.org/10.1016/j.ipl.2015.08.010
Template Parameters
G The graph-type
Iterative Whether to use the iterative or recursive variant of the algorithm (default: true)
Parameters
Graph The graph for with to compute SCCs and topological ordering
Definition at line 548 of file SCCGeneric.h.
createAnalysisProblem()
template<typename ProblemTy , typename... ArgTys> ProblemTy psr::createAnalysisProblem (HelperAnalyses & HA, ArgTys &&... Args)
Definition at line 25 of file SimpleAnalysisConstructor.h.
createEquivalentGraphFrom()
template<is_graph GraphTy> std::decay_t< GraphTy > psr::createEquivalentGraphFrom (GraphTy && G, const llvm::IntEqClasses & Eq)
Definition at line 25 of file DFAMinimizer.h.
References Ret.
createLLVMSVFDDAAliasInfo()
LLVMAliasInfo psr::createLLVMSVFDDAAliasInfo (LLVMProjectIRDB & IRDB)
Use SVF to perform a ContextDDA pointer analysis and return the results compatible to psr::LLVMAliasInfo and psr::LLVMAliasInfoRef
Note
Only support DDA for now, as VFS seems to not support getRevPts().
createLLVMSVFPointsToIterator()
LLVMPointsToIterator psr::createLLVMSVFPointsToIterator (LLVMProjectIRDB & IRDB, SVFPointsToAnalysisType PTATy)
Use SVF to perform the specified pointer analysis and return the results compatible to psr::LLVMPointsToIterator, converting the points-to sets to LLVM allocation-sites
createSVFDDAPointsToInfo()
SVFBasedPointsToInfo psr::createSVFDDAPointsToInfo (LLVMProjectIRDB & IRDB)
Use SVF to perform a ContextDDA pointer analysis and return the results compatible to psr::PointsToInfo and psr::PointsToInfoRef
createSVFPointsToInfo()
SVFBasedPointsToInfo psr::createSVFPointsToInfo (LLVMProjectIRDB & IRDB, SVFPointsToAnalysisType PTATy)
Use SVF to perform the specified pointer analysis and return the results compatible to psr::PointsToInfo and psr::PointsToInfoRef
createSVFVFSPointsToInfo()
SVFBasedPointsToInfo psr::createSVFVFSPointsToInfo (LLVMProjectIRDB & IRDB)
Use SVF to perform a VersionedFlowSensitive pointer analysis and return the results compatible to psr::PointsToInfo and psr::PointsToInfoRef
createTimeStamp()
std::string psr::createTimeStamp ()
defaultComposeOrNull() [1/2]
template<typename L > EdgeFunction< L > psr::defaultComposeOrNull (const EdgeFunction< L > & This, const EdgeFunction< L > & SecondFunction) noexcept
Definition at line 208 of file EdgeFunctionUtils.h.
defaultComposeOrNull() [2/2]
template<typename L , typename ConcreteEF > EdgeFunction< L > psr::defaultComposeOrNull (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< L > & SecondFunction) noexcept
Definition at line 195 of file EdgeFunctionUtils.h.
Referenced by psr::ConstantEdgeFunction< L >::compose(), psr::EdgeFunctionComposer< L >::compose(), psr::XTaint::EdgeFunctionBase< Derived >::compose(), psr::JoinEdgeFunction< L, N >::compose(), and psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::extend().
defaultJoinOrNull() [1/2]
template<typename L , uint8_t N = 0> EdgeFunction< L > psr::defaultJoinOrNull (const EdgeFunction< L > & This, const EdgeFunction< L > & OtherFunction)
Definition at line 409 of file EdgeFunctionUtils.h.
References psr::JoinEdgeFunction< L, N >::create().
defaultJoinOrNull() [2/2]
template<typename L , uint8_t N = 0, typename ConcreteEF > EdgeFunction< L > psr::defaultJoinOrNull (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< L > & OtherFunction)
Default implementation of EdgeFunction::join. Considers AllBottom, AllTop and EdgeIdentity for OtherFunction as well as This==OtherFunction. Joining with EdgeIdentity will overapproximate to (AllBottom if N==0, else JoinEdgeFunction).
Definition at line 390 of file EdgeFunctionUtils.h.
References psr::JoinEdgeFunction< L, N >::create().
Referenced by psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::combine().
DToString() [1/5]
std::string psr::DToString (const AbstractMemoryLocation & AML)
Referenced by psr::JumpFunctions< AnalysisDomainTy, Container >::addFunction(), psr::IDESolver< AnalysisDomainTy, Container >::computeAndPrintStatistics(), psr::InitialSeeds< N, D, L >::dump(), psr::IDESolver< AnalysisDomainTy, Container >::emitESGAsDot(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::emitTextReport(), psr::IDESolver< AnalysisDomainTy, Container >::getAsJson(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getReturnEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryEdgeFunction(), psr::IDESolver< AnalysisDomainTy, Container >::jumpFunction(), psr::IDESolver< AnalysisDomainTy, Container >::pathEdgeProcessingTask(), psr::IDESolver< AnalysisDomainTy, Container >::printComputedPathEdges(), psr::IDESolver< AnalysisDomainTy, Container >::printEndSummaryTab(), psr::IDESolver< AnalysisDomainTy, Container >::printIncomingTab(), psr::JumpFunctions< AnalysisDomainTy, Container >::printJumpFunctions(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyForwardLookup(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyLookupByTargetNode(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyReverseLookup(), psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::propagate(), psr::IDESolver< AnalysisDomainTy, Container >::setVal(), psr::IDESolver< AnalysisDomainTy, Container >::submitInitialSeeds(), and psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues().
DToString() [2/5]
template<detail::IsSomehowPrintable D> decltype(auto) psr::DToString (const D & Fact)
Stringify the given data-flow fact.
Default implementation. Provide your own overload to customize this API for your types
Definition at line 64 of file Printer.h.
References psr::detail::printSomehow().
DToString() [3/5]
std::string psr::DToString (const IntraMonoFCAFact & Fact)
DToString() [4/5]
std::string psr::DToString (const llvm::Value * V)
Stringify the given LLVM Value.
Remarks
Link phasar_llvm_utils to use this
DToString() [5/5]
llvm::StringRef psr::DToString (SecureHeapFact Fact) noexcept
dumpDIType() [1/2]
LLVM_DUMP_METHOD void psr::dumpDIType (const llvm::DIDerivedType * Ty)
dumpDIType() [2/2]
LLVM_DUMP_METHOD void psr::dumpDIType (const llvm::DIType * Ty)
dumpIRValue() [1/3]
LLVM_DUMP_METHOD void psr::dumpIRValue (const llvm::Function * V)
dumpIRValue() [2/3]
LLVM_DUMP_METHOD void psr::dumpIRValue (const llvm::Instruction * V)
dumpIRValue() [3/3]
LLVM_DUMP_METHOD void psr::dumpIRValue (const llvm::Value * V)
forallStartingPoints() [1/2]
template<typename EntryRange , typename I , typename HandlerFn > void psr::forallStartingPoints (const EntryRange & EntryPoints, const I * ICF, HandlerFn Handler)
Definition at line 69 of file EntryPointUtils.h.
References EntryPoints, and psr::detail::forallStartingPoints().
forallStartingPoints() [2/2]
template<typename EntryRange , typename C , typename DB , typename HandlerFn > void psr::forallStartingPoints (const EntryRange & EntryPoints, const ProjectIRDBBase< DB > * IRDB, const CFGBase< C > & CFG, HandlerFn Handler)
Definition at line 61 of file EntryPointUtils.h.
References EntryPoints, and psr::detail::forallStartingPoints().
Referenced by addSeedsForStartingPoints(), and addSeedsForStartingPoints().
forward_like()
template<class T , class U > LLVM_ATTRIBUTE_ALWAYS_INLINE constexpr auto && psr::forward_like (U && X) constexpr noexcept
See https://en.cppreference.com/w/cpp/utility/forward_like
Definition at line 254 of file Utilities.h.
from_json()
void psr::from_json (const nlohmann::json & J, SourceCodeInfo & Info)
Used from the JSON library internally to implicitly convert between json and SourceCodeInfo
fromMetaDataId()
const llvm::Value * psr::fromMetaDataId (const LLVMProjectIRDB & IRDB, llvm::StringRef Id)
Revserses the getMetaDataID function
FToString() [1/2]
template<detail::IsSomehowPrintable F> std::string psr::FToString (const F & Fun)
Stringify the given function.
Default implementation. Provide your own overload to customize this API for your types
Definition at line 82 of file Printer.h.
References psr::detail::printSomehow().
Referenced by psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getRetFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getReturnEdgeFunction(), and psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryFlowFunction().
FToString() [2/2]
llvm::StringRef psr::FToString (const llvm::Function * V)
Stringify the given LLVM Function.
Remarks
Link phasar_llvm_utils to use this
getAllExitPoints()
llvm::SmallVector< const llvm::Instruction *, 2 > psr::getAllExitPoints (const llvm::Function * F, bool IncludeResume = true)
getColumnFromIR()
unsigned int psr::getColumnFromIR (const llvm::Value * V)
getDebugLocation()
std::optional< DebugLocation > psr::getDebugLocation (const llvm::Value * V)
Referenced by psr::DefaultLLVMAnalysisPrinter< AnalysisDomainTy >::DefaultLLVMAnalysisPrinter().
getDefaultEntryPoints()
std::vector< std::string > psr::getDefaultEntryPoints (const LLVMProjectIRDB & IRDB)
getDefaultValue()
template<typename T > requires std::is_default_constructible_v<T> ByConstRef< T > psr::getDefaultValue () noexcept
Gets a (cached) reference to the default-constructed value of type T. If T is small and trivially default constructible, creates a temporary instead. Useful for getters that return ByConstRef<T> but need to handle the non-existing-T case
Definition at line 26 of file DefaultValue.h.
getDIFileFromIR()
const llvm::DIFile * psr::getDIFileFromIR (const llvm::Value * V)
getDILocalVariable()
llvm::DILocalVariable * psr::getDILocalVariable (const llvm::Value * V)
getDILocation()
llvm::DILocation * psr::getDILocation (const llvm::Value * V)
getDirectoryFromIR()
std::string psr::getDirectoryFromIR (const llvm::Value * V)
getEntryFunctions()
std::vector< const llvm::Function * > psr::getEntryFunctions (const LLVMProjectIRDB & IRDB, llvm::ArrayRef< std::string > EntryPoints)
getEntryFunctionsMut()
std::vector< llvm::Function * > psr::getEntryFunctionsMut (LLVMProjectIRDB & IRDB, llvm::ArrayRef< std::string > EntryPoints)
getFilePathFromIR() [1/2]
std::string psr::getFilePathFromIR (const llvm::DIFile * DIF)
getFilePathFromIR() [2/2]
std::string psr::getFilePathFromIR (const llvm::Value * V)
Referenced by psr::Z3BasedPathSensitivityManager< AnalysisDomainTy >::pathsTo().
getFunctionArgumentNr()
int psr::getFunctionArgumentNr (const llvm::Argument * Arg)
Returns position of a formal function argument.
Parameters
Arg LLVM Argument.
Returns
Position or -1 if argument does not belong to any function.
getFunctionNameFromIR()
std::string psr::getFunctionNameFromIR (const llvm::Value * V)
Referenced by psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::emitTextReport().
getGeneratedFacts()
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> ContainerTy psr::getGeneratedFacts (const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee)
Definition at line 92 of file TaintConfigUtilities.h.
References collectGeneratedFacts(), and Ret.
getLastInstructionOf()
const llvm::Instruction * psr::getLastInstructionOf (const llvm::Function * F)
getLeakedFacts() [1/2]
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> ContainerTy psr::getLeakedFacts (const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee)
Definition at line 113 of file TaintConfigUtilities.h.
References collectLeakedFacts(), and Ret.
getLeakedFacts() [2/2]
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> ContainerTy psr::getLeakedFacts (const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee, std::invocable< const llvm::Value * > auto && LeakIf)
Definition at line 103 of file TaintConfigUtilities.h.
References collectLeakedFacts(), PSR_FWD, and Ret.
getLibCSummary()
const library_summary::FunctionDataFlowFacts & psr::getLibCSummary ()
getLineAndColFromIR()
std::pair< unsigned, unsigned > psr::getLineAndColFromIR (const llvm::Value * V)
getLineFromIR()
unsigned int psr::getLineFromIR (const llvm::Value * V)
getMetaDataID()
std::string psr::getMetaDataID (const llvm::Value * V)
Returns the ID of a given LLVM Value.
Only Instructions and GlobalVariables have 'real' ID's, i.e. annotated meta data. Formal arguments cannot be annotated with metadata in LLVM. Therefore, a formal arguments ID will look like this: <function_name>.<argument>
ZeroValue will have -1 as ID by default.
Returns
Meta data ID as a string or -1, if it's not an Instruction, GlobalVariable or Argument.
Referenced by psr::Z3BasedPathSensitivityManager< AnalysisDomainTy >::pathsTo().
getModuleFromVal()
const llvm::Module * psr::getModuleFromVal (const llvm::Value * V)
Returns the LLVM Module to which the given LLVM Value belongs to.
Parameters
V LLVM Value.
Returns
LLVM Module or nullptr.
getModuleIDFromIR()
std::string psr::getModuleIDFromIR (const llvm::Value * V)
getModuleNameFromVal()
std::string psr::getModuleNameFromVal (const llvm::Value * V)
Returns the name of the LLVM Module to which the given LLVM Value belongs to.
Parameters
V LLVM Value.
Returns
Module name or empty string.
getModuleSlotTrackerFor()
llvm::ModuleSlotTracker & psr::getModuleSlotTrackerFor (const llvm::Value * V)
getNonPureVirtualVFTEntry()
const llvm::Function * psr::getNonPureVirtualVFTEntry (const llvm::DIType * T, unsigned Idx, const llvm::CallBase * CallSite, const psr::LLVMVFTableProvider & VTP, const llvm::DIType * ReceiverType)
Assuming that CallSite is a virtual call, where Idx is retrieved through getVFTIndex() and T through getReceiverType()
Referenced by psr::Resolver::getNonPureVirtualVFTEntry().
getNthFunctionArgument()
const llvm::Argument * psr::getNthFunctionArgument (const llvm::Function * F, unsigned ArgNo)
Returns the n-th LLVM Argument of a given LLVM Function.
The Argument count starts with 0.
Parameters
F Function to retrieve the Arguments from.
argNo Argument number.
Returns
LLVM Argument or nullptr, if argNo invalid.
getNthInstruction()
const llvm::Instruction * psr::getNthInstruction (const llvm::Function * F, unsigned Idx)
Returns the n-th LLVM Instruction of a given LLVM Function.
The Instruction count starts with one (not zero, as in Function arguments).
Parameters
F Function to retrieve the Instruction from.
instNo Instruction number.
Returns
LLVM Instruction or nullptr, if instNo invalid.
getNthStoreInstruction()
const llvm::StoreInst * psr::getNthStoreInstruction (const llvm::Function * F, unsigned StoNo)
Returns the n-th LLVM Store Instruction of a given LLVM Function.
The Store Instruction count starts with one (not zero, as in Function arguments).
Parameters
F Function to retrieve the Store Instruction from.
termInstNo Store Instruction number.
Returns
LLVM Store Instruction or nullptr, if stoNo invalid.
getNthTermInstruction()
const llvm::Instruction * psr::getNthTermInstruction (const llvm::Function * F, unsigned TermInstNo)
Returns the n-th LLVM Termination Instruction of a given LLVM Function.
The Termination Instruction count starts with one (not zero, as in Function arguments).
Parameters
F Function to retrieve the Termination Instruction from.
termInstNo Termination Instruction number.
Returns
LLVM Instruction or nullptr, if termInstNo invalid.
getOrEmpty()
template<typename T > requires std::is_default_constructible_v<T> T psr::getOrEmpty (llvm::ErrorOr< T > ValOrErr) noexcept
Definition at line 43 of file ErrorHandling.h.
getOrNull()
template<typename T > std::optional< T > psr::getOrNull (llvm::ErrorOr< T > ValOrErr) noexcept
Definition at line 33 of file ErrorHandling.h.
getOrThrow()
template<typename T > T psr::getOrThrow (llvm::ErrorOr< T > ValOrErr)
Definition at line 25 of file ErrorHandling.h.
getPointerFrom() [1/18]
template<typename T > constexpr BoxedConstPtr< T > psr::getPointerFrom (BoxedConstPtr< T > Ptr) constexpr noexcept
Definition at line 92 of file PointerUtils.h.
getPointerFrom() [2/18]
template<typename T > constexpr BoxedPtr< T > psr::getPointerFrom (BoxedPtr< T > Ptr) constexpr noexcept
Definition at line 87 of file PointerUtils.h.
getPointerFrom() [3/18]
template<typename T > constexpr T * psr::getPointerFrom (const llvm::IntrusiveRefCntPtr< T > & Ptr) constexpr noexcept
Definition at line 74 of file PointerUtils.h.
getPointerFrom() [4/18]
template<typename T , bool RequireAlignment> constexpr T * psr::getPointerFrom (const MaybeUniquePtr< T, RequireAlignment > & Ptr) constexpr noexcept
Definition at line 48 of file PointerUtils.h.
getPointerFrom() [5/18]
template<typename T > constexpr T * psr::getPointerFrom (const std::shared_ptr< T > & Ptr) constexpr noexcept
Definition at line 62 of file PointerUtils.h.
getPointerFrom() [6/18]
template<typename T > constexpr T * psr::getPointerFrom (const std::unique_ptr< T > & Ptr) constexpr noexcept
Definition at line 36 of file PointerUtils.h.
getPointerFrom() [7/18]
template<typename T > requires (!std::is_pointer_v<T>) constexpr const T * psr::getPointerFrom (const T & Ref) constexpr noexcept
Definition at line 24 of file PointerUtils.h.
getPointerFrom() [8/18]
template<typename T > constexpr T * psr::getPointerFrom (llvm::IntrusiveRefCntPtr< T > && Ptr) constexpr noexcept
getPointerFrom() [9/18]
template<typename T > constexpr T * psr::getPointerFrom (llvm::IntrusiveRefCntPtr< T > & Ptr) constexpr noexcept
Definition at line 79 of file PointerUtils.h.
getPointerFrom() [10/18]
template<typename T , bool RequireAlignment> constexpr T * psr::getPointerFrom (MaybeUniquePtr< T, RequireAlignment > && Ptr) constexpr delete noexcept
getPointerFrom() [11/18]
template<typename T , bool RequireAlignment> constexpr T * psr::getPointerFrom (MaybeUniquePtr< T, RequireAlignment > & Ptr) constexpr noexcept
Definition at line 53 of file PointerUtils.h.
getPointerFrom() [12/18]
template<typename T > constexpr T * psr::getPointerFrom (std::shared_ptr< T > && Ptr) constexpr delete noexcept
getPointerFrom() [13/18]
template<typename T > constexpr T * psr::getPointerFrom (std::shared_ptr< T > & Ptr) constexpr noexcept
Definition at line 66 of file PointerUtils.h.
getPointerFrom() [14/18]
template<typename T > constexpr T * psr::getPointerFrom (std::unique_ptr< T > && Ptr) constexpr delete noexcept
getPointerFrom() [15/18]
template<typename T > constexpr T * psr::getPointerFrom (std::unique_ptr< T > & Ptr) constexpr noexcept
Definition at line 40 of file PointerUtils.h.
getPointerFrom() [16/18]
template<typename T > requires (!std::is_pointer_v<T>) constexpr T * psr::getPointerFrom (T && Ref) constexpr delete noexcept
getPointerFrom() [17/18]
template<typename T > requires (!std::is_pointer_v<T>) constexpr T * psr::getPointerFrom (T & Ref) constexpr noexcept
A simple helper function to get a raw pointer from an arbitrary pointer type in generic code. This overload set is extendable.
Definition at line 19 of file PointerUtils.h.
getPointerFrom() [18/18]
template<typename T > T * psr::getPointerFrom (T * Ptr) noexcept
Definition at line 31 of file PointerUtils.h.
getReceiverType()
const llvm::DIType * psr::getReceiverType (const llvm::CallBase * CallSite)
Assuming that CallSite is a call to a non-static member function, retrieves the type of the receiver. Returns nullptr, if the receiver-type could not be extracted
getReceiverTypeName()
std::string psr::getReceiverTypeName (const llvm::CallBase * CallSite)
getSanitizedFacts()
template<typename ContainerTy > requires std::is_same_v<typename ContainerTy::value_type, const llvm::Value *> ContainerTy psr::getSanitizedFacts (const LLVMTaintConfig & Config, const llvm::CallBase * CB, const llvm::Function * Callee)
Definition at line 123 of file TaintConfigUtilities.h.
References collectSanitizedFacts(), and Ret.
getSrcCodeFromIR() [1/2]
std::string psr::getSrcCodeFromIR (const llvm::Value * V, bool Trim = true)
getSrcCodeFromIR() [2/2]
std::string psr::getSrcCodeFromIR (DebugLocation Loc, bool Trim = true)
getSrcCodeInfoFromIR()
SourceCodeInfo psr::getSrcCodeInfoFromIR (const llvm::Value * V)
getVaListTagOrNull()
const llvm::AllocaInst * psr::getVaListTagOrNull (const llvm::Function & Fun)
getVarAnnotationIntrinsicName()
llvm::StringRef psr::getVarAnnotationIntrinsicName (const llvm::CallInst * CallInst)
Retrieves String annotation value as per https://llvm.org/docs/LangRef.html#llvm-var-annotation-intrinsic Test the call function be tested by isVarAnnotationIntrinsic
getVarNameFromIR()
std::string psr::getVarNameFromIR (const llvm::Value * V)
getVarTypeFromIR()
llvm::DIType * psr::getVarTypeFromIR (const llvm::Value * V)
getVFTIndex()
std::optional< unsigned > psr::getVFTIndex (const llvm::CallBase * CallSite)
Assuming that CallSite is a virtual call through a vtable, retrieves the index in the vtable of the virtual function called.
getVFTIndexAndVT()
std::optional< std::pair< const llvm::Value *, uint64_t > > psr::getVFTIndexAndVT (const llvm::CallBase * CallSite)
Similar to getVFTIndex(), but also returns a pointer to the vtable.
globalValuesUsedinFunction()
std::vector< const llvm::Value * > psr::globalValuesUsedinFunction (const llvm::Function * F)
Returns all LLVM Global Values that are used in the given LLVM Function.
hasFlag()
template<detail::is_enum T> constexpr bool psr::hasFlag (T This, T Flag) constexpr noexcept
Definition at line 79 of file EnumFlags.h.
hash_value()
llvm::hash_code psr::hash_value (psr::AbstractMemoryLocation Val)
Referenced by psr::IDEFeatureTaintAnalysis::combine().
IDESolver() [1/2]
template<typename Problem , typename ICF > psr::IDESolver (Problem & , ICF *) -> IDESolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
IDESolver() [2/2]
template<typename Problem , typename ICF > psr::IDESolver (Problem * , ICF *) -> IDESolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
IDETypeStateAnalysis()
template<typename TypeStateDescriptionTy > psr::IDETypeStateAnalysis (const LLVMProjectIRDB * , LLVMAliasInfoRef , const TypeStateDescriptionTy * , std::vector< std::string > EntryPoints) -> IDETypeStateAnalysis< TypeStateDescriptionTy >
ifdsEqual()
template<typename SR1 , typename SR2 > bool psr::ifdsEqual (const SR1 & LHS, const SR2 & RHS)
Definition at line 166 of file GenericSolverResults.h.
IFDSSolver() [1/2]
template<typename Problem , typename ICF > psr::IFDSSolver (Problem & , ICF *) -> IFDSSolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
IFDSSolver() [2/2]
template<typename Problem , typename ICF > psr::IFDSSolver (Problem * , ICF *) -> IFDSSolver< typename Problem::ProblemAnalysisDomain, typename Problem::container_type >
intersectWith() [1/3]
template<typename T > void psr::intersectWith (BitVectorSet< T > & Dest, const BitVectorSet< T > & Src)
Definition at line 314 of file BitVectorSet.h.
References psr::BitVectorSet< T, BitVectorTy >::setIntersectWith().
intersectWith() [2/3]
template<typename ContainerTy , typename OtherContainerTy > requires (!has_erase_iterator_v<ContainerTy>) void psr::intersectWith (ContainerTy & Dest, const OtherContainerTy & Src)
Computes the set-intersection of the potentially unordered sets Dest and Src and stores the result back in Dest.
This function should work on all types of sets as long as they provide the type value_type specifying, which type their elements have. By-reference iteration is required, but the elements do not have any requirements, although the performance is probably higher for small elements that are trivially copyable.
This whole functionality is only for computing the set-intersection of Dest and Src storing the result in-place in Dest. It would be a big win, if the STL would provide us with in-place set operations and those that do not require the sets to be sorted...
Definition at line 83 of file Utilities.h.
intersectWith() [3/3]
template<has_erase_iterator_v ContainerTy, typename OtherContainerTy > void psr::intersectWith (ContainerTy & Dest, const OtherContainerTy & Src)
Definition at line 128 of file Utilities.h.
IntraMonoSolver()
template<typename Problem > psr::IntraMonoSolver (Problem &) -> IntraMonoSolver< typename Problem::ProblemAnalysisDomain >
iota() [1/2]
template<typename IdT > constexpr auto psr::iota (IdT From, type_identity_t< IdT > To) constexpr noexcept
Definition at line 78 of file IotaIterator.h.
References Ret.
iota() [2/2]
template<typename IdT > constexpr auto psr::iota (size_t To) constexpr noexcept
Definition at line 87 of file IotaIterator.h.
IRDBGetFunctionDef()
template<typename DB > auto psr::IRDBGetFunctionDef (const ProjectIRDBBase< DB > * IRDB) noexcept
Definition at line 164 of file ProjectIRDBBase.h.
isAddressTakenFunction()
bool psr::isAddressTakenFunction (const llvm::Function * F)
A variant of F->hasAddressTaken() that is better suited for our use cases.
Especially, it filteres out global aliases.
isAllocaInstOrHeapAllocaFunction()
bool psr::isAllocaInstOrHeapAllocaFunction (const llvm::Value * V) noexcept
Checks if the given LLVM Value is either a alloca instruction or a heap allocation function, e.g. new, new[], malloc, realloc or calloc.
isConsistentCall()
bool psr::isConsistentCall (const llvm::CallBase * CallSite, const llvm::Function * DestFun)
Checks whether the signature of DestFun matches the required withature of CallSite, such that DestFun qualifies as callee-candidate, if CallSite is an indirect/virtual call.
isConstructor()
bool psr::isConstructor (llvm::StringRef MangledName)
isGuardVariable()
bool psr::isGuardVariable (const llvm::Value * V)
True, iff V is the compiler-generated guard variable for the thread-safe initialization of function-local static variables.
isHeapAllocatingFunction() [1/2]
bool psr::isHeapAllocatingFunction (const llvm::Function * F) noexcept
Referenced by psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getAllVariables().
isHeapAllocatingFunction() [2/2]
bool psr::isHeapAllocatingFunction (llvm::StringRef FName) noexcept
Checks, whether a function with the given (mangled) name is known to be a heap-allocating function, similar to malloc.
isInReachableAllocationSitesTy()
bool psr::isInReachableAllocationSitesTy (const llvm::Value * V, const llvm::Value * PotentialValue, bool IntraProcOnly, const llvm::Function * VFun = nullptr, const llvm::GlobalObject * VG = nullptr)
Utility function to check whether PotentialValue may be in the reachable allocation-sites of V, if V and PotentialValue alias.
isIntegerLikeType()
bool psr::isIntegerLikeType (const llvm::Type * T) noexcept
Checks if the given LLVM Type is a integer like struct.
Parameters
V LLVM Type.
Returns
True, if given LLVM Type is a struct like this TSi = type <{ i64 }>. False, otherwise.
isInterestingPointer()
bool psr::isInterestingPointer (const llvm::Value * V) inline
Returns true if the given pointer is an interesting pointer, i.e. not a constant null pointer.
Definition at line 26 of file LLVMPointsToUtils.h.
isInterProc()
constexpr bool psr::isInterProc (ESGEdgeKind Kind) constexpr noexcept
Definition at line 16 of file ESGEdgeKind.h.
References Call, and Ret.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::saveEdges().
isMangled()
bool psr::isMangled (llvm::StringRef Name)
isSingletonReturningFunction()
bool psr::isSingletonReturningFunction (llvm::StringRef FName) noexcept
Checks whether a function with the given (mangled) name is known to always return the same pointer
isStaticVariableLazyInitializationBranch()
bool psr::isStaticVariableLazyInitializationBranch (const llvm::BranchInst * Inst)
True, iff V is the compiler-generated branch that leads to the lazy initialization of a function-local static variable.
isTouchVTableInst()
bool psr::isTouchVTableInst (const llvm::StoreInst * Store)
isVaListAlloca()
bool psr::isVaListAlloca (const llvm::AllocaInst & Alloc)
isVarAnnotationIntrinsic()
bool psr::isVarAnnotationIntrinsic (const llvm::Function * F)
Tests for https://llvm.org/docs/LangRef.html#llvm-var-annotation-intrinsic e.g. int boo attribute((annotate("bar"));
Parameters
F The function to test - Target of the call instruction
isVirtualCall()
bool psr::isVirtualCall (const llvm::Instruction * Inst, const LLVMVFTableProvider & VTP)
llvmIRToShortString()
std::string psr::llvmIRToShortString (const llvm::Value * V)
Same as llvmIRToString) but tries to shorten the resulting string.
Referenced by psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getNormalEdgeFunction().
llvmIRToStableString()
std::string psr::llvmIRToStableString (const llvm::Value * V)
Similar to llvmIRToString, but removes the metadata from the output as they are not always stable. Prefer this function over llvmIRToString, if you are comparing the string representations of LLVM iR instructions.
llvmIRToString()
std::string psr::llvmIRToString (const llvm::Value * V)
Returns a string representation of a LLVM Value.
Referenced by checkSREquality(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getNormalEdgeFunction(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getStrongUpdateStoreEF(), and psr::detail::printHelper().
llvmTypeToString() [1/2]
std::string psr::llvmTypeToString (const llvm::DIType * Ty, bool Shorten = false)
Returns a string-representation of a LLVM Debug-Info type.
Parameters
Shorten Tries to shorten the output
llvmTypeToString() [2/2]
std::string psr::llvmTypeToString (const llvm::Type * Ty, bool Shorten = false)
Returns a string-representation of a LLVM type.
Parameters
Shorten Tries to shorten the output
LToString() [1/3]
std::string psr::LToString (const IDEFeatureTaintEdgeFact & EdgeFact)
Referenced by psr::FeatureTaintGenerator::createEdgeFactPrinter(), psr::InitialSeeds< N, D, L >::dump(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::emitTextReport(), psr::IDESolver< AnalysisDomainTy, Container >::getAsJson(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::printEdgeFactImpl(), psr::IDESolver< AnalysisDomainTy, Container >::setVal(), psr::IDEFeatureTaintEdgeFact::str(), psr::IDESolver< AnalysisDomainTy, Container >::submitInitialSeeds(), and psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues().
LToString() [2/3]
template<detail::IsSomehowPrintable L> decltype(auto) psr::LToString (const L & Value)
Stringify the given edge value.
Default implementation. Provide your own overload to customize this API for your types
Definition at line 73 of file Printer.h.
References psr::detail::printSomehow().
LToString() [3/3]
llvm::StringRef psr::LToString (SecureHeapValue Val) noexcept
mapFactsAlongsideCallSite()
template<typename D = const llvm::Value *, typename Container = std::set<D>, typename Fn = TrueFn, typename DCtor = DefaultConstruct<D>> requires std::is_invocable_r_v<bool, Fn, const llvm::Value *> auto psr::mapFactsAlongsideCallSite (const llvm::CallBase * CallSite, Fn && PropagateArgs = {}, bool PropagateGlobals = true, DCtor && FactConstructor = {})
A flow function that serves as default-implementation for the call-to-return flow function. For more details on the use-case of call-to-return flow functions, see the documentation of FlowFunction::getCallToRetFlowFunction().
Propagates all dataflow facts unchanged, except for global variables and arguments of the specified call-site. Global variables are propagated only if PropagateGlobals is set to true; for the argument values the PropagateArgs function defines on a per-arg basis whether the respective argument should be propagated or killed. By default (when not specifying PropagateArgs), all parameters are propagated unchanged.
For analyses that propagate values via reference parameters in the return flow function, it is useful to kill the respective arguments here to enable strong updates.
Definition at line 58 of file LLVMFlowFunctions.h.
mapFactsToCallee()
template<typename D = const llvm::Value *, typename Container = std::set<D>, typename Fn = std::equal_to<D>, typename DCtor = DefaultConstruct<D>> requires std::is_invocable_r_v<bool, Fn, const llvm::Value *, D> FlowFunctionPtrType< D, Container > psr::mapFactsToCallee (const llvm::CallBase * CallSite, const llvm::Function * DestFun, Fn && PropagateArgumentWithSource = {}, DCtor && FactConstructor = {}, bool PropagateGlobals = true, bool PropagateZeroToCallee = true)
A flow function that serves as default implementation of the call flow function. For more information about call flow functions, see FlowFunctions::getCallFlowFunction().
Propagates the arguments of the specified call-site into the callee function if the function PropagateArgumentWithSource evaluates to true when invoked with the argument and a currently holding dataflow fact. Global variables are propagated into the callee function only, if the flag PropagateGlobals is set to true. The special zero (Λ) value gets propagated into the callee function if PropagateZeroToCallee is true. For most analyses it makes sense to propagate Λ everywhere.
Given a call-site cs: r = fun(..., ax, ...) and a function prototype fun(..., px, ...). Further let f = mapFactsToCallee(cs, fun, ...). Then for any dataflow fact x: f(Λ) = {Λ} if PropagateZeroToCallee else {}, f(ax) = {px} if PropagateArgumentWithSource(ax, ax) else {}, f(g) = {g} if g is GlobalVariable && PropagateGlobals else {}, f(x) = {px} if PropagateArgumentWithSource(ax, x) else {}.
Note
Unlike the old version, this one is only meant for forward-analyses
Definition at line 133 of file LLVMFlowFunctions.h.
mapFactsToCaller()
template<typename D = const llvm::Value *, typename Container = std::set<D>, typename FnParam = std::equal_to<D>, typename FnRet = std::equal_to<D>, typename DCtor = DefaultConstruct<D>, typename PostProcessFn = IgnoreArgs> requires (std::is_invocable_r_v<bool, FnParam, const llvm::Value *, D> && std::is_invocable_r_v<bool, FnRet, const llvm::Value *, D>) FlowFunctionPtrType< D, Container > psr::mapFactsToCaller (const llvm::CallBase * CallSite, const llvm::Instruction * ExitInst, FnParam && PropagateParameter = {}, FnRet && PropagateRet = {}, DCtor && FactConstructor = {}, bool PropagateGlobals = true, bool PropagateZeroToCaller = true, PostProcessFn && PostProcess = {})
A flow function that serves as default-implementation of the return flow function. For more information about return flow functions, see FlowFunctions::getRetFlowFunction().
Propagates the return value back to the call-site and based on the PropagateParameter predicate propagates back parameters holding as dataflow facts. The resulting out-set of dataflow facts can be post-processed if necessary.
Let a call-site cs: r = fun(..., ax, ...) a function prototype fun(..., px, ...) and an exit statement exit: return rv. Further given a flow function f = mapFactsToCaller(cs, exit, ...). Then for all dataflow facts x holding at exit: f(rv) = {r} if PropagateRet(rv, rv) else {}, f(px) = {ax} if PropagateParameter(px, px) else {}, f(g) = {g} if PropagateGlobals else {}, f(Λ) = {Λ} if PropagateZeroToCaller else {}, f(x) = ({ax} if PropagateParameter(ax, x) else {}) union ({r} if PropagateRet(rv, x) else {}).
Definition at line 240 of file LLVMFlowFunctions.h.
mapValue() [1/2]
template<typename T , typename MapFn > llvm::ErrorOr< std::invoke_result_t< MapFn, const T & > > psr::mapValue (const llvm::ErrorOr< T > & ValOrErr, MapFn Mapper) noexcept
Definition at line 53 of file ErrorHandling.h.
mapValue() [2/2]
template<typename T , typename MapFn > llvm::ErrorOr< std::invoke_result_t< MapFn, T > > psr::mapValue (llvm::ErrorOr< T > && ValOrErr, MapFn Mapper) noexcept
Definition at line 63 of file ErrorHandling.h.
matchesSignature() [1/2]
bool psr::matchesSignature (const llvm::Function * F, const llvm::FunctionType * FType, bool ExactMatch = true)
Returns true if the provided function and the function type are both not null and have the same number of parameters and the same return type. If the argument ExactMatch is set to true, which it is by default, the two provided arguments must also have the same type for each argument, for the function to return true.
Note
This function is less useful in practice than you may think. Consider using isConsistentCall() instead.
matchesSignature() [2/2]
bool psr::matchesSignature (const llvm::FunctionType * FType1, const llvm::FunctionType * FType2)
Returns true iff the provided functions are both not null and have the same number of paramters, the same return type and each parameter of both functions has the same type aswell.
Note
This function is less useful in practice than you may think. Consider using isConsistentCall() instead.
minimizeGraph()
template<is_graph GraphTy> llvm::IntEqClasses psr::minimizeGraph (const GraphTy & G)
NOTE: This algorithm can be further optimized, but for now it is fast enough
Definition at line 83 of file DFAMinimizer.h.
References PHASAR_LOG_LEVEL_CAT.
NToString() [1/3]
std::string psr::NToString (const llvm::Instruction * V)
Stringify the given LLVM Instruction.
Remarks
Link phasar_llvm_utils to use this
NToString() [2/3]
std::string psr::NToString (const llvm::Value * V)
Stringify the given LLVM Value.
Remarks
Link phasar_llvm_utils to use this
NToString() [3/3]
template<detail::IsSomehowPrintable N> decltype(auto) psr::NToString (const N & Node)
Stringify the given ICFG node (instruction/statement).
Default implementation. Provide your own overload to customize this API for your types
Definition at line 55 of file Printer.h.
References psr::detail::printSomehow().
Referenced by psr::JumpFunctions< AnalysisDomainTy, Container >::addFunction(), psr::IDESolver< AnalysisDomainTy, Container >::computeAndPrintStatistics(), psr::InitialSeeds< N, D, L >::dump(), psr::InterMonoSolver< AnalysisDomainTy, K >::dumpResults(), psr::IDESolver< AnalysisDomainTy, Container >::emitESGAsDot(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::emitTextReport(), psr::IDESolver< AnalysisDomainTy, Container >::getAsJson(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getCallToRetFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getNormalFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getRetFlowFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getReturnEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryEdgeFunction(), psr::FlowEdgeFunctionCache< AnalysisDomainTy, Container >::getSummaryFlowFunction(), psr::IDESolver< AnalysisDomainTy, Container >::jumpFunction(), psr::IDESolver< AnalysisDomainTy, Container >::pathEdgeProcessingTask(), psr::CallStringCTX< N, K >::print(), psr::IDESolver< AnalysisDomainTy, Container >::printComputedPathEdges(), psr::IDESolver< AnalysisDomainTy, Container >::printEndSummaryTab(), psr::IDESolver< AnalysisDomainTy, Container >::printIncomingTab(), psr::JumpFunctions< AnalysisDomainTy, Container >::printJumpFunctions(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyForwardLookup(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyLookupByTargetNode(), psr::JumpFunctions< AnalysisDomainTy, Container >::printNonEmptyReverseLookup(), psr::InterMonoSolver< AnalysisDomainTy, K >::printWorkList(), psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::InterMonoSolver< AnalysisDomainTy, K >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::processExit(), psr::InterMonoSolver< AnalysisDomainTy, K >::processExit(), psr::InterMonoSolver< AnalysisDomainTy, K >::processNormal(), psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow(), psr::IDESolver< AnalysisDomainTy, Container >::propagate(), psr::IDESolver< AnalysisDomainTy, Container >::setVal(), psr::IDESolver< AnalysisDomainTy, Container >::submitInitialSeeds(), and psr::IDESolver< AnalysisDomainTy, Container >::submitInitialValues().
openFileStream()
std::unique_ptr< llvm::raw_fd_ostream > psr::openFileStream (const llvm::Twine & Filename)
operator&()
template<detail::is_enum T> constexpr EnumFlagAutoBool< T > psr::operator& (T Lhs, T Rhs) constexpr noexcept
Definition at line 32 of file EnumFlags.h.
operator&=()
template<detail::is_enum T> constexpr void psr::operator&= (T & Lhs, T Rhs) constexpr noexcept
Definition at line 37 of file EnumFlags.h.
operator<() [1/3]
bool psr::operator< (const DOTEdge & Lhs, const DOTEdge & Rhs)
operator<() [2/3]
bool psr::operator< (const DOTNode & Lhs, const DOTNode & Rhs)
operator<() [3/3]
template<typename L > bool psr::operator< (const LatticeDomain< L > & Lhs, const LatticeDomain< L > & Rhs) inline
Top < (Lhs::L < Rhs::L) < Bottom
Definition at line 179 of file LatticeDomain.h.
operator<<() [1/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, AliasAnalysisType PA)
operator<<() [2/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, AliasResult AR)
operator<<() [3/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, AnalysisProperties Prop) inline
Definition at line 28 of file AnalysisProperties.h.
References to_string().
operator<<() [4/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, AnalysisStrategy S)
operator<<() [5/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, BinaryDomain B)
operator<<() [6/27]
template<typename L > llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, ByConstRef< ConstantEdgeFunction< L > > Id)
Definition at line 88 of file EdgeFunctionUtils.h.
operator<<() [7/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, CallGraphAnalysisType CGA)
operator<<() [8/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const DOTEdge & Edge)
operator<<() [9/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const DOTFactSubGraph & FactSG)
operator<<() [10/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const DOTFunctionSubGraph & FunctionSG)
operator<<() [11/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const DOTNode & Node)
operator<<() [12/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const GeneralStatistics & Statistics)
operator<<() [13/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const IDEIIAFlowFact & FlowFact) inline
Definition at line 159 of file IDEInstInteractionAnalysis.h.
operator<<() [14/27]
template<typename AnalysisDomainTy , typename Container > llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const IDESolver< AnalysisDomainTy, Container > & Solver)
Definition at line 1915 of file IDESolver.h.
operator<<() [15/27]
template<typename L > llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const LatticeDomain< L > & LD) inline
Definition at line 105 of file LatticeDomain.h.
operator<<() [16/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const nlohmann::json & J)
operator<<() [17/27]
template<is_llvm_printable_v T> llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const std::optional< T > & Opt)
Definition at line 279 of file Utilities.h.
operator<<() [18/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const std::vector< bool > & Bits)
operator<<() [19/27]
template<typename T , typename F > llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const TypeHierarchy< T, F > & TH) inline
Definition at line 45 of file TypeHierarchy.h.
operator<<() [20/27]
template<typename T , typename F > llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, const VFTable< F > & Table) inline
Definition at line 44 of file VFTable.h.
operator<<() [21/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, CSTDFILEIOState State) inline
Definition at line 33 of file CSTDFILEIOTypeStateDescription.h.
References to_string().
operator<<() [22/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, DataFlowAnalysisType D)
operator<<() [23/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, Soundness S)
operator<<() [24/27]
llvm::raw_ostream & psr::operator<< (llvm::raw_ostream & OS, SpecialMemberFunctionType SMFT)
operator<<() [25/27]
std::ostream & psr::operator<< (std::ostream & OS, const IDEIIAFlowFact & FlowFact) inline
Definition at line 165 of file IDEInstInteractionAnalysis.h.
operator<<() [26/27]
template<typename L > std::ostream & psr::operator<< (std::ostream & OS, const LatticeDomain< L > & LD) inline
Definition at line 124 of file LatticeDomain.h.
operator<<() [27/27]
template<typename T > std::ostream & psr::operator<< (std::ostream & OS, const PrettyPrinter< T > & P)
Definition at line 100 of file DebugOutput.h.
operator==() [1/10]
template<typename L > bool psr::operator== (Bottom , const LatticeDomain< L > & Rhs) inline noexcept
Definition at line 169 of file LatticeDomain.h.
operator==() [2/10]
template<typename L > requires (!CanEfficientlyPassByValue<ConstantEdgeFunction<L>>) constexpr bool psr::operator== (const ConstantEdgeFunction< L > & LHS, const ConstantEdgeFunction< L > & RHS) constexpr noexcept
Definition at line 82 of file EdgeFunctionUtils.h.
operator==() [3/10]
bool psr::operator== (const DOTNode & Lhs, const DOTNode & Rhs)
operator==() [4/10]
template<typename L > bool psr::operator== (const LatticeDomain< L > & Lhs, Bottom) inline noexcept
Definition at line 159 of file LatticeDomain.h.
operator==() [5/10]
template<typename L > bool psr::operator== (const LatticeDomain< L > & Lhs, const LatticeDomain< L > & Rhs) inline
No need to check whether Lhs is an L; the indices are already the same
Definition at line 131 of file LatticeDomain.h.
operator==() [6/10]
template<typename L , typename LL > requires AreEqualityComparable<LL, L> bool psr::operator== (const LatticeDomain< L > & Lhs, const LL & Rhs) inline
Definition at line 154 of file LatticeDomain.h.
operator==() [7/10]
template<typename L > bool psr::operator== (const LatticeDomain< L > & Lhs, Top) inline noexcept
Definition at line 164 of file LatticeDomain.h.
operator==() [8/10]
template<typename L , typename LL > requires AreEqualityComparable<LL, L> bool psr::operator== (const LL & Lhs, const LatticeDomain< L > & Rhs) inline
Definition at line 145 of file LatticeDomain.h.
operator==() [9/10]
template<typename L > requires CanEfficientlyPassByValue<ConstantEdgeFunction<L>> constexpr bool psr::operator== (ConstantEdgeFunction< L > LHS, ConstantEdgeFunction< L > RHS) constexpr noexcept
Definition at line 74 of file EdgeFunctionUtils.h.
operator==() [10/10]
template<typename L > bool psr::operator== (Top , const LatticeDomain< L > & Rhs) inline noexcept
Definition at line 174 of file LatticeDomain.h.
operator^()
template<detail::is_enum T> constexpr T psr::operator^ (T Lhs, T Rhs) constexpr noexcept
Definition at line 50 of file EnumFlags.h.
operator^=()
template<detail::is_enum T> constexpr void psr::operator^= (T & Lhs, T Rhs) constexpr noexcept
Definition at line 55 of file EnumFlags.h.
operator|()
template<detail::is_enum T> constexpr T psr::operator| (T Lhs, T Rhs) constexpr noexcept
Definition at line 41 of file EnumFlags.h.
operator|=()
template<detail::is_enum T> constexpr void psr::operator|= (T & Lhs, T Rhs) constexpr noexcept
Definition at line 46 of file EnumFlags.h.
operator~()
template<detail::is_enum T> constexpr T psr::operator~ (T Rhs) constexpr noexcept
Definition at line 59 of file EnumFlags.h.
Overloaded()
template<class... Ts> psr::Overloaded (Ts...) -> Overloaded< Ts... >
parseSeverityLevel()
SeverityLevel psr::parseSeverityLevel (llvm::StringRef Str) noexcept
parseTaintConfig()
TaintConfigData psr::parseTaintConfig (const llvm::Twine & Path)
parseTaintConfigOrNull()
std::optional< TaintConfigData > psr::parseTaintConfigOrNull (const llvm::Twine & Path) noexcept
PathAwareIDESolver()
template<typename ProblemTy > psr::PathAwareIDESolver (ProblemTy &) -> PathAwareIDESolver< typename ProblemTy::ProblemAnalysisDomain >
PrettyPrinter()
template<typename T > psr::PrettyPrinter (const T &) -> PrettyPrinter< T >
printGraph()
template<is_const_graph GraphTy, typename NodeTransform = DefaultNodeTransform> void psr::printGraph (const GraphTy & G, llvm::raw_ostream & OS, llvm::StringRef Name = "", NodeTransform NodeToString = {})
Prints the given graph G as dot.
Parameters
G The graph to print
OS The output-stream, where to print into
Name The name of the graph
NodeToString If the graph has node-labels, convert a node-label to string
Definition at line 193 of file GraphTraits.h.
Referenced by psr::Z3BasedPathSensitivityManager< AnalysisDomainTy >::pathsTo().
readFile()
std::unique_ptr< llvm::MemoryBuffer > psr::readFile (const llvm::Twine & Path)
readFileOrErr()
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > psr::readFileOrErr (const llvm::Twine & Path) noexcept
readFileOrNull()
std::unique_ptr< llvm::MemoryBuffer > psr::readFileOrNull (const llvm::Twine & Path) noexcept
readJsonFile()
nlohmann::json psr::readJsonFile (const llvm::Twine & Path)
readTextFile()
std::string psr::readTextFile (const llvm::Twine & Path)
readTextFileOrErr()
llvm::ErrorOr< std::string > psr::readTextFileOrErr (const llvm::Twine & Path)
readTextFileOrNull()
std::optional< std::string > psr::readTextFileOrNull (const llvm::Twine & Path)
remove_by_index() [1/3]
template<typename Container , typename Indices > auto psr::remove_by_index (Container & Cont, const Indices & Idx)
Definition at line 244 of file Utilities.h.
References remove_by_index().
remove_by_index() [2/3]
template<typename Container , typename IdxIt , typename IdxEndIt > auto psr::remove_by_index (Container & Cont, IdxIt FirstIndex, IdxEndIt LastIndex)
Definition at line 234 of file Utilities.h.
References remove_by_index().
remove_by_index() [3/3]
template<typename It , typename EndIt , typename IdxIt , typename IdxEndIt > It psr::remove_by_index (It First, EndIt Last, IdxIt FirstIndex, IdxEndIt LastIndex)
Based on the reference implementation of std::remove_if https://en.cppreference.com/w/cpp/algorithm/remove and optimized for the case that a sorted list of indices is given instead of an unary predicate specifying the elements to be removed.
Random-access version inspired from "https://codereview.stackexchange.com/a/207056" and slightly changed
Definition at line 184 of file Utilities.h.
Referenced by remove_by_index(), and remove_by_index().
repeat()
template<typename T > auto psr::repeat (T && Elem, size_t Num)
Definition at line 72 of file RepeatIterator.h.
References Ret.
Referenced by psr::GraphTraits< AdjacencyList< T, VtxId, EdgeTy > >::nodes(), and psr::GraphTraits< SCCDependencyGraph< GraphNodeId > >::nodes().
reserveIfPossible()
template<typename T > void psr::reserveIfPossible (T & Container, size_t Capacity)
Definition at line 243 of file TypeTraits.h.
reverseGraph()
template<is_graph GraphTy> std::decay_t< GraphTy > psr::reverseGraph (GraphTy && G)
Definition at line 153 of file GraphTraits.h.
References Ret.
scope_exit()
template<typename Fn > psr::scope_exit (Fn) -> scope_exit< Fn >
setFlag() [1/2]
template<detail::is_enum T> constexpr void psr::setFlag (T & This, T Flag) constexpr noexcept
Definition at line 63 of file EnumFlags.h.
Referenced by setFlag().
setFlag() [2/2]
template<detail::is_enum T> constexpr void psr::setFlag (T & This, T Flag, bool Set) constexpr noexcept
Definition at line 71 of file EnumFlags.h.
References setFlag(), and unsetFlag().
solveIDEProblem()
template<typename AnalysisDomainTy , typename Container > OwningSolverResults< typename AnalysisDomainTy::n_t, typename AnalysisDomainTy::d_t, typename AnalysisDomainTy::l_t > psr::solveIDEProblem (IDETabulationProblem< AnalysisDomainTy, Container > & Problem, const typename AnalysisDomainTy::i_t & ICF)
Definition at line 1940 of file IDESolver.h.
solveIFDSProblem()
template<typename AnalysisDomainTy , typename Container > OwningSolverResults< typename AnalysisDomainTy::n_t, typename AnalysisDomainTy::d_t, BinaryDomain > psr::solveIFDSProblem (IFDSTabulationProblem< AnalysisDomainTy, Container > & Problem, const typename AnalysisDomainTy::i_t & ICF)
Definition at line 125 of file IFDSSolver.h.
stripPointerTypes()
const llvm::DIType * psr::stripPointerTypes (const llvm::DIType * DITy)
strongUpdateStore() [1/2]
template<typename Container = std::set<const llvm::Value *>> FlowFunctionPtrType< const llvm::Value *, Container > psr::strongUpdateStore (const llvm::StoreInst * Store)
A flow function that models a strong update on a memory location modified by a store instruction. Similar to transferFlow.
Given a flow function f = strongUpdateStore(store a to b), for all holding dataflow facts x: f(b) = {}, f(a) = {a, b}, f(x) = {x}.
In the exploded supergraph it may look as follows:
          x   a   b  ...
          |   |\  |
          |   | \    ...
store a to b | | \ ... v v v x a b ...
Definition at line 416 of file LLVMFlowFunctions.h.
References Source.
strongUpdateStore() [2/2]
template<typename Fn , typename Container = std::set<const llvm::Value *>> requires std::is_invocable_r_v<bool, Fn, const llvm::Value *> FlowFunctionPtrType< const llvm::Value *, Container > psr::strongUpdateStore (const llvm::StoreInst * Store, Fn && GeneratePointerOpIf)
A flow function that models a strong update on a memory location modified by a store instruction
Given a flow function f = strongUpdateStore(store a to b, pred), for all holding dataflow facts x: f(b) = {}, f(x) = {x, b} if pred(x) else {x}.
Definition at line 339 of file LLVMFlowFunctions.h.
References Source.
to_json()
void psr::to_json (nlohmann::json & J, const SourceCodeInfo & Info)
Used from the JSON library internally to implicitly convert between json and SourceCodeInfo
to_string() [1/9]
std::string psr::to_string (AnalysisProperties Prop)
to_string() [2/9]
std::string psr::to_string (BinaryDomain B)
Referenced by adl_to_string(), psr::IDESolver< AnalysisDomainTy, Container >::emitESGAsDot(), psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::getData(), operator<<(), and operator<<().
to_string() [3/9]
llvm::StringRef psr::to_string (CSTDFILEIOState State) noexcept
to_string() [4/9]
llvm::StringRef psr::to_string (OpenSSLEVPKDFCTXState State) noexcept
to_string() [5/9]
llvm::StringRef psr::to_string (OpenSSLEVPKDFState State) noexcept
to_string() [6/9]
llvm::StringRef psr::to_string (OpenSSLSecureHeapState State) noexcept
to_string() [7/9]
llvm::StringRef psr::to_string (OpenSSLSecureMemoryState State) noexcept
to_string() [8/9]
llvm::StringRef psr::to_string (SeverityLevel Level) noexcept
to_string() [9/9]
llvm::StringRef psr::to_string (TaintCategory Cat) noexcept
toAliasAnalysisType()
AliasAnalysisType psr::toAliasAnalysisType (llvm::StringRef S)
toAliasResult()
AliasResult psr::toAliasResult (llvm::StringRef S)
toAnalysisStrategy()
AnalysisStrategy psr::toAnalysisStrategy (llvm::StringRef S)
toCallGraphAnalysisType()
CallGraphAnalysisType psr::toCallGraphAnalysisType (llvm::StringRef S)
toDataFlowAnalysisType()
DataFlowAnalysisType psr::toDataFlowAnalysisType (llvm::StringRef S)
toSoundness()
Soundness psr::toSoundness (llvm::StringRef S)
toSpecialMemberFunctionType()
SpecialMemberFunctionType psr::toSpecialMemberFunctionType (llvm::StringRef SMFT)
toString() [1/7]
std::string psr::toString (AliasAnalysisType PA)
toString() [2/7]
std::string psr::toString (AliasResult AR)
toString() [3/7]
std::string psr::toString (CallGraphAnalysisType CGA)
toString() [4/7]
std::string psr::toString (const AnalysisStrategy & S)
toString() [5/7]
std::string psr::toString (DataFlowAnalysisType D)
toString() [6/7]
std::string psr::toString (Soundness S)
toString() [7/7]
std::string psr::toString (SpecialMemberFunctionType SMFT)
toTaintCategory()
TaintCategory psr::toTaintCategory (llvm::StringRef Str) noexcept
unsetFlag()
template<detail::is_enum T> constexpr void psr::unsetFlag (T & This, T Flag) constexpr noexcept
Definition at line 67 of file EnumFlags.h.
Referenced by setFlag().
unwrapNullable() [1/4]
template<typename T > requires (!std::is_convertible_v<T, bool>) constexpr const T & psr::unwrapNullable (const std::optional< T > & Val) constexpr noexcept
Definition at line 38 of file Nullable.h.
unwrapNullable() [2/4]
template<typename T > requires (!std::is_convertible_v<T, bool>) constexpr T psr::unwrapNullable (std::optional< T > && Val) constexpr noexcept
Definition at line 31 of file Nullable.h.
unwrapNullable() [3/4]
template<typename T > requires (!std::is_convertible_v<T, bool>) constexpr T & psr::unwrapNullable (std::optional< T > & Val) constexpr noexcept
Definition at line 44 of file Nullable.h.
unwrapNullable() [4/4]
template<typename T > requires std::is_convertible_v<T, bool> constexpr T psr::unwrapNullable (T && Val) constexpr noexcept
Definition at line 26 of file Nullable.h.
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::processExit(), and psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow().
valueOf() [1/2]
constexpr const llvm::Value * psr::valueOf (const llvm::Value * V) constexpr noexcept
Definition at line 27 of file SparseLLVMBasedCFGProvider.h.
valueOf() [2/2]
template<typename T > T psr::valueOf (T Val)
Definition at line 18 of file SparseCFGProvider.h.
Referenced by psr::SparseCFGProvider< Derived, F, V >::getSparseCFG().
writeTextFile()
void psr::writeTextFile (const llvm::Twine & Path, llvm::StringRef Content)
Variable Documentation
CallGraphAnalysis
std::string psr::CallGraphAnalysis extern
DataFlowAnalysis
std::string psr::DataFlowAnalysis extern
DumpResults
bool psr::DumpResults extern
EntryPoints
std::vector<std::string> psr::EntryPoints extern
Referenced by addSeedsForStartingPoints(), addSeedsForStartingPoints(), addSeedsForStartingPoints(), addSeedsForStartingPoints(), psr::detail::forallStartingPoints(), forallStartingPoints(), psr::detail::forallStartingPoints(), forallStartingPoints(), psr::IntraMonoSolver< AnalysisDomainTy >::initialize(), and psr::IDEInstInteractionAnalysisT< EdgeFactType, SyntacticAnalysisOnly, EnableIndirectTaints >::initialSeeds().
has_getSparseCFG_v
template<typename T , typename D > constexpr bool psr::has_getSparseCFG_v constexpr
Initial value:
=
    requires(const T &ICF, typename T::f_t Fun, D Fact) {
      ICF.getSparseCFG(Fun, Fact);
    }
Definition at line 42 of file SparseCFGProvider.h.
has_llvm_dense_map_info
template<typename T > constexpr bool psr::has_llvm_dense_map_info constexpr
Initial value:
= requires(const T &Val) {
  { llvm::DenseMapInfo<T>::getEmptyKey() } -> std::same_as<T>;
  { llvm::DenseMapInfo<T>::getTombstoneKey() } -> std::same_as<T>;
  { llvm::DenseMapInfo<T>::getHashValue(Val) } -> std::convertible_to<size_t>;
  { llvm::DenseMapInfo<T>::isEqual(Val, Val) } -> std::convertible_to<bool>;
}
Definition at line 187 of file TypeTraits.h.
InitLogger
bool psr::InitLogger extern
is_sparse_cfg_v
template<typename ICF , typename Domain > constexpr bool psr::is_sparse_cfg_v constexpr
Initial value:
= is_crtp_base_of_v<SparseCFGBase, ICF>
    &&std::is_same_v<typename ICF::n_t, typename Domain::n_t>
        &&std::is_same_v<typename ICF::f_t, typename Domain::f_t>
Definition at line 37 of file SparseCFGBase.h.
PammOutputFile
std::string psr::PammOutputFile extern
PointerAnalysis
std::string psr::PointerAnalysis extern
PrintEdgeRecorder
bool psr::PrintEdgeRecorder extern
variant_idx
template<typename Var , typename T > constexpr size_t psr::variant_idx = detail::variant_idx<Var, T>::value constexpr
Definition at line 199 of file TypeTraits.h.