PhASAR: llvm Namespace Reference
llvm Namespace Reference
Classes
struct cast_convert_val< To, const psr::EdgeFunction< L >, const psr::EdgeFunction< L > >
struct cast_convert_val< To, psr::EdgeFunction< L >, psr::EdgeFunction< L > >
struct cast_retty_impl< To, const psr::EdgeFunction< L > >
struct cast_retty_impl< To, psr::EdgeFunction< L > >
struct DenseMapInfo< psr::BoxedConstPtr< C > >
struct DenseMapInfo< psr::BoxedPtr< C > >
struct DenseMapInfo< psr::DummyPair< T > >
struct DenseMapInfo< psr::EdgeFunction< L > >
struct DenseMapInfo< psr::IDEIIAFlowFact >
struct isa_impl_cl< To, const psr::EdgeFunction< L > >
struct simplify_type< psr::IDEIIAFlowFact >
Functions
template<typename To , typename L >
cast_retty< To, psr::EdgeFunction< L > >::ret_type dyn_cast_or_null (const psr::EdgeFunction< L > &EF) noexcept
template<typename To , typename L >
cast_retty< To, psr::EdgeFunction< L > >::ret_type cast_or_null (const psr::EdgeFunction< L > &EF) noexcept
Detailed Description
On some MAC systems, <memory_resource> is still not fully implemented, so do a workaround here
Function Documentation
cast_or_null()
template<typename To , typename L > cast_retty< To, psr::EdgeFunction< L > >::ret_type llvm::cast_or_null (const psr::EdgeFunction< L > & EF) inline noexcept
Definition at line 870 of file EdgeFunction.h.
References cast_or_null().
Referenced by cast_or_null().
dyn_cast_or_null()
template<typename To , typename L > cast_retty< To, psr::EdgeFunction< L > >::ret_type llvm::dyn_cast_or_null (const psr::EdgeFunction< L > & EF) inline noexcept
Definition at line 864 of file EdgeFunction.h.
References dyn_cast_or_null().
Referenced by dyn_cast_or_null().