PhASAR: psr::detail Namespace Reference
psr::detail Namespace Reference
A class that implements a control flow graph. Conforms to the CFGBase CRTP interface.
Classes
class AbstractMemoryLocationFactoryBase
class AbstractMemoryLocationImpl
A Memorylocation abstraction represented by a base-pointer and an array of byte offsets.
struct AbstractMemoryLocationStorage
struct AreEqualityComparable
struct AreEqualityComparable< T, U, decltype(std::declval< T >()==std::declval< U >())>
struct AutoAddZeroFF
struct DefaultCast
struct DummyTransform
struct EdgeFunctionStatsData
struct ElementType
struct False2
struct FlowFunctionCacheBase
struct has_adl_to_string
struct has_erase_iterator
struct has_erase_iterator< T, std::void_t< decltype(std::declval< T >().erase(std::declval< typename T::iterator >()))> >
struct has_isInteresting
struct has_isInteresting< ProblemTy, decltype(std::declval< std::add_const_t< ProblemTy > >().isInteresting(std::declval< typename ProblemTy::ProblemAnalysisDomain::n_t >()))>
struct has_llvm_dense_map_info
struct has_llvm_dense_map_info< T, std::void_t< decltype(llvm::DenseMapInfo< T >::getEmptyKey()), decltype(llvm::DenseMapInfo< T >::getTombstoneKey()), decltype(llvm::DenseMapInfo< T >::getHashValue(std::declval< T >())), decltype(llvm::DenseMapInfo< T >::isEqual(std::declval< T >(), std::declval< T >()))> >
struct has_reserve
struct has_reserve< T, std::void_t< decltype(std::declval< T & >().reserve(size_t(0)))> >
struct has_str
struct has_str< T, decltype(std::declval< T >().str())>
struct HasBinaryValueDomain
struct HasBinaryValueDomain< AnalysisDomainTy, typename AnalysisDomainTy::l_t >
struct HasDepth
struct HasDepth< T, decltype(std::declval< const T & >().depth())>
struct Hasher
struct HasIsConstant
struct HasIsConstant< T, decltype(std::declval< const T & >().isConstant())>
struct HasJoinLatticeTraitsHelper
struct HasJoinLatticeTraitsHelper< L, std::enable_if_t< std::is_convertible_v< decltype(JoinLatticeTraits< L >::top()), L > &&std::is_convertible_v< decltype(JoinLatticeTraits< L >::bottom()), L > &&std::is_convertible_v< decltype(JoinLatticeTraits< L >::join(std::declval< L >(), std::declval< L >())), L > > >
class IDEAliasAwareDefaultFlowFunctionsImpl
class IDENoAliasDefaultFlowFunctionsImpl
class IDEReachableAllocationSitesDefaultFlowFunctionsImpl
class IDETypeStateAnalysisBase
class IDETypeStateAnalysisBaseCommon
struct IntraFlowFunctionsMixin
struct IntraFlowFunctionsMixin< IntraFFTy, IntraFFTy >
struct is_crtp_base_of
struct is_crtp_base_of< Base, Derived, std::enable_if_t< std::is_base_of_v< typename template_arg< Base, Derived >::type, Derived > > >
struct is_iterable
struct is_iterable< T, std::void_t< decltype(llvm::adl_begin(std::declval< T >())), decltype(llvm::adl_end(std::declval< T >()))> >
struct is_iterable_over
struct is_iterable_over< T, U, std::enable_if_t< is_iterable< T >::value &&std::is_same_v< U, std::decay_t< decltype(*llvm::adl_begin(std::declval< T >()))> > > >
struct is_llvm_hashable
struct is_llvm_hashable< T, decltype(hash_value(std::declval< T >()))>
struct is_llvm_hashable< T, decltype(llvm::hash_value(std::declval< T >()))>
struct is_pair
struct is_pair< std::pair< U, V > >
struct is_printable
struct is_printable< T, OS, decltype(std::declval< OS & >()<< std::declval< T >())>
struct is_removable_graph_trait
struct is_removable_graph_trait< GraphTrait, std::void_t< typename GraphTrait::edge_iterator, typename GraphTrait::roots_iterator, decltype(GraphTrait::removeEdge(std::declval< typename GraphTrait::graph_type & >(), std::declval< typename GraphTrait::vertex_t >(), std::declval< typename GraphTrait::edge_iterator >())), decltype(GraphTrait::removeRoot(std::declval< typename GraphTrait::graph_type & >(), std::declval< typename GraphTrait::roots_iterator >()))> >
struct is_reservable_graph_trait
struct is_reservable_graph_trait< GraphTrait, std::void_t< decltype(GraphTrait::reserve(std::declval< typename GraphTrait::graph_type & >(), size_t()))> >
struct is_std_hashable
struct is_std_hashable< T, decltype(std::declval< std::hash< T > >()(std::declval< T >()))>
struct is_tuple
struct is_tuple< std::tuple< Elems... > >
struct IsAliasInfo
struct IsAliasInfo< T, std::void_t< decltype(std::declval< const T >().print(llvm::outs())), decltype(std::declval< const T >().printAsJson(llvm::outs())), decltype(std::declval< T >().mergeWith(std::declval< T >())), decltype(std::declval< T >().introduceAlias(std::declval< typename AliasInfoTraits< T >::v_t >(), std::declval< typename AliasInfoTraits< T >::v_t >(), std::declval< typename AliasInfoTraits< T >::n_t >(), AliasResult{}))>, std::enable_if_t< std::is_same_v< std::tuple< bool, AliasAnalysisType, AliasResult, typename AliasInfoTraits< T >::AliasSetPtrTy, typename AliasInfoTraits< T >::AllocationSiteSetPtrTy, bool, AnalysisProperties, bool, bool, bool >, decltype(testAliasInfo(std::declval< T & >(), std::declval< const T & >()))> > >
struct IsEdgeFunction
struct IsEdgeFunction< T, std::void_t< typename T::l_t, decltype(std::declval< const T & >().computeTarget(std::declval< typename T::l_t >())), decltype(T::compose(std::declval< EdgeFunctionRef< T > >(), std::declval< EdgeFunction< typename T::l_t > >())), decltype(T::join(std::declval< EdgeFunctionRef< T > >(), std::declval< EdgeFunction< typename T::l_t > >()))> >
struct IsEqualityComparable
struct IsEqualityComparable< T, decltype(std::declval< T >()==std::declval< T >())>
class IterativeIDESolverResults
class LLVMBasedCFGImpl
class MaybeUniquePtrBase
class MaybeUniquePtrBase< T, true >
class SolverResultsBase
class template_arg
struct variant_idx
struct variant_idx< std::variant< Ts... >, T >
struct WithBinaryValueDomainExtender
Typedefs
template<typename AnalysisDomainTy >
using IterativeIDESolverResults_P = IterativeIDESolverResults< typename AnalysisDomainTy::n_t, typename AnalysisDomainTy::d_t, typename AnalysisDomainTy::l_t >
template<typename T >
using CellVecSmallVectorTy = llvm::SmallVector< T, 8 >
template<typename T >
using is_llvm_printable = is_printable< T, llvm::raw_ostream >
template<typename T >
using is_std_printable = is_printable< T, std::ostream >
Functions
template<typename EntryRange , typename C , typename HandlerFn >
void forallStartingPoints (const EntryRange &EntryPoints, const CFGBase< C > &CFG, HandlerFn Handler)
template<typename EntryRange , typename C , typename ICFGorIRDB , typename HandlerFn >
void forallStartingPoints (const EntryRange &EntryPoints, const ICFGorIRDB *ICDB, const CFGBase< C > &CFG, HandlerFn Handler)
template<typename D , typename FFTy >
AutoAddZeroFF (FFTy, D) -> AutoAddZeroFF< std::decay_t< D >, std::decay_t< FFTy > >
template<typename T >
auto testAliasInfo (T &AI, const T &CAI, const std::optional< typename AliasInfoTraits< T >::n_t > &NT={}, const std::optional< typename AliasInfoTraits< T >::v_t > &VT={}) -> decltype(std::make_tuple(CAI.isInterProcedural(), CAI.getAliasAnalysisType(), AI.alias(*VT, *VT, *NT), AI.getAliasSet(*VT, *NT), AI.getReachableAllocationSites(*VT, true, *NT), AI.isInReachableAllocationSites(*VT, *VT, true, *NT), CAI.getAnalysisProperties(), CAI.isContextSensitive(), CAI.isFieldSensitive(), CAI.isFlowSensitive()))
template<typename OS_t , typename T >
void printHelper (OS_t &OS, const T &Data)
template<typename OS_t , typename... Args, size_t... Idx>
void printTuple (OS_t &OS, const std::tuple< Args... > &Tup, std::index_sequence< Idx... >)
template<typename T >
decltype(auto) printSomehow (const T &Val)
Variables
template<typename T , typename D , typename = void>
constexpr bool IsFlowFunction = false
template<typename T , typename D , typename = void>
constexpr bool IsFlowFunctionPtr = false
template<typename T >
PSR_CONCEPT IsSomehowPrintable
Detailed Description
A class that implements a control flow graph. Conforms to the CFGBase CRTP interface.
Typedef Documentation
CellVecSmallVectorTy
template<typename T > using psr::detail::CellVecSmallVectorTy = typedef llvm::SmallVector<T, 8>
Definition at line 48 of file TableWrappers.h.
is_llvm_printable
template<typename T > using psr::detail::is_llvm_printable = typedef is_printable<T, llvm::raw_ostream>
Definition at line 74 of file TypeTraits.h.
is_std_printable
template<typename T > using psr::detail::is_std_printable = typedef is_printable<T, std::ostream>
Definition at line 77 of file TypeTraits.h.
IterativeIDESolverResults_P
template<typename AnalysisDomainTy > using psr::detail::IterativeIDESolverResults_P = typedef IterativeIDESolverResults<typename AnalysisDomainTy::n_t, typename AnalysisDomainTy::d_t, typename AnalysisDomainTy::l_t>
Definition at line 50 of file IterativeIDESolverResults.h.
Function Documentation
AutoAddZeroFF()
template<typename D , typename FFTy > psr::detail::AutoAddZeroFF (FFTy , D) -> AutoAddZeroFF< std::decay_t< D >, std::decay_t< FFTy > >
References AutoAddZeroFF().
Referenced by AutoAddZeroFF().
forallStartingPoints() [1/2]
template<typename EntryRange , typename C , typename HandlerFn > void psr::detail::forallStartingPoints (const EntryRange & EntryPoints, const CFGBase< C > & CFG, HandlerFn Handler)
Definition at line 26 of file EntryPointUtils.h.
References psr::EntryPoints.
Referenced by psr::forallStartingPoints(), forallStartingPoints(), and psr::forallStartingPoints().
forallStartingPoints() [2/2]
template<typename EntryRange , typename C , typename ICFGorIRDB , typename HandlerFn > void psr::detail::forallStartingPoints (const EntryRange & EntryPoints, const ICFGorIRDB * ICDB, const CFGBase< C > & CFG, HandlerFn Handler)
Definition at line 43 of file EntryPointUtils.h.
References psr::EntryPoints, and forallStartingPoints().
printHelper()
template<typename OS_t , typename T > void psr::detail::printHelper (OS_t & OS, const T & Data)
Definition at line 39 of file DebugOutput.h.
References psr::llvmIRToString(), printHelper(), and printTuple().
Referenced by printHelper(), and printTuple().
printSomehow()
template<typename T > decltype(auto) psr::detail::printSomehow (const T & Val)
Definition at line 33 of file Printer.h.
References psr::adl_to_string().
Referenced by psr::DToString(), psr::FToString(), psr::LToString(), and psr::NToString().
printTuple()
template<typename OS_t , typename... Args, size_t... Idx> void psr::detail::printTuple (OS_t & OS, const std::tuple< Args... > & Tup, std::index_sequence< Idx... >)
Definition at line 32 of file DebugOutput.h.
References printHelper().
Referenced by printHelper().
testAliasInfo()
template<typename T > auto psr::detail::testAliasInfo (T & AI, const T & CAI, const std::optional< typename AliasInfoTraits< T >::n_t > & NT = {}, const std::optional< typename AliasInfoTraits< T >::v_t > & VT = {}) -> decltype(std::make_tuple(CAI.isInterProcedural(), CAI.getAliasAnalysisType(), AI.alias(*VT, *VT, *NT), AI.getAliasSet(*VT, *NT), AI.getReachableAllocationSites(*VT, true, *NT), AI.isInReachableAllocationSites(*VT, *VT, true, *NT), CAI.getAnalysisProperties(), CAI.isContextSensitive(), CAI.isFieldSensitive(), CAI.isFlowSensitive()))
Variable Documentation
IsFlowFunction
template<typename T , typename D , typename = void> constexpr bool psr::detail::IsFlowFunction = false inline constexpr
Definition at line 23 of file FlowFunctionCache.h.
IsFlowFunctionPtr
template<typename T , typename D , typename = void> constexpr bool psr::detail::IsFlowFunctionPtr = false inline constexpr
Definition at line 32 of file FlowFunctionCache.h.
IsSomehowPrintable
template<typename T > PSR_CONCEPT psr::detail::IsSomehowPrintable
Initial value:
=
    has_str_v<T> || is_llvm_printable_v<T> || has_adl_to_string_v<T>
Definition at line 30 of file Printer.h.