PhASAR: psr::cfl_fieldsens Namespace Reference
psr::cfl_fieldsens Namespace Reference
Classes
struct AccessPath
struct AccessPathDMI
class FieldStringManager
Interns the Store- and Load field-strings.
struct FieldStringNode
struct IFDSDomain
struct IFDSEdgeValue
An edge-value consisting of a set if CFL field access strings.
struct IFDSProblemConfig
Configures, how the CFLFieldSensIFDSProblem should handle strong updates.
Enumerations
enum class FieldStringNodeId : uint32_t { None = 0 }
Functions
llvm::hash_code hash_value (FieldStringNodeId NId)
InitialSeeds< IFDSDomain::n_t, IFDSDomain::d_t, IFDSDomain::l_t > makeInitialSeeds (const InitialSeeds< LLVMIFDSAnalysisDomainDefault::n_t, LLVMIFDSAnalysisDomainDefault::d_t, BinaryDomain > &UserSeeds, FieldStringManager &Mgr)
std::pair< const llvm::Value *, int32_t > getBaseAndOffset (const llvm::Value *V, const llvm::DataLayout &DL)
template<bool AllowDeepTaints = true, typename ResultsT >
bool holdsFactAt (const ResultsT &Results, IFDSDomain::n_t Inst, IFDSDomain::d_t Fact)
Checks whether Fact holds at Inst in a field-sensitive way.
template<bool AllowDeepTaints = true, typename ResultsT >
bool filterFieldSensFacts (const ResultsT &Results, const auto &QueryMap, std::invocable< IFDSDomain::n_t, IFDSDomain::d_t > auto Handler)
Enumeration Type Documentation
FieldStringNodeId
enum class psr::cfl_fieldsens::FieldStringNodeId : uint32_t strong
Enumerator
None
Definition at line 47 of file CFLFieldSensIFDSProblem.h.
Function Documentation
filterFieldSensFacts()
template<bool AllowDeepTaints = true, typename ResultsT > bool psr::cfl_fieldsens::filterFieldSensFacts (const ResultsT & Results, const auto & QueryMap, std::invocable< IFDSDomain::n_t, IFDSDomain::d_t > auto Handler)
Given a QueryMap of the form map<n_t, set<d_t>>, calls the Handler for all inst-fact pairs that hold in a field-sensitive way and filters out all others.
The Handler may opt into early exit by returning false. Returning void is permitted.
Definition at line 323 of file CFLFieldSensIFDSProblem.h.
References psr::getOr().
getBaseAndOffset()
std::pair< const llvm::Value *, int32_t > psr::cfl_fieldsens::getBaseAndOffset (const llvm::Value * V, const llvm::DataLayout & DL) inline
Utility to strip off potential pointer-arithmetic from V and accumulating the byte-offset.
Definition at line 273 of file CFLFieldSensIFDSProblem.h.
References psr::cfl_fieldsens::AccessPath::TopOffset.
hash_value()
llvm::hash_code psr::cfl_fieldsens::hash_value (FieldStringNodeId NId) inline
Definition at line 51 of file CFLFieldSensIFDSProblem.h.
Referenced by psr::cfl_fieldsens::AccessPathDMI::getHashValue().
holdsFactAt()
template<bool AllowDeepTaints = true, typename ResultsT > bool psr::cfl_fieldsens::holdsFactAt (const ResultsT & Results, IFDSDomain::n_t Inst, IFDSDomain::d_t Fact) inline
Checks whether Fact holds at Inst in a field-sensitive way.
Definition at line 292 of file CFLFieldSensIFDSProblem.h.
makeInitialSeeds()
InitialSeeds< IFDSDomain::n_t, IFDSDomain::d_t, IFDSDomain::l_t > psr::cfl_fieldsens::makeInitialSeeds (const InitialSeeds< LLVMIFDSAnalysisDomainDefault::n_t, LLVMIFDSAnalysisDomainDefault::d_t, BinaryDomain > & UserSeeds, FieldStringManager & Mgr)
Transforms user-defined seeds from usual IFDS seeds to field-sensitive IFDS seeds
Referenced by psr::CFLFieldSensIFDSProblem::initialSeeds().