PhASAR: psr::JoinEdgeFunction< L, N > Struct Template Reference
psr::JoinEdgeFunction< L, N > Struct Template Reference
#include "phasar/DataFlow/IfdsIde/EdgeFunctionUtils.h"
Public Types
using l_t = L
using JLattice = JoinLatticeTraits< L >
Public Member Functions
l_t computeTarget (ByConstRef< l_t > Source) const
Static Public Member Functions
static EdgeFunction< l_t > compose (EdgeFunctionRef< JoinEdgeFunction > This, const EdgeFunction< l_t > &SecondFunction)
static EdgeFunction< l_t > join (EdgeFunctionRef< JoinEdgeFunction > This, const EdgeFunction< l_t > &OtherFunction)
static EdgeFunction< l_t > create (EdgeFunction< l_t > LHS, EdgeFunction< l_t > RHS)
Public Attributes
l_t Seed {}
llvm::SmallVector< EdgeFunction< l_t >, N > OtherEF {}
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const JoinEdgeFunction &EF)
bool operator== (const JoinEdgeFunction &LHS, const JoinEdgeFunction &RHS) noexcept
Detailed Description
template<typename L, uint8_t N>
struct psr::JoinEdgeFunction< L, N >
Definition at line 299 of file EdgeFunctionUtils.h.
Member Typedef Documentation
JLattice
template<typename L , uint8_t N> using psr::JoinEdgeFunction< L, N >::JLattice = JoinLatticeTraits<L>
Definition at line 301 of file EdgeFunctionUtils.h.
l_t
template<typename L , uint8_t N> using psr::JoinEdgeFunction< L, N >::l_t = L
Definition at line 300 of file EdgeFunctionUtils.h.
Member Function Documentation
compose()
template<typename L , uint8_t N> static EdgeFunction< l_t > psr::JoinEdgeFunction< L, N >::compose (EdgeFunctionRef< JoinEdgeFunction< L, N > > This, const EdgeFunction< l_t > & SecondFunction) inline static
Definition at line 316 of file EdgeFunctionUtils.h.
References psr::defaultComposeOrNull().
computeTarget()
template<typename L , uint8_t N> l_t psr::JoinEdgeFunction< L, N >::computeTarget (ByConstRef< l_t > Source) const inline
Definition at line 303 of file EdgeFunctionUtils.h.
References psr::JoinEdgeFunction< L, N >::OtherEF, psr::JoinEdgeFunction< L, N >::Seed, and psr::Source.
create()
template<typename L , uint8_t N> static EdgeFunction< l_t > psr::JoinEdgeFunction< L, N >::create (EdgeFunction< l_t > LHS, EdgeFunction< l_t > RHS) inline static
Definition at line 368 of file EdgeFunctionUtils.h.
Referenced by psr::defaultJoinOrNull(), psr::defaultJoinOrNull(), and psr::XTaint::EdgeFunctionBase< Derived >::join().
join()
template<typename L , uint8_t N> EdgeFunction< L > psr::JoinEdgeFunction< L, N >::join (EdgeFunctionRef< JoinEdgeFunction< L, N > > This, const EdgeFunction< l_t > & OtherFunction) static
Definition at line 553 of file EdgeFunctionUtils.h.
Friends And Related Symbol Documentation
operator<<
template<typename L , uint8_t N> llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const JoinEdgeFunction< L, N > & EF) friend
Definition at line 345 of file EdgeFunctionUtils.h.
operator==
template<typename L , uint8_t N> bool operator== (const JoinEdgeFunction< L, N > & LHS, const JoinEdgeFunction< L, N > & RHS) friend
Definition at line 359 of file EdgeFunctionUtils.h.
Member Data Documentation
OtherEF
template<typename L , uint8_t N> llvm::SmallVector<EdgeFunction<l_t>, N> psr::JoinEdgeFunction< L, N >::OtherEF {}
Definition at line 400 of file EdgeFunctionUtils.h.
Referenced by psr::JoinEdgeFunction< L, N >::computeTarget().
Seed
template<typename L , uint8_t N> l_t psr::JoinEdgeFunction< L, N >::Seed {}
Definition at line 399 of file EdgeFunctionUtils.h.
Referenced by psr::JoinEdgeFunction< L, N >::computeTarget().
The documentation for this struct was generated from the following file:
include/phasar/DataFlow/IfdsIde/EdgeFunctionUtils.h