PhASAR: psr::EdgeFunctionComposer< L > Struct Template Reference
psr::EdgeFunctionComposer< L > Struct Template Reference
#include "phasar/DataFlow/IfdsIde/EdgeFunctionUtils.h"
Public Types
using l_t = L
Public Member Functions
l_t computeTarget (ByConstRef< l_t > Source) const
size_t depth () const noexcept
Static Public Member Functions
template<typename ConcreteEF , typename = std::enable_if_t<std::is_base_of_v< EdgeFunctionComposer, ConcreteEF>>>
static EdgeFunction< l_t > compose (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > &SecondFunction)
Public Attributes
EdgeFunction< l_t > First {}
EdgeFunction< l_t > Second {}
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const EdgeFunctionComposer &EF)
This join function is to be provided by derived classes.
bool operator== (const EdgeFunctionComposer &LHS, const EdgeFunctionComposer &RHS) noexcept
Detailed Description
template<typename L>
struct psr::EdgeFunctionComposer< L >
Definition at line 223 of file EdgeFunctionUtils.h.
Member Typedef Documentation
l_t
template<typename L > using psr::EdgeFunctionComposer< L >::l_t = L
Definition at line 224 of file EdgeFunctionUtils.h.
Member Function Documentation
compose()
template<typename L > template<typename ConcreteEF , typename = std::enable_if_t<std::is_base_of_v< EdgeFunctionComposer, ConcreteEF>>> static EdgeFunction< l_t > psr::EdgeFunctionComposer< L >::compose (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > & SecondFunction) inline static
Function composition is implemented as an explicit composition, i.e. (secondFunction * G) * F = EFC(F, EFC(G , otherFunction))
However, it is advised to immediately reduce the resulting edge function by providing an own implementation of this function.
Definition at line 240 of file EdgeFunctionUtils.h.
References psr::EdgeFunction< L >::composeWith(), and psr::defaultComposeOrNull().
computeTarget()
template<typename L > l_t psr::EdgeFunctionComposer< L >::computeTarget (ByConstRef< l_t > Source) const inline
Definition at line 226 of file EdgeFunctionUtils.h.
References psr::EdgeFunction< L >::computeTarget(), psr::EdgeFunctionComposer< L >::First, psr::EdgeFunctionComposer< L >::Second, and psr::Source.
depth()
template<typename L > size_t psr::EdgeFunctionComposer< L >::depth () const inline noexcept
Definition at line 266 of file EdgeFunctionUtils.h.
References psr::EdgeFunction< L >::depth(), psr::EdgeFunctionComposer< L >::First, and psr::EdgeFunctionComposer< L >::Second.
Friends And Related Symbol Documentation
operator<<
template<typename L > llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const EdgeFunctionComposer< L > & EF) friend
This join function is to be provided by derived classes.
Definition at line 254 of file EdgeFunctionUtils.h.
operator==
template<typename L > bool operator== (const EdgeFunctionComposer< L > & LHS, const EdgeFunctionComposer< L > & RHS) friend
Definition at line 261 of file EdgeFunctionUtils.h.
Member Data Documentation
First
template<typename L > EdgeFunction<l_t> psr::EdgeFunctionComposer< L >::First {}
Definition at line 272 of file EdgeFunctionUtils.h.
Referenced by psr::EdgeFunctionComposer< L >::computeTarget(), and psr::EdgeFunctionComposer< L >::depth().
Second
template<typename L > EdgeFunction<l_t> psr::EdgeFunctionComposer< L >::Second {}
Definition at line 273 of file EdgeFunctionUtils.h.
Referenced by psr::EdgeFunctionComposer< L >::computeTarget(), and psr::EdgeFunctionComposer< L >::depth().
The documentation for this struct was generated from the following file:
include/phasar/DataFlow/IfdsIde/EdgeFunctionUtils.h