PhASAR: psr::DOTGraph< D > Struct Template Reference
psr::DOTGraph< D > Struct Template Reference
#include "phasar/Utils/DOTGraph.h"
Public Member Functions
DOTGraph ()=default
unsigned getFactID (D Fact)
bool containsFactSG (std::string &FName, unsigned FactId)
std::string str () const
Public Attributes
std::string Label
std::map< std::string, DOTFunctionSubGraph > Functions
std::set< DOTEdge > InterCFEdges
std::set< DOTEdge > InterLambdaEdges
std::set< DOTEdge > InterFactEdges
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const DOTGraph< D > &Graph)
Detailed Description
template<typename D>
struct psr::DOTGraph< D >
Definition at line 165 of file DOTGraph.h.
Constructor & Destructor Documentation
DOTGraph()
template<typename D > psr::DOTGraph< D >::DOTGraph () default
Member Function Documentation
containsFactSG()
template<typename D > bool psr::DOTGraph< D >::containsFactSG (std::string & FName, unsigned FactId) inline
Definition at line 185 of file DOTGraph.h.
References psr::DOTGraph< D >::Functions.
getFactID()
template<typename D > unsigned psr::DOTGraph< D >::getFactID (D Fact) inline
Definition at line 174 of file DOTGraph.h.
str()
template<typename D > std::string psr::DOTGraph< D >::str () const inline
Definition at line 194 of file DOTGraph.h.
References psr::DOTConfig::CFInterEdgeAttr(), psr::DOTConfig::FactInterEdgeAttr(), psr::DOTGraph< D >::Functions, psr::DOTGraph< D >::InterCFEdges, psr::DOTGraph< D >::InterFactEdges, psr::DOTGraph< D >::InterLambdaEdges, psr::DOTGraph< D >::Label, and psr::DOTConfig::LambdaInterEdgeAttr().
Friends And Related Symbol Documentation
operator<<
template<typename D > llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const DOTGraph< D > & Graph) friend
Definition at line 229 of file DOTGraph.h.
Member Data Documentation
Functions
template<typename D > std::map<std::string, DOTFunctionSubGraph> psr::DOTGraph< D >::Functions
Definition at line 167 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::containsFactSG(), and psr::DOTGraph< D >::str().
InterCFEdges
template<typename D > std::set<DOTEdge> psr::DOTGraph< D >::InterCFEdges
Definition at line 168 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::str().
InterFactEdges
template<typename D > std::set<DOTEdge> psr::DOTGraph< D >::InterFactEdges
Definition at line 170 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::str().
InterLambdaEdges
template<typename D > std::set<DOTEdge> psr::DOTGraph< D >::InterLambdaEdges
Definition at line 169 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::str().
Label
template<typename D > std::string psr::DOTGraph< D >::Label
Definition at line 166 of file DOTGraph.h.
Referenced by psr::DOTGraph< D >::str().
The documentation for this struct was generated from the following file:
include/phasar/Utils/DOTGraph.h