PhASAR: psr::EquivalenceClassMap< KeyT, ValueT > Struct Template Reference
psr::EquivalenceClassMap< KeyT, ValueT > Struct Template Reference
EquivalenceClassMap is a special map type that splits the keys into equivalence classes regarding their mapped values.
#include "phasar/Utils/EquivalenceClassMap.h"
Public Types
template<typename... Ts>
using SetType = std::set< Ts... >
using EquivalenceClassBucketT = std::pair< SetType< KeyT >, ValueT >
using StorageT = llvm::SmallVector< EquivalenceClassBucketT, 0 >
using size_type = size_t
using key_type = KeyT
using mapped_type = ValueT
using value_type = EquivalenceClassBucketT
using const_iterator = typename StorageT::const_iterator
using insert_return_type = std::pair< typename SetType< KeyT >::const_iterator, bool >
Public Member Functions
EquivalenceClassMap (unsigned InitialEquivalenceClasses=0)
template<typename InputIt >
EquivalenceClassMap (const InputIt &I, const InputIt &End)
EquivalenceClassMap (std::initializer_list< std::pair< key_type, mapped_type > > Vals)
const_iterator begin () const
const_iterator end () const
llvm::iterator_range< const_iterator > equivalenceClasses () const
template<typename ValueType = ValueT>
insert_return_type insert (const KeyT &Key, ValueType &&Value)
template<typename ValueType = ValueT>
insert_return_type insert (KeyT &&Key, ValueType &&Value)
insert_return_type insert (const std::pair< KeyT, ValueT > &KVPair)
insert_return_type insert (std::pair< KeyT, ValueT > &&KVPair)
template<typename InputIt >
void insert (InputIt I, InputIt End)
Insert a range of Key Values pairs into the map.
template<typename... Ts>
insert_return_type try_emplace (KeyT &&Key, Ts &&...Args)
template<typename... Ts>
insert_return_type try_emplace (const KeyT &Key, Ts &&...Args)
size_type count (const KeyT &Key) const
Return 1 if the specified key is in the map, 0 otherwise.
size_type numEquivalenceClasses () const
size_type size () const
Returns the size of the map, i.e., the number of equivalence classes.
const_iterator find (key_type Key) const
std::optional< ValueT > findValue (key_type Key) const
void clear ()
Detailed Description
template<typename KeyT, typename ValueT>
struct psr::EquivalenceClassMap< KeyT, ValueT >
EquivalenceClassMap is a special map type that splits the keys into equivalence classes regarding their mapped values.
Meaning, that all keys that are equivalent are mapped to the same value. Two keys are treated as equivalent and merged into an equivalence class when they refer to Values that are considered equal according to operator==.
Definition at line 32 of file EquivalenceClassMap.h.
Member Typedef Documentation
const_iterator
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::const_iterator = typename StorageT::const_iterator
Definition at line 45 of file EquivalenceClassMap.h.
EquivalenceClassBucketT
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::EquivalenceClassBucketT = std::pair<SetType<KeyT>, ValueT>
Definition at line 34 of file EquivalenceClassMap.h.
insert_return_type
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::insert_return_type = std::pair<typename SetType<KeyT>::const_iterator, bool>
Definition at line 47 of file EquivalenceClassMap.h.
key_type
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::key_type = KeyT
Definition at line 41 of file EquivalenceClassMap.h.
mapped_type
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::mapped_type = ValueT
Definition at line 42 of file EquivalenceClassMap.h.
SetType
template<typename KeyT , typename ValueT > template<typename... Ts> using psr::EquivalenceClassMap< KeyT, ValueT >::SetType = std::set<Ts...>
Definition at line 33 of file EquivalenceClassMap.h.
size_type
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::size_type = size_t
Definition at line 40 of file EquivalenceClassMap.h.
StorageT
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::StorageT = llvm::SmallVector<EquivalenceClassBucketT, 0>
Definition at line 37 of file EquivalenceClassMap.h.
value_type
template<typename KeyT , typename ValueT > using psr::EquivalenceClassMap< KeyT, ValueT >::value_type = EquivalenceClassBucketT
Definition at line 43 of file EquivalenceClassMap.h.
Constructor & Destructor Documentation
EquivalenceClassMap() [1/3]
template<typename KeyT , typename ValueT > psr::EquivalenceClassMap< KeyT, ValueT >::EquivalenceClassMap (unsigned InitialEquivalenceClasses = 0) inline
Definition at line 50 of file EquivalenceClassMap.h.
EquivalenceClassMap() [2/3]
template<typename KeyT , typename ValueT > template<typename InputIt > psr::EquivalenceClassMap< KeyT, ValueT >::EquivalenceClassMap (const InputIt & I, const InputIt & End) inline
Definition at line 55 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::insert().
EquivalenceClassMap() [3/3]
template<typename KeyT , typename ValueT > psr::EquivalenceClassMap< KeyT, ValueT >::EquivalenceClassMap (std::initializer_list< std::pair< key_type, mapped_type > > Vals) inline
Definition at line 59 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::insert().
Member Function Documentation
begin()
template<typename KeyT , typename ValueT > const_iterator psr::EquivalenceClassMap< KeyT, ValueT >::begin () const inline
Definition at line 64 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMap< KeyT, ValueT >::equivalenceClasses().
clear()
template<typename KeyT , typename ValueT > void psr::EquivalenceClassMap< KeyT, ValueT >::clear () inline
Definition at line 172 of file EquivalenceClassMap.h.
count()
template<typename KeyT , typename ValueT > size_type psr::EquivalenceClassMap< KeyT, ValueT >::count (const KeyT & Key) const inline
Return 1 if the specified key is in the map, 0 otherwise.
Definition at line 139 of file EquivalenceClassMap.h.
end()
template<typename KeyT , typename ValueT > const_iterator psr::EquivalenceClassMap< KeyT, ValueT >::end () const inline
Definition at line 67 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMap< KeyT, ValueT >::equivalenceClasses().
equivalenceClasses()
template<typename KeyT , typename ValueT > llvm::iterator_range< const_iterator > psr::EquivalenceClassMap< KeyT, ValueT >::equivalenceClasses () const inline
Definition at line 69 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::begin(), and psr::EquivalenceClassMap< KeyT, ValueT >::end().
find()
template<typename KeyT , typename ValueT > const_iterator psr::EquivalenceClassMap< KeyT, ValueT >::find (key_type Key) const inline
Definition at line 157 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMap< KeyT, ValueT >::findValue().
findValue()
template<typename KeyT , typename ValueT > std::optional< ValueT > psr::EquivalenceClassMap< KeyT, ValueT >::findValue (key_type Key) const inline
Definition at line 164 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::find().
insert() [1/5]
template<typename KeyT , typename ValueT > template<typename ValueType = ValueT> insert_return_type psr::EquivalenceClassMap< KeyT, ValueT >::insert (const KeyT & Key, ValueType && Value) inline
Inserts Key into the corresponding equivalence class for Value. If Value is not already in the map a new equivalence class is created.
Definition at line 76 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::try_emplace().
Referenced by psr::EquivalenceClassMap< KeyT, ValueT >::EquivalenceClassMap(), and psr::EquivalenceClassMap< KeyT, ValueT >::EquivalenceClassMap().
insert() [2/5]
template<typename KeyT , typename ValueT > insert_return_type psr::EquivalenceClassMap< KeyT, ValueT >::insert (const std::pair< KeyT, ValueT > & KVPair) inline
Inserts Key into the corresponding equivalence class for Value. If Value is not already in the map a new equivalence class is created.
Definition at line 89 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::try_emplace().
insert() [3/5]
template<typename KeyT , typename ValueT > template<typename InputIt > void psr::EquivalenceClassMap< KeyT, ValueT >::insert (InputIt I, InputIt End) inline
Insert a range of Key Values pairs into the map.
Definition at line 100 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::try_emplace().
insert() [4/5]
template<typename KeyT , typename ValueT > template<typename ValueType = ValueT> insert_return_type psr::EquivalenceClassMap< KeyT, ValueT >::insert (KeyT && Key, ValueType && Value) inline
Inserts Key into the corresponding equivalence class for Value. If Value is not already in the map a new equivalence class is created.
Definition at line 83 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::try_emplace().
insert() [5/5]
template<typename KeyT , typename ValueT > insert_return_type psr::EquivalenceClassMap< KeyT, ValueT >::insert (std::pair< KeyT, ValueT > && KVPair) inline
Inserts Key into the corresponding equivalence class for Value. If Value is not already in the map a new equivalence class is created.
Definition at line 95 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::try_emplace().
numEquivalenceClasses()
template<typename KeyT , typename ValueT > size_type psr::EquivalenceClassMap< KeyT, ValueT >::numEquivalenceClasses () const inline
Definition at line 148 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMap< KeyT, ValueT >::size().
size()
template<typename KeyT , typename ValueT > size_type psr::EquivalenceClassMap< KeyT, ValueT >::size () const inline
Returns the size of the map, i.e., the number of equivalence classes.
Definition at line 153 of file EquivalenceClassMap.h.
References psr::EquivalenceClassMap< KeyT, ValueT >::numEquivalenceClasses().
try_emplace() [1/2]
template<typename KeyT , typename ValueT > template<typename... Ts> insert_return_type psr::EquivalenceClassMap< KeyT, ValueT >::try_emplace (const KeyT & Key, Ts &&... Args) inline
Inserts Key into the corresponding equivalence class for Value. If Value is not already in the map a new equivalence class is created.
Definition at line 125 of file EquivalenceClassMap.h.
try_emplace() [2/2]
template<typename KeyT , typename ValueT > template<typename... Ts> insert_return_type psr::EquivalenceClassMap< KeyT, ValueT >::try_emplace (KeyT && Key, Ts &&... Args) inline
Inserts Key into the corresponding equivalence class for Value. If Value is not already in the map a new equivalence class is created.
Definition at line 109 of file EquivalenceClassMap.h.
Referenced by psr::EquivalenceClassMap< KeyT, ValueT >::insert(), psr::EquivalenceClassMap< KeyT, ValueT >::insert(), psr::EquivalenceClassMap< KeyT, ValueT >::insert(), psr::EquivalenceClassMap< KeyT, ValueT >::insert(), and psr::EquivalenceClassMap< KeyT, ValueT >::insert().
The documentation for this struct was generated from the following file:
include/phasar/Utils/EquivalenceClassMap.h