PhASAR: psr::XTaint::EdgeFunctionBase< Derived > Struct Template Reference
psr::XTaint::EdgeFunctionBase< Derived > Struct Template Reference
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.h"
Static Public Member Functions
static EdgeFunction< EdgeDomain > compose (EdgeFunctionRef< Derived > This, const EdgeFunction< EdgeDomain > &SecondFunction)
static EdgeFunction< EdgeDomain > join (EdgeFunctionRef< Derived > This, const EdgeFunction< EdgeDomain > &OtherFunction)
Detailed Description
template<typename Derived>
struct psr::XTaint::EdgeFunctionBase< Derived >
Definition at line 28 of file XTaintEdgeFunctionBase.h.
Member Function Documentation
compose()
template<typename Derived > static EdgeFunction< EdgeDomain > psr::XTaint::EdgeFunctionBase< Derived >::compose (EdgeFunctionRef< Derived > This, const EdgeFunction< EdgeDomain > & SecondFunction) inline static
Definition at line 30 of file XTaintEdgeFunctionBase.h.
References psr::defaultComposeOrNull(), and psr::XTaint::makeComposeEF().
join()
template<typename Derived > static EdgeFunction< EdgeDomain > psr::XTaint::EdgeFunctionBase< Derived >::join (EdgeFunctionRef< Derived > This, const EdgeFunction< EdgeDomain > & OtherFunction) inline static
Definition at line 39 of file XTaintEdgeFunctionBase.h.
References psr::JoinEdgeFunction< L, N >::create().
The documentation for this struct was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/ExtendedTaintAnalysis/XTaintEdgeFunctionBase.h