PhASAR: psr::NonTopBotValue< L, typename > Struct Template Reference
psr::NonTopBotValue< L, typename > Struct Template Reference
#include "phasar/Utils/JoinLattice.h"
Public Types
using type = L
Static Public Member Functions
static L unwrap (L Value) noexcept(std::is_nothrow_move_constructible_v< L >)
Detailed Description
template<typename L, typename = void>
struct psr::NonTopBotValue< L, typename >
Definition at line 73 of file JoinLattice.h.
Member Typedef Documentation
type
template<typename L , typename = void> using psr::NonTopBotValue< L, typename >::type = L
Definition at line 74 of file JoinLattice.h.
Member Function Documentation
unwrap()
template<typename L , typename = void> static L psr::NonTopBotValue< L, typename >::unwrap (L Value) inline static noexcept
Definition at line 76 of file JoinLattice.h.
Referenced by psr::AllBottom< L >::compose(), psr::ConstantEdgeFunction< L >::compose(), and psr::ConstantEdgeFunction< L >::join().
The documentation for this struct was generated from the following file:
include/phasar/Utils/JoinLattice.h