PhASAR: psr::ConstantEdgeFunction< L > Struct Template Reference
psr::ConstantEdgeFunction< L > Struct Template Reference
#include "phasar/DataFlow/IfdsIde/EdgeFunctionUtils.h"
Public Types
using l_t = L
using JLattice = JoinLatticeTraits< L >
using value_type = typename NonTopBotValue< l_t >::type
Public Member Functions
l_t computeTarget (ByConstRef< l_t >) const noexcept(std::is_nothrow_constructible_v< l_t, const value_type & >)
constexpr bool isConstant () const noexcept
template<typename ConcreteEF >
requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>>
EdgeFunction< L > compose (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< L > &SecondFunction)
template<typename ConcreteEF >
requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>>
EdgeFunction< L > join (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > &OtherFunction)
Static Public Member Functions
template<typename ConcreteEF >
requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>>
static EdgeFunction< l_t > compose (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > &SecondFunction)
template<typename ConcreteEF >
requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>>
static EdgeFunction< l_t > join (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > &OtherFunction)
Public Attributes
value_type Value {}
Detailed Description
template<typename L>
struct psr::ConstantEdgeFunction< L >
Definition at line 44 of file EdgeFunctionUtils.h.
Member Typedef Documentation
JLattice
template<typename L > using psr::ConstantEdgeFunction< L >::JLattice = JoinLatticeTraits<L>
Definition at line 46 of file EdgeFunctionUtils.h.
l_t
template<typename L > using psr::ConstantEdgeFunction< L >::l_t = L
Definition at line 45 of file EdgeFunctionUtils.h.
value_type
template<typename L > using psr::ConstantEdgeFunction< L >::value_type = typename NonTopBotValue<l_t>::type
Definition at line 47 of file EdgeFunctionUtils.h.
Member Function Documentation
compose() [1/2]
template<typename L > template<typename ConcreteEF > requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>> EdgeFunction< L > psr::ConstantEdgeFunction< L >::compose (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< L > & SecondFunction)
TODO: Can this ever happen?
TODO: Can this ever happen?
Definition at line 447 of file EdgeFunctionUtils.h.
References psr::EdgeFunction< L >::computeTarget(), psr::defaultComposeOrNull(), and psr::NonTopBotValue< L >::unwrap().
compose() [2/2]
template<typename L > template<typename ConcreteEF > requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>> static EdgeFunction< l_t > psr::ConstantEdgeFunction< L >::compose (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > & SecondFunction) static
computeTarget()
template<typename L > l_t psr::ConstantEdgeFunction< L >::computeTarget (ByConstRef< l_t >) const inline noexcept
Definition at line 49 of file EdgeFunctionUtils.h.
References psr::ConstantEdgeFunction< L >::Value.
isConstant()
template<typename L > constexpr bool psr::ConstantEdgeFunction< L >::isConstant () const inline constexpr noexcept
Definition at line 66 of file EdgeFunctionUtils.h.
join() [1/2]
template<typename L > template<typename ConcreteEF > requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>> static EdgeFunction< l_t > psr::ConstantEdgeFunction< L >::join (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > & OtherFunction) static
join() [2/2]
template<typename L > template<typename ConcreteEF > requires std::derived_from<ConcreteEF, ConstantEdgeFunction<L>> EdgeFunction< L > psr::ConstantEdgeFunction< L >::join (EdgeFunctionRef< ConcreteEF > This, const EdgeFunction< l_t > & OtherFunction)
Definition at line 490 of file EdgeFunctionUtils.h.
References psr::EdgeFunction< L >::computeTarget(), psr::EdgeFunction< L >::joinWith(), and psr::NonTopBotValue< L >::unwrap().
Member Data Documentation
Value
template<typename L > value_type psr::ConstantEdgeFunction< L >::Value {}
Definition at line 70 of file EdgeFunctionUtils.h.
Referenced by psr::ConstantEdgeFunction< L >::computeTarget().
The documentation for this struct was generated from the following file:
include/phasar/DataFlow/IfdsIde/EdgeFunctionUtils.h