PhASAR: psr::IDEFeatureTaintEdgeFact Struct Reference
psr::IDEFeatureTaintEdgeFact Struct Reference
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEFeatureTaintAnalysis.h"
Public Member Functions
IDEFeatureTaintEdgeFact (llvm::SmallBitVector &&Taints) noexcept
IDEFeatureTaintEdgeFact (const llvm::SmallBitVector &Taints)
IDEFeatureTaintEdgeFact (uintptr_t Taints) noexcept
IDEFeatureTaintEdgeFact () noexcept
void unionWith (uintptr_t Facts)
void unionWith (const IDEFeatureTaintEdgeFact &Facts)
bool empty () const noexcept
size_t size () const noexcept
bool isBottom () const noexcept
bool isTop () const noexcept
template<typename E >
std::string str () const
template<typename E >
auto toBVSet () const
template<typename E >
auto toSet () const
Static Public Member Functions
static llvm::SmallBitVector fromBits (uintptr_t Bits)
Public Attributes
llvm::SmallBitVector Taints
Friends
llvm::hash_code hash_value (const IDEFeatureTaintEdgeFact &BV) noexcept
bool operator== (const IDEFeatureTaintEdgeFact &Lhs, const IDEFeatureTaintEdgeFact &Rhs) noexcept
bool operator!= (const IDEFeatureTaintEdgeFact &Lhs, const IDEFeatureTaintEdgeFact &Rhs) noexcept
Detailed Description
Definition at line 41 of file IDEFeatureTaintAnalysis.h.
Constructor & Destructor Documentation
IDEFeatureTaintEdgeFact() [1/4]
psr::IDEFeatureTaintEdgeFact::IDEFeatureTaintEdgeFact (llvm::SmallBitVector && Taints) inline noexcept
Definition at line 56 of file IDEFeatureTaintAnalysis.h.
IDEFeatureTaintEdgeFact() [2/4]
psr::IDEFeatureTaintEdgeFact::IDEFeatureTaintEdgeFact (const llvm::SmallBitVector & Taints) inline
Definition at line 58 of file IDEFeatureTaintAnalysis.h.
IDEFeatureTaintEdgeFact() [3/4]
psr::IDEFeatureTaintEdgeFact::IDEFeatureTaintEdgeFact (uintptr_t Taints) inline noexcept
Definition at line 60 of file IDEFeatureTaintAnalysis.h.
IDEFeatureTaintEdgeFact() [4/4]
psr::IDEFeatureTaintEdgeFact::IDEFeatureTaintEdgeFact () inline explicit noexcept
Definition at line 62 of file IDEFeatureTaintAnalysis.h.
References Taints.
Member Function Documentation
empty()
bool psr::IDEFeatureTaintEdgeFact::empty () const inline noexcept
Checks whether this set contains no facts. Note: Top also counts as empty
Definition at line 81 of file IDEFeatureTaintAnalysis.h.
References isTop(), and Taints.
fromBits()
static llvm::SmallBitVector psr::IDEFeatureTaintEdgeFact::fromBits (uintptr_t Bits) inline static
Definition at line 44 of file IDEFeatureTaintAnalysis.h.
References psr::Ret.
isBottom()
bool psr::IDEFeatureTaintEdgeFact::isBottom () const inline noexcept
Definition at line 93 of file IDEFeatureTaintAnalysis.h.
References Taints.
isTop()
bool psr::IDEFeatureTaintEdgeFact::isTop () const inline noexcept
Definition at line 94 of file IDEFeatureTaintAnalysis.h.
References Taints.
Referenced by empty(), psr::JoinLatticeTraits< IDEFeatureTaintEdgeFact >::join(), size(), toBVSet(), toSet(), and unionWith().
size()
size_t psr::IDEFeatureTaintEdgeFact::size () const inline noexcept
Returns the number of facts in this set. Note: Top counts as empty
Definition at line 86 of file IDEFeatureTaintAnalysis.h.
References isTop(), and Taints.
str()
template<typename E > std::string psr::IDEFeatureTaintEdgeFact::str () const inline
Definition at line 144 of file IDEFeatureTaintAnalysis.h.
References psr::BitVectorSet< T, BitVectorTy >::fromBits(), psr::LToString(), and Taints.
toBVSet()
template<typename E > auto psr::IDEFeatureTaintEdgeFact::toBVSet () const inline
Definition at line 149 of file IDEFeatureTaintAnalysis.h.
References psr::BitVectorSet< T, BitVectorTy >::fromBits(), isTop(), and Taints.
toSet()
template<typename E > auto psr::IDEFeatureTaintEdgeFact::toSet () const inline
Definition at line 156 of file IDEFeatureTaintAnalysis.h.
References isTop(), and psr::Ret.
unionWith() [1/2]
void psr::IDEFeatureTaintEdgeFact::unionWith (const IDEFeatureTaintEdgeFact & Facts) inline
Definition at line 72 of file IDEFeatureTaintAnalysis.h.
References isTop(), and Taints.
unionWith() [2/2]
void psr::IDEFeatureTaintEdgeFact::unionWith (uintptr_t Facts) inline
Definition at line 64 of file IDEFeatureTaintAnalysis.h.
References Taints.
Friends And Related Symbol Documentation
hash_value
llvm::hash_code hash_value (const IDEFeatureTaintEdgeFact & BV) friend
Definition at line 99 of file IDEFeatureTaintAnalysis.h.
operator!=
bool operator!= (const IDEFeatureTaintEdgeFact & Lhs, const IDEFeatureTaintEdgeFact & Rhs) friend
Definition at line 139 of file IDEFeatureTaintAnalysis.h.
operator==
bool operator== (const IDEFeatureTaintEdgeFact & Lhs, const IDEFeatureTaintEdgeFact & Rhs) friend
Definition at line 113 of file IDEFeatureTaintAnalysis.h.
Member Data Documentation
Taints
llvm::SmallBitVector psr::IDEFeatureTaintEdgeFact::Taints
Definition at line 42 of file IDEFeatureTaintAnalysis.h.
Referenced by empty(), IDEFeatureTaintEdgeFact(), isBottom(), isTop(), psr::JoinLatticeTraits< IDEFeatureTaintEdgeFact >::join(), size(), str(), toBVSet(), unionWith(), and unionWith().
The documentation for this struct was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEFeatureTaintAnalysis.h