PhASAR: psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI Struct Reference
psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI Struct Reference
#include "phasar/DataFlow/IfdsIde/Solver/IterativeIDESolverBase.h"
Static Public Member Functions
static InterPropagationJobRef getEmptyKey () noexcept
static InterPropagationJobRef getTombstoneKey () noexcept
static auto getHashValue (InterPropagationJobRef Job) noexcept
static bool isEqual (InterPropagationJobRef LHS, InterPropagationJobRef RHS) noexcept
Detailed Description
template<typename StaticSolverConfigTy, typename EdgeFunPtrTy>
struct psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI
Definition at line 94 of file IterativeIDESolverBase.h.
Member Function Documentation
getEmptyKey()
template<typename StaticSolverConfigTy , typename EdgeFunPtrTy > static InterPropagationJobRef psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getEmptyKey () inline static noexcept
Definition at line 95 of file IterativeIDESolverBase.h.
Referenced by psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getHashValue(), and psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::isEqual().
getHashValue()
template<typename StaticSolverConfigTy , typename EdgeFunPtrTy > static auto psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getHashValue (InterPropagationJobRef Job) inline static noexcept
Definition at line 101 of file IterativeIDESolverBase.h.
References psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getEmptyKey(), and psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getTombstoneKey().
getTombstoneKey()
template<typename StaticSolverConfigTy , typename EdgeFunPtrTy > static InterPropagationJobRef psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getTombstoneKey () inline static noexcept
Definition at line 98 of file IterativeIDESolverBase.h.
Referenced by psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getHashValue(), and psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::isEqual().
isEqual()
template<typename StaticSolverConfigTy , typename EdgeFunPtrTy > static bool psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::isEqual (InterPropagationJobRef LHS, InterPropagationJobRef RHS) inline static noexcept
Definition at line 107 of file IterativeIDESolverBase.h.
References psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getEmptyKey(), psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRefDSI::getTombstoneKey(), and psr::IterativeIDESolverBase< StaticSolverConfigTy, EdgeFunPtrTy >::InterPropagationJobRef::JobPtr.
The documentation for this struct was generated from the following file:
include/phasar/DataFlow/IfdsIde/Solver/IterativeIDESolverBase.h