PhASAR: psr::IFDSIDESolverConfig Struct Reference
psr::IFDSIDESolverConfig Struct Reference
Configuration options for the solving process of IFDS/IDE problems.
#include "phasar/DataFlow/IfdsIde/IFDSIDESolverConfig.h"
Public Member Functions
IFDSIDESolverConfig () noexcept=default
IFDSIDESolverConfig (SolverConfigOptions Options) noexcept
bool followReturnsPastSeeds () const
bool autoAddZero () const
bool computeValues () const
bool recordEdges () const
bool emitESG () const
bool computePersistedSummaries () const
Currently unused.
void setFollowReturnsPastSeeds (bool Set=true)
void setAutoAddZero (bool Set=true)
void setComputeValues (bool Set=true)
void setRecordEdges (bool Set=true)
void setEmitESG (bool Set=true)
void setComputePersistedSummaries (bool Set=true)
void setConfig (SolverConfigOptions Opt)
Friends
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const IFDSIDESolverConfig &SC)
Detailed Description
Configuration options for the solving process of IFDS/IDE problems.
Definition at line 43 of file IFDSIDESolverConfig.h.
Constructor & Destructor Documentation
IFDSIDESolverConfig() [1/2]
psr::IFDSIDESolverConfig::IFDSIDESolverConfig () default noexcept
IFDSIDESolverConfig() [2/2]
psr::IFDSIDESolverConfig::IFDSIDESolverConfig (SolverConfigOptions Options) noexcept
Member Function Documentation
autoAddZero()
bool psr::IFDSIDESolverConfig::autoAddZero () const
Returns whether the solver should automatically insert an identityFlow propagation for the special zero value (default: true)
Referenced by psr::PathAwareIDESolver< AnalysisDomainTy, Container >::PathAwareIDESolver().
computePersistedSummaries()
bool psr::IFDSIDESolverConfig::computePersistedSummaries () const
Currently unused.
computeValues()
bool psr::IFDSIDESolverConfig::computeValues () const
Returns whether the IDE solver should perform IDE's phase 2 (default: true). You may want to turn this off for IFDS analyses.
emitESG()
bool psr::IFDSIDESolverConfig::emitESG () const
Returns, whether the solver should emit the ESG as DOT graph on the command-line (default: false)
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processCall(), psr::IDESolver< AnalysisDomainTy, Container >::processExit(), psr::IDESolver< AnalysisDomainTy, Container >::processNormalFlow(), and psr::IDESolver< AnalysisDomainTy, Container >::propagateValueAtCall().
followReturnsPastSeeds()
bool psr::IFDSIDESolverConfig::followReturnsPastSeeds () const
Returns whether the solver should handle unbalanced returns (default: false)
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::processExit().
recordEdges()
bool psr::IFDSIDESolverConfig::recordEdges () const
Returns, whether the solver should record all ESG edges (default: false)
Note
This option may severly hurt the solver's performance
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::saveEdges().
setAutoAddZero()
void psr::IFDSIDESolverConfig::setAutoAddZero (bool Set = true)
See also
autoAddZero
setComputePersistedSummaries()
void psr::IFDSIDESolverConfig::setComputePersistedSummaries (bool Set = true)
See also
computePersistedSummaries
setComputeValues()
void psr::IFDSIDESolverConfig::setComputeValues (bool Set = true)
See also
computeValues
setConfig()
void psr::IFDSIDESolverConfig::setConfig (SolverConfigOptions Opt)
setEmitESG()
void psr::IFDSIDESolverConfig::setEmitESG (bool Set = true)
See also
emitESG
Referenced by psr::IDESolver< AnalysisDomainTy, Container >::enableESGAsDot().
setFollowReturnsPastSeeds()
void psr::IFDSIDESolverConfig::setFollowReturnsPastSeeds (bool Set = true)
See also
followReturnsPastSeeds
setRecordEdges()
void psr::IFDSIDESolverConfig::setRecordEdges (bool Set = true)
See also
recordEdges
Friends And Related Symbol Documentation
operator<<
llvm::raw_ostream & operator<< (llvm::raw_ostream & OS, const IFDSIDESolverConfig & SC) friend
The documentation for this struct was generated from the following file:
include/phasar/DataFlow/IfdsIde/IFDSIDESolverConfig.h