PhASAR: std::hash< psr::glca::EdgeValue > Struct Reference
std::hash< psr::glca::EdgeValue > Struct Reference
#include "phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEGeneralizedLCA/EdgeValue.h"
Public Member Functions
hash ()=default
size_t operator() (const psr::glca::EdgeValue &Val) const
Detailed Description
Definition at line 117 of file EdgeValue.h.
Constructor & Destructor Documentation
hash()
std::hash< psr::glca::EdgeValue >::hash () default
Member Function Documentation
operator()()
size_t std::hash< psr::glca::EdgeValue >::operator() (const psr::glca::EdgeValue & Val) const inline
Definition at line 119 of file EdgeValue.h.
References psr::glca::EdgeValue::getKind(), psr::glca::EdgeValue::tryGetFP(), psr::glca::EdgeValue::tryGetInt(), and psr::glca::EdgeValue::tryGetString().
The documentation for this struct was generated from the following file:
include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEGeneralizedLCA/EdgeValue.h